---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: telepresence-oss
  namespace: default
spec:
  interval: 10m
  url: oci://ghcr.io/telepresenceio/telepresence-oss
  ref:
    semver: ">=2.0.0 <3.0.0"
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traffic-manager
  namespace: ambassador
spec:
  interval: 5m
  chart:
    spec:
      chart: telepresence-oss
      version: 2.22.4
      sourceRef:
        kind: OCIRepository
        name: telepresence-oss
        namespace: default
  values:
    trafficManager:
      enabled: true