---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traffic-manager
  namespace: ambassador
spec:
  interval: 5m
  chart:
    spec:
      chart: oci://ghcr.io/telepresenceio/telepresence-oss
      version: 2.22.4
  values:
    trafficManager:
      enabled: true