---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: datawire
  namespace: ambassador
spec:
  interval: 5m0s
  url: oci://ghcr.io/telepresenceio/telepresence-oss
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traffic-manager
  namespace: ambassador
spec:
  interval: 5m
  chart:
    spec:
      chart: traffice-manager
      version: 2.22.4
      sourceRef:
        kind: HelmRepository
        name: datawire
  values:
    trafficManager:
      enabled: true