---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: telepresence-oss
  namespace: default
spec:
  type: oci
  interval: 10m
  url: oci://ghcr.io/telepresenceio/telepresence-oss
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traffic-manager
  namespace: ambassador
spec:
  interval: 5m
  chart:
    spec:
      chart: telepresence-oss
      version: 2.22.4
      sourceRef:
        kind: HelmRepository
        name: telepresence-oss
  values:
    trafficManager:
      enabled: true