---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBs6+K04W2ocvmxECrAdclWZFe6w5YoqmG2AzxPLIv18AxrOKHFTeN9bgHDxcDu0R3dAe/mybhScjTM9g0PfA6L3SPWOrHbrPTQVWWB+IKTn9t51DzmiGftt57J+apd1Zh6qu4TEA8mSWFZYrBEjJ+J5EmRteuCjzsAY9uGwJVGw00WuWTlCsyU2ANdH+E3TcFI5nIrhy1S6BlvJeMSUU8QM+WU4dKSd2/3zxIqsHSmseCp5i+VrsNHWaOQOH9rxGw4qCTQJm9ALi+urWg8s7njo5pbJv1PPeLoyaypM78j/H/j0BVLbluQvKzxgs4rRGJekZWJISUCoIcDRTxSfuOeIxe/td3URO210QL6DuaobUbGyJlRofCpPfZIVu3DqYFL8emuQxMMYNB7gSCD3VF1RZohQ+CiZ7sLHOVehk3OZKlDzv0R2cpxXQDgDCVaAIM3qutDF7UrrpcSVZ27sRYyHoKsEdJCOMxWRqhSXjpAxLAeV9X8E8tMvmeBP8lw5uj8HGGunYvIiAfHSxJYu9YuVZ0XQSPiOCxfs1hwQM/t4ksRb3cQDGrVIlfCrjfohhYlPPpBXkp9nm5LlO1Vbq8m9iyJe6qPEc/WioqRUHd4XJiyzAY8InS7mU/qxrK2B0t4BGnvZqYuMqB5JPx4n032+8ZlfbQ33VIlf7MR2KT2m/LgbiFCMnzcIEjnoWqFxKQTRQ==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
