---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBLKKOLkeKzlbYahQPMdPwXu0RNrN4RdmrWyJ/ZmRTQ7crAlbQtKA8FqG2FKqhWZ2HNbUXGFn1CHinMfOfuuULLyDpJARLiq6M088K0Tkt2X+EXBk35fF0dvKYeWMSqgmTbo2mPFiS7Eiri++KYXFMnWZcekYksQphr7ILdVOojnDYHJHAssu/YlwJKUiReby4foXE/y+HGDUAzbOvdjDEqf0dNoBv/DGpwEv60+MIDdODnpgA9xIa5Uac/8uTj3Xtr09bdA3zgYJG0ClelTqVCHEWm0iscJ3YyfwJ8jp/vTntgaP7SNd/5u/GdtpXriw095jFgzMfAURBZoSVJtR8bQmJLq8CeH9aShb64eIqFd5GlkCKJ/W0C7a7fy6ibCp3KMXM3mqHtPRfpAiv4/hyLBkRlQdVOYCDOLNMVvggqce9wBmfizO6kvzpCeVX9tVmJ32Bis5v7ZRBu+c6v7wYt6QvYu3P0VzHQe5QjlYsF8AWBSgMGRt+/gPTAsqyux2u/b63kphgRSXYHvk3zRBY7M1svdIJq2BbEVSRphL9C4NsYoTwDMoOYVolMPzuoQz6iL6beKdyp9NUlHUG60PvlJWw4TEEYdOIAfPrMrHobvlQfm8278qBm8707xomMSex0iqZFg/zjjBk0H2Rn0iI/nINbIpUHuyocsaX7izP3eNCIR067h0BK9PWYC2mct3jw58XOFQWVcxeNpI/AFD9zfsUR+up+MG9ZRDhR0OVhQNetU5lbd4RVk8ATy9yusjICU59XdFpZapiTPFZzGkSDUIejhncCb868mRsDglYUQ//nhyD0CeJp3F8odKKdUhRVjVfosMPker7WdLx/N1/z6gNt0AwKnJ4dX8OJFEfFp0XF4UXQ5i1B30LTXaBvgM5ePshHsNu9iQWd6Lj40WcPWZh7SxqmF9yPm3zud1I3
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
