---
- hosts: all
  become: yes
  become_method: ansible.builtin.sudo
  become_user: root
  gather_facts: no
  connection: ssh
  remote_user: root

  tasks:
    - name: Update Pi-hole
      ansible.builtin.shell: pihole -up

    - name: Add pihole blocklists
      ansible.builtin.shell: >
        sqlite3 /etc/pihole/gravity.db
        "INSERT OR IGNORE INTO adlist (address, enabled, comment) VALUES ('{{ item }}', 1, 'Added by Ansible');"
      loop:
        - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklist@latest/hosts/pro.txt"
        - "https://cdn.jsdelivr.net/gh/hagezi/dns-blocklist@latest/hosts/tif.txt"
        - "https://raw.githubusercontent.com/Perflyst/PiHoleBlocklist/master/SmartTV.txt"
        - "https://phishing.army/download/phishing_army_blocklist.txt"

    - name: Update pihole gravity
      ansible.builtin.shell: pihole -g
      async: 600
      poll: 15
