---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgASHBYNluACTqpVw1VH0/8fBJBF8cAF+4mHQ/lhMRZl+BF5uucq3Oly5VyJxydQJSY3AwGbUel896OPqDYiT0Iu3pd/USs3wVh1zY+oROkFkAsAJMI4W1uWIOBrZSOgTAzEPHbX6ku2xpsma1evasYS1Pr9CVxdjsMucv2i439Q9d5nOTFTfEAVKtNte6ewOTioT83TnuudxqfmiQ0y4YgADEOtmHfBx51a5HFY8bdYMccPS+R/V9TVePnp8kvGj4u5BLGDdhIwGWY1jFXAWvob9/O7VkttZTSFi0Bg9lZEQOA/bVC4yie5gRlf5xvEQsybKucB4t8DEyYElUvFFSjwzrKisIILVomdwLRgJo78Huk73NFAT4i6rIM0vhX3n1+DRglBNA72xgLCvFRI/saKEHLH+BZOSsDYRE7C42tMGKYLZGGj9MF6UOheRQ4rrjF8iFf9UZBj5ed8JqGsXmeDZiRYStIZdFehGVF7SyfJ+QANL13K3N7+2ZjOtyBZ1uX8Rlyimp3d2EgcCqigZlU4HHp7xhnNYPQifwyzvNtD90MXs2Kgmo3L4DMbzk4J8iuCY3Pa51GPHzHy4neZDSETbKVThWYzSTag8S9f2R7AizIVm20IfMX3nizJqCnqMw1thKHAW8+eziiLaeBTukS1S39JvC8eQA2TixnynavrDQvedlpUxJpCBbE7xF1tEkRX7gt1nHicoTrvUiHWlkf4m7nG1tqO7eW/oD+mx5eO8y1LcEAARV7zjQ==
    admin-password: AgALhJdnxZlOqFwiPzXpG7+bF2wm1VIjFNDdU7tx87mL9xz2chyS1sK8wjvRbL3d2Td95ARjAJgyssw5PAVMGo7JF3PxuL1hpyUfkWmFHmyvd7TE8k9LDgydiYurzzZz9sKsvqQ3L2Aq5hXv51a8xrDWkNcmnxTe4xsNLRPX9fw4iV+77SWxXRsxy2cM+SUHFMTjPV14BfBwg5BAqDQXrQ7x3WSKG3ZTJBDyWjnbcao9h6UgxvmSVg5lKZ2lLBfA9L3+2m5cUSSHEx7t4Vpi/Id4abfeyoFtpm0zaFlPOwjtggH8IvUSKQ4ZiN8vJDix6KZkLfEpiEhLwpVyDUX8n95PDRh1H0sTMYWGeSYPhTMPmRvLzbi90fxYVHsHZxUTVwVeNBlkT1DoW7zStaJQU94YL5siRRE5wZAiI+tS6TEaQ5t4IXmHAza7PwWRCol/dDmdr26BVnG4dIeWZt/WSwGuVSRuATy0r+zzko/JckobqnwKQhkCWg/s4G369yqlGJV+2qsOvVBqKbOBxcnSVgiDWqBgpzEuWLIwmsgFVlT8/eDFURD25nsCorbIUpoQ1uRclDDhOOj6JiO7xojUVERFIKFN4HRzTfaoLTcdoxHxRAgEV2lmdxQ+gAkEoS1EOS3XfSp110qZfV3aCU7lCbUmGiipDvO/NpGZyt3p+LM1iljKJ4e2mK3LDDkp6ozW30mwk9J+Gr63H0wVcqysRuF0GoqVPE6IkB3UbrtJh2gzgjRwWFfDo4GPnA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
