---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgANyO5NaQAq0nMeS2r6kDUml66pg7CxwPcxeKBn0U4C3/a9217hqQgKuXiKeRoDoyaXg4rhOSYrjQQ7jceMbH+kM7t1S9s7CJj1uvpuZzGpZDpftv1sh8ShUamtZ+qpKBNqa0BNr05833qftVnm8+0y95pkv25VFpHYCB4QXELGZEeIWTtvmWiCmZapCq2fxHF85MiBESby9zN+gK1FMRNlfeOvPfpDh5NGWKpK7ty4tyxqA4CeoXJBuaWP7qwfd6K8fsrzAkjUvogBrUC00+DWZFu0u4r9E+HhPXH0qVT8FZrb8/+AeXzETZMH84sKfSDCiULbg2MDMiKIQ8PmmSfGNiscV1HwB9xpBVfxUceDs7vWC5J3zQw319pm1yl+ts02lQ1dWVyj6vyjNeLG0pP57FvCDkzY01HDVBeOISDWKuNgWAwk6rnG7TfMtrpzrZv8Kl4AVZN5yT4QP7yV+I3Vp4ER1GaDvbR5tqOa91CSjhENHUwiJgu68aDjTjdYZDXIvLAWWhuuLEb5GQmGmgufAkUl9zJwzlPL5vJiXxQL1L7Lo5nPIVhY1vpq0wNXztCk/tVtexhRl7sT9EhzEXtTaLXZPMXTZ8jqNYDsr4EXK+NtPD971BVt1QPmg70aOdSHdnCgkYOzLh0n3OujXT4Yd1JfWCvoePz772MqpMBWLYdcn4bgSI0nrcBtU/y3hVAfPGL5h2T6ySCBdX0QGobgLnwJPUQnOTiI/Y2FA1gwPM3K9zprNkk5+Q==
    admin-password: AgCZyJ9p5KCMIzI2vAbnNUJ3jtJHFhIO7fGOKUHwgrEnYetraXc/tfdPXrWiGH2woN9bqQW0NGZ6mJ/qKf0pEm/4a15n9bky4p5K+PfsmMzvc1su0gfkqr9mido/GuLxcnyR5954hRSv6CYwGwqlDoQX/xFOH15xpNVqg8tSh3qn2hJjKjx8JzldgxNE47I2u/363IZ4uITTiO/1gCdxccmvd+5W4LIStUUbeT/1jTTBGsA8f4QXJmdouI1Z9NtwHfE65qA3jX/5VFhLwRXNZytugn/QA+ZgdD7VZPLSjWpJa05UHFh/x/g5SlNnFrL6EEUn3EpQ61Cd9KY/ipRANM1/zQTUv/CFTlepe6bSKQl5xUTfgbF1ECiUVKx1A04myExqP01RGlxnUXi2bbI/q/2HRyx0FLxxfKQblgP9KcFdpYwEna8Vh+PWiJY4vFIUeuHRH3C6ZSrEAa/On9dRxBGG+oU3apprKNUWZocB2GDv6uKNb50Wlu2JrsoTkVhZKUnTof2P6q8XddltbWWned8QO9QKV86hQincLOvZAZaEIRyr/OOwMgkk6tdKc5Bpiqga/o04EUT5tJrjMFSFTN1qmossE2uyi5STngIlmsOYREf/4WDRfUheo/TeedpCuLadkttNhcEWCC3qAGrNldxIp+P+NbNsDZ5ggsQ5qutSEKtoODImehu4p3uF/GalSLL3CN4f1FV99l3IV5WNhWJ+DLCTlz/t/XatTqEre2pXCtY+/yCKRaqQAg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
