---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgCMlAcPz2m/chdV5+GslXBqQyyDkCK3+xec4dL57v5ecnQ7+L/88+CPXiZf/p6s/VFJYye+7ibQdXN3Q8sUXodNkWw4IpxDhM1tEpjOjb4j7KmZyfCd0n9/C6Sr+navM97tlEh4FHLN/Cfx/6J7WT2Czc9W8/Tc4Z+u1A7xa1u/iLn27tJgqgub98t2IK3JbVhiaNm4WERNKqSejqnB1uylcUeNo63WezT+bncU/NNQLx9ww706YJUsbUP3AQeQYAPsoXu7NUO9kcPC5+o3v+GKpL7tl5lWQAgOJgiZ2xyQ1jkk9T8YOgJGn1rK8JALZdWdg/nNp/0RF8yQ54211e3Gte3vKSXatVCShqbpgH/Hn5fa3hH3I2r/7uRlQJi4LPr7bDfPfhfDVk9ke9GVHc3YeQ5l60hN2Wbk+YvTPpd0F7VOAox2QLLZOdgeyAyfJuRZNA6QKSq0V8PPL+7cRJ/TygTRGLa9i7CpSxYFH5V0qNKw9SGU8kLKyPRGMA2fejynRLGo1u4eQP8BExMBULmzuuFIxIHPueDzXY+0Fbz39vMeWmsajbjIraXIDtzgwhZovCaYHEuSnf9aMjVEX6bBptDSd9LWGbQzQb1xzGYONgtrNzb1SsJFWKJ9F1Ip+TIVn7SwVHo9bjMa28hc0WU+MvaT/y0ZwBui0+qAU+iX+jwtyfzOCsZwbQhGVyAw/mdH7+NV8lWkGVelqegcUINjZYRH34FlpnrGonWM2cpxDm9mxUPdCkI=
    admin-password: AgAvJiCGU5ulfSxUVdF5lCbB3GIEWdk8p88AKuaoKvNbO8W/gbCoTIvpz8HtokOXyXk9oTzobEKFDqhFiyuYqf8ZuNJVTZVe0NYihvDBjQ2CqvE5XsYKLNm9Y4Ddvwuz+tnTd51ouOhp3OeyYhcnG6q87aqmeJeao4dVIC1HhWXT3P+Iq1bRYwtMYOBzxhvhz+LvDoFucxQbbcOncILxPizrtgyOCK/j8XxrCu3yl0B9uHrGcvEANxnv4nSITHw317k39n1MeUzkxGkkR0cuBMtDvIEFlmymt3r2FljVvYttzEyC8FqSIQMr9yvZINqDdpVR3ZAFgnbXveX3kaSUzWyTG2WmVlQPfdhrkDp54aHGD5zu5ADY96KLbC0ivGJk6OB/Wh/ijAdLghEm+7GcTJvO2sNgCDnF8DQ/8r77qeOfapXgOCorZ4GxhhuYkg2slaZc3xrsJxryAG6ekOi+Eqj0kaNmTakSMHrHb112HAUqv4pvnDVSeE+NvhTQXQhiDYLE+dEKmpWEc/1qB3bD1E41sGLYiwtNfoVIsmdcwwkiya7VtOdfcPUQBSQFwg1kXo4a6dgXQCMwAYJQboYZM310poUwI2prm6XpyzMgeqdIP7W80u8ABqnCKX8B5I1ERRQ8lQJUKfHYgBHOzGsA2ZaO3Cl0oZmRw3T/mpCwXEbdOV0hdQmpqQg9mHgoZCH10ofLb2XzWLX2FqwNAOgZRj+VqD9BMEsPHSQZJpP/ut5E+SStWdWt444=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
