---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgAeA3c0xv9c5Tm/Mea3l5Z9+iyQFC7Cjvrhv4tNAehOhscuFnJlLrWhEKBiItq7uiOayU93ORjOU4l0t6CEfSujsPdZ46DuEBWMRYpV+n+fNCE6RdQEfKFqxDJXmJNLibWwkSjhR6llR9esnNUz9Xcm5Vl9/qIqk0DNWprCARKliLh39jtGNe0xTyPurThiRpSi47fcDNle8X2QZ97ANGOHtJv3bWcRQD6FL4Ji4ADdeOk6ZpLVXMcUInSrR9p4dVAE7f6hj2AyLIZ9tfzTIthZbv9ZO0KlGR+gBX2sqmcf1oSBzlIYK6h5j86uZjU4CHsotyaubxvCM9CvXefwT1WxW2l5gTtw5+xdTtWxroygnZ3WEAaRZuIq6Yfyc0YaqHtCKi2JevsultiL/HMxKEt9hr89rs5QiJzlcPybffuZjwgIjqPOOYpCuphkRYdEAswkpQrJBZ3ngJNQFmFLYlDehnRQtHStnJh79PxIUxqqQU4Il/Z9NxVCuT7FGn5OXfiCyE/VKX68VQhF4XDSlBnuYg0nKKrs+1lM8IE4eygZtZnnPwKgIER50vMczZoDgrUUjUae7uG6NrmEwZ2BmIfiXjId4IiMzAR1adqNVXZdXla1eyViCjPcJPKYVaQVcBnRj8PmUg7aXb3tTBTzDq3i7HGCuS03jhrgxIrD30r58GF9NmfCmAHOZ1m0HllEs/TA82l0YXmYVOSCOz2IY6aWlz60swaEZhqQopyncY/VJQCOE9QxPko=
    admin-password: AgCyV1/JbRRXTiptygp4+vKJsGJcKxB79qwC32gFQiVwWrPoXTA4YMiWAaBlf/6LbjOoXxw0pWz4EyZTyBwTE9uIwNh8LyVMUXKyHLOWb7CRtRDl79XIsWhkz1NIOexOuyErXeLv5oVDc8++h3JhKx1uZZuAPGYrgz3Uh+nvjSnBu+u07uqQrD04n+oaYvr07m+uaZhJAG3oYBP/wMPH4OyEj9yOlmbIZRjYC1Jrlr228ds6RJeDGMA893l/CkGNxZcR79eM+vlLDCw5xdmUB/8bgXzu5uW2xXwPpWl82fHBY3FJ5CQ0RLk2SZf+b3rbTE/BBprCXtmnwq5I53xsJix4Md/SYDms3iCCFaQp1IfbztsAqNzGtK38BRiP1TQ/uhy+tAH22mQw+2QlmBWtLObA6lN9FXcUCscZnTqpl5M2K+HoMgh9efRh4PeVFOPAC88DdoZ3tObHAHYwZa4wxDLVJKEPF1R2PqP0+RU7zaewwm0TXmZoDkbw9PI2tmq0jm/jTm+77NbXaw1rsV/BfbAg0eYn+j4FraDB3mVaRJeDT7s7Ec9lUMX6IlwyUabTlTQggQz4pZi7taYvX5AJ58OPHk7bXc2wn9o1lC5kMWxpMaKaetnfEi8rk1zXovWIEU3C0TdwRJBJ2RWkHUGcqgPt2hN+o5L3573X8hjtnI6FXaeUrLgQkLDl20AzBf6z07G4SSZ71R3ro9v9/ZuSA+5Lk2EbfcrV8Af5oZzJtckvcf0LBY0+Drg=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
