---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgCn2LcJNcNsbb65oWRlu4NHiZNYbEvM2IwWbai5JkcIh0X4a8bjmOq2GTrPhy3Ig3j941o2pLDXhqmZ9oSSo9T97e0AzKmySzkz+1eBNWaBrUqIFD0OA1B+6u84kQGNPLdUTOsd728WnhZiIYzQkAKYDSlLIPZglvz1wobDYD9tLFLvDH+6U5+tpODf/5MSArzowWH4gNe/Lvy0Y2boGG9T93igzxmkv8BLWrmd4AkT/CFVIIJTXDErIIWqivcaNxdewIROuvH/NinvxhhCEtHdxzpkXyh+Mkd9onDCJB2eqGHLBVZZ7xaM/XKTASDBXsCxCzX85aDQ/b/4M2kDchnpdwU71BP2z+Db349snLNLDgcBCOknmiaYV9ZlWsWCTISn/rX68XiSDkQ7meVfLkvNLr3M63owoN94wx+n6oK7JjtS2VL1x+/Nj2UToqtlwMBFaFEvXai2e6u+wwxWkzOASn+8tDgGZExqxQcadcdjjfmsBN+cWkbLddyi42gCr7wuAmyvi0r69G/3J1SsW89LT6NltGxHXdsRGfwxi0QaF3Akv5wkUEgaVSkcpm1ae8lcYCFpnLDVg485bCnF1gTUb+mdtDofOv5NHxMcMiSZxHpx9yPKAAOlLC06WZ73kOzo49pZAFeUFe6a3rBCi7P8WvybFu3Rusl0H819WJfO1N6fV6ijPdY+uk27VyxKlHG4sAnTTwW2uecJPZOMUcmxzDScV5Jo34qNNHj6eQ4YdUgdZ9Cl3Js=
    admin-password: AgCSCF/mG1BQC0rPnn9Qa63NlLpwMWKCNL5/L1WdzccRukRfw7a6XOX6rgA8cgkDudoug1bV5bA1GPFmu527wEyGZOJIv5y1watDOYdkm6ewtECkNCTxGggi8d4NI/nRXLpu5BMOTMlhoSMW9iSE2Q8t9jglA9SUmkkZs7fTdVTr19F+PUNIpYeQfQwUvE3Hz+Lsy7f43MJqB0QqQdXrOEU3Qi72MdoL/lt+wc7fUZih3gnUU81MD8+3TJbVS3EuW1229FGxqgOUZpErxivVYIzB4ycq26SKxE9H9wvEiQ38/uGiuXTFIUf3khJPfxuS3+7S/UA+1WVnVC5ZMQRMpQibOfiyzyPc6eybVT3KlGu7l1TwlAqA09+pDAp8k5jwX3UxIifvQoJyv787edmKovyRH+Dnq/mAE12Fd19IDhOSjsvwZLsB3kaXNEKP90qMgJKx++6IbuJ+ac9jrOr3zUQT52g6r+5hxFIVCxYxRJ6n4FoS24jmlP6ZGfueygjuEV5ufss+RBC1pBl8feXRTbe51UdDOby7DLJTCxl54fTKFOBK6PRPhIWNiqdfyKqKcmvjWrU7XZVLnJZTLAstiwaQrRZi2tPZ44oMEc3tmqFnGeMMn+/cWuqQwz22IQqIf8pqyqalNd6OhCoZzOTNgfZK/3R+Aao6IX/JNe4lzlSNP6LJ5OVoKWBbZ0oOgCeteeyKgaMKKefe9AI7AW/BbY0RTUQxMyHPfLifi6/ZbD2057oStMolW90=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
