---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgBVCLLev4Zhh25Qu4BHgZKg9jFm7kcG6m3MJiP/sPpIwfF1AyCw3VhUS7i4wfrUlJmRrgelnfvtG5u+QkOCVGM7TebRPXKRR7GyAuuiCS69G1STH6AVzRJuCu3iDXBEKgN/k19BNFyOppBExvmx2arVRJo71tScgCHN/7GhVwd7wJnqrzZ9D+rhUgiFzWvRcvaHiwyW3BzAMZw2af03MCmoAhpUBkOJyK5/Ix6aNUZO6X4ului/JdpFc++LEYNZyXV5oxj4DNoO4VP5MIR7g1C/5Oj4d+cDGSU8x5BH5jePkmyb9e3WZrSKiRUhh7abqZlhLAt+YxVbSAlvADgJWRmXHcyZQqytstoGg/54ESemLSNvYk0b4EC7qD3u7JyyInHuWuNunUkdciU8Enj2mfYT0OKYu1q9BqApVeIISdLTWBud+dgQBt0FRcKs6/BFI69eP4RwPUg/+dtCeJpFxqaUeBkh7C9dxneVNJi3sGjI6F3FEKmQ8lQPMzISL12v0tu+o9Mcxaqy7HJ2HRMdHs2AhF5UgLQL/ppxOPiCAYfL0OLevvgnP5hHQyHX/L2wiSaC4NwcdTEht4xMmeP0Z9z2UlhJzNCg4wV39CfzMEuMN5q/rJMBonmWsFjGKGZUwtFuCNfMKfvvImZX6jmUOSIQ5ktE5fqxu/HvdyYATcZITnlCFItPl2WXN+5RklX9f9bcrNCkYlUX4dEs/2rpX6oAOP3R36iNyF449q+VMCVW5XENEYgaN+ADtg==
    admin-password: AgBZzss4ObhK0IC/O+xdwUqqCf9W5FcZ8bQwD4ykPfVhxkcHBTXtT+lQok5hMWIOXUaFp3pjYpC2NUnTCLqxK3Ma/DmIuEXpa8yVnd7pDcrGjhKcgc+uMOyLuw7lNYdga9CFTFDIP02SKlJaJKIuSNV8nYGXFziMglvC7lwCd4iSKyWs/9kUK3Y6ou7XzSoWGstspO+9DXt/f9bmnoaH+E23nVZLHCEq/hB1XFq1D1wZF0pxK9lcnBC4PXYEEkcW/3uM/4tMlUoZs/ZnjST/hE7hXqnUm1GTvlyuIdxQQ1bd1lA/e/kpEPNQb4rRr18mfnzkIQEMsVB6bN36bvLIZnGPo2/Rtrd63B1AOZgEVyLk9kDdWpTyYlq7lXzD6MieeXacn0sBmcohdsJktuxW7fBXPlNgwVqYnTR20Ex4xE/0SKxxD2wzeyMSrjDW9MXvGoLPvtlMkBDyOkujlNvwe44YWhg/cBREIxvTO5yV88OVmnmHMHFByqLExULWsTOJm+tnVty/CWiB4b/OJ68fdq6o0B3aI95Lk9kPZFtjOgm76mYhxxZWgJ+WJQq2Zix9cQ4Y0oYI1Q1ayTHtjB6v9xs4JGrDN29UgHzRv8mmZEp64wT7KNTj45wRW2JRaJfffHHVRx16yJ4365Tgq0w6AHtktJdE7BcR4iNGdCHWcheOtWzibr/cHBUXnEtwWPeWmULj+qRLNyoRiPyMO1WBAX43zgTy+KN83l8zCCB0Q3yDLr3PjymwBpXtrw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
