---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgCdfXbz6SlxQrocPK1iR4ncdiAgGYn/o1bcF81AjV/jrKNPF8ot/JfRUj6+0CkdryALYfq2O02U8sLokZawb8WSUabmXVKoNHnhQ+/tCxmt0Sc5q571qZ0sYYQgyqyISjPE/AXibMnfxLzdqAKtiqJS8gFABGUyoNBASxUuWzV21d9NX2myVwDfeZHScGNgOK5RhaFFk1NrwTAKkPQuLuElHmRJLrXOvh1LgVle4Wi6eMYgZUBg1YZglgboNq8be1jfikIev0wqYWFx4c9BX/15uIn3J2NYh5V1ow4+TmneK4s18jNbaqAIqXWaIAn4SwxpNYYDAWwgHhJUpVOE7pidNXGyX9PI3xIA+HGpVZ1xLcFimhP6OhyjT6Op6valQlTgwipL5ZPyzUlTIWIt4BDKLja4utHG8CJib4UTfVU44lA1xaYDNVh5TKIUoIuz+udt3m6FAninimZ0ZgViJETOevicZkPcTolP9TTxIuxnPa2sEfSYfJEwQzmPDAJ1qTppkvzLE9LjAT21smTo9ohRqkDVhKoqxhxwV5ayW842Wbaief4K6lOF80rFC1eW6xq5Zs+aLUCtB1GVLjrgHo7t3xgOLuqMVk3hr2T3cqBcSO16lUEqM9+832pKUwOZqZkFMYC01mnLJlk0BL+3MNqL3Hs5JkM5H6U+KtWsyRHXOOQR12aSs3tjCykQPr5Rik/ge9/FK34Kc5m8iIJQX7A/9Z6vXj10L96TLkmMEDUthVeeGiTczpo=
    admin-password: AgCAzRxcTSztvBx1sIOOlao7031Ir5NTh1F0Hto040qBwa7CMO8TLsWMYaI3Y5SSWEvnF0aW2NZRWLe7EKIWTHkiMoSL3HfrASpPwtKdJVyfVFCuX4fo3AEgTGSZrTs5SxzoEaSN/HhTdAf7agh78NsdP5C+HL8YSp3tCi4z+DhxnAzKX/cwuaOFCzJDFsF0UK3U8NlDZqJdeKdZJ29a/D6S0LjhgnAZ6CSY2gzudn/l917ItAEeC/J2vtxq8RBbBrZ9qtZTI1qcmoY6Vqs7S9DbFTDGWwmSzt8UxIJoXkBaorkZirkVTzbm8gDS8z2TfZX4DJcCwHSWT+hpy/fYKbdkuLg1Yv5wyRFw7RlBLaqr1sYi9T6LDetm0rEEI/oSQYnwryJq8lcsR8gDxQ7UQKrHQB/XwEeL+6gClrzJI1DB+FL2gsgtWcCMAFcogRoVL7pRvQiycyYnTSlkkP5ZHIiRShuE3Gbw1YIhe9k7lNBR3ga5qkU4cqAwIYVYu6Tgb7Qfxol/TfTJvHZFrUddzTiOfjr9TsF6QoZ4At2PDbPt0IlRkXpCWi/ig/FaxRJRiq/pWdcRVZ//axIoB5va5u2uTuaThcX4Re/lsNUzUC/tnw9tTeeSbnvuifSwrdYlQmSiZegqCJnJHijI6zKdjt+pRUL1EHhh07Y6r8+JWq9WNgIYM8t4V7SCuKhX7R68k01enV/htFme9wzLgK69+GH5hTcKN/It648FfTy0IiOnBUdST5epPyA=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
