---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgB24Hm3qXvTAWvs3Oh/m9XCevpOTFZKwZk0DKH3+sin+JlsAPi/yI28qxli4yxG+hPfKjs5nuiMoZw8DusTMCcQu9+hteUbwN7alSu3yu8/CxIQz3oZ64YoR8IwpH+G6njIyGfUcE5GdnHecHd1indC4C6LcVb3Y00dfU7SmBIUK+wlSqu22I2ADUkBlGASv5r8hTEKk4exQQRl/mcTWrRs7uV01TUKYYp0lZTz+U4oC3ZeEaLpzt8cZyhpSyqwexrASSm7OUtoAnqfN0aa/wUekFGw9TFnNf5QGa90XBkkrUj6yqjpoyOeidPp9kLhnp3DnPxrlTV5/h+7kW3t8URi+Ta7TKM+yccaw5ynQBipyyYa//wfjYcic1anQ4N2uPCKldzcBmlGCbpHC+cLACehJPI2+PUrl4aYoVEwgNkoTvOGUUamy/98+otDlWG0J3WzcDtk8hK7+kwJMBLLfJjdVKJ0UY8KFAfW9dKj1H5pfavrcBw27ulEf0aGzFweBOwx01AbkerAU5N/tm3p1/aiWN6U5G9fo4801GUCJNE//HBwFonSNVKoXPq75lPf7meC3dtjgQNdg4Ey2Zm8rqxXeGweOvdBTZp2Q7lw1E1IcnlEIRAz7ANnUrwoEUBbsyJvzckCJGF6oy9II6+8/jYF0SppDcsAGY3xAmLhi2ndTAIVpVuPrC+rcjFlPjf0KBg8hUtN1dUAucya0I5imqULAtKfDfmbpVWWSVav3ZutTODdrNxUQtk=
    admin-password: AgBBCkZWsqVIQcjQkM6W9I0xFF8RXJPzhQKDAQynf9yCucaRsMs2SpSI9W7EHJ/B99glO8eNu8hgNqVsF3BQ/lNoMURUfEApbY6UWAfAJVllCI/3NxPFuHI6oeHG5PEeqw+74QsP+zSzvpOcDNqMmcok0ksmKZr8q+qvZDcoSPHA8uo2MalAIU4L75QdCaS6uAkoCKAEa/HRXoIjl5bobgzailHl8NtiNgl0rkW5WlzSZ1XAf7TVzHZv1Gz4TGsTjQFnPISGAzpGB3m6k1+wceRoRe8LA/QwjYPpuga86TEpfGw5GpzAlvrqlUlxFFioWmoTkwW6Q8AqU/lrdkdX83BNyYMKTIpluE3xKRiVpGJs1i+pCLZn3lRYEQz2zJPdVxTRyMSe7dPuQHYnjV9OkggJIaVveFl8oolcqx/ZbOD/bI6ZZ4VeN8EZslp5VI8f6gx7t0PkhOcXmA+0ejjuH/13w/bFgXbl9w0RdJqWkZqiMiasEFY2RM0VcPY8C/pYw0CKA9hKnyOHr6Ah89HmmIIkwba8iCET55AFHWdxOzb6ETpPGVv1WQtrqQ30FwXfuWY41xvFU/5YSyiCELgcIgUcnFM3KrHLGO9lJ24IHsBJb/sx3uANMpL3xuHXTj5j3yu4BFbfMd7+Vfs1u8iP9R13pMERnNBJH7fg20mXmQ1ls+SwD+TsZVn5US1dqMIPgJhYH1dFTt/DyCwDKDuAJhdytauMLILQYJy42+kxfGnVrQNts9xs+ao=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
