---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgAAEc1m6uTHcT1qtQ+yn/zDLKw2C0umSVgv48t0u3Z9XCd/Hfqafvwvx/YQ7qqpD/x4e9qYePVAx0MFvlCpc519Ioow/o7SrvlvjvcjFIanrMDtM7Aq3Wb9O8pKmLYG0TyW4AL9RQgni8qKH4hdkKTSWlbwoamIRlftDJcNVRh4ejDHdD7ifk3mabXHVY6AogyRkW3gqUh82U5CKn4cWAnbpHRdz5nlval5xWbks7sFE0sXG03sOJs5t4DN4+BAXHQiCD3PPtSRXDudL9iU3pQTei9QLsQUOXccgRTmnPwBslUcm0pGi0b/nAsHKk+PC7vD2mlzRqf2FfC0IkFfnLEWOLsMDiQcunSeqXflV3fMMU0DxevYdnRj34osgzHY+lVrkLm/HpDs5OWoDUiKHw+p4MvfqJCtAeAuVObtfVfgqWq1n7qQY+cbX3fVKKnt2i7pVfUktuB0HJLs10C4qBCRz2NJkWXi5w4g4lT0Ohq5EBJAqEUMZtVVrGdVp7nfQ23/iTGCvm0EKJODo9iEZqAQMlb08FGndvSWf1SwzS5BZEJKzjRhebxesYdcmQMaY5DBPEJMhPm9mrKN8m1Wscvs/+fkWfNLm2H7897aJ2f82MrKSPUHjV0P1seegFhGO/LxV22FuN480uVL+a6VMCVtp3lc5siS0x9A9E0f3mb31FeFUbm3//ePIoW50qlSTwNhdNPExLicLS7oPzA/P5MdBN+TqfalbOd/etxE7vy4r/Nb9V5aEHY=
    admin-password: AgA47jMRfLy4tgzprcy1hGIEYABzTQcU9E/ZWxvL75jbPafC+51rAYj4xoma2ZlECZH5ThMr2EVxTg0QYVtR74LYofVxDUScqRPgy+0H78oTTTWEGjiNpPtwLP8M/TXqANhO0t/P/Oup2TQqBbZ0bNCVwjdfacelrjeh7I+3iT+36hvotFpR6L29Ody0Kq9bYFyu/XTniBGSC6HwIkVQNqSGfbBwyueaRaomAkSv35Kf6WMxKICQo81nusZu0QR3NUJ6J+YncfqDncm0LkV+Xzpp71mASbEdIZtjef+KO6KPtZ7OUsF02XGFvegF4IU8N751N9h8gnqORiYwAGScz1VjjkihtEbwnUPGqeSGO8/raAaIoDNDXLahI2WhIK4/SzMrBS6Sfot93SW5Ii8FPnmMGUXQ+VswVR1p9yUYYBo9DxYdJgpzb5OJOntgnVb1wkfBuSa8vThwywxEr96KG87AGJBvwbDhRS4D09rQePiI5dlLvtPXGCmYsohso/f/wcYXGvJjqXHBcZ/BGtDxoZzu+NilnocBbsYDa33JDH+6kZF8hS5oh5UCEWsaFbGD2crbWZDBFUvuu8xjZpRLak0HtYD85Lt3rZDXID6UxQOXmQjVWeMZmh8Fxj9a3W6TgQtJrmT6Oh+Qr6WH7Y2ufkbyCVNilNOYc4+3EcqusUJQBEeVP3wrhrZkqENtrqhGV71+7tGK6RQsaY0fcj4W832b5atoKgvIde4UjL/mLBjRWReRj916JUA=
  template:
    metadata:
      name: grafana-admin
      namespace: default
