---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgB2+xoD9D+CeNWjxELc+HNN3mBW1FiP0FPvxQQ5m/ISuCdnCW+yGzI2bXw4VkAsx9VdMvlgWckP6WcPuEXvOdzp07Db18Gb6AjYIB9fT+zpOxCzEMn4ZptGyGAdg3BRY1/slEOfxYcZw8mOwGKqc5IacjRUhonSVq32ik4uV1BjmFlBQldjk9fU9n1sG/b374vjKKfc8TBfE5zFTGP7quXMSpBIxawV2uu8Fn/lvWlv0/oZZdHqut8aQ8NqyhDmK7k99irhop2sZF/2ctdOZmOYMNNlKy8Az0rWrNfAzNvanZQreILXHlTz0pSIIwFHQGjN7xScWcZu1cQY7hoOwp53fOC5zZPExNd4QQiczeqa1xqVeLabpavALC/f9jSLXK1I0/iUzTxpfLt6h+MnU/9J2+muwPf4Kyp2CLs6mZwFpGDXndaHz7VyHFIV7Nl731uao8sD7DF8tpIgCpZdesmBdFeNRatVP8j2XTFgc/2pYhBrqvnJZ2R1GIvAWdUQvnqXWER9PZMsGi+qjf4UCv/o8FaPFg4R6uneTezyI70sDIktT7qBOITEVOeb5n5X2xBCJc1Shf7Qeb2onNh6Si3lseStXP3qfJpjtsnaCUy7eKk+v2v0Z30D/3qmkKaWea+4J/j5kH/7HCu9+dqogdW+lK5PDAs873SCT1crfWc01JnVLnsm1swT/tRsPXq7ZIV2B6wyB/XsiZ7yhBTwGlOG8n+6do/EEipkrL1zSh1E+M+UvAQf7Uk=
    admin-password: AgBY9ityMjsSmM0bLbJ+PiydZ22aD1OdsPDncTecDDOLggEUC8APEuushlWQUEzKBKzrl5lq4kgKrEIdy7QKoGZBNzgHvYtnVgC/OaDuch51aL8YBhk7u34zDbBioOtxHY3Bpa96TTbNUVcOy2OvGUROME5t3s/PMEPMDJV+YsKX4iiqy1eLYpDoi9IffxJFEEDMQ7sU0K10keYGO1VnUyoKOsmaWpSqe1iRIuXNzWIwBtANFk0xQNMPHBtrTM18j/CHvCoOKmECa02UlN1UsgxFBoX1cL4ppdR11AbClDaSumpOzBSED3rPKA5vaIyJNJyVkN27Vdg4sc5misv6Uc1EjgyhCNDj9+iu0eSeywqk+RnNuALotSx+Vja6B1nN0oPXq+Vji1AZTw/nyiS+DzHDuXqJpqzqyzybjTt86aNiq2xOKCK1ZlvFj0fgDRlF7frCBDZWh2IQIBgcU/sgaO9YDd6c4ZCB3lAwC/lKHWWAMxDxRvc1QTwmwg0xsKyUmOjMve2YEBCbuRsBuDcawilKtf7mYIthOf4V51LWGQZyfc3iSOPB71noHw8T7lYWc6FBaz4hOD5bFHr7VXPU1Zz5cSHsL25vIkX/MiKPuacyXg9ktchg5oRyIzFCbRKwb/xQz/kO2n7sVtr7iwBbFqxDW2neBhS80m3/1lFzroi5F5RiAbA3CG/5Y6qCbwGhpsL13vbK5JefK55UDmU+jnfvlS28ftTLMCACm0hdQEvdKl0vJn6kWic=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
