---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgALMUosIVO+l/+saIkwXDSbaniqi3ujmarzWX57BFKvIL+haGSFkvBL+uZsWuQQepCEreNBFdIfpKn1ibLctUAOJ/mhy9dYUfRFgCq2XkZGOD7jrt7XFgSDv+6sdnUENpE7qzlHky8HeveGF6jherWRhz2TqTiSYBuBoGXg4ygOWUfKEpM9fnCPIxVEwK/wIJ+0iH2wLvzwYljEa5TcyzmLQl1LjoQYYW//7EwwtHh5+fYCAe597wcuVouPxXBxvOcFJ9Ur5y8cvyTFVzz0HaVZ8hitaVrl4+oCGoNKXRgAHTgvVdVHoIyE2aqToBA/mg488JllAC2hoX4HtJiiFGB/p+QeXDXz8L4FGarH7sNscddyv7L6FiFLL+bOKVRDfjCH4kWuyReXv+rrPyaDnKClKKIN9DJJ+pkoaRV/7PkQP9Ebps4RJ1jtZqLU60b5w9cypBhbjHPGQWp60JZ+uTJTNZOfYkep4Vm5/SjlTs/8LTSkGg2QkfgzpbOrRU61HHHxXqMtPTVUPk6y3022a8mAKcc4SFDgH2OMjEWTG6ipB6eHKTi9MBJSbpSzcNtgpIY103uDwgBsszERvzW5TYCvUsvKR13NtJHaxUKv9sBVXH0GYvH8h456QYQc/pcWxPlX3JkXyPjwdor/SwSvmDfFaYMhHaDEs4eIlFCuFiHVJGiz3AR8uWbwIgdIz2Ij04YeGlw8dsROM6pz5ZU8HW+71R6DjXRTXp5VQAFpFvCcsaicicAo2QU=
    admin-password: AgB8o6LScbsA2siMh/9BJSSvpgKJzGRiuFngegr6qzaFzsE6moEYkhbV0IDEbdb/AaLTmYjgNA+2n/+4bevv46Uljm87sZx9sizMMGM1Tq3MTBd2bPHtLpYMchEj5SCRcpMyamG/PU/L++UPNmjwh0ChLwD5cNMA4sGXf8IhtE+NrD84YWygGtXtvkfzPut+R1Y0CJX3drnvdYlARQEzHgmxBU/MbVkJPV+TODBPzNUuVBEdGfWL+G+GXiI+fVO1GG8uAi32eQLBkFk5w9+iHhzAYbn57L6wTWoYsWRw7vr8QNxmrg3JaRq7ZjwChtVFYmrwPhXUd87AXCcJbko+IKGB8Pvh6Tg4q9C4U+95oMpm1FEOriamHjlpGwsnt0GHXc6Z3jbqNu7GGEtP2OGTq1xXX9YCh3HfGF/pMKBV+glCFgjtiTWd8Md1sYr5x1t4fdaR8TN0dJfbY2mekmBT6h8sQyt+nTK1+Om9xyWM0Xm9SBEOSkDMiq/xzRL4fGwajHKFtjQX7YfjgaR0GSj6sFyxf/yvQjQ+byjVFQnCBXgC/Y0H/wHAgxuNBNlnLSJ1HwUj8fQKam5ZH4Yiy1H+SCO8D1zQCOa1AtBPnQjrvhuqHFW8lZgDV9pB816866MkhAJ5Ch3rbLLOOcC8CCL1NQUAXtgLg6JkvaLF2/rDsfKqTcJG6RKHmADroSeSuQdLl2i+5wiq7aQ3Oa8eeItemCHg5MvLlxL8BE49mUdo3GBZu5fgqt3KOX0=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
