---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgA+LRUQh8lt2XSkMwvkm12jLTQ/SCzf1lyAF9nhX7AzZtwP9vTDvJidQkBpc01MRGFNfgfdqCrDBSf9r70/spYIrabmKbRxA3kXrcmiaSabrddIGPF/6xRu9/Ggke8ZzSkKXQVhB0rq3RRiqseDNWEpDapSMZPsotdS52y2i2cn801HiBQHwn+I1csSLPPwQrJsb97dFGIP4Qjy1M8+bYXwhGOq8dzoo+1zPGSPiHTS7IkJvrT/5veoYkREkn9L3z+R3rBDCge1J9nnWonOtjtJA5zpHHN4DS77Da/qtuTT+FuRDZ6lnXJuRg6gwGro78CnlYmp1Wcysz3QWxtRkvRb8UHoT6HhCq9NqKfDx6nHNdxyARkGKXyrPuYiwMeEdJBsUGysfvdSUTZWtrs1DNzC4yX2uNqXVzQwozAbnqbQuGqRoTOBUI8kNR+5Pg1q4xkSf8sjKLc+BEdjRZEyytC8T2kP4O471qmjuAaa4id7mC9Fq2ShaiblpWzL588I6N3sw54+rMUXX1klS0LcZ8FdVbi1UXeQqQm543fnI1i0cH0bWoO3taRdgdUJxZ+Kz0KA/TvfqTXW2GhGtnFTqCV2tT8CtOs9858XAUD7JABfjQS+2sCo15wC+27+mITeuCWOVMAfXLXZod1upjtpQc+9nIgipel+Kc52s5vwJJTGp+snDlTMo3xWjoPLu2qhDZGkV4jdGQVFXXWpDAwBuW8gg+4sjXlm//WYkyCWVyDfGF4G8q81Ezk=
    admin-password: AgA6khQqWlZ3+sLLIRpP+leWhsBbgF4ujzQ/AsRaoT1U+i79SnjRlrz30d0/TW66ojEceSi7kuk/AVYDBl336+FToOupFP3N3qzE2a2Rmu8Vzstbfg/DozGYdnU3t98tb2Rfj+vddfdipC+i2MWsjs0AWjbXiU/J+OQWBaYoB6z2rCs7wd1PGjAysk9HB/JAUBEZGAKS9WWCFTMI7KT8LU/JZx6/TkD/OKEXhcJ5JdeuFdBu76V5WS84xSXCC7mcKOZcm8PhwpA8YH6DQQGu0UG4TQT2ExGIR8v3lxbcs7qrZKJvQoIZgpEhj49YJlNfv6Vw7rqbp9C63fRFiiA94L5rmvX0ix+hPfYHJDKJ1aWqVbXGD62V1xw1SQ5H+DafjqQIJEHdgnnHb8ggtsYpG6XconGAm0o+ffkKXdt2Qy8nM2tO2oD63MwHfEvX2UpDqDyqQzTnjj6KGTAsuRCrRzSUZby9fFwYGfruptJN+2LPJBZFEdAXJN+yYa+RFPsk+q9m3Ue9JWMfOi5qLRmq6rW/ZkRL3TKTvKGq0IIDGC6wS9DhKQKfOU3ctrBne1glKiC753FXA90cQOXitR16Rth7fjbNDTvASuOMw8amMaPwl/BYQmEKtq3zd7lCWv+jEIzvVZ5KNwdbkLxFsgNUlPkYKvF9UKdHIn3YghdmBf5TcpkyDkkY9QAldsHlXiWFWYNZtOJ0OWyz2ft9v9hVpJRzto5eMgiHp387jNlRZUYiNpa1Lh6ABFw=
  template:
    metadata:
      name: grafana-admin
      namespace: default
