---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgA0IpdBify5UL9tQBIBY2MrpXa0o/5NWDyuYt6A3T+fDCK+rYBb2ueFI5+FJAQvc9WDlncIOlxv1qVhuF6MmpMSlLLmQiAxOzP+muZa5DFlFgcaiqkOdOB21tkPxwxTLg8Yzw2ImkF07U7enDH0GcOhfLwFEdlu58MCbhpbPcsRcecHMAXEmrGNShA7++SLa9pcQtkDEty6HQ3tKga7JO5TmspgWXUgommAtw++n3BLtNDdZEvV7OZg+yCdAfJq1VBu0voKKqv8Ang7bnVwJzyvOTjHHTQY4M7lJucLEht0JhW1v3fGPsn+47nXywROmCCtxVvkUFDHsKY+wHq75nq6lw5kuYIr0zTgrDjN68XveDMAlMeOy2stuVaSqACXdVjRgS90GvuktDuRG0dOwfZOlKKZl033V1DcoqXK4U27Ogjs7WtvT0Wqx+NTZoRwRd47MaHU/5IE6uU+MaHJVpegWZlFtRNWuiKk5qqAsPF/aY/cZhiofC5sNLBepd/+Ms+Uo2pvmbE3e4hqYOyYDomAkmOdbW/c3aheDwe2XOoMLhH911WAXIXed/JhGuzKUs2uw/Ktm5Fep+ibJqLO+VMgoLDwlkRHjK3kmVMV3YhwX4d9FZVYCnl1GWQTwVBROniYSYHvCXrOhok4CXPsjSmPKDScRkNMhATREpUSP9OGzWhVRl4Vs9w9+k7MxFSArcpDf5HIJFXK4djOdqc1I/vm60mh9MVmLu3kYhMy9IsWW8V96V0isWN52g==
    admin-password: AgBxucPcBy6x+hOoZfdBngMZug+tMIXrrtapIiLBpjfXcyMSBwPeNCLh5nd6+qbDPBzukIJiWJ118LWuwCkTwbPeXDkJw9Q4C4U7XnAW3IZrU0AVrx2Z9supggcW2sPAS2ta0F6Jvig20M/uVlUG63i7uG8uFdHua0w970V2XHWBbWsmarVJv9ZgrxeQXOhn4mO0bbR0rM+n+IEbJGIeyaL0K4LriTUiLYOSg3/a0FxwrOgrZUlwafe2YE3ay1DRR85ZRvI+WgrpwjD2V9TBMBYafoO/3M0yd3WBUv/r3gueYAHIfn8+pgK0U3GwNdXyOQkeHj3rgRvZ9i5tvkbrszSSamwnXlQkAUhVvi9aamu4ezxSAkkdIJu1ZOXlHEh78M2UwnJIEbkRt/jt7PNpVMhP558xjnf6ApWG3eKWgTpqy01uIlI4i9Ep98K4JSiDF+w5dfY9IkVfQul6dtCFZCqHKdW8/05gK2yWCpr1jns5Qkdu8qnikAcuWsXAWGyc4hAkNkcYIFSh0q1QOjkqbZ+urbuEoAPvZiQsE05Y88Cz5d7cqvwrLKYAljA8hJ9VUTyOkp2cwy+l5TO0S/j240smIk04ek+aSK9E7S/ANjdT/9eKEcccVDsDnxkQ+axV6t4NDDlzzZWvHYbMuFbEMOmCnibVkpO/gAwuvaJTdYZsf13fF+HhtdJRFd2Cdw6gKDdKpg49cE8OYtdlCqO9c1B7ydQy/FXbRbbo8t4DHcLfT9+ZWL3X3VsjSA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
