---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgBqvarU7q7vX+LUTX0sOy4nGXE71ovH0k6279CXLl99xEqIFnoHx2QYQ8RCsZR+CVEOi0V3YQR3Dvzgt/5/VmZQFccX0e5+7al5I1QTWETNcFB6NUkcP8lBPlEnndWdwdQ8nyY4q8gYbQqf42Y2Yw2HujG9PYbECXXXI46OJ/dG3nQoIqAlPnhF1T3aLFij6B9JXCBJm435hyBiC2taIpR4LfHcOpDrBFtqS2TSiTlNlEe6Ob1NuOX01+W23FrWJMyn6LBJdHHChFXEBDuOou6OfcRFSy5cGNxOIS8TDx4ZLViWDGUmKOWPBAs2vx3oTzCm6ugG1B+jSW94F4Ksf25Wp+zSiaCjYEfwYbpuKM9zyIa6jwpWaN2yjTI7q038jng952a0Q8wMHZd6PuBdhdHZ+6VEdcPAIIWeTZCFPDv8R0q8SEPM4SAcvaiQKh7Ntm5+FWSyWdEC9jRBtAim0vTZJUF9yRbboO/QV9bwQN9CmxNRCrtLkUVxTYeRNHVvwGbsB+3/vMopK3IUMCzDD/0c9Hw1VR+9T4CZjhJf6Z2TlrYioZGlEmNDYkgcQzCh9EiTy44/pwrNgEJk6leFIRh+sKp0RJUMaRHbC2HSBdfgvz7EQ3c07Mi7IgHFyLkwRzxlDLsRunb14aLArskR3YIdznreSugbG/Ijnxbo3fIYRuz9WLQWKPUgcXsKzja7eDirEn4yxxMDAiw/9OBXs8LdVTBOaR8gqyPWHp8aD5veerqk9eUCeDM=
    admin-password: AgBtYht60kHtb4vr6bOEyz7DUPlPI+3BJgJEOyyXOPC1XBe68mszI4sdpXy24oqQvGlNxfiLE08GxDt+14zBi6OWiVtgS+QjdqzGnKkYssk7lWkBEIyLep5piK2ywVRrT0PzbjW57NLDodjQYQcyz7k99XddtYJcz9RzIt0GYMSKJ7M/OCycJTmq6b7x16Kn+VemhidmNdT6KhBiY/kBtfJL6BCaB9vTxUTdkPQYmM6SLHaWeaz89ArYGvjPnCslxAkBf/2jJh9tLH/ySz7isB0DFQW4vyN9Ikq5zGPDZrNB1bQaT1sowcjj4kQEArcC5rTjKpqzxiVUriOiNOD9Iv7w7RFYHsB5gCb4kogXIPB+9VPBwvNRc/9EOy+r8FMdv73KXBQPo/Hp2sw2HmFP23/rdSzPgD8Xe1zqLSJp8OGy3gHmJk5h1ddAdn0YiE4nTwPVt/fDCv6COD7AaPqMia+bokXLs3l2mMHcGKg0WyZfCpHrCpimaCCROdcYLaftYFrllBCs7yOuzE2k75ESXNowH9uoVaRf03Drd+s7cpS1BvJqaFoiXUsMxIYZoyaeaLXc4ukaMXAVONZ+mZ316zHQcQxRHACMC9sVR2y7f7GjQYwTTIfChvlqIy9o5/GywRBSgYkgj+YAcYzqMuu5JZY2VluCd+r8RytDFSkygSCTZ4qs3L0PrImwRTD6uMs6cG8un2ig21ZVR6bdJjDtjjkjErzUGmrZ+SCqkKz7K9GBRN3SciLUzfI=
  template:
    metadata:
      name: grafana-admin
      namespace: default
