---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-token
  namespace: default
spec:
  encryptedData:
    token: AgAIbaQToU6Mf+iUL6XuU3eer0LoHB5TPUP2529ZS7VYAvEzzXNSVKv1JzE7hnKELBHqGE5WNS59V0UkWr0irB4ryNn9BTiTNLaqwHEEAxPSkoZlx4C74otXQNvwf0isiSui9m+YPEadqBZqbQZLy6Q65+PJpo0WXFtHC8Y+64jtoFFnEboi4rs6tgcEs4U3qrrsG/fGJZUIhP3g1qFEJUn3Oq9/cLXoFXrGxsEMNBeM7z+4nF1F9wxYFfLRyikvZuIAg8FKWjE42RKBhQ//GNrRsxwu01jdhy+/LBmLq0Uv1XD7ihl7iQ2Rj/o35LFuQf+vHxEnllYCs/924gooTDJsDLpLGvxGClKwLgRDFBROsgGfAXDCyj0QzT6MBl8uRme5C8O3v/JvTfqnWjGkt4c1j59ueCNMJ1C6XYYPa1rCOjj7k0bR1gepQWF0hASq+vhRxl+Mt/V9eD97qV2adPuw9h9gusaY+goMSLODOSPfRZJ42lm3t8TOVJcdrGyqmwyqyMp5rfCAm48q2rmvtJnqDU+Oz2mvgLjnv61nJW17+aTwMLeQ/yV51bNG9jTf5orxkKRBd+os+3ptsbtffU2hH6AW8uWvszzxskJG1CnnZAbLcrR8ouPysLajofHcnnd+MaEWVpc4OUHN/TlRD+mCQXQB96zXAsadje/Q8pU66VtN3LjDBmjniWICxl9TXvI=
  template:
    metadata:
      creationTimestamp: null
      name: home-assistant-token
      namespace: default
