---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-token
  namespace: default
spec:
  encryptedData:
    token: AgAPRu4GRhHuey5fL0EMQlkY0JW90M9+J3+Gww9J5P4wT7QUq3c7ZwxRYSJ93moSuLRrDvCK58Rw85EWiqh8FUEeEHi/aNSSJzpKEAvJ3R68l9iX4HyOSWj9ZKytknXOW/zS3X3vNZ+ZaImygeM6t7pW9BFS56CkTqYUNUFbgPxuWw0gV9m6oNuq57BPdKnc75yGHpUaH5PQgVDO9FEiNbt/aRocER8MfopFkPpQvfWWmjr//5jnrp8vzlP/bK5FdCnXDKig5mvztcri6hgLm+/2NYfFa50+0px2vGRDv/2L0nMhhDY86FjCson0shViR/TZkfb+lmtMsvaa/K7cdMcBKVZtNfD0O1KTNbEHMe30CZxuSOywX9Rvr4+/f0GCwOct+6jQIVqjKx9VcrzHSrgM4GVGfU5704sanlZ7OvvkcE2/qFN8PSM3vL7gBgVeLEFW+TfVEjcLTnlp0wLsO/rWb+tedyvxxUH9J1xu6lA5U0E/12VcrSCxTBdbFALwErLD5rPv0S1+mPD1M6nSrzoa5Kin4hjnMvi3xI6Hgz5eXVTmt7ssVT1m4vXE07hEJDLR3QhhVmi0h0SG/blPd/PYw/fAdg0YipFbF9NdD+TkI93/PsBg9w3tmvk2nfdUJp9Ty+alEXvvhHKYZ3kt6g+mhr1hlMxiSiuVLjL5HdXrK3AJGEZjyVLqJMQpC5xBEcXGjg==
  template:
    metadata:
      creationTimestamp: null
      name: home-assistant-token
      namespace: default
