---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-assistant-token
  namespace: default
spec:
  encryptedData:
    token: AgBg1Cb8ZzCMPnExKC2DPYhSlBR+UBAddSTWovo0vrKGEGS4ja/4QBeFB4VHX065tM4EvPg8I73NtAHrUW6D+DoPC7tC08aYJmR6moBQr92GQvQ1/c/LUjeues63WNux//okw5hKJZ17L/SOR322WMHx0aHrNLxFC1xlyjWZmbhVjBZOahYNCnD8YO0jzJxHk9KF2kpA+UAvH9jT2IlKt31WhPpuWCbJv4ocHaoGf9cJOVjQVYvEzL6LcqHb4171ADqzRMjYFwcJUZd/j3+xc3IpnE59wmB2+ylnoK86tzYKGop9N7jsjVArAhl7LyzHNhOnDmB488vOWyJJ9lPe9gPEYntdubz3pCXS7UC0rCavfze68pH1dBRaN0r3EDVuR5EfY1UGDN2ClefZ5LRwgao/8C9ldxHydi0J8WHFSz0fF7dEgwVA7Xh2l1DIHTZG0i5DhaHcLFeo4uKKOY3bFnWYutmdwbilKht8BSWu7uDcj95tdcb2sjzVroYvpwynMKEOK8CsBv3AuG20Y0+JbOnFAMlLHOsFyzDc4/BuHhDzETrLzdIbtXcUGeSpCpKhN/MMv7jJx7FAEkzHZ2CjdpXIWIzpofR1x546vySDvBqU8UvKSeP8dDxT5gG7+CdDJZU59FlifBBXzabBKTqZE/HKxN2sKio3Lvy9GPvQRcEPXxnTcqKNutj4JQRTb5jj4Vi19KGnQ0ILAnZwH6rUFR2nm5ncYfuXdwnQ4TuXPMYNrzDY+tFBlAANQ0N7eCXUbGkxhvs1S1+8qqxS3Eik1Urqkw3+lhdCstdaCwk9iQ2V2KWWI6Uag+SsZ7E+CKanRd8AVpJ4SlBiVlNa9xBwd5XOEtsjCDc5FFr6gJmrjKmIzKQX2GozxwdxUZEwwIkSZE9tEfCyOX+qJVa4qF7G30/FUG5go7oW/e7b5MUG49wIqbazuBOhNmE=
  template:
    metadata:
      name: home-assistant-token
      namespace: default
