---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqtt-passwd
  namespace: default
spec:
  encryptedData:
    passwd: AgBh9VCo6/rMDmPGXK1t5Tp4oMf9U8zUWti0oy349Sf0mZKBYT+wYydFsSIEpuEB1+gs/nTDhR/J8p2/0zdjowIyHOS3Kj7WK6vlQtgKD5iOMnYHN0W7F230Z0LKmszCy1wZ6uZ1Xd0UQ+a2o2A3vgxMlUyfQw4t4xbgiEfKwrDnnmFVhpjxPOov5mVbm//k3PobEXCT5A4lprkaD1zUk+KOKawx80i7QmwO63FVJ6pIloi6oGTH5UqwOhF0Viy2e9VZbScCnw4mV86o9o9apohaZ3pPH+GR03R0+VBX7CuYs2JjwTfQWmYgUePu0VICy2KtcHVKKwrn01k44xqZwazV8SS2aqTM6SpUnYEe0mP1i0Otql/Ahz0pJW5HalDH/WKjxM89sz3gHIsAsoEfIpxM/+SOt1Xl/GzA5MaSq1stG3v0HHT7u0tJjinQlaykbM+BrA4I9g8RdMV/YQtrW0GF8MpReD/6OXDXomU/adTvkZY84sNJyEyxUnXJeh8IPB78WG3gEYpvSM6FzlOgGlPIzALq2srAwI/5EgZgzs03bQGlTywPgY/+XSW/5twqaZ31h9zqlFprFUN2/6SZ82EqtMrqVvZxSJE9AEVJ8wcvrnMd8yRyb5kYATiHQAXgPUedC7nq8m1EXn8dki5vr5EWa4uaevbPU+rHSe5i3HfHUEqF2sxea5YkqjDIiDxft4S2jvPhFpTcDykxes7AYPtWuhljNlE+eUHJg+e6Y81VPwZbN0JJj9YNQXhuYArfbqZXlUVQGUQ7zP0wk/TYuH5rElQepmgJK0+wEW5uI5YhxFCYaCJDmCI0uklvVm8nDB2LNI+AVvBs+GuZsntQo6DLzc9WQJqgVyVFsNP+zGl/PxVS3w/9pp8C4uWNxuTus4LEEs+dYAKFMWIKGLpgFhJcBFKkpJlzBg==
  template:
    metadata:
      name: mqtt-passwd
      namespace: default
