---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mqtt-passwd
  namespace: default
spec:
  encryptedData:
    passwd: AgBxXIWDOu6z74RiPdO6lqGG5+n7x+EkkbsS8Dqsvk7LWV3JWRWkp6xDNFdH+lOXK6gYROqVEfC7HVaB0QZbzF2J8Jm4izDC1zrsjiOlSmhdoUnITITAHmXBfg2d3DU43kHx/jCbQmGT3Nc1OLFCo47Tu2Z5GvrWbVVb7QA6DnMoGqbRWT5jVjhGHNP9WQUOIx1Dihzj7W8jHlgm9NPgzsZHk6yTmMP53/A1SxcbvB5Go/XMUdLFYLceD1lqExOmGMkUzJRxx+6ScjUBLRsaA36JQTE0dHsDmVFJOpdwmRIQWqtpKmSQ0GGinfeF2uRXxmE1/o98yk7IjgX1O3gtkmQjggP7OrTvq4iA51urJ1ZsYcl5lNbZ+RqJFXEoHTJrFIQ/vfaualSCv+b1PvLlcSPDj/qFwBaX3PmJJEDdhTQQz5tZXpSED0GatqiDpu2CUOVU+4Staw4/n2jCYatD1Ek4D3g5IBGZ/rAVcy/RQ/ia1eJcY/vkN4EfEv0MQ+Pm1x07kSd317/OtTPTpbgSQSS6G/OGdURDKRZGCiCWhDHPVEg4hnMMKflHllqsKssJi1KPiw8SPw1rvXrmbqsKyQikoa1ZKPaT810Hjwu1WAJs2Mc4r3camC55mNA5hCEcaBuW1WOmqoCw9lj4ih9zpU+MNbi7wFxXwAruY3rgqWLcBIE0Mpob6nfHFQ9elCtJB2VjUUkMJXkV8IRtx9twWBYO+osdPR/xthQ9jx2jQpcmaC4sVzJ9q8g6v1g4UOsXt9ZGuLxXesGhv/CYoPozj0cC1+9VAwont1r51saxsUeg/wtscTDoCtN8Jji66gHYVvhs8pvY6ZC4YxmI4r0VSNJjRtHvm72klJ8GMHJTCr/m3OQ5YgvSoL0zBwKrwYxDq77W8lj1mFMAgqMr/a0+pcGd97zxvii3xA==
  template:
    metadata:
      creationTimestamp: null
      name: mqtt-passwd
      namespace: default
