---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: playnite-web-credentials
  namespace: default
spec:
  encryptedData:
    password: AgBvtwZW+14LuunDWCJPZsTRSJGzEdTj8wNN0HTtxyv3d5XXivwYXb3D1bUG3+oNcPSpuubBNiUEh2t9rdZo1qCReppNkiQfOaMDQ8mbl3N77OB5HLnuePrY84mp5pydrlXoBfI5JN/CpB5hLUxgxkYE11EsazG94VfyX0jru02VRz5ViB4qbWJgIIIt0YjNvy7bUrKEYkdo46R8Y6V3B9zK7ZqFh/eCg4MyrAqxTeGFGErlFZgp/CzK7sqNhGhLLrzJMkxEoXCs4Zqyvr0+9WqGN0IIJty5w4UMyOfzbEONLFctOM4tvbQI4iuMRL9ctThIHZ0Yzbw0am7NLIOjaKKT0H0eoTjUgYZdnRDDf4USUWhhUnI5G7/93jF5wqUPInE2rO9TV53/u2IkaoxSGyAG8lv4mF2y1Qpb7JQz0uPlBMmcsW5O5rWGJmL/hVOqDoQpUGJnBqftaIw3MzxBZrgmXIwWfKMMrqWwzV+Nx086P+e/9SUa60yThIcQYtXICvYVyJdPw+0+ZX9gciHvJmPHQIqW2kQLSvK4RAuzPT4aCVHJVFCn4kjTTAU+5THAgL/4KWd7pa2Jic6uWBkse/sfhPGd26MLUa1Aq9b7rm/PKLYJfsyrHWUOfvVJR7qsM7fiVXnUGqQAGZds7BeFnzEqYkWfuW+VBR+qAUy3Wkymg34qbrAe52pxTKXt5hrIaq/a92/KzrBvk+AMVnJMxBjhx2ERLhxzbhGiZo/L/B3CjT87Dbedrh6e5b0NaXK2p+GktUkEya0OlwhvZzn2T/LuLNO52CmvpMY=
    username: AgCM5UEFOk3on4qEEk6Q/La9VEGomT1f2AWnKtRsH4+ao9jmb/SfftKijU70d5AACPoxzr0/H3HuDCn0YdGiCQdlWLvIh4de+ATzaFbX0owFeVkUfjKn244XCyYWpimJkOB9M+VxqGT7poZ1Rg0bvwMm3OTUOVPOegmSzmadwO/f4tCx2+pmeDu+30/fU+QhXegKhZpALguYHBHr7VuMlgYzrcWZge8vB8IHsOBVG1yTX1rveTCKcjkYvgD2377JlyUxrsKpyVS1xITrzoqQIReosUOAMdYmLlWvdOSDxnA5QbHJbAIQCFN4MbSJYKpv+aBN2XkR2sw9Onem5YP1yQRYBD+PReKdOyvkJ/BKmqJhpwcXjknLp/GbKcYK8ZV1m0Q16lbgXtkKQqKhU3YnfVcKJghGlK06iZR8MBTC1vevqf8KPkdajOHKN+ibKWssn55b4iIsaNVUBxrSy51zFUmanTbWGGZ5skkXD5X6F4E5iFBlyvJfFQOfj2LlWew4ITNEyLqaGYi6k20OUcPhvnsMD0OVa+CJJUzEN/ti71KuDzDcx6Dxpom7wBTgPW/AXr3Hbduky6ivIpC8FRrZfjPXHQaYt9JBY29Z+qLExgmaFZB0uSSZlmz+WIUZc8e7/obOJ7u+fPlw1j8vd9wQOV2olxdRdSqRWYmdRNnvfLigH81/8Y/5PvHdlMqu3u/RTcz78/j6+RhzRMjKVaPd8unzsMVTsoVT3bc1TvI3b8pFnxvX1RKh+IjXZsZpYFajZiKMA/aBOfvoQP0hzuNwZ9F2G6ik3BfVvUs=
  template:
    metadata:
      creationTimestamp: null
      name: playnite-web-credentials
      namespace: default
