---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psn-accounts
  namespace: default
spec:
  encryptedData:
    accounts: AgCb8UQ5qbnz0QsELs//bA0VEYk1PKt+qATtCL9F4O6/cy66XKJoGYej+WDcL0vGWIAYF0ENJ5jUQLBgIOHDgLqvYxBWzxMW54z5qqrmXUSDpvQHx2rFmvTf+ZC3fM2cWHnfZcdZnZFnNzB3U0yg794GbYAkdDB3CpbMm1gMmjkMGTzPPrc0wjt1Z5FcnNNEbLep+k1ZSzBvWrHylYpKo+K90uybxsiTdfqFiQjqyIgth894qLcTxkw/myHrBGc8wWWe5Na6r0XW5GI1edHdBk46YEmf6mJdDJpWE9CHixD8ARreyqMGzFxP9f4cJoOjphoKpukavB5zvzmuL1fBOv9QDWWA4zi5hFvHdPSm114y4EQW8IXotZ2AMV6vrhWw3F2x6/aOpaRVdj+2GYxOLoXU6DalujRcR6kFseXh4aADPwCQJZXCAGh4dRFlySFJ+9z6Bbn6Fklb75ROOCtTk/GNT5DVbUuD296//zo2hp2bdLOV/AuX4q3dJF/9lhf5LZKhpLZQU9mT8nzXrh1h9kw6fNZ8h3+VjtimtFDfMWt76PQq9hHvQeUs9arjiy0jdYQitebcAAeVbqRZJ5nwhPFheBHHwiPAufdELyeMAeIyaqjex0CItqVwhCncn7FvnTQEBXo+pukgL0LPSifF0Kapz5J3dCyMz1rxKHryg4vv6WMYRrFv1aSwPdrUixnIaxzFHCImGaTOq195abFeXx1vVVrKaf7t/NzH/f6NuiVC80TlZSiYEpWf3KTHFnQuMxiLD3uQYipAduon2KqHjMnRbkqKK0x3cjf5IyNNUb/eJjM89AwZTc8i4NdsamvgiNnQ0aDpelHTRcAxkYs=
  template:
    metadata:
      name: psn-accounts
      namespace: default
