---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: psn-accounts
  namespace: default
spec:
  encryptedData:
    accounts: AgAIA5CKIDyndfHnZwV+VxRz3KoEIkSeDTGrGBuFxoUBcd1QIBxkvGqlo7AJ2fyX29+xsdwfgYS/LxJf6qhd7okPeCfm6s7jRJz0gt9pyFsvfUGesopXGm8x3rhwrrYMeerTyX0i0eHx4wvjUQDi734YAFH6g+qW4wIs0dHwPBszuHVeCIeY931CPzsRr+5fAcIdK+2Gk6BilnWDSThwz0l8johfwudrh+k+jXwpFwo2d+wQ0I/x22ftXR5k3l47TyuG91HcJNi9KMJzjPHftsTd07uZfZefz5w3t0W+TuRLzhubLpj0KpbaQZ/AUEyMpEBeLdZi7T3t+ihfwrv/hSlOiGOFMkUZMux4gXbISttYlwd6e9WIHkoa0cItU+hvkkhrGCkLRuvr5kWxRyd7JSRR77Df/j5YT59HYX3lcE4R0Q8e5y8uMgrV1qUfzeyu3G0R3cH9yQCPWrCEmnnELbCeZTQ2tiG0laz3B1I6+Lay2yx82LBWG9XJ0yLtYImi+oMIjeqIbCFWBTsN/iY+sAsOM2+lN/SWzV812sh+MSA+g/NkZAvYNwWPMok6xmWzis2ie8LryG9HevbHSEqgvNH2armYUVNspCnbQhURmiduquTvpdoHIzR5iaMbq1R/mohiIEbLPMBTRe+2IuUORh8Mz5AQsTPGshXdJ8zIvN5WyY267ZCroXGosuM1lR+ogptNJNpCPdgHMIQTCJ8wPQz05QwAvWGvhNEz6Deece2zz6luVCgY/wi9aj1o9wkEM2o1/v0FmyFGD5b2VnEIxyGDXDuuyTgXzBJOofOXrUJ8dwYZDhZptm3XAwqexXNxOoh1YbJM426srr7vxnnbzQ==
  template:
    metadata:
      creationTimestamp: null
      name: psn-accounts
      namespace: default
