---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCIqis9mgA8sHTVQ5+R6N+WPw2sEMWRHZU3a6twytKAYHqyMDt+x4RB6+dpEtfbbpeXUo4J+F9XRoItHRbVnUikY29PmFIKT46V3MPSTZISgyzw1F6Z/3KWBEMiEr8AXADFCe2T69gwo/cWVbtvggApTyZYRDyaxtq2EgIva4QW/96UxU7XwmmrToR0eF7ZCp/rzR30tIzPjtEbDvmbMxzHrKYhbm/ZoYuOy7cv55oZS80Fu/Cw0kE8SPSkQI6/1gqlEeChTHXnmMIv9Tu7+fT+JjBK6JjmcfPY5T3tSHx/1pGlQfkPm1c2AewCD3Qg26CcRiP9EKeHt/NQT4SA416pOgek94xS5HdB2OII2YCPv70+WUg/GjL+w5HrVPPiqWcT59C6nrnBuxr3bddeOKhRLuR47fxw9O8HQM/CPmxa87MICaNJs7/lrS+EPNlM9pKLGkICNOBB3/6FaH09VDweZpTUdkPC1/GjUvibvWcEmazKhuawlLLaO+fzuaWdmJVEkcohb6Whpq822EYMd/fPdtYq5TciwFI0LAQvDbhmS6T024WW8nwuuiIDUlBciiwD7+ToJQSbKbuaj7vySG4P1qA91Wpo/9Z47e2hgJ6w3jU4037HH+NpeK6opOJUmIDYqSrh5y/ck9tKAyXOz6oc0JtSsdIq8Ljo98U/jEIcc0vgcBrPzLxKz7y2kMWK8px58EqlO/jUFdvQjhUIYPOQeh/N11v1OzObU4rQ2h5wJivNzD0gIMRomiPjrjV+1iE4aX4BRG9l59zvAzGRHfq5aceNUpYJlWPrz7NZOfYFe/0EFvrXpdOde6kMGCL7osgfcNtPQasCpmSDiovaanvVo2HnmQWrpZzyVT3aeeqYtkRiYCPBAQSKc8JFzV0V1HThylhw7poRa8C50Go27FqL+pByxRPXkIGDf4DvRJ20GsW1p5kiamd1c5ahKxbnO7Q/lAQpaNRP19lgPdf2qWCHObcRvphzhg==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
