---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBppg/pvjnvRq++6dOsudSghHxuv1cRwh4WIiFH4FyrSjS0PQps1G8ju1S9Rp0/QlHgxCdxiVfTFxCaFzgveMLVGiEruZS8vfzy9X/EeGN1iDazFGOYmdNEe0Vi7wsiV4HnGdBtiP+r82N4UicwLqePgrJhB327BGPemkZi2YjwQEwINvgNgBMvFR8X1X4Lmqnmnuf5+eF+XpbZVQ92s2KbRAdDijo7GMP/M8lYbgrNNDERgFqVdNMHTxbV/tJVFloGh6Tor/8fSUG641h9Rt6yPPHBNtyP4Wmd4zhN/aRMW3FVRi/HhfUWq7n0ExR0VxqpxGN8upEjwzr1yNskllRZiI8rfAe/mPtchiztCXD0ALB3MGDY6wFdfhnpeJRzJimE/vEnKlH3z33nypZ5NWZwo3Qfm6Y+lMEaEBjt2Sg+c6eYk+3Gg8pStyRBbzmiSNWY+x8opBvxNxfLabVPe+W6JXoGLtbnB3dNKsC+tLLUXrHVrHKF9+DwOajir8Bs4dTgEMFDgzrcM6x8d/F7bzRVbtsTQJHj5f4jgh0Y5Yy8Cdp8PFtzVxJBYYytaHs5hFwWg33sIxmRlO8OCkC4oCejjwqUekMI0jpGZ6llMqh1cr35kdrtlqmm4LavLn3lyGkuZ8Tn1gDCX6oL55T87ioSUbOSyQQCqhfR7ad/D74Pz1khL5f4PLNrbpBEZKv+y2v35zmCr+v/Df3EPTc4rQdD6ApIxQ3/BvEqXc3ffNvKGl21VmiAlIkG8WlzR3OJ5QOg2MobY+wkKRrO5Js2KSabYa5S//V5RO7rgbV57oetoNyaGxfNg/EReEPzD6Nfd/1Yz4XJAkDVHzZQ7iBu2kTeoPHIVUSB859XM/WoEcGQ98itVSZDqYqFUm39G8LAcvlxACed2Qdn6n7pEFZja2KUUqaiK1UR7yqP1nk7psRp4jVPCtHgm3CK67rB+CfLu9M+QEITYEMcOaIfH9h7xdWSm1DDp/A6TQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
