---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAMhF5iNXhrYqUOlT6gmaNbGlLupFKsZeOv9KWFXsYk8utRHIPEq0mQxI5ejcHqfJAua22LWP90S7k7iLqhkCKoxHgWwdBNMxeririW5i/cnvloeKvjJw1urxPV6HOV7ANV6LeuLVZT3YfGulAe4kQWWOKeO94HmXZYdqK6Kv3FKO7vExBhyVAwHRV3lfSB8QsDebTUIAV4yTclzRQSHsvrMTrSiQvubw4+hHCs6W92zVrS1ld3qx9xSD3Ksqs7P+UyBtGZ4PeV9QXeYJiofWych/rDPjSacxVfN1t89csOJtXjaSMTyazNl3hJPr+FMBmbgR/LLLIu7p9ubD7f4c6Ee/cxpYIcNzNMxJfB9A+olLVuBqlgFV6Cjciuvs0vVbsWgLrSRtW1mXXsDzWisf4yF8aeXWZ5f20+gE5wLSGG1EFlBlJEKlh0M86KH4W8jd+6JW7UCHYMKjyTFC+eXeUrSMa7+u3CmQP56ERIMVobj9c+RoTPS0GfB10Na4c79A3y/a6UmwyabKqig/S5SbC57Cn/W1r9PwQqDY2Fl/U1/ANrdY8XDTrBkP00EgJjuSlEF3HzPhnrdI2JCklHJtFFbmIe9UfL+UKQvzunhabzGS5J2uOEYyH66Q9zw6mhQaOpVvuM5oXYPHMsJHyHVeERBPpBCmRDaaicvoTRGCSWIOgd7lVJ+wiKY2Ar29iIgXJ1Zarjl2jgIwDD5uvZygrJ+8Lnowu+waKEZtmki2xw+G+TNYAb8ivyEZpSii5kYUgDpP011e5SB7H2PIdP7fQb0D8Yxqcl1JUerZbBLa3OwZUjyAKyIrffSsS8CoXswAW9GaZE1z3MZ7agHKHB0LfKi5aWBQLN/Ehjke6rkFYVkwfeBnWihF8kL/uESWnIoXHYclF/MKZJQ9BIyGoNDqYx2tu6omM3jefbMqGb8/ejWMBAuO7KTJv0TC0EhdrdQgAMngZfNWjvQr6I/UpG5PbvOZXPM9Y5vQ==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
