---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgA0rpXvGsK35+WIfHWL5QHI1tIhTCxTUYdGk9M5a52Ix1sTPeMdJKn2t1x8rC+7AYrkvtzCLfei7mz+n9B01RIrJK+BjnUoqilW6TWMIK/w4m/xb2/Z4EpwNRrd768HIfSCItKEfTmpenp3qlKvrWrqLlOs+qpje0WB3lIJbFkkyA3sUQPQQhmP3igAG6CeAjpev++jepjUAC1celNgRvYYTHm0avqyUH5FTekihScwogZ19AlSHAF1Mpc4cfKXlL6YyP8S78EbDVHH77tkzjbw4rssmrcQm2tGXOqE86N1DGjbU0GWuSA3e8UwlTX2JjuJkHBDd3LNOV+dEnMLwxvu7Pe+NdkxSKvuA489ZbFHpMb/wav4zxIkod3UNI+RhoEIvwbNSOePFd7HCT+WB2RDxY14Brno712t3ut01C94diyz7lQifsmDc4x/rgZJvVcnJJKy6rw5aPkFSJBO7dxeeoS/741NmpmC2IkVDRLMQu6bIhQYcCEY16lrnXWtnohQ4UkT5b7LrBO/CFDvyKKX2uCL78uACY5bXigt0YhI2d1mownspubb14AEyhETncn2cjLX5gvDz5+ewmirYDioQ4CUIS6ZKHayHJqWFZPbg/UCFA4kweN62FCE2Wq5NG0y4doSgflpzxeyVW679PklJD8W0M5gzr8kpZOrzxlPkBb0GW9FZGq4oHQHyhoqJwUBm0ncZSEOW8mnKGYxoDS/Alc8EJFEv7ka5D9VgyV1BACWm8tR4USVnPi/Uxs5LPMDnO2daK6HKKiujv72/VHhNcI52nEaQUnUbp05E5ByyB9IU5F4XvmWmS4MMU8MuZN0+gEAUTVJ4RQFp3Y7p3my+fJwY0GONXFusQZk17htGiNyWj6gpW9kKOwt93AVp0kyWawL9aW1t3wToTtGCMA+TDSu8a9ZBJMsEvYoqef4qOeXVkxLYibEJdlVjzewvk+n6OLGwolpHwehZhkv9y4LZSa/9GfddQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
