---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBzgYgN91Hn/rQxpwnlJchInYSj2KZp3fmgHcGqzukX6n7aoAeQWo3/9Nj5ac5ddmQe+DqhSqnFVazTaBaMcwPIgjHRFFSPfSqnSCam1dr5mlyIYwjvcGsNDdgwoOWXYIH/RhlCJLiLCrzhjNRZa6Vn6Lsnm0BRaCVVgJAuViF6TsqgZU/TEDJTI6C8OAzZrvgqZOZGnwvKYGfJWD7Ox1ZiIUREGDCO7AZiOaFhBbMJvDwaLzHv2/b3EwDp0x3IxDtLa+hCu9vlfBM6YF7qHJiWwxdLSOSzkvkg3UQgOxJGFAv/HGueXSH5GOvBkxlwn0EyVFrjhZf60DgkZGElavbNCWg9StNjXh7HLLA1ZunOq0KMLTuz74wkE7EFzivSHfRIkR6SMo6fjwSgR0/twFbbQPmisWpRc0YRu1dC2bz9V7J8COdwrBk7wcD7n4JIrxaXcMjQCMSAN/TN3kHkrZb6YaYu+2BFSe/cueKZJo+ntzEe6B0J9KVWpXpiJk2BCnZDjz6lOUnysqG1Tboo2m08NmOEq8jf8icChZt8zxj8dVtFMc9nfLutQOvyHCPmthkT5zbmf2qb56d7z0yRDPjHouqYClYcs/tEsTg04cZYu/6Fsj2M7+8Z1stX0kyNe47szY6tbtbdgyltREW1QJM0I3ppCstEzjJq5uWQ3dY/drx3dEV4NJg3atjM4iTiqhZU/NvweWT/K+BnOmi1kLB6TzKPuMrgpBP5maT7qhaE8ibtN7CPFaNn88vVyTqc0RYZzh18i86cwN1ALL6CZs1G3RqeyyuqAu16PKe/w/ceWJsY7AsB6hFUzTrDI3PuGLVq75Ubu2T5ukSXHzvD3kbD/rDiLIp200LQsXi8B5LB17aLLkL5wH3g6DOjJ0agpfxKY0NURa+31FN6VP5qDXswyzsT40J4FRdO3dy+22pwbllJu3kj9/YfjrxYu78/F3DiFSE17jICpjIS49L4DjiHq4e6xautwA==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
