---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAaJO+lKqv/VuuJVcfvrR/isIHs/QQ+Kq70A5rVGa2L+15p+YXbJfgzpQzIBXN5yPH99bYXBMnK81/23GErky/UvFjMFIcGytx5vnoNCdvRZJYjMJmed3i+hxzQK+KDevdXGS2wPQB+Mplhn/7l6kBpFaZdOCRJ055d8EdFGSck6QkCK0vgvCWxWcGzmRQ1XaSxEcBJl9I0F5qbJFi9YWi1urlIint2Oopz7AfUFH/KXEqlaZ08y5rlbPSQQyNnyt2qnmYpFnNRXARYXrJlxiTRGIuWb4gtNBz7O48prxioOGo2VILcEY1QZSVy6VwgjNH2EXKICocI6IMlNjt87rgSuTiwodLwTnTrDZGOAA3FzhEE5nVYz993NlCalNPo2dNuh7nnE+OYKS6UIkM9vOVJ+o48Gepq0Xd3zmMq9wieT5/scCcIwSTLQ9hNHwXzhG/qeSeaWcrKgCm+HzMayKyr9Dk9lOHNQigAztXvWqlhrcZg+qSTDZLJ0S27I/uwmiCeXTGc+nFg7bA83R6ywawwEDJUrZXEf1CBVtnIiK7hdbRzpHEBxAx3QCI9vWHl/9+YdOFTz/28QYe1BVuqNP8IZXaOicduPNjHUchjsPVuL+u8rO03snwyXfdAZd7l74beN1/cr1+37tamnbdpF/8/vrBhO2IwdnpQl+D94H3USObKKszd6/yB+5a1Njip59GKgE45qm5HLePOf5AHI2RGNfVRZGo5VX5W8hXlEtw30By4wj+ymYyg7ss4B+9w4GdQqd/llnOE9zrdkQ3jI1NDE8HalSzwBX4vs6Sa5Wzeg4nS0WuQ8iyG0x7FVrFMI+htnIIBvohqBLaKCF+oao5RNh7C8Ff5NFEstlcszxuROjAkW5/lGi8fVXKfgjuFngpLG9uRKA7dg1xM1U95IJGnqJegopYHKsm0u2VtMjj0Pwu1qR2udOJJooHugJXSBh/Z74Y+29B7QHVCvEEwn2ClUHpF6uClvQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
