---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAb2QbGIJ5QxiskAnIIQO/B5XKh0mo6x6x7UESKXDKRXeVLLWuVk2PxrsXvCEQpKke9UML8UWkL7NQFCRqw8aBYr3oUNz7USCg51GFJLfxfhn6XKCqJ38pqUbst1FpbnP/F7/Xfgp3IiH5oare/hyYiLD3d6c2jbN3cQ7nyJGifSTa3WzP7slgCOSLWLCi92TYvhACv7FqA14TrsYu8tuDbsjyxlfGMU/1q/Bz8N4cYG2EM5CFW3kH4DUK6BbdjsZTGQkM2yxKDojiHrnrEqx0udrxWknIo3RlvWpU74EWVID9UXExhKTsKiLHphUaVAt6EznKty4lnc9L1KHCfLi5q6YeEexPQG0/steqav7Jg0iMZ+/YZfUh+klBSKQavrYmO14tjhH3R19LDbrGkh5mP86QEeTZtL9uCMKscDzPk/Ubm6e8LTCeg3mPvbzQtAbshNp0bThjnLZnXpQRELZVCIg/49iXL31kqvAiNebF4tJ7JBa7AxqE9aorZuFSXt54ir8IEOa6h23awzl6W8RK7229+3WqxhwFVGySwHSjCWrWNLLEFVKpQsrLelBwlhmKfXcDbiWAPbu3rpLL/s07WHNjsPHU2/tg2BRKnH4lJJYeH4UJMu2nicpD3Oh/mCnNHAxdVM4vY/4yLZTmd8NYm8g68Pxsl1voGTJU3mF63QcGn3CWQ4U+Hj1fuuLA5sjdqo5c8rN8PwGuf9YiErVn62iqQ4ZJkcmGyJWSwm8nfkNE0MXjSX/lb5FqjxGvJwn4IqSh9a5JCkqaRMz53pJKc8c+9UmrfuestePWpkiXEeM7nEGbKMNxs4uU0LbVm68sLeqKPptGwEryuq5ifI5/Ir9vstW3CvYdmh08FzEIMs28LVyNZZiBPaoaaFHn9bfwrT7Vww2M6DF8/udiCFYoCdWFH4wM05afq8jot9WtGXproJvOBRXzljuB/dwByswuH8RlvRrngZZqwnrFbESJepxU7xC2zUA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
