---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAJ7WZsifWMcbaAzgoNwRHdMvRttexMGgjNdmt6sQTDcThtkreYcL415x65db8UuBbdt/iN/jCkhCo9BjsbbdggXBdECN4/WxZwAyjMjXToMu/l54WnL2Es0464kTTs59KnbdHbgl/sAhWj7ntdMQPE1EebidFxYjp+McdtucLHzltv18VyhmlgIQXm2MefVFgh2wnjma5a4rTwfilGD0lGIK2RwSAG4hFuawoNZ3gjexTUL9Hg3QebBFJQ77PvhG3FzWOeBrQcrgONmw3eGDCvf+3Rm4MdcsPRTG6PY7ajesMLLg9e2jOBoOHVeNBbDNzVe+0g5kojFbjl9bsFI7o6HDGd/pfqK78lV3yty85ccYemRLV5B+Poz7aAw+H/Havj3hVMcjU6iL8OgVJSDKL1hBMj5BDNQSUP+0BSM4yUyKLJzYKpzVZ4VDgixIeZSpfR4fXEbSRgdK9h8ARuFAEyPHgLbzCSAhLp4FLBG2Vvk3HiBoVb3u1Y5oD+1aay3LMd/gQMMqxe6oAH9iqN6vDniaJZ3RXJaQgQtMBTKLjov6FnhkTvBrtMbUje76eDNG4+Hi1o4yrjwQbjfYSyOg5vLC0vquDVUFMRNysrIGsnQ1QUf5BWzVV6DK7jJZwD3wZ4jqj3uohlqaN7WyebmtsRpPgWXq0j2gzZpmusD1+v4mjxbRCuMvLMdycLnkVKI6VhNAdtKLDf3v4MhLZO6eIV00dM0qO3SVBcvdXR5k1OPVaEiHhgVaVu0Vpgv60ktIJZ7l/LGT/y0rOGc1cj7LS2+OVeWihDfIL16lZcA9/IThMyf2jGdgsba/GFEawQQ7EjMjsDXsJATpjZ0tH8dtVTRM1FGF0hr+gfjz6jdaegOeh+pKMUDnan6/qcs7R4uIlAVRIXQaHrh9nqSvhPXBt30SP4iFvn52otja0OurkD47GEKyipgAhAyt/yK9bDgW4AA7/qnAevJpNtpMc4XF77XPsJ9r25Rw==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
