---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBQx5Qt8pvOXOtnzaJpC3xg87lnUEiKRlW9FnuxDpFt7KFNJYBrVP/jeOo7Uicc7Q8jCOcwAezxdC1GaSGsWpIfxwg7gsOVUciDU4CO5c+h+ykkuqQntHJ5DAC5m+8M52Tu/NnNnSfw1WuAR+mHqFWOvb2cCUFQPJ0FE4Zs2BWgxqIWXD8Mo717kYYAzRUOQJJ0rA2ZpLOzTrrC7MHWQ9TaNXSX4aG1fgcoR5J9la2CkbdY9PtT2/HD9/fbcLUvhp6kKuJI6c/Hlr0vaUIxFiT4pJkqP1ZaSbFt6CAAPxikEZtHf15wO7Xu3BHGq1l76DO0qfL3/Lbco1rjH5l6JroDTogIqb/WSxTBTpWN4KtLnJteOkSO2/loWIMmzfZkzl9ExtMbhMzyTohL/eiUZXS3FQdlz4RKs6k8YzJyeWk9nrKlgHkHbZIjcV4qAOPWGuiqabxdB6Hu/JEU67pEwTtbBmp7XdjD04wLEvuew0Abu2EFRhd4iguvMmlC3OnAhCnnAcx/jof1DKpLB2UXGLP9GILs79U1hAebzDk06J/8QjhTGwC2GOdWlSK2+imSedazr79xp23Pn7/ofJAOOb9I4VU8jNln84R0dhB3ixCCd9OPRLT8TPdlWtVj6YRes4Su3/wHzX7An01LLyLj45ukMKlywLxkr5PBeVVO1jujT6GQV4CyQAZM/xigzMAMx5JoR7QZm7DzMJHyy4oBstjyp6WAiVBAWxZcGKIjtCoiR44NI5V/XQdJM7SS8F/6c778tlyhYWWBeJ41QngNVkQcKG1ipWlLafsHX/bm0HBupLxKqAsjLdZGGgDYtGoAjxeL0h9CVPyys99yC7NobRaNDjCkM+EwpioUpMzYFqOU+Ia331SBq9o6vr2RNx905X+cnA0IZ2+miNL1vmB77JrM9AXr8vJTANJdkK36r4aGTNx8Ior7HL/dzQf6EATTIVoQlcvblhHIBn3tgoy1+8Yv5/gLsjyFvg==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
