---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgB8cXGfGF3pc8kEBREskEM9jetvB+yYdzzq7SSgs8wfQkRGdPJ+HFw7weff4lCzIUvjdoeMtRkHkc1cWehJyqUjtDhIth5sbx9iul8JcTA/Oy9vrh8hl40bxebE+KRWaZOI7QZb52Jnz6D6svYQ2aioFQwJAww+elWcucC/HDV0Nb7TMtnce2cjR2LlrEHHIgtlLVnJgLCBm1abqCQ5xl+x5hdygTi34ATATdIp7iWrs6NJe1gk06T5mtJQeA/KGb4TghSn7P53SvqeG1b3mszO8LSZip6K5cxsiARMsJXUOJSdf0m1IvcuoL3yWlS/HHrPR9M6hcUnou19QuxiypHfnVe/5rE0yec5jAjj/z6sGrZV5fRZ53Ad022aq5GQeFWWsnKKPdUHzUpFVSwg/S9YwNTpN4iagSTsn5vAL304txy7PZnB4wygYdlnVGYhEboKiFI01hKQWdbAbMtbIalJIJm/cw7TXdUveS+WNbm8Pc/Q81H7wey4fIy971w54mKxpDef+nrpMG3tp/q2362KykZwjhkMhFEFKU6trfX3mg+HZgXqpYRYREewugzCWK2kHOvxit7HHcT4wUMD4fZZO2vgd5w9k6abvdLAWDx3Yb2CYD8+olPvmP1fHpo58Uz7nrF9zSeaDO8wLwy0z5PWukeTxsppWwOCbZ7cR7PdroyWLr0RoFyZKJhNK8a8TQinDLEy4uom3qYX9z0kbAGdrN6YoUMzLGSTrC59pMwMPSc7a0MSIeJ3xWpMOXLahaRMvdXbKOPxnc3G9ssT36/eYkvzelSBv8ZQi0arRo7R9Sp5DfpweClXA2rmzga8viPBXJiB/6Mx6KdkdBxk5ncLI11+RNS0OGEcf9Ty7L7LxIgRRk5yN42H8V5AKd3T3Ik/eblzKCenj7wo5C2ToATfNgZFlzCciV+HV4UPeNYgkhA6lSgIVnGvCcZchJit74elQbFVaxIX4pTPAnzA4WJCG6oIoIhWTQ==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
