---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCoMWnnQ+5yR6G3gY94SB+q2CQ+m/MR5G5mPeUbSTl99AtiW/MgUseKMcEfrk33mjCbVRkSou0L7LnRD5EaHehVul/ZkercTIYceuZXIyhCkrxpMsrKdKr+1F5X3JwDCnze5Wa4tVNojvUj2ktr9triGsyIWuaJFi+4Va0PB7HNwEfSJDrcLw1ihT38Y+Kn1Z9CRfFXVJMZoOeBr6iwZcuXbU7Pz8UHeoWWE0hE3BTA2vQC259r9P5ibkbtGKXPp3t0nTBz8WwIBIJP8jXkCF2+D+nfJWuqFntGy+zc2i4XKhLHmXaG7sZmQyIkIUwq4FQAVfozejbkw0BImWteyXdMn5uT/hB+P6yqLkTbImr9OeW48+S678Af8Tl56iaMmXSyapmYpvWsNDN1tzWtYRFeTuM0NRKlkUQI6mV7oEW8fqkCwvR5jHbO7aLW/vQDEjHmtCS/w8DXJ6DgCO99bHLQDNuGg6m06FBrmoQfwQkOb5M4tJtshQwW3TnFvvhZs28qqAoHYBOtD7WwA812KSOmXLUEH/w4UeBi4Z+sGQRdlmOVW4MpHTujeWk3cFA8Xlmy25rem/YAM1qiw9nZIDX/NZeMYYIojCCZNLTtgm5Z4quepRKpRzwyJmxlZM9T1n1Awr6WQbLJo2rueRW7j6K5iRBAbauy/rjbM9ksqCvLLvn2yy9NM0Bzd20xcbKtJ7wMPyBxTJuMKmH4GvAysEEYNv7fWb6/1kgixFl6ELTxUjEOaGuiKVNUF4ej8gEq1UlIGhG7AipCFS9dVQB+yJ/sJG125lWgZYiEmE6fMUnJnMwiB8vkyRsVNuy0Wr7cdRXRAHpqpT69pHoEUfRUoVsqETBdG+cCGxMeq5v/yHZ42kMV/2DFnmGVjWJd4WWNGWDGqQPWmiQtShcEXmjksqPKC14yS9aerYFicrdctrTka5W2TeMK6Y1GOwx8gJjU3smYL7ZXvTmTDFZ5e0qRAHgM7pJ5kf8M/g==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
