---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tsauthkey
  namespace: default
spec:
  encryptedData:
    tsauthkey: AgBFWJVAxSCkZNRgjqfUyAOf1G8+Lc/aW2CT5SeRtUJtIivpR+c5SR+t7usv4yVAr13qQW8YhhneeW9n+4DhRz4Dcf3DVjYiyY1cRv3zp6QST/US3xKs7s23ObT5ca9yU73XIN5F39KKJakKPb5RrHfqV5tkx/ugFMr8mcDZfcg7P1zy5ZXiZ3aqAYOCmKsICZ9Wh30VHCY3BO/6wxMLKwW91caz1He/sp5GJ4dwtiu5BGCrv/KSHpZid9teZdOMC1Jn6xKunGaSfs/3rDTUww2R45Ioytz9YPjW1ctC9r8r3mEY0q/uZm6ZvG05up6RMX18aLpTaCgS2vuOUj6ttTljSk8mNrVdXJFc77pelLUpGjgBIuNhj6xkjF6RmwWJKm6vJCy/ejL4iw/63wzMWP0mVNceOWA7ZX6GyyxMWNGxezh+NU4vITYOBnA8OG2vLXgZ903F6/Pe5LNlS3STtGccOpJ3LEm5CcsIxvqsXCHd7n6DgRHVicCVK8tyE+jaEAnJxNLYtYLa8QihypPfsSJdq4beVFYc0CWiwgio+VwamJMOBg9UcoWhLgsNfyGpz2qcIvxMDF4wx9kBpbjC0woMdggFpO3geUAtfavdiuFnjKS9cyflTb6f3OObxke89fDufe7y4rmbhnm9Y02mFHH7NJkK6BdjbiFcTU3RzwSoTUxZ/REFFHiQ5OCGcDixyLf4BB1AHOzoMw==
  template:
    metadata:
      name: tsauthkey
      namespace: default
