---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBjE8aSENvigqNJga3MSwAq3OoWuaBOxFFdpZd5tF9VyaMe6EkC/SHEUO/CTGKIgQqcG54IB02emrwmZCqs/Xp8VzP7HyV8R/xVFkbFh2EIDSp7RX0B091OhgFeZ+Qg6lArFaA6fcx9baXt6wIklYMPvkfrjTwfZlEWF5HlMtaF5fDs+QKmJ7ejmDgcnvpavcMsqaaPZJTl9jtE9DQ/fqLFHjJ2xC+losltKaoOjCKKo/XRhYtKpjjrdTf4vVqOjpnTAr9kjJ+YHlTKzVvbXVQjtGqRKo10Swdv4PUm0TpMF5W+/vr4NlyeBGUvuge8q8SLIZYGJYXq6SVoDmbmiuiJf/OpkqEWiAUKu5LwAo7gYMAdVVV6zWUvF4xgsHntc+7l0QONn9s5fqshzFShaoeATgYVsp7uisIbPkzlAhB0kThrJMo5n5ABCAUExSc4C7fjLGh7wxRtGbR+erT4258RopkkM4RtFBvYxPz1X2JdizJ5FVwGOV+Dh84BqDA4eiUHCeuVqpynevAko+54critZzO5autFxL3qYj5+iY8EV4p6GsaX2zPVAkL+/Ah2su8roiWatxM2DHy/0IH36fZ7AU3wk+tjJT86SO8bG84qEDVf8OD6pLBakCYH4vVqYsmXB1GPDBJjuTwECPWZAkxRyxL3dcINVy+x4z7gBdC/haSj95blil2PDiGH0q3XaLU5VXJC8NS7VsXhor1pIf5jOT+SEHkgj9adpOczo/57wGMwVmKxtupGw21Ddvdo/+UgFiEvQ/pCLyVAx4WlhzkuUugVd6/s4vv0q8c4sGsFOUd+TyHIKGUkn7xue4PNx9ANr+E7lGYVbrtLdPJ5tc/ZDeW1pb32uZaYpm0OcOsqks5WDRfT8VH6bK7iiCUpK2gGrUq2zWof82/MDcC/n7/7jMt+o0k6kc4kedFMcsbp
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
