---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgB4Vd+Zn0RYQCt3RMrZWdd2kbLW6ClnzAruycf8DzQEQn6viL47LSlKsm/sIe1bNudlotdBdUsZnmhpgyEcpBwVdMK4hAa0utGapakmcwCoagPeSI5jdXow9eIJfw6XLopm+ug4F8z/2AQyK3ovLqY6Vz1c0OQT+EtmTPrxYrhTXHwhIwIS0+5JSz0xXHspWLvDagVs9K54q9hbBb+XZl1PAlw7/3Km5PopHGVQfmE3t656PAJZuue9uHsaS30HBBTJFbOqgA4xdc+qLCfBiKE6UUiczTMNYGDMlooglvg/jXBP0vsAmTEyl/kdq9QO0aaLd1ykQ/u9Xz1+4aRlz6hKFRZMohY2huFBrxzR6SVzSxIIpGCK7D1pOsmBmH7A28rdCUzo0MfqdP3AVVTRt0R1Fv2+9cGkJYFDotGc0HVJnfQYsxCFVqNexfxqU6DLmjMIiPPi1XhoERb9FW7szZe3FoLvZFo0zOpCT+jsPlD38gTtKcKcT64kRVQ7tyd0tUltpasSvsnXPjPBSLsmdNhqe+8h/x1wUePrpk09qF4NMn2qrVbh07pNAPdtHgGz3JnAkRUIQxo/2HIVUV4uOyx5EkZbhU7X64IpcJONBYmAGpgql0QDw3JZvj45bAznmrI2Rsu2tq4h/ZC9QJsqvw70aRPHqh3p5SIuUi9SW6eYwv1Px4CcFlv0zBNuwLBTlV2PShJMuxlVjze2nOZXIczS0tRV1EwCOk3IeyX9gqdHclja9j/W0QnDnkf7dFcgXSNlaPK+A1BktpS4RT6pOn85h/d7UvPDy0gyj8/qjzWhb+3mgicxfxOIW1p5WJC12OoNLS/ChQlQ1Zb0GxUkPT2jQO3ldqYX3z5LM4M/p/MLhWM7w+81BcYZQ2QjLP//XPpQ9abR4/jZdr2+SHv8yLnqcCSZ6A222I1MszmA8lH0
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
