---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBXElRS8nhjJAiSuDLBGjdwI2Pu6/tL63yQibi1WfjOqxGybjlYPQWnS+LHxpPQIQPGRPf11+M5xjXoEmYdhgQOOmleznN7ki9KzNrLrzQ0OBfP8araIZxZMIYw01PFcMKTjJkApJw/+uwwV6bLz2ET8IYX0ySn7tgwC8uw4k1OpCbO9p1Ij+47aECQ88R/EgTtjpuqVufBybEP+k4VMTIbecjOc4VVIOo9g2e7UGEe0F4y5bMF7GSX/DWSeH+fDfJqJhH/68zAf/h4XvbMQNtKWq7lUwiSZuPRlmEVl7ZgUy7nRB3f0N7dCFvFkTkrAVA2bpS8IFY7MLgar+WX+zoOwtf2dak9sb1t9KahIEMzOjUQZp63d9Wzchq2wtZvTDA5BNSvwr3ln3viKjGusmnMROq56THM/UaMc6iJBd9nJHLeLL247iZNKymW19d8JO74QE7qHGmaJFpQ3JcInVr4jAuirPlJ610M7pjRY72CDqHrnUcJZvvQfwb4ZRvpcc7ctrvLpSLdynqe18v0EFnyt9ojgnoJEVQ2pkJQb8eZ7pb8B/UwxphOSkvgxvleeIcLSt3bl/L7jGiwpanmMBtj9wycnmMHM7scUJLs75FfubRohMY3mkjmOrdFHnSqCMCRTjrutDTEJ4rxPxFeEEIe2fpg58Q87r7Ci+CY+doM+VyK95tyrrljtc0ojRvZ4cVW8JAMatN4ufWehf63UKGi/KfRWwvK1lCW70cQ+7Hzv5QqjVEeGqfLHAw7K0/DMPqJlj46hAkLaPhaZcKibAbpxBi8lXyr0oc7YzoMuEFsFr4aY0Vazu8+roHMr55BvRKnMx7iHtkgibhmINI=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
