---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAY22zjIZBlEqBb8H7dLGP9uma1utiYInvDga/pIK2BggIpHFe2SYbzkovTbrqxpxhe94bWapntmzTMtUn8YRQdX+gJY30VTOBPPqC4ZWzA376UHVvbp7BN1RH83tGtMbBD3JT95F2qSKQ/D14EruOSpHHPtbu/urjwtLlTs7+SfXuGH+FhQeGF0VZ9pxVGLIlfgxh2zIF6gfKoEmJDzCbMjlnCXv8f1vsOGu3o9FBcKraZusXTYZdaowYfVHRMHgZmI0wyUcNPz70OxeTrDyR8ZMOZhKP5/di8l9cmvZYReqDjSIG48RlDxTIZw1AWVLWVDj3hCuTM/8YjynaIJhcO0WghtTN3Jds2V9iCRXolhzY1AYI90JNsF7I+6BRuE7h7ZFLrfUWVnP7gZm+D01WyfcQ+IHtu2H2zbj5F5GaT42pxiUch8In64YYVmi4XWxLTgxNCauj/e1A4z0d4FpCETzA5yt71hQHZyTZtnxTB1RWNH8L1/P1r0smjCTOlJofFtctTzfXvHdnn+nVCDnZjHxGvBqyfyd2MZu2a/IROxbVIyuHhH6WWnTQARrFVKXMaDBAnd/Y+traHFtd84YhI2IfKgLW0GxEY/E/gvz/zTO4xceRqiBmq7Q0fda/C3FQryOaAvbhAB+83C9QTzFLwcma1J8tqfEVX9bNc2Dh4Qcq7eW4Ewc++QorvMVn3040aotpxVFNH0RNsZHRoRyki8SJNx6x6SvCC5RhcCllfKWXggAAO4971UfvqNrbjN6qp4Ok5parrzndOV+KmySSblMNffbGlle6Z57xeuTOewqLeyQMguhhbH1uVanxlXd1GMRPkri826ZLIe9k=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
