---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAyk7xYQyliF0zvjnnDEeoeeTLfiyvSBpF4fnvifrd8C6DdLDm6sgOZ+rHU75ciT1X5PWxU5oZcUhkUlnPnqAFLiBpSDN6gad8PlHpAnl6P7i0LSxLqOFx7anLtOYo6BAUA9oBe96v80SJQM5XTWaA48orTxw+YXSKomxCSuKgiMYCav1M8Lns4TEhxk+ST8w2k0FfFkZXIyLzNclyqmxK24WtsLFx/6Xg/qwtgwvpyAyn6lfZUmr09nvOCuOIDTy7M2RnuUzsbMvs1XBgDgJyW1+Zn01kFtW3Gc4UeoRrqNa/rzf3EI+X+y/DeBSk/VfABPXVGa66DcKekFuq1JK82t3heza2Pg0M7ZXqzJw/POR0LdqpxF3ajfggEQqXOxhLgA3CK4MjJGbhANsFrZLbLubYetSPS3FmrghGUT4z7qJDlacUsp7YthdBXVUoT+ZQPqeDTZa40oMKF78SUyrzYtPUcoKvBMuPg/v4zLpPWfw36Y5y32VCeiXL+bJNpdIfrNFaP1YmCHnNmALvdEL8upgJYC5wFadpDW5aZbygmN7aatyeHCqPllfX+0Imm5f5wC6mJJToLcGBzEyaA/6q/clf7YYpoT0sKdvgkiSGYh0Un3dIdOdV5abEFKVCdtBnnpY6stntyMTm2R8pIBHKRXpTZ9QhWWeXRVZsqADSJzFdYNFHl2V5yYorJ47dhQ2bya/RYXdqXR7L1BC28tMKr4Kg85n242WwzZOvWad5o/lWB0BqiBtqBs/IihgU13OL8dPh13V9kXUYDPjnDB0PC9/KBj33xfTpuauuCU1cXyE3wz/JyPs7piIBY+nLQ0M1Qx8aurZ7NRI0G8iU=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
