---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBngC+Rsc2N0QD9BV9ASOHfOo7AkD9sBDdPX9DegMa1HsXWPS+iTQBj2gX8Tv/wLAXb8qNdwQ0JK4HZehMvyrAyeXcLXCAde6rQP0BSZ29JU9NcKgaExVpDcmQLaki37ytZgM6bDDiOso2KH8iBSazIKsWwrbRWTZMswclLsUdfE4W6SHkdsF1lgtj30yQ8JPVUDQgDK2n6es4PanERratcbLaeprEciW6IQnrZNrSEAikwwkN8GoCFQYhfFAOAgq4PnqwG3HBRUo92iKceX1I0Z11B5Z5AzKMwO8xMyyZCgYu46/AIgX1t5T7lhPXnP9mgGWe1aEkOAMtORVcZ6u6N7X9EietZn+ZMnzj+hlB8sHWNoYEjSCqZlaz8ZNF+ykYVE9vkIDOosFACX68cI9JfhacirXlT88RAjImp01uPSzHvKwkKC+dEL3DH9TDPdEF0Jo8WZsLtOnWS+EII4pCGBwU8Krr5DLWB1Jv/OsQdQoGAc5DW6+F15H9vc+d1R+jv5+7Fx+kV+2vuzDyXRJy97RChd1WZNVz4l7yJLyN3fdtNMya74jPfDwmjxuXSV4WFyAqQJAASRZbABo4KPGibIvvL2Zs605Sx39Ib9yyKi+QvioxB3WfuQgc1/wsLbyb0VcJaxQ5YV3+mZYjRqDPAEalG/4+prBYD7q5Ajf3c+iVdzCGYoVev34jl4xDnbdZq9fFhaJ4RhWfr2Ig+wl5hrYGktgn32wa6Q1Tzgb/AzRCh+Rq6ksBkLQYbNeyaGfHkQXIG+kQXSFOvhLBB5Ly8iEluAJJmlzI5OwwBZqVoXQnY8wA+FFsZ6H/8MhDWuAxJGFwCjO9OS4+NbEE=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
