---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgA6j8qbWLlwBZEJoMrGQ72+RlGk7Sm/lUmo3LWShJ/DCoug7r1DsqoaS8FTpisiJjc0gRgJrUqjv5dURkhGbrY8e9SQ2PYNU1ZSSRRuPDd4gxztLk9gZF6w6WAfxkgMaZzLyYWzuGnFEFyelAq1y+z9vpnxzS88W/B2To2yXfg4WNf74ThhHC32M766qPsW9ktebUGxvuuCuzYREsox4RChOBI9lr9qxSTDNgANUykqPjMGujt2clYHs0aS+PWGPq+e88+C+XdClSGSjUQkRfQ+03yDw21nqJDCWpQ2ZHi42lApeTaTzxM8skEkYm6gIZIR3TYg4UcU2xZ5THOqY1Gy6cSzGW4HZprgDRyeXGH8caBYaDZutrNWD32RP3uHWluWgMl1/RnbYcrLPe0m6Mhh1Ozs8dNFt1DszNmBJRmNi+OyDuYDBZpx3lw8rjm/jg71MrapgcCyRznby+APF0g0q2TkVB4bveWYnL75pTitsgqa8P63MTWOwYkWJDnyfmOm9mD+KJMzcs6aEL2J21ySKN9i8lELk3R42Y3P5YgdPZSdUX/GW1zUuOb7cr5S5/eQVaO1Gpesr05u8/D+dqE6npLpyC5wESOqaPNbP5cKtP4ijqZBqcOeTPUCNCwHbu+USIW7hU7eoAsiSgCYtWWNfU1YFR86Pry8+avS425ZN+I0mP0YZxJeJ86UIBmsb9UWDnypYBgCTTNuqZN9rZeG8ORBnh3owDpF/fOYv130e8JfvwR9o9/VdQppk9sfVet2f3+zV/EEEldmOcqwlbbNnpKpDNPxRCHhEyRKMLEumeMugVIqlD/D+zn3xu7hGUp72AgWqJUaXuPkuyI=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
