---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBQyJpO5O1eKKxDh184a6zvfbQShXoFldljIF9FNZLy9A7s3FnVjPhWhURem55sNafpBdHyJ6uf1yLfhUaFR7Yz/0C4VZ+gwup8KFdFOx3gGRoDYkTVoClr/l2M5Yhz4I9XjRiyF1zC93VZdZJ170fbFQwH1+KfbXKd39J73vL4zbb1hqOglHc9TNBVDP+ahFy1XuUgBw2hl/qcS8n+gofBLUdYFkW87NRfoXtYCZXZ54H9DJJXDfwmWynFe8iPJYX02SYbKKbxuPtKpaGKk0tXgXk4+wXgHEURP54KFohiCyJaH3kyHM7a/klJQUPizmPiS2sKNp0zrExWEvS++KPEY3oo+HzFlw0nC0VBPkMl6T73vqn7xdS9f/jmFP5GVkLF27xB7GbRAoEA0e4Kep1fB1HMMISSgaUT1ahJI/bkWD8to5FXEbCs+pBp6teDs8lfRxJvOhBokrNWpkuKVLa9GSE5CJ80B9w68TZl21AUsi7tnCmWBeEWqBEJLNrhdySxPFjnsJdyCs7zC2fnPmqp3SB+Xt0A9dMUGN0B7R5C84L2vMLsS5x8S3K+RCU08qcz0epYP9IOMYDXBSbBJU0Xr4X6BX6JGVTU9xCZ6e9rIWBlxPToBK+rUe3FWcyg78dqU0H6cGt00pHWaHNILw8v6x1tjCeMA/0eQRtgy9/3AYRQVAdV+Yi5OPMSVHxaqmoIOeo9OE67bcAU2Y2HB6uHxI3KBoyjHtw9b3uCkJAhfnm8TpENcBIEeXHQSbUg7IxPwO1bpOc9jtT2hpzktmFRser/jXmWAPXAwQuZMi9C44o/pEAgxTkSNk4NCbiPvGCR1PHWH/S9IeeQn/U=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
