---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgCj4iPiEduhOJk1IdXkQNtL30O7oxWIiSk1wd6zgi7uPy7ysfmxq+uxN660KKJ+vp0Pdeye9R76MqZdKklHvvBaGw61m+387CgSv0QzDoNS+Ua09ECbbFw2nvVSUAD29h+uSyQy9P9UTdcrUoE1LE+4gBlGHgfpEEtBnfeGc4rcnjUKNK1P236+OO2oa5vYkYoFRGkpwoFejpgEif4jaj4hxantx6IbOI3TLHowvF+KKwkP4+Qf00cCsTyZ+kDk9wGmfBkjS8eGoioEh72kCUrebkamWc8zTniYl0tiqYUx7Fvf5iwY4GqrLxL2pUDTb8+31qKOiZ+ECInx+z2Sbouz8UWSjuEE7yBOo9r9XJcEVoK8r3Gqo/VAuxaqnw5C80+tie/pSqYcEbV5hdp9mLoFDtYnFEdpP026WBvhP4yeMN3KCMpeeSkm7TCrWVOZpsGoZx+8Qds6pBIz5kOqVgyNFXh2Q3dBxvrXN4hjbKgP1s4e4hVYM2zHdTM2ebUdPuIGBpN7ixSAi5AxV4hOYe5HSqeocUa5Kg47/2MlbtIPfDzwZ8KFaAjiECamFGMxWZAu3b/lac+nruaptALIBSG4wGKqM0eox7qjM9K5xzAJ4gGZfE7rl38yXjlorfadb2DBflCvgA9m4K7rkdliEtNaGadcp2+B/DinGMxuzP9U/vNO90D77hCd716ll/uj89roCR8t6/+CIYDnnqnzLW9IhJopUNP4dx1NurCFEINBf/UL2y9ROF042+Rr02xXl+xVUFgLcIc+oYxXg5Q6m4wZW7qIoKdoZ01u5np2A9JvBLzOdcAmwh4bJxp584/yU6MK2fzTRG2ZLrebJ98=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
