---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBLDxmME5FQUsTNaVVrjZ3z8NuOo/E5LYwsu5NccTQsZAED1WmsExS868m1Af2zC4K2t2Y9grbRhtD5R+EjkcsFZtMf1rUxtBWxq6qMQRKdJq8O3TN+xbDHyQiA90Pcli0/nGy+eItSc5aDm87q6o4ZlQYUouIWnYIVa6ShwWuf5EDWhwPC1JnFZmFrWdbz7h1lPL8Dca0XLsEEvPp0INZswsHKicIC2R27hRpqa3nOPhP+bQDQp6dWasEZ/udt1lQJtmLloXEULCyHjiCJFsCBBSAHMKb430oPyRHQqK/J5096+PcgwU5wgtY7w7h2Kt+wk/yn3lPVck/Vfx+BrJjkHuW7YEb2dYGjXLaAVrsxJ0vby9EybY47CG6+B6pZ9wS/2FX2+mI7UYPIziw9DG65nZDLqE2AdOWMGHvnxXI/0Zx3elR8thd9vN1qhIBfTOdVKU/eO0TCkP8oEDT311h388rQDl13BMQmvfvewdh5J+PnZdJFKJ+ueJjrbnA83Fr8QtNGX6ELIPDLosBILAED7UvRVvFLB1Mkvr4F9rDmmARBCEubSHVbf3Z8lMG/hEY9B0UVJaULD/6p94N5v44Eb/BEQ09Fla2econ41+aUXPaqaVL4sjgNyodIXWY7nJUGj+m0rTq1w2lF8X9ib+J3fkcmk/dpvR2uh51EYA4j32LwIcg6Z9FvlIDq1Wbx8X8Zs8/rUY/j6bnEZQMAIXDmKengN+SqoOIQ2lEZkf+O98uXib8L5DpmId14jH4b/FE9hqwQwP18CD9Wl4h0Z1J3vBNza4asYLBCjo6anl+PLF5ASDriTJAO2r8aRFsJ9bkJKAjyMN6EtT9150c=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
