---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAfkZZzer51ld6sz1U6jWkEfkPGIFbpAO1hQcAdHpPs6Z8RIoeX7DWuBM5n69CFxUbdUf1NW0P3O+yQYCJpJYG/H3w2USC5BIyLwe4bF2rQOZZoBNevmknqR4t1WqDNknnJbGY1Xdg/tFNSac2W+K8ZXFzjSl91HDSajAJfk7qBn8WaX8CqpncJ273rlgi+CT68OxRUZHfjbC3VWjM0VGIni8W03k730DYghZJ1ZAWJVnmJ4DGq1oqPtwgRHUEyvaiFU4gMZSsYxgnCdhvwA8nmk/ZAxX4XfaMDyN4xfaiTv94Z19C6w1Kb3K1draduypxfxjGaH19oit4PnjR49RBg8YClvE+SIO5NLD1xm4gg5b7cTGsU6Ta7JOU7gbaK3JhaFN6ND+z9GVqPJBd7wYv86UzIj7t4fgvgKEhz/Y9PMbJQ4cRKLgVH8cR0+FEbQrfL6nD7GjRuT4c76yR0oMwrDovsnXym/cXhYLKRA5IDpDVAVq0Kl8LWMoHJbk8vvs/cOpDQIzIy06ksm+wDKnglSr8hB/9+pC4QyZyeoEIHLsndeC+fFQZlQgk3hVqk5DMOUBz7F8RLsAEl3yNt+D/SiQ/3ykdG4SSDjLAaUmA4v5VOXnBB0oEKvt7rrdD1+3v3Q2GlWd6Nr2oUla5BuhHsCxZPAKK38hDt9WexU+cOGLmswUZccD8W5B1ayeHpGF871nxNqPHtbkExXNKtSgurFAQFSNVbifJZTjzfLUqnkWDCryYGS5xDNuujC9XjR5tdgp4eh57rORK4xWQXZonvsgOT6l2FTZ9Rx/xT+xgKWd7+C4IZaGJMb1MfUMvQhyq5JXicPEig61qUDUTBqg2uKWdqawSDab+mtgBG+BrIRBn8ayw0SSMKdxmY4KOhnJcga01qIymIdpMXkeoycEyOT3VBjYWXhSQgPUPEw4gY
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
