---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBM2M/zwIeNbioWtVKNjenMdWNJ2GUbRQOGEYLTl9rZwNKMDXKPZLNWp2J/aQBue2vnT+aSrKpWdZJA+Bfwf/PAK8Mv8/UlLizKWlEXMi8H7Gxl/HnFLhMvh760e6ZMCAWF6xWTByo3l/ClkZoDGXWjMC2cmRrFfX1VYVkX02CZxvFgpveexlJKxNjS9CrCo4pdfmupYRif06kFbQ/r4t0vbZNE+UxZ1SqLQr95cwHsmesQC/DdH8tfCv/5kYW0OyyHcjQ2Vv1s/SQad6oDwlAZY3b2rJABxrg+3e7ftqqCJqEYoA3hqNds9k+KP0yVQD6uUVapyGsjtMzDs0xloiX4+lIhtmWgt0EiHLRfc92MFz+XhFdUQHl/xqc4gNBHUinOL6DbirTkCt/TJUZB4QMkBhzy5HHgHFEhGpGE+8VPn1yc9ZVDs1L1sDKxbtkXqDAPpUd5VGHLZMLX4XpJNNDmhrBHqzF3/MVt9ngm+fl+sGZe+sv9MCaeA2j0oNRCJIwyTMbCKLXkNaqywjquFGywlcCq7YLwICQo+j4uy+YsVCF7mnXTyC0BGpuE5g9R+OOmtptm8mNljXv2uTueRW2YG1zAQwJznLV+XE9UdWUP8r5g/tGOM4Vjra8ezRNr4rNShF16bW0Epth4dZ3kowMX5ya9n6j0cy4sV2P9Fc/ZIkN7DiqBs2ias6+zmffRseMr9I+tT0OjHTVyfi1kcWR8/N3JEja0iJHuMFtGy0yrU4QsSBI9wrPvdWHNBJZfD9jmvORIcp1fyKn2LNgS7iQAiMs/6tbTUaLib/cx1lPm9IJ9KLWSNZfbIUGFPjGcX6u7g3qxDaIBKl7+sEQ4w8Tef207PJTXPpaOWOV7jXK4LkeryGIx65i97R5vxUEbxbxakLkBlBhZYJQtDYJUdTFsY4V/hqYGjS8yTXovBoUE
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
