---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBJUjQe8uyBvI3Ocnq0tII1TrvI81o35uyeKMfufpJDnqzZbudm/Fm9HxR4+9hLM5O8Mr+fB6egey7K/FudeCQInfL3qSoPjTj1KMSmIQixEY0ocjZUys/u6iay+Il25VihEiOpx7dVqePFDiB/Ab0rbLopem6YWfK+CccnAx/lrRqPp8YSgvPO7V8Sc67MliLi/ZZR3WZcl4xD0P5pHKF0xxQQfY/ZicA2KubXjAJNcYF6TseUb1QTVPbUuvex/0BBSmOp3rcYTgdhfz8SqYIo0/kgXN8eZF+13Lhq7tvD+qiWl3DHDunUF5SsBQWhsAV5BYLIu2s232n5jIRogDeG5VyOkrM0kr/4u4AZCKSSPYLKNbI+JnblG6DEa+PAchwAVwUEofC8IartX1vDA2YlRofQ4cy44/fZ0N7Aw9B00Ngry40P7AYWRfYX6Yd++jWjBKsb+m4vRZPqD3bDQSjbykWhZdcP7/pfaM8Hjdvys9H/CgiElGFj/6XukUuJDL80K7bq+HqcAindu+AAwQKTm8vdBpK6UT2+vwfurqUdaL1MeZZAXAJzq0DB7MFG2mFKnALk5ajjqFegOhBlT19L62ZqrOCyrPGbpBk8mQ7vaYinQJkzcq4tnTBBm3VGHT0wtVBMr2p6AnfJUwZPWWtbRkUVThyirGbCvwnBqPK3EHUXat/4s7tzXE3j9OX+dkYbiADnl/lSNRTsasA5YV2kkG72b2BpP4AnTN5YMQ3BZ9pHJ6hdJaf9t2dsz2re5ETf3rjhly6E6MsFKKiexFV2znw+xd0rwHsEtCH458pXgN651/XBE0bBLOjuhG8PcPcCneYsjoJVq60nI1Ilu/+oCFwfkwvhSnaRUMemVXZYXQzThEz56qmFuYxoR8YEG3O6LXkxs3DzH+OlqZrS7eFzG+0k+9LjC8t5nrJudCeE
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
