---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBGwgNncY04NaYViY0f2oFlN0aS3/iaa5aH3JzIkL9++G3KnwVCNWt5dFMMgWO8i6l1VsRgtZuY8lIhulEIQZz/Oi0SzN3GTltliU3lJBVLwJZ6iLw8uAeuGWhAEFtaSKWzLCZJVlefhdgtLfhaNuST/54EJllhy8nZ5fzC7VH17eq0c5DG8m+zfHiwTH98BEBsj99r7Z2ii2rBjqzzgfANLWSXXtPI/3nuiDrhSGtUOfznfhtKggbg2hUfo3CHk2G0AlxSA4nDcheOSgMbP8mNGH+cICI3FUVP78h203Xy/BTEdppLNtt6Asr+ZnubtowjcZMmm7QZ0GAdANHbcgsfY4KArjAfyP5MsSG2h5WQdMIDkRGQB+7SbChr2qrHAzvi83qwf/X9mQm1TJ4cOBauIFCpGrFcr85/KH40njZfQcxEuoS2fQ2lbMHzfLt18gCj4z7w0DF+rZS+hoK/uiddQNPjBuWgcGuQcwlQ8yTJyyMxMZotwZbvIrnBh0Qn+2cstz5It2hSDbHvnntxxfCY7hWRmhMYq5EAhGLCdTL02oZYh02Eb9/tWA6BqXBCTLBGgAkoiauXsswboCULD4P0GZq8Iej/gzjBx1vQqFPvf3OJe/Z7vUjISnTZnglfPtmWInXWAOPYchauxASwmeXpfd1FgfXrDhsa7J8ZUusXmF7UpkHXdIrYBpaGhxPVw1tL5bY0B37p6ZxEUrDaPdX0SOYbp3/Csd+WjnOvOlBEFT9Um/VLAmnxgAojOLYGViMrgLq9/oNcPW3FkBRqQ5EIBzIQJh/tW2D/eko3B5wX96zQPd8qSC41kycWMciy7R3FAqBC9AEqSmjllyWrjVhPReJkqVYzxno4s+hdmlYF0o2hoJD2yO3XoT7fPAqk1xpUBJfRRML32AbxcEzw1sSMCaXUQK/vL1QqKhCo4Ze6
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
