---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: home-assistant-app-daemon
  namespace: default
spec:
  template:
    spec:
      containers:
        - name: home-assistant-app-daemon
          env:
            - name: HA_URL
              value: "http://home-assistant"
---