---
apiVersion: v1
kind: Deployment
metadata:
  name: home-assistant-app-daemon
spec:
  selector:
    matchLabels:
      name: home-assistant-app-daemon
  template:
    metadata:
      labels:
        name: home-assistant-app-daemon
      spec:
        containers:
          - name: home-assistant-app-daemon
            env:
              - name: HA_URL
                value: "https://staging-ha.smith-simms.family"
---