approvedGitRepositories:
  - "**"

compressionLevel: mixed

enableGlobalCache: false

enableScripts: true

nodeLinker: pnp

npmMinimalAgeGate: 0

packageExtensions:
  "@langchain/langgraph-cli@*":
    peerDependencies:
      "@langchain/core": "*"
      "@langchain/langgraph": "*"
      "@langchain/langgraph-checkpoint": "*"
      typescript: "*"
  "@nx/js@*":
    dependencies:
      "@nx/eslint": "*"
  "@remix-run/dev@*":
    dependencies:
      dom7: "*"
      ssr-window: "*"
      swiper: ^8.4.5
  gatsby@^5.0.0:
    dependencies:
      "@babel/plugin-proposal-export-default-from": "*"
  swiper@*:
    dependencies:
      react: "*"

yarnPath: .yarn/releases/yarn-4.17.0.cjs
