apiVersion: apps/v1
kind: Deployment
metadata:
  name: zwavejs
  namespace: default
spec:
  selector:
    matchLabels:
      app: zwavejs
  template:
    metadata:
      labels:
        app: zwavejs
    spec:
      containers:
        - name: zwavejs
          image: zwavejs/zwave-js-ui:10.9.0
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8091
              protocol: TCP
            - name: websocket
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: zwave
              mountPath: /usr/src/app/store
          securityContext:
            privileged: true
            allowPrivilegeEscalation: true
      volumes:
        - name: zwave
          persistentVolumeClaim:
            claimName: zwave
