---
apiVersion: v1
kind: Service
metadata:
  name: zwavejs
  namespace: default
spec:
  selector:
    app: zwavejs
  ports:
    - name: http
      port: 8091
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: zwavejs-websocket
  namespace: default
spec:
  selector:
    app: zwavejs
  ports:
    - name: websocket
      port: 3000
      targetPort: websocket
      protocol: TCP
  type: ClusterIP
