---
apiVersion: v1
kind: Service
metadata:
  name: zwavejs
  namespace: default
spec:
  selector:
    app: zwavejs
  ports:
    - name: http
      port: 8091
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: zwavejs-web-socket
  namespace: default
spec:
  selector:
    app: zwavejs
  ports:
    - name: web-socket
      port: 3000
      targetPort: web-socket
      protocol: TCP
  type: ClusterIP
