---
- hosts: all
  gather_facts: yes
  connection: winrm
  vars_files:
    - ../.secrets/ansible-secrets.yml

  tasks:
    - name: Configure Windows Update scheduled installs at 3 AM daily
      win_regedit:
        path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
        name: "{{ item.name }}"
        data: "{{ item.data }}"
        type: dword
      loop:
        - { name: NoAutoUpdate, data: 0 }
        - { name: AUOptions, data: 4 }
        - { name: ScheduledInstallDay, data: 0 }
        - { name: ScheduledInstallTime, data: 3 }
        - { name: AllowMUUpdateService, data: 1 }
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Hide desktop icons
      win_regedit:
        path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
        name: HideIcons
        data: 1
        type: dword

    - name: Disable UAC
      win_regedit:
        path: HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System
        name: EnableLUA
        data: 0
        type: dword
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Ensure Chocolatey is installed
      win_shell: |
        Set-ExecutionPolicy Bypass -Scope Process -Force
        [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072
        iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))
      args:
        creates: C:\ProgramData\chocolatey\bin\choco.exe
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Ensure PowerShell 7 is installed
      win_chocolatey:
        name: powershell-core
        state: present
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Ensure Steam is installed
      win_chocolatey:
        name: steam
        state: present
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Ensure Epic is installed
      win_chocolatey:
        name: epicgameslauncher
        state: present
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Ensure Playnite is installed
      win_chocolatey:
        name: playnite
        state: present
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Ensure 7-Zip is installed
      win_chocolatey:
        name: 7zip
        state: present
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Ensure Apollo is installed
      win_chocolatey:
        name: apollo
        state: present
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Ensure NVIDIA App is installed
      win_chocolatey:
        name: nvidia-app
        state: present
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Ensure 1Password is installed
      win_chocolatey:
        name: 1password
        state: present
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Ensure Windows HDR Calibration is installed
      win_shell: winget install --id Microsoft.WindowsHDRCalibration --accept-source-agreements --accept-package-agreements --silent
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Ensure Dolby Access is installed
      win_shell: winget install --id Dolby.DolbyAccess --accept-source-agreements --accept-package-agreements --silent
      args:
        creates: C:\Program Files\WindowsApps\DolbyLaboratories.DolbyAccess_*
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Ensure Tailscale is installed
      win_chocolatey:
        name: tailscale
        state: present
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Ensure nuget is installed
      win_chocolatey:
        name: nuget.commandline
        state: present
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Ensure rsync is installed
      win_chocolatey:
        name: rsync
        state: present
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    # - name: Ensure node is installed
    #   win_chocolatey:
    #     name: nodejs
    #     state: present

    # - name: Ensure Git is installed
    #   win_chocolatey:
    #     name: git
    #     package_params: /GitAndUnixToolsOnPath /NoShellIntegration
    #     state: present

    - name: Ensure vscode
      win_chocolatey:
        name: vscode
        state: present
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Install the Win32-OpenSSH service
      win_chocolatey:
        name: openssh
        package_params: /SSHServerFeature /AlsoLogToFile
        state: present
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Enable HA Ping through firewall
      win_firewall_rule:
        name: "HA Ping"
        description: "Allow ping from Home Assistant"
        direction: In
        protocol: icmpv4
        icmp_type_code:
          - "8:*"
        profiles: private
        action: Allow
        enabled: yes
        state: present
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Ensure .ssh directory exists
      win_file:
        path: C:\Users\{{ user }}\.ssh
        state: directory
      vars:
        ansible_become_user: "{{ ansible_user }}"
        ansible_become_password: "{{ ansible_password }}"

    - name: Read authorized_keys source
      set_fact:
        authorized_keys_content: "{{ lookup('file', '../.secrets/authorized_keys') }}"

    - name: Ensure authorized_keys contains each required key
      win_lineinfile:
        path: C:\Users\{{ user }}\.ssh\authorized_keys
        line: "{{ item }}"
        create: yes
      loop: "{{ authorized_keys_content.splitlines() | select('match', '.+') | list }}"
      vars:
        ansible_become_user: "{{ ansible_user }}"
        ansible_become_password: "{{ ansible_password }}"

    - name: Copy sshd_config
      ansible.windows.win_copy:
        src: ../src/sshd_config
        dest: C:\ProgramData\ssh\sshd_config
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"
        ansible_remote_tmp: 'C:\tmp'

    - name: Restart SSH Service
      win_shell: |
        Get-Service -Name sshd | Restart-Service
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"

    - name: Ensure developer/tools directory exists
      win_file:
        path: C:\Users\{{ user }}\developer\tools
        state: directory
      vars:
        ansible_become_user: "{{ ansible_user }}"
        ansible_become_password: "{{ ansible_password }}"

    - name: Copy install.ps1
      ansible.windows.win_copy:
        src: ../src/install.ps1
        dest: C:\Users\{{ user }}\developer\tools\install.ps1
      vars:
        ansible_become_user: "{{ ansible_user }}"
        ansible_become_password: "{{ ansible_password }}"
        ansible_remote_tmp: 'C:\tmp'

    - name: Run install.ps1
      win_shell: |
        pwsh -File "C:\Users\{{ user }}\developer\tools\install.ps1"
      become: yes
      become_method: runas
      vars:
        ansible_become_user: BUILTIN\Administrators
        ansible_become_password: "{{ ansible_password }}"
