---
apiVersion: v1
kind: Service
metadata:
  name: vmcluster-victoria-metrics-cluster-vminsert-node-port
  labels:
    app: vminsert
    app.kubernetes.io/instance: vmcluster
    app.kubernetes.io/name: victoria-metrics-cluster
spec:
  type: NodePort
  ports:
    - name: vmcluster-victoria-metrics-cluster-vminsert-http
      port: 8480
      targetPort: 8480
      nodePort: 30080
---

