---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playnite-web-game-assets-processor
  namespace: default
spec:
  selector:
    matchLabels:
      app: playnite-web-game-assets-processor
  template:
    metadata:
      labels:
        app: playnite-web-game-assets-processor
    spec:
      containers:
        - name: game-assets-processor
          image: ghcr.io/andrew-codes/game-assets-processor:12
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          env:
            - name: MQTT_HOST
              value: mqtt
            - name: MQTT_PORT
              value: "1883"
            - name: MQTT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mqtt-credentials
                  key: username
            - name: MQTT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mqtt-credentials
                  key: password
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: playnite-web-credentials
                  key: database-url
            - name: PORT
              value: "3001"
          volumeMounts:
            - name: games-assets
              mountPath: /opt/playnite-web/game-assets
      volumes:
        - name: games-assets
          persistentVolumeClaim:
            claimName: playnite-web-assets
