---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: playnite-web-db
  namespace: default
spec:
  selector:
    matchLabels:
      app: playnite-web-db
  template:
    metadata:
      labels:
        app: playnite-web-db
    spec:
      containers:
        - name: postgres
          image: postgres:13.22
          imagePullPolicy: IfNotPresent
          ports:
            - name: postgres
              containerPort: 5432
              protocol: TCP
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: playnite-web-db-credentials
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: playnite-web-db-credentials
                  key: password
            - name: POSTGRES_DB
              value: games
          volumeMounts:
            - name: playnite-web-db
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: playnite-web-db
          persistentVolumeClaim:
            claimName: playnite-web-db
