apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/playnite-web
  - deployment-postgres.yaml
  - deployment-game-assets-processor.yaml
  - service-postgres.yaml
  - service-game-assets-processor.yaml
patchesStrategicMerge:
  - patch-playnite-web-db-pv.yaml
  - patch-playnite-web.yaml