---
apiVersion: v1
kind: Service
metadata:
  name: playnite-web-game-assets-processor
  namespace: default
spec:
  selector:
    app: playnite-web-game-assets-processor
  ports:
    - name: http
      port: 3001
      targetPort: http
      protocol: TCP
  type: ClusterIP
