---
apiVersion: v1
kind: Service
metadata:
  name: playnite-web-db
  namespace: default
spec:
  selector:
    app: playnite-web-db
  ports:
    - name: postgres
      port: 5432
      targetPort: postgres
      protocol: TCP
  type: ClusterIP
