---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: playnite-web-mqtt-credentials
  namespace: default
spec:
  encryptedData:
    password: AgCgr8XV1We25kQ6uSNSx/lDDAJ84H7jbC/8f9ZIHGwm5sUcJHiIjGQXul6LPHvUSqP9bejQUGvORyevBldB6Q+J+pJ1sZaq2NwOPs/DGgSvExnT7kRs+ivMRoeff1L1ofO9Rrr7wmkzHjCoWLGfWG8Sp9pJ+nlfiRZB9XaCtdeTvY0VSdc6LtfxsWD9AUVUIcngUteBawk262BBSUaPOk1m9KrJgPI16d7XFfwnM1AtAiE0yNbMHqM23A4EdqLiXukENF2SYbGkgI7YQuxXguh7DdEQyYnk4WMfJxPlfwQn3q+AKsqQGNRxviX+joO07DYoyE0LzFRsasRK8T1MXxUgSkOyy+HYKDdE66HQr+CYZVYDZz0n4ZOCu3gDHgFwlxhp0un0W0KV05RzZoPYV9dNmQBuF6cAblt797NTTACPDELaO5e8uMyRKki+pLArQeUo2/6xEAcWSguZ7xjZhop2CORBVsCzfHenKpupWNTRb45p4qvzN5fsoiSfQIGTeMecOifdXu/2nqIwe+RWAR3lyMCc5Ui6CsdrkIjlSXEQFcqBE4f0kYzDRxCoiuLhaW98aJDwexFPdc7ChD8wGb0SQ/f4oraEfpuk5Kx/WDG1zz7HLMEw5tomLHeRl3sCZmkFtcteqG6f77wr2xelTDTJDqIGOLgUOYPm+yoRjvWrqnFL67olCDDAKkGr9io5CqYCXq5VXkIyMMOn58oFBfjFQoVGM807PO/1VEOgsEohnN1LvtHhD+tYKeKAYGd4GuTAmWJjQSw=
    username: AgBLUaq25yfJLJhOyqUAtW+6m15WKYpUHzPAzS8+RY4GmSSVM9M5XiIYxn9/cOTkadg9dL1T/kRh7ERQp728DLcIhfyKwEqYyATZuuZJD31o4XI8EWqqcVrc8hFb3k2U1a0HGtek5OLCc2oNU1m7rSpg4MaLjPSl1VivkH51E0XACGgr62aDuRGEiPHEu+PxTlfura2LkqHOmEC47KY4g9BbIVU6SN6kBtKQCT4fgVeP7DvW7pgkA5KaOo4Clqk015Qm75vizz1t4gjJB7hpbB/no+zI5n0ZK1YG69U3zquEbgciA6YlLwf3njNbgwMmpyP+RxBNO5b6icZtc0qOX4rs3/mn/2VH4i9oFXpXhBDFtmf/5oTqGu0t+qz314gnk4F4sDzJcXswae3BOYje/EkdTXET5S0QSwCPHsXfs3ILuTiJEZYvlIoyoDfhBao9BRATQ0G5BfLnGnR28lneZGYTwVsXrzyoFXpKHAzhO8NKL5oGM0uWYE6bJBt50SqdN5e004+xSg2TvWaPdp5lKW9M6nWMnc8XgX9PRAH0ufs1gw9plGDlElcnGhX6k3QP8h3pnINsGezeHc0AqJtIW2v/MsriQBUjnTLUSENvvgze43EF5veQpzkCpotSvl2GQo98E9hhzSmLTbTwMvlAJioTiXQQAp64o7K1Fl89XJxBSntB00OXV+InwDl2xOi9vQTF2ddzYLc9ODlezxU+a6r239dS7nkARbsY53vFMBkYRuUuxJ3bsG5PMxGi2sAg8IvGLDDg+P4=
  template:
    metadata:
      creationTimestamp: null
      name: playnite-web-mqtt-credentials
      namespace: default
