apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - service-kitchen.yaml
  - deployment-kitchen.yaml
  - service-game-room.yaml
  - deployment-game-room.yaml
