---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: couch-colors-results
  namespace: default
spec:
  encryptedData:
    token: AgC0J4TOGGNjZBasv/zvSBCc/AQN+BeqpKlDyt2bDImp8viumwSAIIf6QqlGJxWBGnIjCZfIj7HC3r1TWNXerSJ4Kh0lceUbwwakXjU7krZ0h1kx0SToT9LX+zCokFqMN2/veKN3V5HB8RJ8bxcw5HOGVLSmEdmDU8aBE0iI+KtSS0zWfC+XAonG3WsK91ON2lcbVRQ7t3zQnpADfj5LejnFFB7bzQJOAJylG+eIyR7sCtg+Hr0XPpuJGEFqUlojPAyb581/wEimIUT04cJCIMS0ZuLufrKJuuxn5DB83OJLrOG4vuMYN7L64x8V9s+BKFbZmXGPRA/K+ovnVKwPju+1oTBEJlp4bgcO5dwnWcmmeqktz92KJlYX5VU6kZn1lX5ilC1OS3RVB5XPM/gERinD0FrOA4hlYS8YF2Pa1kWx87wlXu7MSO11KgwhX4OOICJwHjdtGo9H+/KopW5xKMXQsR++DLmCDlgCjxmF3Z/f3mG51m09EWV0yEY24m8lxlVrWwvVRBXvb6KnzEWuAQCWgZz+Ip9BSutg+Lhf1Kk1gm3AdsxPp49HNsnM5gPJmfsE7od6XvT6XLnoVGiGRUxHM2WXC+KrzJbU01jOruzVEhst7gxWwXykNP7nkiP4l6HuU7QvjD9880ZA4RxV9ufvJvF2VaB3KKot4uC9HZCsHxMb+dSZE776V8rzU4q0MoD45m4u+lLpg0cfBRNWe7ftNLEhFiNF4m51CpdRQZTRQK3KAtW0BLpQyppc
  template:
    metadata:
      name: couch-colors-results
      namespace: default
