---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: couch-colors-results
  namespace: default
spec:
  encryptedData:
    token: AgAIZ8molUyty9zzyU5kB6kjeN3QFp6II0kF7ME+2cmSVegL+kf3QGHl0BYO9huap0uyWclCBftWP7LheUb6iiMzF4fijpZtZdqNJUH34hZmwApHN1s/Xgw4KeHyXvBCrNKnK9+rk9/e6O8aQFu4ldQmDaHK5Lk8Q09nabZdWNtls6ttOQ+Sqm5E25ZUvQITpVSIusMH6/47YC8uIhK2w/uDjRQSLBgEJgOlbB4SGlssTZzOzc4olP2EsiU8JASlK6Ssikn75OCt5Ao1VNglTN93N/2vP+r73vH68ODyOaRydJ8oT4emnY3ulW60fBoOfjcm3L+iUvdWHWu3hkGhzmmmBHpnfhC983Abu+WsLBcg737XW6UVWuuUaCWdE3e4ScDcKsFgu7q4lbGGV3R3k/XJz/4hdYO4vTHX8F+XqFJ3AVCBADQmZfLnA+d3xlOdIe+b6npMJjyWPAHZENggDsLjRVE1wRHdqKKmPk0mojiWDdzvvc50aBgamUkDMALgk9ZloTIMvCHSEXeTcuzm6VhvKjB4mz4/5KozHxmJJmqd/m4HguFhtIPzcxXKb6adEhPV+feOCw3pm59a4hNl5paWaSUpUWTxBGw+AJKBwwGX/HsM8c/rYTdS6OAi/5ncar811K1HKw7rnY76TMF1cHQANWYwzXz1BWzdANMubvHmGrA7a5KsUvNIMHGfJVawqS6tLi1uZqqdtlTM/ZTgu1Gg+0uT1U/yak8M+GF6WG9n0A7k3jM7+rmSJiwbiUQybn0=
  template:
    metadata:
      name: couch-colors-results
      namespace: default
