---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgCraapQi+5574KP9Vv2KCUxA4R1y7/ylbNTNvjKSK5sW3wA79z7KPHhoJG6D4yaRMGHT15iQvopJyzJl8RdttH1EMkeTkruIHYvQWMX1zmB8XVacLce3l7E28npsftGhh/Cd0Dx0zy//9/vBCkY2XLizs8HFHbRRQirpNiV3s96TmtSmzPundTVt8ZSWFxIj59wfWn1aiEHQzDMX5fXrWU5DnnfTWxOMurehLCKnkRJMWeMTMz93I7/yrE76dv6RZSp7IZhvDoN0FSePQH9NhaJXqzxmaDEusGawM2LzCOlHjZv1Cj/OyZemHjgjELiQyfJSkwzxTQTnFvwH6x5aFzO7PSEgvj2M+2lQJ2yAvQzUnC1LYGnhfNPE0fpKEyw6x9MhCQy0jPApKskbl7ROoYbNdjDRBkPEwLq1/VBNb18EpvS64TAQdHsRzv4IvcyJUMX5P52BYhLsQqkrknwr/7dvf7SXwsc4sOWSPAopTVNBWtXbxEh7FLRd5kMAPyYEqDNeK0KDDg4aohhYvCn2JKOOTLn3NJhq6Bbn6imsACqsACmYDb2l+CO5M6pvu5bdE1ZLLGYp/H36NV9b4k3OBlw0X1FybKs5WXyo6wGXCu4nbOsV1Cb09KRiFzqw0rcdH8ziLf/g7lG474kBEMZRqFHPF7dAuxXUKM7GKUzCLmWbhSbKbE4gujBW7MLz+ooX8TjFQIBoGZPDsn9z+iNzxuYuHdT8I/oyXQXE9MqhKdS/woKCE/Xwk0=
    admin-password: AgBtYa6Pjw18jYxTgrgmTTY5X6PDVv2Xy04RXokwLxCmrhLFFlKWubDZo7OQsnh9v6docjJdc6nutxr/V05a00QqCrZHI9FwLMXuxKGuT353UW3KioFo6t4GHP7UzrsEPtAMiYsL8X6LPLenARpm46bzqHyEEJpNKO5XTRYDfgP/glGTNEkIo9iubzH2sj1aI+LtX5zCrxF17RcyUpZX1AwQpRIZfis1GWMZVIALBFs/2XGlRO12nMtNPd5yMYG76+wPmicXE8KZTKPXsB7h+jWQJtDQ275nzeHrRhIkGXcMSLtp3yQ+H14TUPb7/POWRg/AmbG14xrDqu4ieoZ28wKHMJw3CgN+Lo7DK3O2PZdxBlghg42Jw3mNgbqSngTvMY5O5+ltGf683P36mOQSQ5GbdX7Qk5/W1FDwNLTJwCP9qipjZ532tnfREQjBIyFqD0pPt6y/DpFdyfXOEPil+OmUMJ/VrTeUSgjyNrO+vdRLcdqrQhGULgWifcoJ11qLQA6w5tvTQnKzXGZ7jskRTJusbDrL78bfUcDfmNnYO69HfrFvefxlNj63nu7eGy04gTgO7HqhRxqOtao2AUmKoeIlRiH30e3aRDgPxEeKlAvsgWjax42IkXiKzSWwwZnHer6+rNKe5nErkG9JLI9KZ+l98gm949lZ2I672ai9j/oDk4ThQbqHMvi6RqZsRHfQ4+zKrdRLh1OBO4jZYjxWwd/uMiF8lYH33RlkV269pLFVYGAvildexHU=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
