---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgAPJ4VNIHJ88adG+BxfCoDlotX6na5NT8IUBtzr22q7UYd1JEkghBP8Lz8m4scdQp8viAfNxkf7IS9oMcHy/t2Vn37rJvEMFKkbRBjXFBGnk9rVovd66nfTP3sv+rMaGju9tqY0PyUKlfiPHu9LlrXF+DgXlWmd3SfRy4UunGvZzOrnA1voVWw3J8QH3CizobOQPmSvTfGQ/I7WU33O4VEkWAJ/th/1HbHyLLUVuqVVukaWOuVb9+vv/6bUtC1PuocOrh4xg29+YIX7t0FZsbJoXvogaK35USVYVVS/dRLr5YvzQdUE1JhfUdoyB+KO0fyr0+/AGV6W/3UisNYJ2g76o+2hj/1FdJsU1w2bupGkiApI2JBpEy8eW0qxiK4yre2W3gaHi6831HDfBnCY6WOBViG0gPxvqXy+VGdS4pg1wI601hLcyA5nrr8CnGqjWWIHXngwSKVh3xrqJakPMmn4BPX+5QXdT+1OMJDd0ZE4isg3i1O6FI6j4SkwdcOHe3SjJt4OA+iM5MZi/X37n/61SSCgjs8NfYw/UdE8/PCPX/fTpFhii6KewiOoJSOQJZD2Bw89XnolXmRDPWWxocnyX4OG7sKybPd+bhxLo/7cQ7B2GVvtRamYP4/cLLncCeEP8VPih+GKlLruC19UpddBIlyvSzbWSnNsH8JgcLJnVYuOwNnQsu42P6qM0b3/AxEPOaS3NnJT1t8rcnFJzqKginEMFnzIxGx+S6qBb28N/0z+4AYg5NA=
    admin-password: AgAALf4tSilBoXhDaNbUrOn/j+or10IUN5B8A0g8z/3huk3dKAORqs/zMtXPwiMV3x1N1CkJJZ3DHbWAAy6O7EgUd/6nLxiESMYco3z2d74WHk45BwI61WCGVrcUy8CM+MUqwSLUMc/q6NWT0z5gpUnipEk+W4GnvmUR6Ag8DuBQCGhoyFnFLGigzvPVwkG6NE8dErSx7boZz98MZIXlPxQBK1enT+XWqpUkT4sZtOMatjV3COILuzL9q7hBZMK8TZ/q9bz7ahWByk0M386FlKwYweeMRZXdG4SLc2mfufTsW+URAUfjAwPiiG+yuHcUKoeYE9dSnrKGqXGYzSE3TuIEJmEc90alDCD6wB0bNO45hsv1khpiyhV0d7bP+Xv24+UBKTTsWEaGXEUG6v8y8qkxsX0plDaw+VlqKkqPulQVM1F/P+ynroq5HRLqayeZFfatnzheAxflRkYsIx9UjG6OFPBD22R+IbBBlqZ9aaVXGFLG/BtziENyPPDlyhzyV5nV4rzb2NDfYhO9F+WU6JcuzJo8T3hpJ7zYPjf4665mEhWaZtCDTrqjU+eVL+4G6tXeDAeUR3vXTrIN0La7jktgqn6PhYMYGbWTHWWqk2lQ4vYX0euf/AiKHDUV3XS2Q3mcPuvGnp1UlW0VSIAdEf+uqhxwvKFMg3AxWeB8YhyaZkwI/b+oUYydtcwllspUuO3dKgQI3ZyNAJGWbncYdGExRRfAKLk+WK48X2mzrVTH180ApnrFf1E=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
