---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgAIE+I8IojURugw5rFMwEvFpUH54z6YqGotyf/7dSB90jyrLVXvUWcyKGw1E6h4oCvF15ma9uwyYjJSHZLpMdSP/6n0QOXV5vwAAbh2GnGgGcpqUyt1awhjm3uUmOVPko4XVljzIjmDfV+bEpiUNIrF5y1ue568btKjTbLuYN12B6JmwzW/dGa9C0KIzql4e6bdHAWbY3++o741VTjG01vYwz7wiF9zcse0pTwcVgffPijYpqzUXcHGUrt05kjq8gaiYLhHFz2o8TK2NSGLPlJJPtNA9BtViwQIPVfcRWqoav1+inEsK9uJzGcbM5uz1xdqwuebdpApTN69VsWNUeSbcTJT6nKaIeF/Dsfmx+L3ddybM9VvoO0Mh82BLf1PrVGtpfP5vA5C1ywmE8YAeCJidBhUJHmeJehZbUbF3HJIoX1umj7+lpg7/ItGDbDZigMylwFsbPs5FESmJNwgObGw+XS1jGJa+JPC6I7xl1m/xVYunA/IUZY7l+ZsA7AF8AKtTZRBzs7+khybsE3TtKQpP2X5awKJbv9oEoKMca/SiIOTcVdSVNdCNvjqYm0nJjYu11DEpbrqa1SJs3nPFGZVK4ByATUO7usTzraqs1hFGIMf1bAeryNuSvXHnKLI3HJZK4b8JiMVpH2QFvBbPkwARMZPE1Q6ouEc9bUfWHUwR0EUrLEI4cmFLKookn/VlhhhQimK+hPuz2iJhEscUwO32wtSZH/TnsT+eqIXk3NsVy5WpHzEZYI=
    admin-password: AgB1mTER5xjk0m2rWBriDGlImgDvyfMsGzZmlHjF7c8sdB7bU6BFGGRyJs16QQXKxrwBF36l1ZjmRy0alDOiCbg+v97YC7VyeyxAvb5gbNGpftobjCQ+Rrqcn3P4CpMAyhHlAy0umJqx8pt8c47+as7MwBX9xvsztODenDZNW5eWo1bhpmOVTpZPm8FYoFIjjBkkg56fQ4tCmk7Ca6Td56rdSeJ/qOcvX7tirZWBL8WaQRxvKcoizSfWNjvlcOvkGMPkilKZhECZG5+zuwF9SeR2hgysF6oSQHT8TSqq7jWQVHHNGGo6+YJFYGwJarfkYblCIcY1dIBU2Lz1p5btbzhxrciuTQA4eHfo3lDi3npZr6QFaUtpSoZofhoByRO0kcnI9+fkBod2XD19xy97MEtlAVWXG72MrBZQNGoJIf+uO2G/P+iB6V3D2bu6tuo4Y2yMdfptxuG6pdgjniIZaLaUoXVF1gSMO5l2AIC74FF5Oo8HGZXmHBfn5caDzQqWI6qQW9JCPApcYHSnMP4Daiw1RwIMp5qRQjTs5L/nrS1gdntvGCv636e5KirbkyoYJlgSftg9iqMqgRWUWOsBm/texVnFMC/CJtnN4q9oePMnH9ioQErCMkuqSczLXsJ8IUgDOKX1cS9l29/yNcPJxioKatSANTyQBOcJ1+masDbe8p1gx0t6OFOaYwNoF7xLzfsAjic1A3kyN2q0CboyfnJbSKxKiAQBah/qiQrBWNLxJGKNyaVPFP0=
  template:
    metadata:
      name: grafana-admin
      namespace: default
