---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgDeDGQMlBuX1fsZw8/vaebx5YDZK6c4m+zFd2P7OL2ydksZKTL5q2/L8EYRGRpYrVRuMh5CxnSrGaSzAYWil8R03MsJpqncT3VztuuKEkAdEJgGBBZzdBztQagtC0M1UuKho26+lTOo12JYNJnnygHAcsDoMCKsO2MupFXJMBc8jyyhYfkH7lezLb5+H8y6c/g7h3eY91qUDAaoovIRWXeilHqATqHbXU55L16IdJEessyTDxeI6tJWSxucDzqQDSYTxD53s+FpD707XHF8C2utRjscWeHJyvUfft3TdfAU3AcQTJPk/2MWlo31uep34aIPjrHy87x7K2wNcjic5Z/cndW2E+vL3kcyksum+AO72Gfz+Tko/Q7SBYe+Hr7H0frt+i2fvlYLrAyMrWa4GJB1bAfZEA8g1RTudKMWLT5BalciHcSakktQ0710xPsm9RJZGOKMPtKRSnB0YXP0KP3N8MVBmy9zQIYeI9LVhgwbLJp8//Kn43f1xNJQAiVCegZUsygN0eDssj7y1crjYIs2uSPOreXus4g6bQ0ezPn4cLLoQ8PffdXn75IJHKZrIsg/LPtjZg3q15oaDua5T4MJaMTYDIGtczFW8ETXbn6tHxTZ/Zqox3mNyLqcGAep5nS/40zRaCdoScH2VPsb91fuiSqP0bH7Iy8XssvUH05/PnQmuWma+Py61vM9HH1wZrn3jtEYl8IVGhD2uWiJdZ4BSJOt0HkU8ULdYCrYI3kg0eZ37oJxHDc=
    admin-password: AgBuWQX0d4+HOTRTnbj4lFabuxcmPiBAaWJ9Wx4J+HNUXJ3RaBVUfO/pvlSgaFnte57sirMBFsgVu3bNmk9Gu1Ejfsa9zATkqRdZBnOJ817cOqyuJCTsSH3DsJcJMMs5+k2/VIvshLXBPp5R5EgVS6vYAVPTAXRFur6vbx5GsfZ2Y1eHZIDrvJyTeRMXFYqZxvyol5jI8M7xnXJgbbGOR7IapMk+FrHd97WTpSUKUjrayxN2sEl/rbkS4tJqpEq3S6j4tY7U/Hva3AShtPyZJKQFGdJUa0UYemGJDfwkUB8iTppWwpJ0mFXZxwGx5uybTJEqCPJcVPDusjS/p6O2byQrAYT3UNWL9GijWDeVT07ZKD5KO4e3aN/KbeBNPP/OavoqEBUftwwrrPrzxi8BkT77FFwCTp8fZEmKQ+G0YGxxefvnL1eCpmCKP8XfA0MG7utQ8mqfTwsLzpplFEVrVbiNtMdu4QzZG0INXpCCixXoTu4OPYpLF28Kdt+svW+drgHdRJPKnoPHK/Myo1ApAike3UOaHHp+PdvvXCnU6i2bCVS5RBqXdYNa40cZl47Dz8f50FEHBJtqHlCXGfMCOHIq6L3XEZ1wbUk0h07aIEjZRhGUsHk6kw18mTIMVF1f4U10jDTtIbKrJe4/4pgpWuKHEA8+nE7vljYtVeMi016BP6E14wZGNk4kfVPoMUw/Iv4ToTQlCULtkWMIA3MgHcc64tiuiiLqqUjo+haW5CWIPppQq0/V3e4=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
