---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgBA22gPlpLpAqoLEyhS5CW1IbMRJsN1QhoFt4LJ7xQbU2PAlvOtHZh9XYShbSpoe1SQTCwl1vQhIwk7i80pEVtETnJO4/+hKi2Jmt0vLwnuY1Hp2mzQOcdBee37ilLCWno232PJt+p73bh57x+ZeuBauubiEUtv2LUthybBK2b4RBA92I+yAWlu+Lf93CMDcq97JLwubV6Tz6a0qiOD3rZCd9VhL4r7A0KUMRe7uFiDIop+0fV7uO3VNeu9clDzLSQ2k0H9GVT2w6nUaEVCfuc7e5bqVNdDW2UoRwPyXWzHf4dO8YOUKx5Kb1B+Tpc4A93otfInjHxFXByn2NyVSliiTyy2fc4Z2goudyMKWFgjYfmN9afp6AKuybo4/prqmIwnH1h5Q89psCRB26aDwWt0hVseuz/g4II6LIXtoqGcGJF8iw6qf8+QbMIRlhEl76J46oBzeKMuwqHzG7ZLxCno1lAL6wOo0SGT+SNouIOGJdTwdWxr1+tXFomq36fDnzWmJ6jahHNA9KaFhxrbXw0yhgX9DfAWZ/19Yfv2QRXBq/IdeVRxoekLaKy8Ya7YOLxxz2uhlzEqC4vJ/0GcMIVNuVLj6pXU9PguVUUME47EOY/IcFN9qt3mf/TU8g68SYQts8FuaFZrKKT8uAp9rqc6xTYQmcnptRgeymwx6SU+HYGvkadD4nzvFP2Vw6v1/neW+O6LMjyUfw+Ps261WpAgtK9qM/bnAPJMxQP7lNgSIF13inRtXSGBKA==
    admin-password: AgB6sMj/UTJ7D+J/6/9Jfo3V8Ih9bFBsMoQRifeThUilEYE/7FGa2kzdSBCK+wovt6c6hLPZCILS+x6auzilwhlQeQKbTfyuQ4p1Vk76BP/9o4syOU6NPf9S1/X8lrzFrpbvKXkvyMYlv9a/kdT7rV1fefArwykQpWP3mjC7RLJKpQNIgEL7CEJ/bg4d0bdgoukRLJlMjM9Fk+S91JzAQsZVlX0OfE3odccQLG6Y1V1TLOgnQFt7bNynaTxDNH42mhDxFLpcuMD/iFMyyl2E9ROhhFfjJKrGSJGT1yfQAbwGU2YYN5Kb9Zj89MOYY3Ne+1E753+U8+FzzGx+ChZotoTOqkvps8Zu4fVuy5fZMxBcaPtQYw9dh76ppTmm0H3KFA7MSBN/oftDfklhIgPuSupJBowrN8mui41irwl+LLOGKzR6/qNwC8YUQyBoROL5nIbgftiw5dFDFHIPHyCng2/CtxQPEvaCzhcEfh671UG3A9vm/Mgylh2pRGl3HJRinA+7j5IgSNvJ4P/80x7NoSYndYy4OI2eHM+g0S3ZDiU5tlayNoGXBoh2Fwlvszww4PMOGS4EJBAERPzfL8Rco6Rj6l8BRwEffJXWZgqFDQJkCGdJSYUogTBKKpCiNAjAh6nwPW9XP+72iZyd/Alx1TGDUE+Lb0Y9gqImXuKRWWP+VnyVWJmFLCUopohnKkdtnUvKvNV609qdqDEv89Tt/if+n+kmkUCzDrGilkAvqB8lXfCk7OLb2NWo/A==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
