---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgB/q7xT9+yimNbseMTScgqZ+LS8rVQibzCQWuACietXZCbFnVwyzJ3IQED5V5rNyrTeRtA7Cp9UoLTQ7TnHGy/nZw/TOPrG9yV9vlHOIUrS9GddeRQoZ/AaXg9O79pejE7g8TEl75bx8uA2aFehT4TTgpOXiobrRnZddgfbbemV5/kM4YwPV7lfoscaSXaNQrMoeVIAXPJtgxwQaDzRiTMYqbHvYu9kRKLKZlEj80IsHFfWJC3KJOi2s76Swdq19AEgoV1ahjUa7NVL5osPo5Wi+9klnfaC6iOkRFqsE3C/XwyzZimOCXtajNscboVXygPcSsmCx0e8n9KKbyF8k2mCr015CcErJ4jTfZsEzuLetp0yY59ws/OSHsdvQVpeHpnDsDtCuqmpcF0pbvyK8RmjrwcC6VWbIIOWDxx5Wl1GRM670V1akKG3RaqxJ76xZVxSiPb8OywcHqe6rZzh+E08ZDTxY8AxnJcRMPjwPvcnYLQspn+h8xoh2VFAV6dgoHI8/Qx7g3Y6rfSCuhCaPr1GpoJoC104Utfk43f7x3U+m1WdXinQyTaIKVGR0/5Hy0H0IEPEjPxqUHgOtaYqZazon171lPZkX21bC4K8JkCMc1MzEtca7TUUPARSGEI6khLYD3XM5phd07Xk57aaV5UcS6THKj3WrYMUmghOx7iIxa24JW9ySkSun8ODcrxRhzUfcbbzeKjY3KGjMKAfeN6yssCr59LQeHKKVmrVkwq12j2X7tuMUeM=
    admin-password: AgCAlqc8DmX6gKCCEP/5WyhA2r/JjO9qkuNwiBwAjkVW60ebn8RkVA0VxI2nKHhUej0qDHVGZ5coh4uaGrQZEm87kwTr1Tkj3+4ZBrTWTUl+M5JzsHEz10PDhTz+Gv4kCx+sNTiRytEwX3RcHp0gWGuiKq+T46paydUOkfo9fyrJFd2IBG5AZfuEblp+T9e3wapazIkMEB/cm3y3Wsxz0bYE/+CT72OQ+PhUK+786ruVTTCWhMgc6N2TiC9k+dYTBGwzcj3mIbzntKu0cLqgI9lpFwa6cjq6ps9eyiR0bdSaHIuhuRYvtLV85LXBl/LaXDnqSOFBHexNW5Ab6bTsY6XmofD0O+EDD8aXzkmxWxUVVMyxxp68l4Ne87gVwHAM6bLy99cyxCs6dO4kbPlKnFUB7vRKj0EKgZIhfdlRQPXJzWyhCCQPB4L03cZI+U9fFwEHFqhBnqqv3Q76xnTv7Q+V8jOscUGlsqKCVZypMqvNBV2gKL7BBin4uAnHgob58QD9KKMH/uHugH0Mtt1xdnuRbB7ibo6GW9fS2wbG2SynUpv51As1/yyXlPIR8MfIKxDpq/bvtLT0Qwvflcpc3c5q0ck5cgPuNzfXT+Gzy7R+FC3L+UwjFUkhGUCEyWHOMarcWaivllg3YZ1cFmDhmzffS94IJaqqceTQyckwucVk+ImwF+si+psmRE2fIK2S2IqoXOMYFE2fQl9Gkbz5UyqLXBavxh4w2JIO++johpOyzziOQ0su6b0=
  template:
    metadata:
      name: grafana-admin
      namespace: default
