---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgAJzMUtMxbzZkUKti2fEACyWSy/kpQv3LDgkgzQX6QelYE5DLoJBOSss3wP3g+CFFYzQmBLx4DWh6yTbjfx5YkCpEQEvrZV1GTpJ3S80vm6OsI6I5PQkBxj1oeV0qj0iG+DWS9bBLBWtX5Gd6E9WI89ANBTF04VJ6fROQEXpo6CWh87oSHoapn7kD66hcpVqwwXHf2Ck/qfYyESLF31OCXrN3rnqgVawyxu1HHGF3LGyqaAXzyDPfWomYk/N3d3W4rCdEUqHIDsDmJNhE3OCJuhi+ZBcCDVbfxGABqXn4g1IQ2PlyZME+6g5Vmxq9Ka4Z0faa4uBwF6sRiim9EFUaHTZNYBSofGJP686mwMPYoPMfVAzsHG7Nq9QEIb/xihobmju0qYyth6KUXKA4YijXy4ABMBDz0WEihrsWBHQwYbLsQj6KWrsOzXqZMUAuM3RZHBT5YC3wn+xXolfs5hip6enMIE3ILWlQtbQ23MOXtZtCvKy6Ilv60MJg5RorXiTSECtB1x/meKEL2I9GtpgevHCBI4Nmgm5HktsnQ7gbJSxm2m3mrPmVtZD68lY6cfRZ53Mlap2W6bxwyAikAXe97BDW/0WRainXkFZUv7R37jPGVDF9R8rOpZ/B5PIFij4bRV+MyXUOM95PvMOsbELO+KMe4pxxaCCi0iBb15WWpIYVpwZHd5VX/XwnIQ/MIHZbwPLcj6dDHKseQVYeO2ROZCqkFZ9iUIrEQHQ44L2PTQM0uWUo6el/I=
    admin-password: AgCBO9kwFFDEkzbq6X+cl75niO2OsgHNYmH2jvl6HTcNQSlGWGEpXTlytv+lCLcFfAI82OSvrgg28lHVQ2ers42L/q6HRPOcigWUyztnSKLJ0VhTP+uZIu8zUT8/TdT2tkAi3O/1vCEnxY9kXr7c92ldmdjuIK8E6WB++7NrD4vRAGubgMBoYk9Mxk/swih96jC3PNUjmRlpGYEz6asopnzOLITTQQlowUE3O6P8w5qvkh2JpAJybIfVyMNXjNI8r+l0lGkxGFVNOLfKTrwaf0xvOv7qZXkzPcHj6vqrPEutJLUSjN9cOViz6385g26C1l+e5ATxgsqMn6bm76CI/TmvG0XNBEJxDFJa3pifRfbjg/+FkfhZmjyrmctkS2xfUvsbSroPU3XB1ABpKKlfzCHsOcReOmd9oEVTTZwmSTndSCz53Vc9egwJ5DIvqoJ3y6tLDzv4hv8BwO8j6kSuPbdkvDrng8cqWx4Bl++52Vkg44CbKAflMAjaLLKn9c5WLcr2boS94uf9lOxUJ1Jf0uvDgOL2hjlqUFTfMSvx6AucyLKdc12OBACcxb9GQhGU5jbJLnTRrA34h8J8Ojmf/zfppDVxYqe/1XRs9Y0g6JFQMfopnoglhUVE3GWVjG4sYNKLbyYzvlmSEBhWVYBN+LvlP0l6YpohXn/r4XnWBdKoIEZ9zM8aR7fNWVYzhate0f7KTH5Jc13N0MBrfPK0hGwqFSoyHzHiPYDGM7181I6A2ETOBbS4ttw=
  template:
    metadata:
      name: grafana-admin
      namespace: default
