---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgABWuvfXq4JJr3ZhR/Q8YqcFtjw5iDnkdeTlVOUiFZtFjT2AMCo5ohLSQhGtmuRLldB3u/Ad6E6tIaeM1hHVkzLEUowHfhU6U9agdOehQI2evDSCXxKmk9rwqzcQh+57iajWN3CifA+Qw+bkKopz3DH8DxdahsSO342hmgetAahnB86leq1ccaIF4+sPexsIWj6dxT/TOKC8GqwF1o9yx6wLdNMtggknHE568dnmJsR9dvyTDYjcsF860DyIPoqAWkDAH0cbL0OHAlfHrxpf7D56bLWP5M1fdz1L+KmSinmcLxoVBIwkhi4/CCGkpTVkUWh2TWMirLHrWJgA4U6QLoad6kaGu+uNvaHv30cp4mfLxECbGrdsAmG0us7hYvYmlIlx7uGqwXj7d2er1sN8cy495srhXh0PiKCnzonVy88+EfBgVPxUs+5bH2k/TT03wUedVYi6pYJLLAZd4MW9P6aVaZpQRqQKqq6X+x0/TZoyIwRR+GpYoUoBUvOu/EFYJfz0Q91bgRi0Wo4iJl84tuA8H9xREEP4Zl54BzLDMYzl7ZCVBfNsaj1hXpnzBXa//MzyQR8fg99vee0RuKOr+M3VO+204c6wS4QetH7nwhlSZBiIM8rYuEJu5gjzp5wfK6Ho2kM5vXIo8XF6FUxWRP5ic0/LAMJ9gOKF+HMVYhzjwnkrXK4MouwPWD9G6pddZqbhrYT+tifAvfBYE9wvdERCLBy7N0ujhBh0//xqgN3KbDdTi8D9Mw=
    admin-password: AgC8CT7v0XZb7HzoehuNmKNB1ISYFZoBSZmjxV/Qo2cJ9oUsihGhfWoYDiKxiMeb6JZW+2W9yLZzBxeKLIXgZg7zmvPGZbxIB9rg5jkOyw3u3/s9B370OOPOuo34rDd1xo/0Vi/+vDVt8zBRkuJZbQrwwdsUhEgLO4qtnGaMkYjmnjtID4I2gNdFFbcIlIZt9fsS0PLTfzMe6jFV2Afx1NKOl2sWYKbKS5lBQG4rmNSRuGuxKID6Fi97b8ekjQ0dOdR1VmsmhP02WjTkKyZtGIH0SFki1UHVuDZ3fYkgdToNvumgnL/MDbFlE4wMnidWulebDNoJi3wrWkg/x2O8Y8yCDx6lqpsrmXhNN0FVXlXL6UShoGXoHjRmZ6ImE+0eaIUBEEZB/1TcEXnJ4bWaj82UDKwWppyuyF/PFSd30RSjulehYOOWKwklEyfc7DVgwv1pu8ajZUD9Kny/Psogt5n3qJDfPUTeWC5KbK7qszQ0KVx6IKmhW1JIJW3YAX9ka1pYl8AQhj5zDoJvgvvy7JDbcB5y58VigyJfrXY7YZ0S7spQK9LF3gL+GI73BOUkgW/7EmnC08bRDwJWXiLZE95bhXtRzz0D2lSXO6zJ+fFWgBaJ6o1KkJc25jxAzQaPgE0iv2Fd4/aiCx0lq8xXRiLx0rC2+bgf23GyNeLZor60eU3PHW22Sl4FWO0Fl8nh7rhJQp0BUaRFgOroxArT6UBJ6E2R793EN85b7Xx3UCH6GPi40t1nuUs=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
