---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgAYkof4vfyWJcsDg9u4rPcnhbnsjbuGXZFjQEuHZ6+ol7UEZoLhMAD8IPwMl94UVBw9qsDoX5ou2jXlsjyqDIV1CdryFDLvfZNDnMCRZ451McsH0PqnC53ZCthgV7hgY98Q0vLTumP5aYsk8YFfRhfvaKPzzjOUJx1629a6wBxv1+Lon98e57BQikadyy+FWF0KLnTTkCV0IwxaaHgJWgSKlFjzhsTbleZ0QyPhW/tAMJYE+btv5oTmn07aHV6MARkXD4ZUBZ8aQp+SHcrvEmiDNM1zbipSsBqaH5S9o2bMt8EFcTcBGIDo39o3hWOw7op07jyue8Z6UntwknDEZyyswTqmeMpvQV0k8fHC56KkN19omQjjm2l4YmLbPL6zNeBD2NJB6EQgbPglRTMWo3Y5+kR3ZLZpj7NZuhV9FO3h5nCjm55ZCkk442tz3AtS598TKyGoqkqjt4D7lKxj+rO1wbmsSaKvKozLOWXhyFIdS8hKeboAaEK1uJFHNc5A2CgNBQooNRHWQfXOnIcWLKmFAyEnxfBpc7RHZMbmKvGvZR0Py+2aLU1Ap9Np6Kxgqx1kB8c/jOP/5vhtAg72qGOCe6bPMqv345FvOB13Exj5kvqk874+S+soZoRutd7ftaPBTrX4Ji9uYWMncCceqPAWEZZyHECKPlSxZA9GtvTurRqk0X+eXVMsPAKWzwQZ8smR3wNOI5ErFVG6fPETPzHpqnQm08tevh+p81xrZaIu6HG/TVi7CUw=
    admin-password: AgCQksfehS1umBfLnv7BRXOE0hq7ifQOqZ/cIM8ZbsWqkgkRkwJATKnIvPBz3W+OFYfZEp+g/YEC0ZBJs7FnZf2f+sd4/oyqkokwvRWtvxqvihMZVR94H9fyXkGJPy0z6l3jvI2ZYZMCvrHNmM5oSSblrm0Wi0ao/nQFxMwzRPpWjeqaG1KNrNbHgerH9UXYlLpL0fcJAOrxCTn+zuYKnDY/7prvcbKwEFrTgOWq/GCZkp1mNF+yiaDmGdVk9Qc6rKV5NTdK/HXjgw9/FMkFdDMs6+2oybPKN90MQZr+bkfRZnHiLSjOEpMslDTQmOH7MAGsFhU9s0ikqG3GXl6UVlfBj+UHvNN78ZRsCiD35Y7UyUfWwES3yj8TS6zUbX9KoiR8LNcFRxIm+Q+61mCZuk+On8EOTGVl9A8cGdBhYE3uBWipIt9XzC7rkzZKRUPRB2yCUIzfdzwGAJriOPtw2ZOky8nQi+RARicKM8HTT5E6C7I21s7hFoetbUMrgYrzPNlBY14ZSTaR4Ykb+sADiT6oewLugkhQD78dDTgOJ1GrAK5ETgBBsoYmg50GeJ11gszxMjiG5v1rnW89S74lFucuUUYnxqtOoWKMz18eWmbvojFK/Zn5mZMJ++LsE0jDh60YCGJEl9geVnRWmhEdXAeRvVXQZGYifVRnaRw541vQ0QZP1jZt3hcJLKOPXDZGrGtJNKVhNTNzU/+4pTgIOhlyhdfu2/fbGYIWv6rTeykNQQzcWCzKkDU=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
