---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgCEw9gzdoHTw2pIZ5x2lQzZwGYIrladb4+VZSmciXWVtoDVh7fsVOhS/HtIljM5KrWfwx8OyzVaWkoiFF5eoDA7N0Uk1LOAmX/LMGyqAtuS61SVWAS9X8uwAz/lsXv0KjKMkQOtEiajje3+819VNKf9L95ydZaHRx2wbetGz+Cal1lE/XeyWLLrAxJwjeMC1JD5ReOGu6979D3oGw2X+xwT888vmg6Np4w40m0ITO0pRR9tVVBTfewjqDmVDvMQNZfsJxIJfIUy+78X0Zkh4mKdMZamD+o5Esfg6SbyfsEDFWBptlFQYZkHpX2HhLLJv1XEnHegsL+zu2Q+SQdDRdbkHQj/nhANPqUODV5seuYyMdsTKtM9Cql1bDMSdwK6Hv6cvgazsTIYHk7GfzrKq3U2eap1IshKdTRxz4jo8sm6JNCAat3but6uJql/RtLXWeHpJ43mIVduf6Y8wpbhgsuBNcBcRuFIfgUfaeRQEQO8wqhesLtzW2wjhuruRNdOkccZb6H+6PH7WgT6o810Mbr7t5TZuM8Myqj+orKwtsPpf0ugyHkc01dD+o3GwbxXSXoKIetDJrDXHGoSTKpjHt4spu2d2br9Urt/sj4eUZ2Z42zQulxA8OaL0Y16konBY2kBxSl1AwWbXtTtBRH1eXqaSl/Sxy3CgpAnGc//5NesGyB+53t45PUC36WcgDEMtFI7LLHgGg07gnGblfqYkUwwmM5604VEnJxYvvfJ/Y6le3E9LHyBHh8=
    admin-password: AgBu+iYgRp0s0xCyPeM4tbDGIkQcLu6pXtGrZ/QzYslmQcyqwTz8javER0VEsV6lGQb6Mxq3unh6p79nLVjlyHHQr+WGMlCSI0cIkX19Tlv8NHS5dCJ+4yoN4uXpp3J5ltSP5rQKl9e1+CGRTSpdYOn+BAnLZKfV0A4im3gNvNHUnCmjS03isEK/+/p41GzgT4MfB0z6WKzomWOkwsBUsk9xQRoB9PaigS6Y4NL65wXHfQiRsiamAqKq+h0r0a/ywCLA3ECnqC0MwxFTWGgyhksD+TWZmEkLf8Fzv4tz+poH8tUgSakajY/qURktAqEaVsyJNo/OsixlxctXbLbpoINdHdZ8GvVVDXjcs61Pyv+qHlg2wcZr0TA0GyLUiVlp9qPZHqYzFjRFaxdURWRmcYwFWuE2cOEvpfP1QWkuuz5lGAfXdoKjRTagdS8apSxDvYEI68SMioTG4Clk37J5UGlCUJEbDKktCfrNruB7SwlJYU7h0VWSI6DgAoCh3uyEJs+QOQiEJvWobMPql8Fsu4JvyKQe47UF000bMIi1Ik2S/nXQfWlK+psd9T1u/tJFQ25UlVNz0ewW9dkNobylp/8Qs0GFVfzq0q5FAmfixRTw/mAUItk7jQU2Z3iKl0hjaDECqEx+YmD0VPSHj3NSMcFw/vO2gNmWRrxAqxdj+/0//yvc9hbGWMZU4DpQ8pvsai5RQYrnvkas1ovymIEE0ip6LHe8HdFZ0acbXihfJgY1wQJ5/udMt9I=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
