---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgBF7G0iVApak4XnXbido111ABg2y2rf57MAuw2R9UcILksYnnhZeeedV+wKQEHKM1LsRRDGrzOClLD0QlmTGZJbZDARO4tPoX9x1rLY+WgBGoGT/D4GKWHWJt5bWoUI8Z4l/UAsOr23rCEUjNVQ9V6jmYw9/sPWidb31elxL9E5Nm+80oeXKa8SHQjrN7m8M5YuOv1WCEROeQok3FlymTMv/RSlDv/e2/ycMGLmHxVkg1CIzcJ7Rafc84YAiQwhLRmhX/jwGMT0TeGZJchrcUH9A9AEgk0cPgJpUqeebtdCrY2XgPCm3TYMGap0yKZddBNR2pdt2k5tIA5SleiZNZQExkDdQgSQdHs2wizdXgVYFod4jc+sGTwaMAMqLf9aQIz/roeq5SmsNqxeFjYqwKtiEpnH5eU1BJx9ReuI76ArpZW7ajE2SzLp97KFger6AwU2Jc2q/fAbF8WDzKpF6n5Tmk0J9scc6LDzzSCMWMLfgU4qPZ3XWb92ei/+k2zPeouQn7xndUSuL043Kb7R3w6iE28SQl9Ct3H7kfaSpir3uLoV5tZUpUhG1B6uG3cpSsrQSl1XAnSpYhWxJlzhGMDbYwWXEmIc7ko8mFXi+L+1noOAuPVbTN+acXhfVGxm5wekQHkSsUtsQ0g1Rn+PtDiQBzoM8N+xawTSnNPja2ibmTmr7lLmARxWn6PxtASq2k1NUHjQ2lU/zhmPoy95wO29cclEiBJb2o5gBwfQXGHvpN97Cd8vE38=
    admin-password: AgCZhr8YfnrwbCCsQfC2/uHpdHW5Kf+HbJaTwibCIs5VMWH1Husl5KzoQ86tKBb7So7db3wzunrADjKvOPm3PHS5eCdUppqXG1MDC1/aMjjf88IjPQC38AguPCtqrqRfcigVM4ZPLpH3RNy1Zw/r1CyFtyLEMGrVMq9fGZagy1nN5uB/hhiEtpriWUHOC9algg4JpJzH3HWQRBYYQyxoQhLFevjS7bZL9zyxx3Nq4MrOjVQtmFeMwwzZ+Rl1vqx84okiIh6Nle2gHpwbfbl/RumQoEe7n2WBTWTJz4QYGum8itxSlXWyHNtHGfDhNLR7CvwmYes2c1XfOflvgOHXhKt+vJxVgZ1YIXKrsxlF5XS8d+Opw7hAfp/wC2pcObu8z5kDWvXseLZ1FXykfEqEEmt6cGa8WJ6L7A5TwQrKBhrqNrVVNUHYX6BzYaltkuiiOw+rmWpOWijWrervPSxSuF2CT7UbU/Adr4tN+TJAc1M4ByHSEh8cLvK6HHXI9RyeJvRa0YKhZtjGC+Jh/rOJUp8QJSqUlNZ73uJ1osKmMpp9qUPsKl1oxkcA6NmNHxanbqaaN6+DN7sTRt6vbgeAdkxeS660cfDtr64oWbfeVa+93JQ7c21jaRsI77025dXKSaxjyLGsl1nLm8N/jLwc7ciRjPCejTZG+5WmSqmC24Uibx1jWMNP9WHdtGgQH5gZ9WwZKepgnxrpsPLkNqdbYgG6+9ZVHNBkTUnnaHka/9n0vlC+oqMM+5g=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
