---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgBd4nx235weJiOPNedAuC4WJk5BJyQ1BNc+J2LEf9jaVbdxmHNR9HpSJ1GKwSm7D1TQUhWRYbVKPxEC4W/gn3aI1qI2MvpUcGFQPwmRkQfXvkystZLRq6d4V7v/EoPyMkgbdvLbglXx3J7MoUoU3Hal6czS8nMYW5ZemUFDGIxDvfyYvbf7v353q/kRifUZPcgevNRD0tCsfv/zEMe7YfQwuTx2tfamFeIGujx4Xr3GxBBS9QlGojsh8zWAAD9/Wj0kLml+zKPxZBQBV53A4OkmxDMZRpFrwpHShA6k/1XqChpxbKG+Kta4jQ2DvEzBimQxFy0YHYEcX4+SLFw8oC29srs72XHwO17CU2W5Ac8xFJsXi2UTms2RkPgk5+gbs7iJA/qByq0pw5wNEfAnbVBEyGza7c7NjaObNLBv7cyjC2aEspAGj1Kp99EO6/rPL1iz6yL6SBm/y6UgngPXicESmotD1wmrvCKoH2UQFf6ORbf3UDdzLSOaS+fNTShuLCfu+vyFICnJAu91RpiUMdj3scpoRWEpUjAbi1QFUUyJ3FQrMuUx5P6zcBg3IXLkxK8+DVaQdchUSLwQJxECVY7EvzUCgqfOj3LJh76Khs8krXMLwAKwO+IorrJx0CNKcYa/WPHhKF/y52/+HeXfwjyYOpNW1QkG6HlqMVd+Df/9ADkRcoGr9DGsIMiluy14Oe4ehM3ejUNNj2WnmyQS/j5Pf2xfNAYZL95rgHvA0yJGMeOuKlxsOZU=
    admin-password: AgAp0/ZA6O0M4tp6KQmf9ShsvbmH3LQX1XX8R8CCfdOCDMe8ijB3XEpO2QpiI/K2iQoauqNnfipejv10BqLDqHCUz4N0DhulQArW+oljwAPDkTCEf1+7BkzpQUVq2cmQNbQuEAUoVpNUMVoHXPTh4SLgm+o7TG6v4QFYgYiXOueVdQXsJjY2GWFdnmO2s25TfG06ldcxpUPh26iaQqzvagp5BHI5q9wD8N9Of1wwqwl72g3choYWPnF1pQ+5sLa05AKO63d5pNd4KQcgNsiiBSStNLD30vqH+My365YRIh/xx/hvxHu+3kwVIJA1xJFRAnFhioiHy3rg/wyeW6ujin2XF02IZxY22XtXO1ayTfWImj3rkuxFiWnVOzPbedGZDreGPlnp5auczZn7llMDnTIabBNMBxStPZQyNjTvwGVzpadYwHVbiRTlskZQbr9YS+8/03EB9C1iGvij5vzxUq0lyu13tTShGhVeKgS33rT03ZukXDgrACl8Z5y/8hkVSAe4PqtA6U5B0hIAbOYXw0O+zbOODdZw4HYd59BhOcGB/Q5ee0Iso7n8lIW8LTDiknhtLfxxHQ9S4yzLJCxC0XnwpQmrahqP7mly8fzW+Z4lFCGZnRO99hn/4UVo9pvUqOd7xC+c++xqw1vCgCxCkkewmDpgysTdVknvm3NVwzCVgyJZuxr59nwxr91WTYFOUSqWiUZ1wEo0qUlLZxSgYaOT9ggsW8xTP1r15qFPG9pURp76aBhCYps=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
