---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgAUYo5+anTb+pW2j0QTR6zWIG5+e2bU1SWUjDNSwf5ZqbNeno4Weim1zP2iMB5vXpJqp2d6MZSlONdRCK72HXwKbtTsT7vJsskfwrUpG/9J5x602OfznnHTnJWXF+rA8Hjsaax220JXUUQzN14ybAMBqQlFkZuNy8nvUAtuxD8xGnFQH6Os7Uhn38gyDF9UuxDJ83th4k2zphyvVG1yVmVqmpWQ/Wr+xJSjMJ8zDlL9Auq6Nx/GY27/sLHImn6fEej/Bqh62EuKb2KXuyl5+A3ltVodLmZpwrgyl31n29iVov6IhMzQbbbMBk5p6xBqZJ/HG1kYFkwtYzvx93gBBOhntjQ0hQqlIBbsVfOnx4pmQf3y7iOO1xw9VuuFWpzhbwZyQ17ToDq6hxGw1orbeoVcEOl0ys3AAT+rVEDtaaJKEsbfg/cSrRLy7kfbLKDQQgXuGFgeMqW80r57iBe6YOnqUl9MH+Z7c25nqQ/Nfp/iwfIgdm1LKurfXopi3SBJafsfVFPfYAUo0xP/rh2qc0+dW8WFz+9eoxjuwhkPTflLS4D2GmH31EYGVvF+fHZkSRuZYY7ltchj5IF30hXDIYqA+BARuRdRo54EJPlDmUPL1PUCY+HwQ+1gVOT0HyFihDCDQbKkxO4aFVTRjOWGW7zUfm0/C3oMvOV/EssCkVl7LzchW1CXCkypIK8lwVcyC6cwHS+PVBrJ4hJkXWteeE8sXXqprg/weIJc/dyy9ev+iQfrVFJ2Scs=
    admin-password: AgADt00wXMu3XcbXka57ZRxGLWNfEv8rskLf+fCC6Uxemhzec3pIWEQZ8/XtXjbF+lrlAd/GApmLy+pJP2BDL2Imrh+NkLBr1UGtPtBcXeVbwumMIneDmz5oInOhENjk5/lT2U3vG3DZMYfwX7IUCqCVifJmWdHQOyK29O5roVZU+Es9bj6AAiilHcH+hdYnQ4y3i/oHlnRtbc6sirqcmNjGK+zg1TBR/2SztTpM15l57SAo3Pfw3E3R/lMgAcZthmybEf7fCZCcdJL76txl8hkGWHxWa1CBwJLpSN9dhNoLqw4oTr3uZ6PSilj87sTW1JA+arGliKZT60oDuOyq1cG2gG1UhWlvmlQhBkvK3aelivFhRgzxDhHAgCLifNSdcfTPnMbtEAlp+r4hMtVdLmyDAX0mdbzf0ZjQy6hEIuC7Zv8pSaDJGwVZreIn30Fjsi2n76Wdj+5tfPdSQ2HhRdUyqbAlEfMofvF/z/+M1+Oge/v5y7AZMeHY7AQd7EgF6pYy+YLKWAMnsEcAWouGvbMtQZ4zVWulIH3CStNMffhgfjYLXmgucsperVyHJJgHhE+CUHD7oI3OYWRLDCKTt+SnXXpyYuA6FsSmNG0d2UGQKpiTz554tCWoWQUBhEyrjkpV11DEKb6YQt+NzIHrKmuCTWBAEKWYdnkIh5z+gWqC8wNbkwCZdbB6qYIZUtx9tnDYSkGBhW2+9/LgScXhc5jaWmR+uRp8CdL1ul95pfHnvezIR0Hq89s=
  template:
    metadata:
      name: grafana-admin
      namespace: default
