---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgBEywzwYTLVARs3gNyuRPRjITJW97wQitj7oK303ys0UqO8oIEBFxSVTA1eApC08I4G1764orQ0XIP7kCFzpmrVA0zCEBQ/t9UF+AB16CQqQw06GNV73P6w55mW7w7jF1H2/8fu5j8l0Q49EsMV4P3HeoDU9a2fCjMPpgZhEDnAKABv71iKBwGmoIpwLy7ZnsHUxeYm1R+vIMwZyTGFo8snAtKhEq07APdxb7H2phbkFRPACURxYTqEgn6nongXa7Hkm0CYdZTxq9YQJoeiZaP8LtJKAt+t5MX0R4UwtTOp5jCzuTVOD4fJ+ZtSE7FzlHOZ498YRVngZceqrii0P+oRbWuyv/Z+H99mV7DQKWhC8ZfCFE93LDugEVJiO/oA2KzeiKQJxMEcuS7ZOVy0V7h1OPBMCj7LhquZ6kkDgiVCcPm5OwRYFLKeTITTsfYeIJvAFTq2hbgqnB/Bj1GxjA+/ZXieDR/Ag+V96wZiefzHdXKqDaEcOSNo3m/VJzZJT1LJCfKDaTtWaEQefNK0ogjwHC2UnXmblqhPguL6+buDPbJLEIpAI9B+542lc9jE+ltYeCHiSdcnyql3bzASYnrfDAHFT3NB5d1qr280S/wGxdS1J6dilsnPfwLvSuxONq7bcV9Uf3fcY4wtyHvSm3/MQjYwGbZNEFLFNVGKHmzijP5JYs1JHKcOdep4mTCJ/ScHCoZy2qiXZ5Rxlj24Bgg0lNa0Qulx3jSZI0crC3e7/1nHgo7XS8o=
    admin-password: AgBcemDGJ4a7KByZ643yAKOe2wHFkinj+hEzhxcOnC7w41sGV1TZDX9D/2L3M7Pe5j5cbOeNRA1D166VlboH7pJKtfLbQSNVKQ7rcArnutFCzt+PwpI/ulNam3hXOBO2KjMRD/QWGrS+Tp6Q5WP2hkwHKPCPxos3Ohh/LUYOi7P0CiQHxyLqiaPP03tJ3rKjrqaP9NygH23CH9SOQfWa4JWsd2V+Nvza0EAMG/NTOOItegquIo6KZE0QEXD0voqLCzB975eL6JBTtybjDutMhF+mrev0pYjDw1imAp7uUQIf+SBdPeIguVTiqmPxcWBH/YbayKhetQOlXi06Hs5WbmiP/oflEvP+DFCHrDiZuuWYjqyu+fU4NkrJ/q7vTmznaUZZtaoKp43t7129a63oUNEhejA7PHzGqI0zIEKMxEWuzNRcKMimK8D/AisaGwraq6Ns6bGCq+hYcttI+/DmXd44//bEtwqOuQSFoUR7L1PQJhWIcsRniXeKiNM09gPEoB4ZsTrfGtCzc4XWEuLACOA8CbxFT0eOT4oWr7vd2ymW+3jv6b+JwMVsOQGqKsQj9VQwYK+qh1s8kxt8O8JVOfYgpyFScvzY1JUI2++oPWWNmfTck1S1pESMEuvo6IwWhM4KCbpPoEF2ZpEVywULKC+HsSxMbihlxKJHPQ6UPVXBViZssbO16mLQizFOlCvmnLD0hKlPxsf+iOoCUNL0EPjYqWnltxHAjMkfIv6e/wLBC4pQDEPn1Gs=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
