---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgCNuGzBbA6eU5FzfZSDOJZd/rejEFx7djY36bSWcikMcZRBP4RzOfSzZGfn62SMLjqUbFdAThauMRCSmJXgvYDS0zv1jPD+IX51uLIfRpI/XxGe7ushDHgR9dZWDE6qMDzZuy3lCBg1SLmn2EDBwzj22MYSN6vig0eTd6ObIIdbjasXVxSkGpPpvBNgw3aga6rcWRn2a0uCtk3jPUB/kV7ZcJTrexfCnefJZdi2g9DntmF9QaowVvx5roWJQp0dX0+eyFBTKFhj+YyKT5NPbc+SJ/9zpVrlPElQqqCxHBEnwCDrIGOlEozjhp9U7Y3FfFpDBkXE0pMkC9gXRuYe90hKFa3tX/IvyZ8poOCuXX76F9KhBuCQtKtr6TIzC+14j/kfnSJjJgXAbJYQnfTJKvz0uTWZ/IBcQvRGj3JLYtsbPtB4lUkAGsLV27UEnn4uEIi1NPk+aRunbBRalWFMiKmCt7gv/Z6DvZTYGtp3nrQC95TwYLSQrwbpSJI0O+kUzwpM6YGIYbUZxOGXjNHztO4/L7aZo3YZDNVZ7ri8APNsRCBLiC6LGttDdViacR4B0ES8uDAjwlMatW6JzfMtPKUkvUuwumLse57eBbRqH5gQrKYDLEfkUIhwxBth5buZflpJpal/xqYXkYLAqbi5B51sxzPNlCxLz88wi7Bz+wkvkhnFpgnPQ1AgbZF1fhNxpupuwDbvehNTW49uECkTC6zmQv3Vo2y3AED6HzrhuQ9ZM0CLO+c0usk=
    admin-password: AgBzjOjCBRzXwBhwY5jnGbwkUHxUh+Sk3moWLAkdwJUhbug3XzzWZLiK2n/8DastCjD7BllAHCGGBYPK1swDQwIrU90etR+t4znl2d7JDVbZ/03bMig25sdv6FVobcpaNmMArkeNRoMAgyxUQD/VNPiI3VbbUFN4UtVW8fy81qyaNM2irNDklBwBgoF5XgMsH/RRezLlIQCJwXpvd4FhoNa8lTLEqoHdRqA38Bk+s6JuJWS1oWvggv3/1isJH8atUk5n5/pCv/dHC1k8v7N2mktFhfUhG8rvXNZT3WEaXcodLNKdevde1+VdhSKxVknKt8RweRwBYSvIxCcLvzOt9egI/HTpuoH4u2D4YNUQJalzNWkjxpYVGFK9F4GTisH3VcThfb8Y6xEq63RQwbfaMMiiA6soFmy9Ota2+5181k4w7it9iNN29mLlmRV7zOptjrtKAxbWlqBQr7jVonXA0y3NokYdJgXyiPPGXHCHlrmsNXIrJJ2gPSLmPuYwdVIAgZq26ZUjB9FnSGeaqj5OHR4ahtffoe9ypZfmbLd0o0Ipwz3BumVFwS78qz+0prWBAiPo87dGgMjl2RRCVcHaSPZiY6JGMVN/1OMbetjRpmZ7HHw40HtM/yaGIJTJ+NwCvRzxh4WOujJ7AE7V1/ppbF4ukzM+2cj6XCXktUecE5u3tDAfyDXGJKHN4pvj8dT4YZ9yccJ1qqgXNMmUcflpCa6yqKCw5M4lddCF+10cjj0+iDvDZvB/CPo=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
