---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgBwXQD9qy7QTW1wJT8/mQ3Xbbvlo4s+taHIga6aIoNRR2zGIsu8mOJckPA6B5pVNMkwCiZVPwAnB0Cp2CNTXZnWQxUksZ+wRKvgW9akU/HRnpS2JAMZMkuiyOvDaiENKdbinA8F4GxhcmOlddQpaYAQQYJP6v/UsCXl1+xxUPJiB/QoAKXOJZeH7aeTdLAbs4YNxo/L7XbPfms1ctvbCWFCTZNNSx00FOmin8U0eIBJsy9QhSPxCbBIe72WVjhz0TYXXBSE1HoJm0yhmAjUJ79rSIf/wT5Oo44GqRpfkMhoNBl3jU7rmR7FDQvErZtBdoh3oyfgplZbXifYKD2R6dcQC/GjlV4E0khoZ0aoowVIzR0msHb+8NgQRhLApQgPzEUzPzBkVRvUmMkXhizIiEOLbs2imFHDhnlMO2INxrqILlpp3BV8qaDNQrRksuVESGIgJw+GGCfn8BTc0kcSQhPnRo/mFDnHAKQmJlkmAQP7xYkjqzF4AaVX691skt5we3k++2RkxdGLtGbDYhhr6pu75dsXO29CsqNuY0smMx3oXZFpcMWvpiQTb936Tln14BXr1qzGB7ytg+grEqLTuaWIEW+cka0/D0Nuy0QkzQmBIsZNrkFF6mEOyUITCcNXOCjSFMPnhSycuVnXjWUCU3+l1Rlu00VXj59m5FGWIXICHS0nCvBiyfpW/jgEM46e3FMpXB3PJwIzCYnjNugLFaiVgM8CAiQAKbfePbJkrxWEoUuGXEoREz5RiQ==
    admin-password: AgAOCmRV2Kka593EzDLbVJmSA/dNWDCmSLnjyasJLfbb1XkLIBGfcAbzXt3iSBXqvNpHQvMePg6Q+AHk4PneAEiJ4cbBKd4BbMxUxkzqI7qIbbCG9fyQA9eWkyE5E+mbQS/3umebgRSRrx+/mxMj3c8aXF55fkBkiD8uvHhA72tSmq23j8KQsfyNdZOHu7rySUc342cBuxyb4cPi7AUH7kHzc50HmnzT/pt6pdBPoOwbSf2FBOl1urdsFv5q3SvjA3rXkLhtx90NqnADE3WqwoKwHLGjEpq4Rravy0uFOWDh5t3Q1tYj6slSS2PA6s9q0UZyxQZ9m/oGX/4TL3KybN9sRI+bOx+9nRnqDtcfjB9O8qLeRaewCmiJp23EXAlVWyqAC04+OfhGs8xJNl7KuMqAkzEHsPJdA5UMnKSdvbKejm1RPLWMV1eIqx4/92+lyJsixQQ1dCoaftxzNs0SecBEtt8tyLMTIFvZsZlleLdSRPjEyLuu/D0eXSylPbITl909DW/+dwXVZRayfAw7oR2eKO35fo9WAqwv0Em3G94VorB3IT3+L6am3rWt1XLC+F0xGXt+iY9hg/nPi6kO3fDlE0td08W5K+6I8a1zfGblt9yqqZ9aTGZ++r6ATVsFZKw4uj5sfixvVA7PAn+qoQBJzejqSFjnKqrVf5rL+NzSYsTqqNqCn5py3H10Fq3MEj1DEmokF0ePb5UODbOwzkfCJqK18ODgWsvApto6fEQUyVHqA8PZtsQPlg==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
