---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgBZdbd5Lk2wEGFTOSJodxnKevxTyXbDCx6FcTN4PJ6jgi4FwQDj9NvRbzHab6uW2/6PC8hDD/EOz1Lpd+oqW+5lYi/dTlpg9TZz9sl2Jzn1HTpBQCPgp41tHf7sw/qkVJ61K9JdSjJF6SdpJnKsKzYeLmsDStJF6zJ0MBS5L07OxQ+ii22bQzcM/hy4910LpAxdYDqiNFYs02a1LG40KyfaTsGhEmiO2/ktIR+DurmqRKZpfi0gCn3UvnQFTkf7rbH0c9PeAAAF8+aBOpdGdVqP5zhvtCJ9+vnCMGE9dAa/DV7bQXdTVaeUmAD2hmV0lUzjH7S/lLxeU+ocjPqYnQahLwqaexT8iScvUjXr4dR8+fjwTrT+3CKMkVLSwJIAblnQDrpoz322pnn2xmNhTVvHlI3P/Lf5P0el0TPlaY3yhxGJWTiYUqubJzURNdG3NKvsgDtxp5FGN5fuopSfcsnq0owujrURKG1/tGF05GbvacTmYTd9jh8jjqXtXRHqD03uqfRnxs65anDI5GThKz0MROTlbOCEhunjjK6J3cY7n3YVvjwtFY8gQDsRiixxVsa1AJuJGunZ+z10whqLzS4X7LDBzhIQcc+nAOmvdKSL1f+ad+IekpijLcEYYAx17ckavzssUqY7Sct4Liz+/g2DPauEJPKFhbzevrEWqQ82Zbi01VE7guZ5TFYDhWwOHyP4IBb0gfLtrX3kJyVH83/BQG6gAmHGGsQa63x4P4Q1HDJfqhsfqnY=
    admin-password: AgBqZpwdgiScfVbHXpQpv2nSxHBLrkt6jiVvSqcbDPTg/h+zKbJAulDzI1YdcDnb3LMnf3gUn3KoXkvkC49NWAqOwunMJDrmyxnrRpwy/ceE9bILYS20VQfmjNJrwOZXqmIsHgOWZ0WTEMNBFYbPvrDngDDNqsKoQSrkB/0Cg6eISz1WRC/i7qUJr38GNLSAOQHJAHKGRKb8QkYbulQM2ufhM1xwxhp6s4sjfTP2dCqXPR7EKha/kNWHAhn6MyONKbw/ksMNSOK6q84X+GJGmtmeonnGDZddzlabXAuoTkz5vt8uFGu+fV0dh4hL2QZByBHRG6pxcct1jljU2PDwmATK/qJDAISm/fQupt05XATMbDWZF/0gxuzTzjtSq/7LLxvy5vWxZQCMzPNChXUyUTYMgdKk6BknA6BtJlBOzU+szNyBNXgGY0DRBEnn3v3KtH+6+umTVVGSlmUC04/htXyUVKPUXPbYBp6nrG+Mmk7kylFq/NUpbOx8xFVRDdhAWA/lAzvqS0RewcRaLHh1B/KNdPH2x2BkVCrlwi5hehiJQjqVh8lehQg5v6afxcyow7lKT9GyKzlOyJMLry0R4fMML+R7u3f0LAJ1BQqTETKrT4Bz0uPiiz4H7X8zv2XDZbuhS3+NNo3KskI3lBbEG1hEABZXxSfGs8ejnuhFRQpXCs48w112qJOqKggy3Q8e1iR7scXAnAj4i+9VdG5ZkIFl3KL1xNmqQrlQMaoPdqlbBLvaAGB9WZI=
  template:
    metadata:
      name: grafana-admin
      namespace: default
