---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgCL5+s/HbuGqCnArOIpQwaM3cPTPnTG04ELrgCbMenks1UVvVR0jyEoqqSvVtjJ399zLojZ+L4+aOAlTMuxcA7qLdcW+sTrztndle5jyhA+/j5UPGph8IiFyMXae8sD8VaQVLlUuvd7tiZJC6f3s8trtqJXxuh34Z1WIfT9LC8zGmaruQ4sBy2rEukKn4Fl3hSw8R8LNjcuTTL2Lkqhhzd2ymS87MvDDOtEdeow67G/ltTOdT0naMIV3eZG4yCskppbd+UYXxTjHOWBAMN7JlZ1NUgLIHip2acRsQEYOtI8vpsaTuUUXeANDK5bIB67h5wc2xaFABfc5+o4mM0l+QkxeRsBcJOPsXUS/YWvanX5WsyvgHhN+r74cpI/HYz+k1j7bCHIbSsEFPz5Uu1MVJIzyYzgF2IBPNX2FQbXmMsHKLcWpQdHdFeXixWFa6ORsOzlw+CV8NjzFdoWuiJyAByROOutCzHqeoK41RpTLmokHV7xwMYL7DOgRPvI+H1ypPK7+qlkw9ttXy7Ax78X8k9NOdo2Q72zTd2EX/RDs440I5U/ZI209LY4hbyLkE2w8YCYEF60bduKdRubKcuiNWhAlQbQNmK5f72vlA/wK1wGLEMwU8FMNAsv9uLWyw90QAuzMLQjNMukqmfeYL8D46XDfr2LhhrL5e2g4Uwi4M3wt0B4mx3oWioH3ivsgVlfcZNjNGN8dKaK4HjSDuSHRMj4FmBa4iZrBiJQHuhJGWhWpgVliOyaJ8U=
    admin-password: AgBIcVcsRj7PhWRVJV7J9gdSkCyUqV2n8E/iyj/WIDrgVnsyl8J0G3la4+d+MVbqr50OOb6mp03l6mLlkeB2e7UEyxlPxzkpOQdNNurnF/Hpe5/c6XScYtzYtz2AiusawAQJgxeH0SYKg+SlW1mHaqpNayNtjZWDTj4WKQ92uCkdCOZy9fJC9YK8tC3l0hymARQY94CHqW7f4ypPfmnIVTjAUy4pEcPiTIymjxTpMb/avtb/FR1YvuI+11PXuvx02hoijNU5mZFpsLjHqD6uVt45QbKxSMfSXkE65kn2S12Ozly5HRzlogo7XWI/rE0n+12zrHDZzYgDPI/7fHeaDbD9LnKxueyVgrhd3e1o3Pez7ewjjcQ0BOb9s9ahkZ+j1DgJyjiHDEF85pn9Jdao9LP+1TDBDu5Kgm6dIz6izqTause259mS1QzCtQY/4LFymahJi5x+xCar3IJeORIBkVdWibG+/qSDXL/03Fe587bmt7OogDLoyHekJfy3fdar/elj28gqYFZKfPDBSRdukEDShEt8bHmuijnlUJrHyezDSMwViIKh3jc3N0JEX+B5N2qq7oLIvCmuSFawthhQ+JKHLp/Q4n76e4Mc7M7CmkHo36iqn2jFE/MWbHoqMZiEbua41DDsLV9XzmKc7chou5Ry8lsN+1RcdKGLdB/h5FumAdSE4QLv0s1Ay0JRKKHbFo2JCqpISZbK7ffPAe/sDtcAix96mrT8PL7JniyojsdzWxbKnWx6P3Q=
  template:
    metadata:
      name: grafana-admin
      namespace: default
