---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgAfRXc5I5RznFTfvgaF/LE0W0ArZRjCLjSHarXh5uiVUH476/7KTXTZuSAhUP6FWNlwO2dR4/vr3MUlVP438egBjaKIiTUEZVPvzDZE0QrWE12fVAofOH+XPgkTBCUFi1rLW6Q20LpcUdUX3znAgGFaiYJrQUdnwFcUt/nybblMuTwTM4O7PNIiJxeLqlrliz4ubd4EvERjIHVEizeaBoLLfOqn7T8ZB/XtgvppBDbSqAIpRHh13uMRp7/rblOh0+tpOZlNwP0q9D5ScQCZI8iOo+VFUK6tikcnIWBZWdvECCuckLaG1NnhpNCmWYECXCIBjk9Eu9LSTjHGLlbSQXhOMz1FcD7u76ld9GrM+h7VklN9wsxbNFypuchXRaWhIbLITwXne7qU7bjoGBad6OvxY6H1t2Xx72ghuGu4POT0OBUC/2Cq+VUoXQjU1fCZtmMJ+R8V7mIEtfJnZ76iUKwZgWiLSOIzVbvwPp8izuCeG0or6OaJjd77kROxEJTH+RNLoc6D7u0AcGFCWVICsBoxQpKjyNL4ts7J3UataX0B4FfL7r2BBPwUoh6ZBUXljrMDdgOZZkgmFLMP9PrxcrwTj8OqBD5Jbp1yWu+KpZhc8vJ0AftjYIr0ZGQmLavt1sQ6npRxDzmn/n4XrBwR68hTweU3IworvSAsyuG03Uo0maDNHvx3Mil12qGsyoao+sgUL+tPRB0l/3aaB6EfEYii7kxrU81zesWQQzR1WqrsCcWqyUBK5tQ=
    admin-password: AgCnOnfC63rZCWGR3a5r31PzmJ1phl0uUrDLH0MjSxj9aPRaUImZXZzWd/8ukHUX+qs28fnL/UwkZfTy4dhr/nTsx6XwmJcFU2OrvvmpAH3Xu59Qk30SUFlByhSpgXmH24aLQ50GcTLr9dmg5Vol8kPqbIXU61qZv6IVatfjSGqO+26s/zEHvzjrLdzbgmbpOCktTaEi2L9PqzS+8rhEKdnQuE8Wv50OwOY5XHal8hVZ1dL1cgPO/fymnD3ezyjK43I5cTsK84Z4w5veGsycjl3xjEuDIhqA9YvabUKiDCrdA8/fg/pZNxDp4eJNy/0I4w7cT3Swev9DA5evFRGcicAPMixEKxTHgP7xG+TazyCNzsgYjdBbvrXqYybpq7wWg5SDEi0Mlwp06XJNdRZPhK6/6Y9LucQ7cPELYshwSkbvZCCNq0Ay4yn1k4y+9BcDub0f8IaoUeoWoXfJMf+eQXeB7qKMSRLBe7xOp1TGt4XKTKcbS3ERMORUQaw4aQjdCTELrkLNItG+PjTwds+vSLB6rVghQxiqqKrgkeHLKGlOu0JTgjEoh1X1fFZ/QikEy4ZFHskM04k+19HaojKTwIKhRtlytbpp3pAs9XfHoPeFJ4tmvrMs13RHz0rvAYGUhelp8NduT1mT/cXdH+GUy8fv0C/bkepLFSK3BzQ46T8iWjjoVvYrIjxjH2T1dEgcPYpj91uLr8LoWEvHI1zHGF7ZT+2T93cbtNniMt7pgvPqYidGzuKZWhE=
  template:
    metadata:
      name: grafana-admin
      namespace: default
