---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgAyLPvhKPgEsRNDvRZL/Vj26m6oZBb2I3R7WN7WALdnOKu2zzuQUuP+pnBiqFao7040xzNMC9VCU9kZ92507+w3U2ALw0iow7Xdu6U23noOo6dxeOoVgZGPEvfsqHU9SGJbDT0YGdclNML3LVD+iplLSJajYXIqSrYYqSFW7XZIKXbQhIYOudxvuxRa5WdB1j8ddsmqgQ+SSdZDjTFd09g4wwyNKRq6EZ0aElOnDpYjyNLL5WzadlTjYu0tkgi8R6c0pMknVrOhewrGv06e0IkrZNZ2iHxaImzmftwcHVL26JaV3OKKDBSRauNB49E8n2JBNtUMMpT6IZOlObgeKKNZRtKuKa3k8bEKIlCj/xlMYH+cngfLB21dc/aIy8/gd3+mJ0/7n01rbQkT5/HD8Var4ii2XWyGI6aVkt9tkM8k77ixWgr8QIy/PHwG1Ktf1UJfa0JgwJy+Jivkp9v7hf+Wy35rp1n96y77YKClZHPYQo6nmhLHpyExd3UFIsmj8Iln8JEWC0aZyI1SLrRHN8ccxN/2AuUKZ44ZbNWlyLUPjDhMnnd0b/hu5zLpYjKYS3lx1mDJiSNSFrtIjTYF9wkpAA54dy9wduKWLwaeIGuavdPqb5d9lrBg4/R2Vx1bbehWMWiLhYh8wCPEqCX6FiWywgP9a+TBaff1q/8U4ON4tOxdzsD4MC5hWwdX5qPlOVlUM2kXxcDa7JCmrJN8INfZK0hIh0oX+jwv6UYuVcclcNgjjZT7HBg=
    admin-password: AgCIiUG9kt3ExfwHqq+tsf4Y0Sbkt7aZ7Ge5KAO/QX2QK1iDWkUDHjqd3I/1DGOLKtH6dyo9/JIQ5tFYS3The4nd4oVJoonAxkzeMPxhExIBY7q8N12fUub11qywRLiWxq8ZPED5EzycaVSEXZFuFptidqMFY8exBrZ54SFWIgBiFudNaX32gPHQmey+zlY45Wt5PN0d79WnC01jGlPv6fWyT7eqoxWOygAo8Iil0Nse3DyL9exbBhu2FMxPNoplllasCM10DOmwmaoC9ZXV704bXQfg0U5JXif0syPx92wt9eMBk9xQnpHH+Sx+lI1uk4L6wTZPm5HTB77gcshAn4AwlNUQqpPYaVBXXuVKuiYWVP5/6Mz7kmUJZ+2ZFe40O12hXRroVwnSC50IkkOlTTL78i+X1ZI5L7YLaOPUQn4F+QkY8TJ3RObXXMga9YJQGte+QZW7aT9KWYCEsNc8BhqaTBosvLCjw1H/cp+kIepRy+14wn9Wva21MbBlPYqAtXLapaih+EWdARY0wd1lZn/maNP1pcJgPCzlQuZUBjD/uwdU/yM+51PBoBIEqb4NhrXuaBIjzdW/8l1LUyEsOAN3hZaPCf3QRy7z5vvmMr/PNchTsWSrlGQ67we3tnOU2yIF6oCP0pDyKA+2Ylu23NktGk5DmnJCwNWqNLJHlYXdG2MOGJoiX9v4ncfW9AhPKhVsqompRDvxe7HybEMSOnHEZFnuldgaMIu1ZWqyaUvsIOFrrc/XYO0=
  template:
    metadata:
      name: grafana-admin
      namespace: default
