---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgCNbXMuEhae5tBemRCbb64zf+8/JjeQ9I6cebBtWMUnLDUvW6irPyISggex3f5wI67GcvMfjojHK6Mg491/4OtKN7fLoHEt1geGpqIlLXZPwrdMhk2OG2hhnT25Pi4e1+OmQRJFQ0FUb+lV65xwFMzhuAGCPAw1OfM1SrnxvkkeQl/h2GpTJYEI20byQKYmptHTNOaj7OSLhlQLzaOPeeLXwRymHE1LMOdq6DpLuVY7QcJkyUuo83Adf45BUWxoRoUHiz2slIvEpsqZLiRKHyyJzq7KhJGvGR6hpEkS7CUqm9BQgpONlpRbuLCwrgz267AHyHxTct/w2ydQDfudVt3dEWr/k5U2Q8Yju+dp0Rl3U5W0BCjvGembWDi6j+GRcdj0lo0vWu2Nv7ooGELkVgIPCqefLIc7TaQv9K+EnZmLaZdFOxkTJzxtr5Oka78okZvvz+LKxwB3J3TPk0Q79tnN6IaTyhddRzY9AAS4e0fA7I4v5L4AqeM+j7e8eimyIVHeIhxlOjkskSVBU1Xy/6fKVec7wBFk3i/Ynj6CXNKYBeKKxNF1DbYdlhdKesFKOhkAlvHZkD+hQauUCAFJjlj/RQ1cOBgAyCov8aHmkUfm592BSpMYTCBceVmOwYFM/80B6NTZFQ6KJS8Zj9fkHsaaIX4hhGgUzlSrScxhEOHAzQt1M67dMbMPtDO+jmQJCpy+4v1tm7y20fDJsI4r995J6xcyYoKzq7KnmJaOyCqy8nmsDLPw0Q0=
    admin-password: AgAp/RBtKn4QOyk/l9Nd1EaVV6r2yP4y57iuodUEZdlV5kBKgAhgHkNaV+1DhqU9y1pTg6VTP1cUBNDUCiBOqWvOPHLFVyiJ4jhwJ6Thz611Ninr04wzgEXBW0dF7aRO7+GpocZg5Vsfeh88g7gxMPDYVgq/IqbispMG9YumG+xTUlBjE/ltYbTMsQam/ODibRJm9WLV8YyToQsobpZVFAJcnN+cCMAQMLqfeYDQDOr/JtMGkFSvAR/R0ZzigVuUa+MH+N3SN57kAlR4tGtKNm7PGFdvFq+Jt4Jv6Fh7BZskwYC40FzlqmqJc5lhiQZYxWEZnu7NhW4S3Gwfcr3oHd9tCy1YFGKWBfpSCSOOkrtMDptq17nMBgabC1rDP831I/CYtxPMuezh1Ur8CrDgRzeg4SKOpnWfnY/frtYn4FNFmuxbnaLwCItLMxGfsPkvR9LN4SbWj2PctPMbLirzJFq5vAy2YR499jWotHRjr3kK/liWrKPwU95i0HFwc/MlXrOGi2Jv1ZERv1D4w2LMo8upFv+z+GbaX6e8x/4Hd5Lr7aL9IWVZGt+QaNqbohAdDwCwYZYsdALAQq0zeZUcybVk/+YvYbuGT9ji+vGZAIFoLCy5OlRLn4pqyFIsMRiUMfz8GZqeH6pnQ5xczQvuwLnw+Gx5aeuJTN8J7y++eK+VIpNDFhCClXt9yNhqGO/T4kPieIvYzHs8upOs2ot3o3v6CDUbi2Nj1L3vvMcpYRVJjBq6tHso+0o=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
