---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgC1Ze4mWqsRmRiQ70hEFqSF1lzJ3uv8KkhGk6hu+0q15svioTWMY/ZIRJbvn+O6XgO7QVwUCh6F1npPeO8J/lYZSkhPhhxMM59krEwO1+oIZmfqiImbjMHYeXIiI2mXYgaWCFSpc08FAdkqgUGgvW9Qwdy7nqO/iACWJ8VsqkEDCmVbp8bjdplrUmejGD7HBVXJJXmN/hwzzSkEbQ3oPtkpLyRv3Nn9c5Pf7qeNGRmHt2ce1CCirKLTdRTGDX+PoVxyyvSjJOfWiyf4FCfCyjFk1/k/sWlrJMRzC3948hlxDXGeeDPylsNsjgh+XcudqK5welRbVhsO9w+Lg/u50RIhTxY2F0GWCKaWmuyYDiNhTdsSYr7y9rUWrCcAwtrItyVDvzOWjseTcxlzKHMUCxg+zMYk+Ba64TD4hwRbnUBqMN92HyZOOHGRRIN51bLjTn2LvLRtbbnqAImlk9R9WgqYGOs8ambJvw0HyiuQPck2MKhrNAPdfokOVKUEDzT2Ci3WbLi2PeH1Ve4wJS6apkR44whT9YNXRT+Sp59OZtPeJpgDBF1M1kjDC3QsHG62cTU5D9+PEIzlFOlCR+DvdIrBVosAdGGiRujrZl7UDlQ5TfPr3pZtVMa++7P/w/F4WaON999yR5pjT03H+FeNqSmaxwUmhB8bUBE1+7AFMiqXfO1pL0ywnLQ0t8/Y45rAkjep0g74cyIxzECZso6SwxzyD0vJfIcn9KV+CMCFh+oF3GnzAvNk/us=
    admin-password: AgB0GkzsUaDEPzUQkFIm0kgvLFLc5iYaFNT7S+LtufavtrHefQWC9tyyPAY5x6ISYNx0ANBjDbY+3MdT5tzzlD23Uut3htHBiHLP3gvmGPmWnHvnKd149APe7ubr26TBH4hZplep7Ydz7laaIUhkivpM+RUcWbv5i9JOkoNVp7g+qL56WepXgFnS1izsbVMYPMJKThcFMqbeMIDnTCQHqFel7lCxQPsf9tMg4iCJ7BiIxlx0gHnkF+Rpyl2BYDrBVkz0vJZkSIfdidGOBKye80DahkGFos/gF9rrArfvstDsqqzJb7u4laEfSRkuNTCc0zJQvFDOQEsZ/C6lTjQiWbb+5VnoxS86VcMKs2kYRPZJ3NCFQkU376oUJWByPtZ5R+Vo9MUlHLFWslQm/aKdCbaH4UkY9MOj2/WXZNHXCd7TbV+YN9uMNSmggqQCCy1lQ/yyhJFMU3GHu+c97rWzTehxRAikFTZXWb2JepLT+zTjS2xipUCdyB1/0yqkwD2No3y7iqPbEh0C6JhfUY9LuOFq9+V1rMl1hOPzLuIUWBRcZ1BnnwafcBEZTH/OD2jov+7QRKsEasJDRR4kxKQkDymMuCMm5vKwQZnudJQVzF5uWeDR++fViXWliPgPzRAdgVBYbXNZjN4ImARclqEAoSJRb1Ko61l0BKCF+fy43bj0BZYCm9OMBvmfxdJ6KO9DYBG8H+G/vzHzthBNshIpcGkLXuFmGfbBgpIG1vvClBR9v2+OD4D1QdM=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
