---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgCKTJa5DDG/Z8D9mTM4DuAetVPtr2IoPdQubCSarGkTzPkAyxIFtWbqFf0Hjk3zJsozOdd6OLYV6AieP1b1QhdG4EOsn2KJebRNtqxA6wX6etYddh1eBHfOI5ND/+2nEUoJtDwTwBRK21TXVZsbuFIOTuQPdP5bQLtJ5mOPG4cHwlwFf2v6E2OtdoucZqJv7a6H4W67jwFQyEKECj8bgD+n8grPR81tG3B3qYoRDiIVkm7fGhX0xG2gPUX//W59eIh+1YBg4gvfDgNeeTMKK2iKNxkVfaCSewgpuWfex5e2LSVqOI+AdkisYeLfKIeTbFt93L245yuhrQfZ/eJNxvfmTrAalMcQEME64H205Ki4WccbflRBERouAzHlG0SXCtkLMNR0nzkqusyln0ax24X2bWVYTtSStiDMM8Ryq/x5kCdRoEs593BBgun4i1RowlBO2oRKbupufCcBHzei0/HmpRAGU62qldR519/7Tqis/ByyVgJPt/CJJlfI/KA51COzL0VvYCrJZ7+wx9lnKaSZ6a0c1sVe0jEeHQdJNGKvOjTjFl2w0tgwIkoZI9z/avJtEcwGlhygolIaYm8y6Qdde89B15CHUOd3Ji1GlVpqFiFKUNEXg0v6Y5Q/nAZiqjRZ3YcDtxA4g8KZjRpRVkhDqQ2K5+0E0Q65UYHxKwa8yGcGCsBMYF5oDEDKUD9AQuOUY/K9VjejiwuzpM5GO2EdV/vUp/spJ0ETRY26OpjZux1mJ7TTDgU=
    admin-password: AgA9yZEJgs8F+qI06HTf63yuiMVLhP+Es0pS6AfQQlt2LaItRrt4Hm0ahE781SS03Hmq65aTa6IEbbAWJg4Nl+W4noe+EWH7THQmrt2zvT0rREQswg3LMDYWBW1MvstvdtnZqt1zqwpnIwr8DaMz2YhFc1zQIODNinKE+KMNc7+A7mtoa+j52wd3oLL2E0Rh/5hpeaptahKm2dwlrfPh0fpTLmP+ZEpGKNuT8cOppSDTEp9yhUYCSwdJU5ursT9peNk5dOuCOl1iXgeRZdpykON+V6Au/XcYDvk1JZJ3d+vPO+E4Id7xZjPdUta5uKnw38lHR/HJHSlO//xb19NRSAOUak01p+AYz9jnES2p2huS90uhS5Y9Wv4T+iy+uPDW466i5i2EAQg6jVXUy8djcpVxSnuuBV3e/2M3K43AIjcRnGSbphs6H/+GHcwayLnhSyqTyV6iN4807wcrxvwh5Be1Ztdp6Z2dHounNUObjRDWsgFaSJ4bYVgc3qBPxD4MbmRbEDiljgy/SUJpkiA5kgmaIJO3fRlJE4wFcbLXP8ZlxxsgPXDhXoyDuEecKZ/wwyFKvutrhfNr5rZfZ9Z9gG3rspYHEqcdKWmnGPE13IlVU18VDA6PEcp7klno44uIqYhXXiYnHjdrm38DljsudXBeKZTKuQE9batfXkQ3FLGG0h5h+SV3PEj3e7jOHSUGwXEKbvhKZ974QSXWbEqcGi52GCul2IUkt/5W8qRn3ruyt9yTZaoEWWQ=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
