---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgAw54hmWooNIxSXYghg/AWOzbNFSspSx1iYBzwJjXfUzmAAE/Cs4PfewqWTqQ15vmn+VcaGJMihTcALLggO2rnrGRx3g2I6TZ/u2cvrASd3ZxiBktsk7qGEIbsACOr4s8ReLVEIH9hfy5cXPYAkI3dA6KzXnh1WjhDFkPRwOJwzY5/XY0crIehvObtCzGMxXEA3yrMnE+484QCMkN4JS7zDlJPV78lAGUAEctY7z3/eDPKYKY5p2K0DnUqqoUq5cKx3XEg5MDFbGifr5fc0xy7I6lttdCCrbTJxldogafm6wOueIKDu/fi8Nj29+e0M0hl9KszfzrtpuG88zXIGRSdBcyPEpfhHVxvoOvFevUNoN9erZEhhKAURHkvvL4+wnGVwQ8YajueKzKWHbrr2VeKj7ztTkbN0Yr8aykr2caVjpWzQ6U1urgoG3nEs227UB+1RrRgU9qbLr7jp+ys03Lp2yG9KmTe7MacJ7NWvYqE12fu7eAEJUnP5rRDMKllb9XGgjB+KYjO0iXe/jQabJuyGVj/VAaw29bSseUnEL51zQE6btBzHVwCCv0dH5ZdNSpUGWy+KqoF6W0fnm4nl7W/fHQV3fqDMDKqGjd1hYDY1JccK7xB33dWP+bjK5WBfo3IMPQV2wKllDdTWR4Rw9eHuLFM1Q/3/FRkhCJE/QOkCOd9Mwh3ry19MYWtQ80zRkr+zS909uWglNJ9Kz2GcfAUl0uNwLq9Fk++s9idg65JEAvglsPi0fXQ=
    admin-password: AgDS3YtOV487Fp4I4v/NIfq75QY5WtHZ2wgwjT6QnEZgBr5qZWt03rvFrI6gfyO8b+WFeGHn1jRIqKty89Mg1hmQrLIxyzEVq7de0gv8ZYvc32bKF3/PK6d3+35YGESig4zkldyvHs6lEULRBWs8TpE2nCh30BoqfZ1t1hm09NVTua3r0QXmgpjUiT+lFF8U2yZJIoIoi7On0u9aKsOeoGXnfa0lnUd4pGFAYEfAFKoDCssucexKKTfzjEwfSGnjnPy/I5zh+tNpSa/DfmWoyqXRjlbXsgBsALKwWYcFMjQcVRb2HRToLG+TGWfacqVFQU3sjFr6Jm158Z60Pac4IpJeNwQusntsOWQBZd9A1BTpdVY1u11OxG0CEJKSKPipatUrIkUGQXcG8JRiNShriyosKTvtUvE/YWl6jIihxZ+6bekuSGgqynZkyyBOUVjoo1QXztsQwkj3zcfVxwauFluMmtZhuF4nkD/g6It78Bl9HxG5fPtYTpqCI1hS+tatacjNPeuF3bFSVxu/LlEX2hdk7EcSsMHErlDRQJsX4PFHJuj7mXwr5pjHLC/8Ub54YSpI22Vtgm6MksY+B3UfqS+K+TCxIj/tdjoLQMEqXkTT7ZvrPO2Yl9bR5/NbrprrnUmyNGId3iQhlufr1Hbwedax2GbTYvdziNUpSx4DD2axnritduorI+hAG/R8K3/GKNWpyjomSloRuXEj/hrqH0hXuDK9Q/IrtUV3Uay7Uai76B37coAnh7k=
  template:
    metadata:
      name: grafana-admin
      namespace: default
