---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgAcT6vYmUTkdSWrdMpX62ZaHIkTFe7vKGzO6Ooxs7bZZuQ+PZgpCVxqL0i5EfmemLB0kx+7EOMBF/yRjAVlrLvzrXODwcax1dOVvU0qmZUsz37Wx43j37uFwy4jt6efsloNrI7r7q77RItioNSwcUOpFsnQbJCItx056JLsIQuQKB+ncLr/lvb9/20grfC45y2tVuYowu2vwHbKj7kwDmyzs2i96YFxxDfbyiiJ3DcnEQeYUXhl7TvIB76Q4M+FzhqPppE5CPt7xadduKMFU+e8mw7l4gJTbkUM5mQoUEVl2RvjD+xLC6nQiU59VpVA9ByEGmEwvbzJyMfGS6KFfO1eXlXZsWR8UtTcWUbQXLKKjLego/vQyvwyhD/+61NT8aGS2QXIeVTz1pGSRQYKMP8wCenbnUIPwf5wn/e5RBgVZpxyFv/fjWPx34TJk7LIPk7mgoAtwH6ZJZzWQyvbPp5z+RmcP8NUXMVP3Yd3/3ENYTGvFrLSfF9QLmDMGU7v6KXrdp4gnN+Tdq9ZSUzCgJA5UDHoR6PhAwFVoQblJo875iOVpx1eKQKs3Tg4YQN65XzTCjzlwTP080r8bxS4uADvEQMrThUIgZYciGZI2wNri8xoP9BHDR1sHVZqaY0lIffMU1nxTsw0opkyVsAhC2F8KMmgVGv2Pf8x58+0XBOF46Ta512lkCnB4QEhTRGpWN/Hg4kFJlT09QhSw10nkpYt1Afn9UdbaYQwafUmuiLYcUI2szU0uj0=
    admin-password: AgBfGQykWgzRRb3dM96ansTbjKEn1Q53vrLeflCCRDuboHWlARJAVKXqeHdeXfSY5513TP3me0p+OQVcjpFk7XGlePSTpDxGxeVKao7hPtW+dpMMgXWbcAv4X6xKPZ2zTRdKa1QYj6rY5x2Gyz/8T2O02UIRpBuIXpmoYxlaqSpKrPbyf2LqMnANLpvN0RN9lduSSUdiLimWxPmzpjKAsgnYbyQgUs82q1FqQVKqqWGFinPG4dey0h+cw6g6QMpPOc43dUHsZls//SviCegnesnPuN4CiZ6/6A86MLSgHM+GYmZcafMyKT9gD2oOn7sxte5Nqz+W0V+w4kUgNDCzOSZpYe570CMRlXBe5+u73LmN/G+WltKccM+eGULhFdUMEXmIdcRcRwrQxLmOtoQmTpujpq3dN8Yl2uVJ0FOpsglMMJ0z5q0k6texIMFdcmKjpkM9br4YlPfGA+jj0uMbgKj293uidSqPsvFO/XlSAF+b91gC6zwiamUFOL5msuRHGibGhYgj8Fa6EfDeXyEnaxN0mAll87Q2T9XGsqaDI1PpnT0NS2d5Q3jWSoUIHvRfGQ/diyDbB4s9ZFECT/LoijfPZhP7zMGv6Yr7HkjtuSm/bVqNpcS33K8hxYLbxL/SrWV4SmrWpS8KEMA5XQZPAc+Cp4Svtvh+m5f5KosqKEQpbrCiBn2e9gBZcxN0ZYSSH2aBpScjPPV5Wn//l8r11BonV9umGC1sh7KOvRfWZZD1ykZh5irGnws=
  template:
    metadata:
      name: grafana-admin
      namespace: default
