---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgAoNKGAeBxrEbzyclgkwMD7JhV/q8+nuIZ5SjO8SjjthNSgRpCzhDpmaILGPtAPfIUTJcKgKRlCyLakb15SMUvJIGp+Jbog+JwPAOqh4D/lrRuTlO9AVAaWSl3cQnydGAhqhvTBGir7Whf972lp+CDce4Hebs4h1dxQ1l0p5LiSYiJnwX1zjWjvYlK/3ks3knpn19M0MGshJeRqosTx490/GEAOyjzZChUdTObQ6ycMOIEQvNFaa1P7ggm4hkYgxkiNb6ZJvPT5PzOednkJWzzPBnhQm2ZcJloOG5mLjY6oJwHc0OnelesYmihQB8fU/iH+osIk4pEDlxand/Ey7U8maWtJkqfQCDtd4wKuFR6JSBt4TXRbfF5TE41KC2kCWrmAjaoiuSpKRqTeMTrXQP2i/MvqLEtYwGyT8aZytuFrzWNsgsA1f9H1RfloZKY8g/h4L1UD8b1gbvHpq2/UZVmTI/g+PwJdriprmP858lTNT9OxrcirCc0ZooOcoc8v2E0p4Ys5JkknHsY7KnlYRW+iD62+1bUProiS9ItvNFksQlJdfGlF07jpLNC3jjvcdrN/+jGndqT+7JfO2TSG5+I6y4NOCHubqh8JgyH2h/sepVNOXHvTgios7D72ylqWfIgsgPP55vKI4WQtUmoQr0hhqNdDdE4ekureDGGF4N3BqcjwAyEZ6exEyjfm4pQP2G9QjesusRAYE6iVqFnNVeQNtLdlBq7dLh6wWHg4N+Y4GPaR66GrCPQ=
    admin-password: AgA6WOOWA4FFFmjkd42BQpKizt7IlPkX47F/osRCDGYZc9wR5AvGf0slSYj1x1f+uEzEgCKdascY+/KbKk4jwNT3NLEmgSYTQi2s0F9tkZlOjHygEiZRyhdDwLjmw26ji9rixmwpMzkIXMjnSlYq/3xzRy31Lkr0m6B0E4riUoioVPO/auD9yaRBqI+omg+VNrzF4/WyH8DNRRaGtP3XI156vx1sqW3q4kNW6GynD03ogoc9e6YkpVBCjBIrx09Vtp/zu/RfV+1WZEyP8I5Na7HG/ZVZsEfjk/uC8GvoXpVq8eUo279OHh5BsJcMtbcPBnKBtS4TAGjGHTKktLSl8UbuNv5AqW4HjoWWn5GNINdXeR8xV+e55n2vu7Iao5Hm/6nphZiZ5jhsP372clsTYIiMWN3qVvClnHv7NIr0FjIuBaaEEV7euZlP6fVJNZ4bSWUPig6LAWzCBqWtZqaSf/KlZBOqaS3qB9ffCpNv39LjpcvsRRqy7exKfEa266jxaSJ3YZ163DKYIMsZV6D/Xoy3+nCeAKmBfriBi8F32WbfXLIn/h/+u74ECr9Ya6HNU3ta903eWEtW3cALd58eCPQgoynjqli17AsxVMxCh2hy9w9s2w9Xx5Tl2wsw/9/GeEQFMkBkm4k0Qlr7T5LSudmOWlPOL8HjIQC2yMORxGn5WAMYDAu2w4kSWD93luOHLDYdjzc4EbIoUkdX4tVnFNn20hcrAuf1WK4JN2D0SAQ95eawWmNQr3M=
  template:
    metadata:
      name: grafana-admin
      namespace: default
