---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgB+TkI4c4Tp1VisXiW2zs6a9fsfrljQLd24jyfHhzHQkWAcRRo5G/nVCYRhfwhz4hOvCW3UMwtTI9MAwD4Y2V3v8218gz/SXEEvUChB6tofBowV7I2fplxpzw0K/4muCbdmWXFNelSHdepNrDVsBzDT4+S05HwfsSkkmIrZdRvra/x01X3KmZPReuShDo1BMTZIv0lpjgo6C2qGw9a97cbCedyYeFs4W4DzE6LIFvTcZJ1xGtKgy8p5MxXlc8hfn/qxZZbg4AXCwT/DqdfPdOf03nPbf0O1QqPUKAjAyBOfJslRJn/ZjPhGKxy3gd3GTIAfggQI00AlGvT0Hh6/7WqsGUn+4TkEiOawQeeLhdnuGcFMLCq+NKTa7Ow0/WwYVgQ79CpWBWsvlY7naQdBKYZSDF8cd3zrsu/Q4wgL5OR0Dzc2jxRfKwCgAiau7kyJ9lvObM8MOk2BHswFz+i4h8mQ4PIV2q8PGzVBrhhvhWZVqsaiFWifA5iwSjrBT92BD51hq4Sj6cEGF+Mz3bSrf8dTYzL27Ke8QDoL6AvLyYZ2vzb4jjr69JBS5jA7KdKbF/+3bPe5PI2bRmBCMSNEw5nBDpNV157vGde/KyRQzg4L6u59aqKaF7xzn4hU3WbqmDC215JKh8qzIGV6vgv42Qvv28iY31ne+L+t22f9N2rClwgC9Mn+KUz8IFC1WCvQ73wt7eQpLJ3otb854RLnS6DlgX1+9u/swV8qjjsGsZQuMUtIqrispu4=
    admin-password: AgCK3u5xEO0kH2ilZUC3jD0Uluqzn8BluZwRSovWbUY1T0xHS4bd/8b7JOaRIuGQGwPtidd+UG4MfnWks2mxhGkY7CqyQaIL1JP88h/zR4djMU9Vh1gHhCQ7DW6UjY5Hsa8NJAlBer2xTLmE7JvRXDxh+l/ZHv/C7bhwb4gLw6sbtyyR5/tueMRlf34XD00bcC0SzlHfJDMn4r0KOluQTvZYUpV4QqI5fxbLjucGzTCQLrkpvNMLRKXPX2tU5eAJcdmknuEsw2frYZ6nyOpUGMnXy1TxxfIDxfCG2Nc2GxlkTJKen0/LXVd5QffpjiSfkL4UjivjVb6oXn+vXho4/rZm2fXfjut8wGoIXSQVQMlEhtbLNDAOEDbcZRDT4Udt8r1Ju5l7wB+jlKkdOe0ekeexba0qeP+oSTsrybXE0rOarg5vsL5r5kNVYFPNLc7wXOX4gq0PQl1F64zfUC/6gC+H8Pv4w2HrksS4gWVy332nfETOcGYqtmLCV11I+Q4zBN0HSzvdiTRlNCktr5iscz4bkAmoVODMnmohjoRme/+E6L9Tuu+BvhkQf3ENkWH2OnL2fP9gVnyGGs6CCS0TtnUyTgoC2QrHx7a8PpKh7h6G9m3Jv3p+DJ9g4UOFpvt0u4x9uFZzQO7StKeA0sdMLDs5M3bPUa9M31yobJ5famICJ2pqFNpEoo5xJX8QB0HNimTWXX75j5nwNIu8quLeNNNeEh9bGOsWdfK+cKw9kQmaQ5iCnVMK9BU=
  template:
    metadata:
      name: grafana-admin
      namespace: default
