---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgAN8eebD7EhbK83O3M0ldUxDZ0umMjoE+SYIEffQEDJGalXmfaOHo55XuLJVutLcN8OxAFr4ubE2M5szWy8Pcpy+RKISSR3gleLMUuNoVV6RbOg36SLWy+u1K9uYTUE6ml1nQhTooITkTM9wYlBiBh+0651zBax93e6vSFfRtY4SKkShKdRy42NfG3igsnn1utocBDXENkYKhiHUVbdwIftCyIft/SJk4P/5qLBAb3F5XVyGaB8w7SYwZvjEPUNX+z9SxnTSkE7QcsvZmugnziCQTIwC2fJfOTHOiVvT5nIdKXuWxrxVzM0ukJatcXFTMpguRUv9tbthP7okq3gKdHZYpcA53cxgu6CG3j2lQYK5l4VxJn38z+c/O1RCNQYfQOjWOR0z7GvG7w+anUuwp0ggQpPT5BPeuMnUkSZt90h2BvWfr9mFjoXJ76G5jAyXN9dZL5Dqo8nlej9gSpViSd50Q0pvJOlhxp+OzXyIW2wnVeKXg+RBw8NfYJLDHLAaMpKmoI/sqtROi20vjx0f1GasRhViJQtepH5AMgBG1NU9TnFxwJ2R/kqd/WOiEKSZn+ITEJ74oMN+pdyAE8tn9wQBDKdcmabLHlmryRayZxE77Fknuyit/UHT0PB9yJYMm4eijXtXQyFL8dyqJCdSSHCNl1+2UBF69pSg+LeSaVtwRF1QzWQlKIAYizjGPmqI49uCg69ghvOMcjitGFWPCL8+GPU1wmXMdlJrpeK7nnfFWahbTnaZQ4=
    admin-password: AgAUtkHOVMw7cQdeXrDIvsoN0P+u/SidDGtS71bXqOJJSaDab85rlqZh/1Xz3eIxPAwAn74CSJVED6SAyVUiDUIN+5qvShgLqjvwCQl5djApFhQ2rX4TSHRZcSBTQsgV21je6sv5YinVnjc/CJHbSKgK3WkH0olkti5ig70bVdg7tG6KDeTPy5ZkrwfPWEElS80t1vtuO7TSGcVgNznmFa9zX7Bu5Suo5+MT04M5Q+uv8/KkpeG/sQDl7/wZff9CCXGk32XaYx0hncTSHtNwrad4MsqHuielmE5rQXghjw4FYP33Cydm8YPKhIuhMvEjZoK2Ld+TyEChfV7ovu8I2JfGiw9IgaKy7bEyoCOj9/jd1KAq9/PkkJWzUfPgqpLPKf0dJ4DcRhmZz6o97/S0b8q5F8fTfGkwvm3ShaDPY0D2MNSkIEHfKdgpgCK+JeIDpAR/r7aZJWKgI07Tp2l6ZyqmEz3FyKVlehxDTajhqF8hGQH+rYU1Lsyc8NGou/kte8r0DuyerMsgGYSTlNM4hHNJDl3UgmWAxv0QmaM5viJ2ZStxEqLRPkPK0DopDmgY5OR06Ew6bFHOJygkUtCgxUIDBjov0zLrwxp87st0wUCoA3WMFga/U4JOp3OagazLuq6wz+vwqu6V1+Dvj0zksRxCFQxsyyq3JAc55SkWEXINJ+VGrF/ORbmGB0zdZOYnlfZnheNG8tPiAHJlhkxTvCQmEgw7ufQuF2GdCX/D0aRox+A6wk+DA2M=
  template:
    metadata:
      name: grafana-admin
      namespace: default
