---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgBUOLr9hcP/rq03vhVar8BfahYcB7Od43u5k0VUJw3WZCiGMpE7FC32ARnXcBMr6ii1tHYRZsJ/KFhGsrrAdcAEXTX5HhdhCH1c2GzyZ43mXdpt5btc57HPXxn+w8UwHAi/HY2Fn9w+fYlTv6vyUV5f0n7Bm0CeI07LeHdmOMl8av2W58p3wkATO65xXu6N3AosHVKmFn9CYLIKq59Swz1f8DV+T6I/9aguWHLX2uCamfd82Ju7ILFLFj9CYl96H78zcAeLBIecYyWIAs+hrlHuK7RMsYqc/lzrZSu8xvhmjKCGlnSVUCycSHYK7ddKVRHoC4UW4ruQJDw2mpRAig81feO+mkvm67IxyMJOnht/wcB2oVjWlTV3Sz6hPqyelBXAgXRR23sblKltkRgN40V8q3MZM7p200njIFvHo7ScwsmRsN5FCtt8p0OvjQEC7flRNNUWMJ+66b7zs+VJaxe22D63H+lkYtKZU03mSxTkVcP5K3s2IuPhfRYJxT1K/+tLApIDkNqLNFCdNvCDQa01I8N+vwlfCJPd5r5JCPTeHAhf+hZx19UqscgrDXLZ67rWqyiYK/crhD6Ykf0mShQAMDRQEiC74IgRhK075qKX65XxKk2w8fqym8CsN8CVlpxIqQ4SEfeSrgZT4kBz3sxba14SJngpFR2QXSJQlNaKPvuEjPAuqxlpF7fxbLZIXRhzp5o+qD+Dc4kJbCtD5biuKim34gbxYkvuRlj4JldwkLogXGGAw9U=
    admin-password: AgC4mj23DFDhbrukdQW0ZlUJ0sN1TJcigWs7ia5VH+Yk8P3cvUorE4TMrjs3zf8sYkvXBCx50lir0XvgFhn0mhfHzWQTeh4pwESBZM5z6hczcj/ZxOJSNkCOrZE01MNRaZz/TZvrK1YYl9fp7ztpEDoN2Zsppo5aUicJofj7upG0E7YBvYMliIszsVuKYp6Po5ZlpLvYeBRsh+yxUq70tFC7KO5AocuhqkJQtgvcMaXzyjaPoFMghBju6Ky9wr2Zz93mVlSCcSVXTHMz2bAp8kJbsbz72hGDjPbXWejEuMj4qOFVLLcKoYXwL2oq/0tfQcwHtbiIvouNC8aJiOl5ybrcJhmyr5DBc9/SB3qMIqOVmDlAtj5pvxblyImeYVjImupCfXMEDnqt3NE5qbe2/cJRO0q+T0wrW/1IjN6Gc4tTWMuBOc7fxEiJ6+ru83i3vyhaiaL44WN9sFfRAobAQyG5irgvLKqq2Kuv7AUmxeQAdc/fqg50UlLkwyZL3zU2qbsVe1/OGPg/7SToOxBTblgv2cW3IGLiT0djSIbbf5jwAHXfHo2l4kl3ezFmutz3K2ygHqUden4ekMaU0PawSAStGT4Sjmgki7wXDHG5JitOMcQFEI9osLHGPwfC+eJ3iNAWDRp7LyM+PPT1N+2dd588G1lM7+ACbrK5D9uLbz8Y7MxrOi1tk00opffndlG+sI8a4rOXW0WNsZoHeZC0k7VM6Fsuir4kd/UWevcTkGRddq6C5nJApeY=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
