---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgB3LpqJdCYqDD74pRTQFqZV6GkG+69iyExUuLEzBePwlwCqWdi2Wysi/Bmqv47Bs5+TLwo5CCZh+yMlT1Mlz175KwWOcOHR82A3WQXWjrYq0nhJMyPrzAH39p+vrHdX+zsUujvCQbqPYDwnmZXyPuPkuxnmsY2gvfLa8PQVssY4huUQZEOwQC3yVnz/3BzgMInZVFm5gMj/wTfjGFw4fnz69LvCIhRiKPrgycCkW+iq3v9GdkbzyMYHiT+mqztWc22reUyMNfC+QAQu5gutdRL//ms6s++4NcdeeTZHhk/KwywfBBOjzmPeTn/0/ijR5WRvnpYYeK0CyImsJFfVOY/8xpPNzFKIiYIvAPfJptqYgX3jIv6wDHwWSjkVkTtSo6s0UdHtHnG9Y0db/320GE7rKTrGVONEv+sQ20FV9JEJe9StpjMdvA6pBZ8Pf0QiQk0KnOy4AFLvLKrErtbNYrUGeFxGcXUxXZ79aYi+ZoMMX9jC/HMUR9R7h849f7Yk3opdQErB67qSaA2X/PU7kal0hg5SGx7c5S3wkfhcvcRxyQk0X9ILJbpjBTEicu9whEszzaVcKjBG5qGSS4w5YynAhjoxDLZgsAq7TO2LIWjDlZaV8Ym+W39BfUBvK3FB6g1jsXsW4g43y68F2GBWEXJ1jFdAGCfUzTliX+onf0bdyEn3sRV2kx5pZsHGEntM7sjsG+DtVWiSYF7kAaKxfsJ3xQFgIpx1rw97UT+ZDPnbA2pI4SlKYmo=
    admin-password: AgCVC15D3xlBLb9ZMcqQu2lzpQyQOuA4GgKpcjgHCWcQdsx/Dv0203YAjoQk+fXg7hEQKp/hPNM56t6ZkjKqwu3KSdB+RTZE/hRVXwXi12F2mqp1VBNv1PaE3mS8C7QJZ8EiOgzp2FV+tTgaVWMb70Ia1ygdFpzJ/reVgGMM8mdaa7oW1WrGUnPFWzuG8WASMhl2bN6bx9TM0j1Vkd4wAM35S6S5A5TjgwcIb9CPuA5l+0rW38a2iwEEtcKxSU4cuMjLBv28VJ498pl9w5Px7aGuJ2AuzEEE2doYUxyoYZd+Sja9uV3UMwe9YRlcJNJuGzudPlGjN8Guc1+pDfVbhKz89zk9V+T+jRRfSeZyfq5zrx4o2KKuMu2KIctJMXvu799HTBgrh4c5DmU5sAXGYM/7UQvDZxGG9IJvbEHM5LZaFtpAQ/HOqHXTu7FLCsHYsEZ+AhoH29l62koDutDyAA+OaRQMgyE/j4VXegg0vXnOnd2GjBIBFwtyjAq6iv+QRIx2tfSMjrBwIVfyI0T2c/EoRfD6Frg8R1EqnDCjmy4VIy1rc1VLkJf0WUlLTPeMgEYUTmMMiiikJk2XJxhrai7s7VV4JLCFTxhQ+F7RQVnUpFgPpfhWVHArhAsYrserlKo1qyH1QIbbCG2NUq5fvBRtuYXrDD/HKp9/WGfpQmqUORCEYj4yFA/zSvDPYd7DPL48Eq0VJVvYk7bGwnSfnPIjKkyiagE6SOD+oSucs1fVEHJ/GNQoBSg=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
