---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgASB26D2kcrvzA5ekqkBjVpdi8024HYhQf0ik4IKthYlw24HFR34NqFPzs0qyUKuB9NGXyFUeqU6QLeJnEjqwZDU9xEcgRp0/XSAgUlGN9LBzk7yUaqTyjQiRoCYtLbjLA13cHGiYc+28otqWbgPPz0P5jGN4r0xPv7LvsQWW2KYVAdXbnfjV0OrGqVQ4sUjK3MBa0QHavai2haz1KW7rDunN35R8czu1Y5Y5AX0VLRon0pD2B0Ipm47RUI4lGh6AHup9sThVE1zTYx9C8rcuJjeUIEcY0KTjEAyDwTilW3zTBM4PmnYUxNZDsCgofPP+m8jWwWOvk3T3EfbM6USFOX6SAfXpNI0EpIfGCaTqyypAoVV7lYKFEign3c8NRt/QtzhO7dmi3pyY4SXPqGyTM9kXml0Ih4wu025dxzpEK68PbMQ6mSgqsBFGTRINYaBJ1mOJayPPvC4vKNThlirfmD20pI1EOHIlnY/ZWfdmZddh52rSSlVqdLSYnfriSlMui6ImlJjCRm2z260Di6wXMVrbtbJy/bed8ilhTAkYnrEnYrFHCBOkkfs9WFSqES+rV4fR4levaOCK3lqx1f1jaBwdDVGHXlWc9BHkUNvLwy6Lw4eP4SpBQI6IUD7HpIDNVDC9WR3pC5B0TyQuvOhM0bikUnSQ+ADumqf9AIXsr8A28CARhY1avrOnh4druN385EE84tvTthKHRVenANiHXG5nqEy9qzO9nvco5Vi/2Ez4g5T5ICsVk=
    admin-password: AgCEq2FRvVblJcGuGBVaUHPI9IQ5fjly5mTzdw89sI7gL60Ezuzz6f9/KK5rad1ZRoVUDOOqRHy5sBA2rhEGP3fItQ0kHjqqFWc+7j7+8QQYJRi842fVkoQMaVxUO+DzmEvXV4JQEsVmjO+4rJhFeBS3jS8B7oeAJot0wu+qHMnaN/+XLgMJkl4bs3bOuM88ygqb1wwcx/+O5tgb5MlirzON3wX4f3wI3vEQpBg0/AJMjICtlGP/9l2+gXqXKx4lDjhahWIOZfWUniXiQm5y/GtDJTYNO330F0kPyqnZVZSdYvRuhV3/OcuOhixF6HAbN1oweCYgoduI+0qjpO33a1HjL9seY3rhfzvVmaHJkrX7p1f0qaSrhrK10cjvmZuSQClX2jC8GVmGX3D7E4m3Hzysqz+iD8uz4EA8+zPkEkAUO+LfrBDfa+sQTh5K22wsLZZ7SFlhbpJepCLxyZzVumRgA5e+BOqPCGBC+ZMhu/jozrVDi/8EDwuv1kVTRD5p25cNpaqKRc4R+1M9oVL2SRW/odh5oba75uQYcUIvBc4n/mF/mA5SW4lrmS3vZHHWMQOP9RSI8sesMkT+k6jB5s704UoYUUXWMVq9kiWmIN0bWzT/QK9d3iB/7dJoYNPIICNtmClMq+rUgFAu/DKDewnoyIF8QcArcsV7BafJ61vbmIvouweAOrF5OOD2pgw4FV9DWIQVB0KoX84WvYaOa3VEFIPWIjpCQvVjBqI56nJeZbt6ip2X39o=
  template:
    metadata:
      name: grafana-admin
      namespace: default
