---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgAOTswlPAobQ0Hns43jdS+eq8aKeyqu6d0Aaadxv3dik1EBI4NvnFAUrchEmde/sI8mius97SK19ygMWUSWFwbY9DCvx7mIJcXphFzzKUpvwFub9uTPZGdmjtZMYWYKGftj4KBXQZsMvTYAeEWqYtC3pPGzoTfir4SpS2yA9nkLx8m7uOWBwGJP732cN5e7ngqxaOm1NEUMFEQZqRbl8pffkRftdhdwxMEtmjvwaPOvCUVsOj345no6v+CHfgVNTWdjcw0uyxO04ZK/hlyXzUeC7D4OTAZ1IQMV3c8vvsp/KIJVDz27SMoCWcdj8riwVP3+F/pdExUELCJjzDQ6bpmgUAghyK1IQePYAIxt9j2/gmBpwxGpvI3H/uJM232zYewlSDMid3DwrtmM20S+nxAWbeg8EQRuIqbT2BEKVfwjC/9hil/1hdIiB2WOM5b7wAl4U1vife5+Y9fc5Er2/6Pd27orsRIJXpT+MXbr5wcGLyYux/Qs7HSfCZJCaDyo4+OWv71m1brctmqIWz4L+uEaZQALajcUAfl8QkDjLl3cbegek4EZ7dhicsd6leohLuFzDd/taer0c0EH4bBGSMCpKFQ1VKyZv4GS60QEVY2AcmKY9DPVHgBkIoyz2BwdX1s7uufXWHQiTBvnGqRtyojGPx6YsH5YkTH3u7gkbbTqbR9Ftd6phIjLZgAWWmLYkAlp+yg63sFg45EbBnaE3tnAFe+EP9mktHuvghQw37ixYwz0zHwtEWU=
    admin-password: AgCmb27AS4v8lwjVV8wiJYA19W0T6pZB9CSudF94mAEw3q41F6ORf7gzQ7epywroPsw1T7Ky5opSWQvQPx4mYzpqqpg8O/uYaLmjISVJL8ExX+11Iuwxg0D+MTFPysmxnKZ6j5tBnsi2A/yfpidur7FCc88g8EfDxD/trwkrcu0HQ1osWUW4eBSWWdvWM7UZ+8F66qp77dVoB0kY5T/T5J5MawYrs424lpX4w11/1LoXNesw6MqvLYVTx8IFSx1gNLorLp6N42q5FTXVBadg3sN6b47EkEhskCkmG5AHTLC5QlG8MyZGa+muzVmVvCVS5cU50yUxdAhCO3orm3xMoyb6CpbvjDWNIBZGAPXWk9a0w3EnkQJgyLM+6NuzEMW5Lrh+rtzgNL3Eyrt0YtPSmVahkjgkFZEZXF5rz/GkIHnRPgdxE8nrG7LjcCZNHOW3pjEoL5tdIsDGliRV1EVo1JNUYZ69Tp37GARzzXR5mKv7S/rCdl3hf5UKZj/P/TH09Bo+KjwQkxT0y3jhaDPDk1Vq0W2bHuPno6yM4E7WW2brAfIAuoShoZ8El2RNSwdCD+k5PmROMWsr2IjZtd1fJN2OLwGBzI8+ZtsMETMFbXFkubpGCo3CPy6uudmX1QtnV7jjUfV2DiZfexL3BKJ5VjAjTFLFGMhiOQpGx0iHUgGFaaclzDYMUvJtnW6v2L315OxDWsITKqZCSY8G8jjVJcwSj7/8FYKppSx8/KhsSZl03CGuo29kJWI=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
