---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgA45mZSocC7NiZj6+BvsxqZsdIQ3QHYmbVp6jjJH/8hDNzvxoO8uJbC+MW18misTcHBMJ0FS8W6S7NvcFZ5C9F0liNN5LlWDr+r+8Q9Wugi8k3dP6cHOzXEpyLWlPIcKGScnu0cvNeHoZl4r4s6BNgpuykg9Dq4shj29AaDWBZIhbdVpLJlj+2QFACCkeuN5/0scI4ccW84DYGJyAoSt+i48Ssu2ysZKDqioLMrqukq7SaKjBnxYq+THhgLGKc883AVS9TJ1sS0O/4XjrvmAPI3/4l/+Lidw485+uk2nDIoSGjZo2OEq7ScbVqMVKZVxAFwe5DvOeS3g1UdQhONLYAAmllo18f93RhAQmKH8fzR1QwbVZh5iIr3SU+aqRp1LcKKvGTkrWRqKz6jw4fNszEDyrLnmfU6AaU2wat9NZ/Ht/h5nPqE2bYOEDdXMEuv2n9FoDUPozum+spfY005xYmywVz26EvPWBngKSj8xYhvjf1I0D0Bgk6ZHyet6yiCjBzJ6gGuS+gEqxP3DnAGr9dma+MV3JD4CaiSNp7+YVL8KTalRFi98hv9lGdpMwiinrseIGe66K3QjWBx00iIEzxfyV2PR0F0g+iKAlnMTJ88CVDZY46LZkXy/dsFCcqQBG599CgyouCTYqwWXp//wHJtlxxLFZf9Nn/Q1jaUsvee5wHFs5Qr3ytC4kY49O0MPCp5rRaIWgbrIUdwcNBQ7RmxwgA04Bwl9kcvLWM+wMuySzLWl3+qmZg=
    admin-password: AgAm1epSc9tzTlBHjKJK87hHKlUR8FA+Sy87ZIyYVjfosKsM57I5dADdDHOHZA43qUh8YYhrbU8UYUDMzwKzaNK+9R2PI+wI236LEpXYZ1eWNV9xvjxgwwXU3hcXOzpvhvyU03cPGWQazfY5W4ywiA1DLzemB2tieN51k4DGFNICdlE8FjSlVCvNShojKgb7k9n294uzyqQ7rRhSJkKO6ZVb9yAVLjETv+CAvnof0bLGKTT56zV7Nk+YwBQbaFgNDpMZNaFRjH9p5myxssGG6M10DUefMAYloRHRt4vyTIf3dKk2FzjDKg80GEMCUc5hgEVnDhUbkk8G+AnRXKBEgRB2IrXZDSg5VxgcSbDldWMwPyQBBx7asjaC0JdtKd+WqmWGsyF6u2H1Zy1EhjP9FhtUZFlh4HA1gVx+INvvbWnxAAVWX+3z+dKcnSNtJG5SuySHNQY+YvlQDlkSpQOGZ1azwfLbZluFmKVek4X7iVRBj0oxRHQ3/wsF6Z41FEhs2nFeQIDy+uwfWdGoduYar9j29qx8WwvYR7KuDmxB0GBruu+u8WUUiYP69bWOPWHr83T5dMiwCwHewvUbqoChNK7aR+7Kb0Xnqdo3Q20fXJTRShpUPNd/bIS7Xi8WKB/RYHq9CoP1U1WRy3kG7alXuo19fPYv+b/XDy2XxpEjHnu9HCDcDwyvtMy5nDcA39rZwwHNlw8LiyoO07PwwaEEahlx6sY6MN3mUtoA7mNS+I7TkkundZE9h/4=
  template:
    metadata:
      name: grafana-admin
      namespace: default
