---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgCwVqJ1fX0+N8MotzFxLDkrL0xq3kt6HBPXtZ8Rw+cuarNGXE5T1X6/rYXqJ4NSjN4QftHfDl0346xmwX3r1fd+IS+ESclplpTSpkZIjPzuAwq4EMKw6XypR4rCJi702ebU87KX3HiUNzO+Jfz66UPbXZEhz4Fn2Q0HHyOWv6cBLjVtvlPBjQahii2NuukhWO91OFuKtMMaJmG7LLwmzo+EzbyxPLjsCBsmF7mX31BhfAMM8ftcEly6VgmIrnn4ImGjU1MrJZobvzkyuZ0+/iqA82/3YUfyWor1OYXXcfCXGZX9ZQBTIRyUHah4bOhkSkU967TxMEI5PZXumk576DQwvRGZoO7yI/Dex3/5t65pdIYLKvS0q38mSKrCmKEN7N48QoNYMRrZ1mpczYA0cdrQwds7ysWlv455hRlScWJjEmwoveMsJDxTCsYkRDOd9PHWRZtX8I5lthHOZ7mBAYV7ueVmvu5MUcFIOWO3KYwWJho1GlneoK8KBUUODwmcQA9jSh9jbhw3ga1flO3VE6j7pMaDZdCc7KLwRM7xVYUuGZBKedCMvxfa46GbXBBvQ+xmVgfrVgI6Nei0spOnf/Ed6+tdL9zVQQCM0LwBzHh79YbnOmzJwObdENGQXpGaJ1nE5fNLVxW4hHSBbQJLV7Ms9P8UHTg/Ybc7o5jo5l27L3ruL6rOquMmVOY5NoJ23SrQQQYa2FX1YkCAKAckuWkvmyPsXJJkcWOONAxdKIbagnmOIwgjr/qmaw==
    admin-password: AgAc12idMdLYWs8b/iZ19UJ989HuflzyktSsshiTlgQAk9KjOdJBIBAuqHft1GH6jEEkuk+4LYk39tYwr8CNDEOeNKICVaNRZ4CL0dTkt5hDaO0dO7QhE9kvBTpkvcXPryVW8g60xVfOU6PcrX0ryHmo15SFDbc71yCV23G8EKxe/C9sxrmb+ojShrK9LRkMpT1Vr1az7sN2/+tSWUdJ4h7hBNL8ZHWeQKoy/yb02ogoehEht9XyCcBxYlOfXu8bGKtzreOTNnnBBQnXCZ8PGDkfh2yNlr/h5AkEMNlStT+OexOzULjSao6ezPa4H5u9O8a4QGzUhJdxp+5qs1JufadDnn++6zunr6lMJIQddw9iy6ptDZ5ffICdp0sR7hdYvoHwW7P+burz5T5YB+u1bhUC0hh81rfqB6JAk9oQZ7vyh5D1HyNEdHeC61m2n2Mp4e8YmSfLMnF30M1autvS5BEOnOMqTnsEcgvNiUnTE9IKUBkTzL4R1zy1f6AIFwEKmdcdwZIrzTnmXd7QWHjho4rlYExE8SIf8oQ/00ba1wa472cLL96Uj3nOuB7IFSdQOusbasSD1gnz9I41pk7ImwfKMzi7EBjvf6d8S6ynhNozAO7bHfZ/rB7GM99Qb7lrDd/PWRTPWDHt1K50Oj7seIiMqZwZfGIwtLgPQGOAzYwMlszZc34HVprdjBUWgFl2thAZ47W3INxZH062IYhL15g21RQeynQTAMNQ8o31Z5V9OHLY2ojWB3JQOA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
