---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgAQ1XRGN5fNu7sDYEXCnWjmoLZ7j9m3fCMr1IVr9U0JGVX+sv5joFmvc5PaY7vHB/bPiIKtIXt0lwt9pUycYztF1LHR0zEe2REPBAozF1c+IpQKFhem3GOHdapEg3JBt+groUy18mwxJl3vgHb2WmamUiZ0caW0k81PgpDQJa9k2NyIQzKkEp9Z72YqurfBDLrGtPbySSm3PPau42ipT67epWmDtaVzI17MyDJ0DAVrjTiw8hm8VlBDLnb7stuFip8aQgED+6s27mGSN9ojBN+Aoxwp3eZf1wL9uss6I/KQkBDm3bn3yLaZr3sfjhNcGKugDDh6d0U/XNWuIq85hrBHPCjWYnqQPdJTAZqtKhySQFC8L6cWZglBDBoqwzXO6PbM8EUZOQuUisMcDyQ7Hz9uY9LoWtQSsDJIegNIYuKb/rlCsAPLZlnTBRXdDS+zM+vmoC8EN7gSrBA6fs0eepvPJTnB38io2gVQwBfTpMPe1pNpyckOizfTjFrBNGVYWN3+gfflyLqv1jlSdpsHfdV/NDT7R6GY04o0lZslI6lFpr+3HyTe9hUPxS1hyxAb1VeNOZQ9oyog48oPQ9ItaSrPBsJBRlGZnFhXlK39iDS8DHBR6dUG/l+F/JQcqyT5WQ5IWlmxo/bccqjwgSVwmOXXiVodub7IQnPqPRkAIfbtsXAiG0x1soWTAmMd78+MURAlsLvp7/ALe4qfi83JybLElTIB5RXGeBSuJcEtpY3alAH6jwTilHI=
    admin-password: AgCci0rajUw+egXTRHVprLH94EmLFC54BCLlnI3ZDBw1OtjjLZ7WCxvE8thf+vpG/Armgmdj8YhPDJMPe7b9UlhLMhuHLXOgMZYepim0hUJKI+qraSDf5r28CVgLD1pbXVv7XO94c/APwIRh2QFLRJv147XBuwRrr8eX1lBac/6FqNu4FC9XOOReU4VFJdzEiJeXfSkvDE4OBxun7vo6hOOZaAEb5yrBL9TMOspxsMOrjv22OYdr/OvaPtB4nGbZ2IRvRgaVOwbI27hUYfsvpCyC3joCGT7MtbZ8wi4gQJOBuwGHs4wQsGDF0aiHDzUQc1dzB2kIemwfukdpQrkJaf+79HVXKBJ+vj8ImHka2v80cRL+LfkEiU3oqU3qgoBFSGMu1K7UWttUDGtRmfzoozhVBb58AWYTTKNtJV8vYcywWdUQneZ2/gx0drgjDXj8ToaQmKDZiqUX1jf4ra+zghgTkk9ZM8xudpz6fYE5qa+7spNeYDq48VwRaJXF7uydaOrIWZ4Jrt8JIQMd+pUhHmlO9OFMbfJw0kN3KrTsNBbnx/ty6snJLB3W3xyqB4zq/boPpi6xEXF4Pk2VxaSAkaRcyx3qOpIhYOUE8OoHxg5NxWmh+rkXr9UjYsPeXPMS69XEqwDiy0MFZl8Puskebj5gRiwkjUPdic+swn4Xn0kcaqkvk6Upa+1Tx7hUeUCWZx7c572muC1w7okOnQ3hwTZcNuHKb6LARVeDo/2RYwExI+/7fJ3dqiE=
  template:
    metadata:
      name: grafana-admin
      namespace: default
