---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgDJgMUjNkJKlgHTbkXICSjGfqCE6iXoyIqrWyWox1WnRKQerQ209GI73TvDpiR7NPh3WyhULUMX6ZsfeI3i48ZrbR6Lm0kg9pMdv34vTgDdPWuYO9osMipEFGoqDAP3KAbI2qQVHjeRWqECJKOd/2cgCmMfmFE/4U/wTd+3cdAh73sLulwub9ekD9SIUVM4+BVvsXdefdj/kTXiK3Q2rtcapbP9PDET+1YeDGloAq+uJTfDbhEK7G4Z2+5ZzivS5Z5LEUr8Z35o9qeg7ZNjhUm5Rs7TfPYP1u+X3fzkcf64Sfjaw51gxoFSI6wRY86Lp9CVBlPkqRbejDvqj9xFODhtcpkHoI4UZBJW2c+XrvSiT/X6VYUNh27smOMEycVFCWqUWxPE8+F4bnP8Vq6Pcn5xFOJZ/3y6G+bQEhvhMuoFA4tt1wQEfMKLc+bujIvim7IX20upiQEAbEGAu7EsVWNR6Evwz81xPXIcbV5gW9HYQBly5rmMoKhqUZwgYnaL3wzK0PnNBVwFbyvguzsYQljLiIfj5Ud9bMWDSL9+GLG9iRmBgUGRMGeX1SDS3qx+CexjdUWZTZ68f0mRRJ9FE3iwga3u/f7+z2H24QDQnsrTtBbXZFs/krRfQNqcpba07/Fq5osV5tgBAZ+OEy0RLf2Tw0a2rXn80jBXcGVZLjkcV0bRpxukgn3NyMC0f7ORy/hu9USu1TC7jXpO5hsjTXujx6h0qaIsPId0m48Bcj/Z/WpVwbsF7w8=
    admin-password: AgDLJxquZ+pX2m5IHCja5K1RuOQsKxNkr0JGbM+tgf2maAR7XkxoKM5fngPXArwEtILeHvyPqbAQJE5ntqCbh9/dryF2KfEyMsKY7eSiaZeETDP/LN5WXV7UAQ0R/EXgelo3W9PDTjU2OM8TTgIAViLVFidKJYrUZ5vj9LB9jL5NBx0jvS+EB2tbnbGARLQrEfOI8et1VZmeAeJl9WFDW3yhd0wXFDb7L7EuzQSS3weYztxyns08XY0EVcpjhPyn6s7jTfp15b23NxhQebAFCegx2mlSwsWoY9QetubTZPb78pA89Aj5XsHVh9s0wtIJs9kaa78Ned2Sb2idi1g67WVILGxUjr0Ol8TTrYfE7urG4CMX/4+kwmbtHj6vtENnGxdIsq7yY5XbmCnjyt1aoYpcwgUn+m5g7ELS/d8bWDOnnuuamHTb3rx+hTRoYf95ybQbr25I262+bYnRlSdkj/CbTKWQq+UkF/8jBRLXs4/IIj+c6WzV6eAf0tqVn3FVqo31+Dzo7b6UVSO8f/I5V5ASQQQl1zF1TjBqZew7ZtcTa1aIgqr2bfP2EKf1/CsL5xdtch9jMLK7xBoSzc7iVB344ZZAlhn/+WflzggsdtxxXgtZ5K9yLLdEUWQXNA+QHpZU4MOel71exWgWqeZ4ne8Nsym5pyLexr4RBkPpmoy22xbHXYR/xgP5VvZgXaiJKM3wS7P3DdaHUIEUSytb3Mw/v0Xvm6a0mbOOYHjAwy+5eGZKRlZvdxg=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
