---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-assistant-token
  namespace: default
spec:
  encryptedData:
    token: AgBBqjswUvb/EG+R81Z9kZPIKAwlfsq5h+VGalN0u9SO96yYf+p3KdNO/E7XdJAOOS3R/TaVRsF6ULmULgVfhJxrWWV7Hk6F8sZH4HftUzCGIxG5Ngej6UvYgCyYnGekVIx1l5HhWQNERwUHMDWanegQpyWRbzyym/TWfrAuZkZjGH2JgMt8rE6/7L7HKZNeLS5j34nQoCNZfwcD3Pb2c0AgN061jJ8lmh1VjNtfDD0j6mMY450Ch6YrWw7d1zY6cwsfNr7FnIjuTc6ls2+u2CLKlM3XhZfkfaok3i95OSBmVIviCSUgf6sf9TXuLNm2Lp3MHTfNVET88RUiDtAC/ab92L3kelhQ8Fis+yqgld7its7FnJIXRIJzVGAd1r5ppx2ouM4faPXEpcN6ZJX8tl8oDT11hX6HbGmle7dV1PgR5RHNjZR8gyRoY68P6GXFcUuy/NJE8Vrw2VeIIkJgtXUvCp6SehpalEnc1SQdqUT3YT/E1e6MuKXF1wpD4zbFoN4U2rTBgC68LHrd9B0RFAvD6sIg02F6WGFzhxSwyoTJzymF7a1xD1oa3PU+r2l3aIYLSeiRWAjn6D4GqdUVKJ5Pu5VXQiwNd6+m384+U79yzM9fR/AL+3ozFSwydHgXjEADIkQP94PLrCXe+G9gZOmgIZ7Wooff+UHaX+rBsZ/vbA/PrPy8rcsjINvNDeVe4tjtug4uLyr5LIdiBVwFVSU0VFVJKzqnolR/iipdT+ms/Hds/C/RGQ7w0QqWmLyyyNJIcZCkXWQCPvoZLW0cMxUQzjqu/EhFhbnKAKSow19uFCvKbVBpsvESrcjVb1s4NDGC4ewtejSJo5/YTQB1DgTOHlwWtDAAjSk/NycodYYCYh2OIpBBxFEb6ONhMqMm2+XRtzeSrFT6qjpYn3HoisLuVqmtdMiRkaGVDdnKDrxyla/DRdiSB2I=
  template:
    metadata:
      name: home-assistant-token
      namespace: default
