---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: homebox
  namespace: default
spec:
  encryptedData:
    api-key-pepper: AgAKKTQzaKRN/VfJuWmo54WDHlwfDN8zHg1OrQb9TCCf6lnNwbbweYCycM1rHqWwjQ/XdwIj2aULviRVRkWOy5idXag0MaszOd81wUlXN/iU0xxpCLh16gZBYwYtrvtrX0ut+d7w/qtBDH0R2sBEWNLvIdrAeJTf3vrWfURfHA/B/uRB7XcoBVDY0wkANTC+5TM6/5pDRGEfnJjSqzdLRf0XnPQGpLxTO3jyT/TOTvungXmxkaDM3a+djtGv1BQITvkfQqR9p3cPbrDzvUEDR3JyUacAasJ7sVL7z39HVhkKJ73ov4LIfFY2dqypgwY4gtJX6rlSOMbVB0Nw1Im/Mtlr/or5fwK4bHSMyIJ+XkDcX9tDOXv/4agCOKhrKEyZ09gQsFaxWUJbWBDKNBkBOlDfXtMieGuvk1cp4RGvmTjZncpOSap8aLWp6zX2yw13OjOPtAR5gYzl2bPBD9duIMAtTSmwlOZwuNYHs1JGVJN54jWD2ypw/LS497yPXa739f/TYcsin5Yy53IxDXEXe1O7pLfVRsYS1cwVERs+5R0CbGjUIzEOLDQ1CZcGPtL9CQk34Hs4CjNOIDJkluhBDr/u6omWqLcpue687A4bzJfwIi/oZr79n8Y3WCXJjveODQnuVMcqgX/buoWQtXJpt3U+NwWM2yltIZcifn01R0n1rnbqTLTFW1NxnOEziDNbNBsOUraU/wGkzt19+j0uF467d8u17eVoYxXhrCWy2vuE49w3G1ehafuM8+wnPOKk/z+6MfDklB3NVkMVulTvKTeX
  template:
    metadata:
      name: homebox
      namespace: default
