---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-assistant-token
  namespace: default
spec:
  encryptedData:
    token: AgCvgriFobQrWeKpGoGFOOvK/bKRqAfy8NzH6RhOw383mw5uzZ0vBOZJqiwcHLWHbPQPXDYK/ehg2YDMCZA39RILFsqhEQqLtu7DvjbV32nsTkwUUtJaQ1YCMMHV5F2GgPhxSjtgqVo9lxwNOkrZwkw+lZHyA1cWqjpSoriazB+ebFRG4Rt+FgTyA3UhBFhpvgH+6unxxoGUqs3mPgjF7Ykj1pmcbL+8G4kEaJFbMLqEGQlp1rTDqIdhNvzfJ9QZcWcxjZHuZ5WvCDGtei6QGWcwYuSO1+D4z96KZ+J4WXjZyRd8gBf7cUqgZxhl0n7UwlQZQ6Uvg42rlXi3WJMBb8UrSuzqtg/Zae0n81EXegTtatc7Uy0x9uRobfSUmXIMhxYfSE4Vu983mNNRa+VHN77Ov65GpSO7GtGTKRW6cJBZtwps6aayyn37OHffFizDhTn3Tt+uZSTBzlgtYoMCZ5c2q1g1Fy12+qNsxKjTy4tD7fSetinOWKPleQM/j98YhcsQTaU95lS6lXs7On3CcpmnC6aT+Z4V0et8m8KV7KQFcyLX5ThmAwjRH0Ngnge0YgMp4cJX1kNX1VVMjnNYHybiz99fCZ+W2n5bOt+zuPSSiuEGB25FMyD1OpRXZSqZe3rIvG2Drc5pIjDGZhTDCQeCOb+Yv7jcc3/S97yTqhytLOKVswHivmCLuTWb9DjRPBtF/V9Q/q99lPfixIQTLqHwOkBs/pbnoxDbcISiRFYsPlDpgZJbW8jY4lQrUTkUDITvRrJLkXqjUtBRvSkYF+QCO+Mhi6d+O1pWzVWSZguF1yhZWykwPDs5oLP6IYynj9AWkZLZI+GpC+D7QXUo6Ffrfu2ymCwVJVgY938LqFyuCnVe3kzbhrlo1IioMCAQB1oYJ8x6THv0JR4Ododc23EBpqnaNR41HtMhXR22qtecvR1tBi5F3+c=
  template:
    metadata:
      name: home-assistant-token
      namespace: default
