---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-assistant
  namespace: default
spec:
  encryptedData:
    version-control-supervisor-token: AgBp7m8dLRP+Qju4EM/gncAlEYAT7vvVb6J5u9GEaNIAbe/qjqRv2OH7IU2c5Ef1NZHUSKY4OkhiT9lL/Ki6ku6uPSnrPdlttJkYh7bXZ4qlsTPJmluz2unGsIE2cdWoKwoi1USt++4b0voC7/cVtvJ5fMvAqHd5wEmrOQmv7Uo5Re274yp5DB9iob1kYHJkG5+X/Z+LKo4Aip8NTVC75QvQLFpr6ft5LCwsUx6yHKfLYJAbwjvc2rwE4eqMTqY/By3teX82r60k89amNHngMxsyebfuOhyHPJ2qVO3AEjw1u8HzlYp2kzPNjhHzJZ3hJ9nwd4H3a6OH5G6/ESvk59hHwrvFWSdtzZPGXZYBxHszirvhLghiPghE/DlaK020YQY4XQtEzHNaid5kCnNVMPKBVFa2iaBenH9fMsmUmII1kXk5biwf4N6lNhpOOdGdgUA+mTq7XymXpcjnll0OCjiRzRVPlSpwxPtEC6qCKtmR2/vYp0H/9k8Pfca6GVqzEeYRm7XcH4jrzjB5urudV3ZQ/Jb5Y6GEbczRKJb5v59MP6ThPQ+tA9P9Jp3+shpwv+1opZE9fOHVk6Aet55KU2Vnk77cGoDY8ANAbKakhWe1pgz44zOASMq+Rg7J9jkzDTlsUZxJohLutiUPCg1B9BfRrf2keMHyq01sgJzd6GZVXiKZcjIjy7Aeky93QLJFWQuvmaPWfXlHtVayRV6BTItCHlxdWnaYahyOVAgXt/LwIFQyNHEXfwxPRksw5dR3vy+pj1Fe5Q2Qy+pZ+7AAiQ4t7KlAvWNiUHqWBcSfDRo42AFxsKcb1RaYVR1o8bpmS5yY9ZOhx/abq6Y+YxFto2p1Girw2FsMqs4nAzVm3q9BDdDjzdHbxLRb5MV97k7mjcztph57i+cB+cIWH2dFVwMFqyulDujjFuvnYobdlGpI0UMooVI2jHg=
  template:
    metadata:
      name: home-assistant
      namespace: default
