---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-token
  namespace: default
spec:
  encryptedData:
    token: AgAhU9wdDtjjfvw+6YdXI0HUYqtkxuQ8h+840mArSvytKETwZbJ18FGSQgF2z5zIgO+x2Gj45mp3F3L+3Yr+z3eZY76BLtueD44d6o3f1XGiUsuw34hBcMMiTA4ooUwKwMqeu0tjFcd8Bf7RBCnSYb3AQvbiOCc9FBueOvHDlpb/dbIFIV9v3JGRqmeLAIibSVVMU4vRo7cfS1YDj1KwA0+EBjPFWRj0FObWSuCFxKQRkBcU5oLNUYL3yrNNJ/DAh68Azq65xcib9CMZHKVBi1XgxgcQ8yehNfHh7+6Xb7NcMfS9o0V0etJS+3eUmH9PDDQA2j/t1lkdGMeLSf1vOWeINMIFV+PO9wqDLxKjlzTM20NvzQzq5DcIdNVKvPBAlypXnLxE83ITuvT/nhel7ZRAkAt40EVkV3ALr0OjvWX2YmZ5Upg+xKCFvhN0eFfeaOGlrTNFi58fWebgTsm05F8r02sfkP2kf7xvSXc4MCAQU0ZY9FTSmimkj4t8Y3mtaX4WoCej7vAbwpHmbvPkwUXZZuhtwah+fQ5VirOwFWLzOUjrs+/RhO07Gld7MsQOfV7GwIAkiDDxjZ4RvIyOlLuvQAQG9elfmIv8tWAw6doTOLV62MSHqCvqfuEnweKZzd+ot7dDVmpJK9nV1SlgDjq+eR+h5bYSJRUMWViogjI5mkcPvtaJ00S+QSHMyoa55Ra4Kny31Lk+7i6rtCA/DN9bVpKmlgYsmj1mqcrcoLbquwh0G06EsCv4/OQ5tdodgv0AivSUDhxs4J6S8DMDqheuNwwkPCUkPI1cscuT1+HThGJ0hDspFVSJw0o9mo6l1ikvEwasKFWzPZm4rgmnPig5KnvvglrBbAWRX4TZE5RcyQgR43puGdLe3UwOgDWO9l3Kqk7h3uYa7b2+nLuxId44NsuVZTmQ4URGib8HVzaMlO1tvh7yQu0=
  template:
    metadata:
      creationTimestamp: null
      name: home-assistant-token
      namespace: default
