---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-assistant-postgres
  namespace: default
spec:
  encryptedData:
    password: AgDY6BNNHNPENGqtK+fL6b1rK9S0wkTnkwnbnPjkw2uGjGf0J+XKfy2bDf3qoOjXjVCoTxAP9MDVdRLmTZpeYYIvvGd7ixutYMuZhFRctC2nAGMiF+4E5lzb6yjkgxS1gyXSZfNx4eUl44aShnwjGhBV9wq6cwFpJXE/HLmkHUD/LgJQune8JisBeTNCcrath/UPWqIOZG8mSn2zTrdz7cmny/sJfRrFqYhSR5xY1eNAiRniRztAaKg5BkZzDnJn9LXCXaItjHvXbhtvkuG+9yufAR2GZ0wtGlij4ojleVwO+kaGsnZwwwRM4nKhva3fCJxVvILD11K4IDxBNDnVeU8dRx1Po16TkkfBIc6ol9EYzSY+8r0ZJh1P9Tx+OUfYsn5OznJWMjYe6UaiZoN8eOWXrMc/mi9aGIMMoIQNJDRBaNWWEQT7pTS+HScK/QwX3vtwHNy1bNirTRq5h2tkM3s5KekgHtEGBuTm9juNcWjP3Lmuws3HKZEIeSIVcwBG/q/pBgLyyNfHwW03QgAMSictOx8zpWvqzyRuZMM33zbKl0dTA3gLwI7OsiLI7OpyJe3VpBpA6nlHpQpUnObTnnKWK5Y/NYbGADCZJjtB3U/Mh9DUWloblUaBBUrGZl5UlLCoqN4xmn1NZRh9ADqlZsIMGJ3G/1OBkmxpjB/NAvGNKLOQr+4Ss3Ix47C9cIuP3lZm6yM4PbGLQcBG2SZLSYbCFKj5SOOHpayglgaD/ro=
    username: AgCyD+hJDTNeQ3b2XebYS4h3t+NNnQkWjbfoFQy5qAmy/1suj4pwHJKmIrB/grlsIJaAST1nrRxeIMAQ1coGz81XMyQRAiZK8th61zzX/+nrb2kXY9qDOMDanUxeqcBrTQGbCcF8rqeT1VAFgaM+0dzcrRPnllxuB4JnF2O/W5ecdLDOFc6+h2eWTAdDICZWRMsskC0HBn8wI0OUk6jqMhpINGR2sSqYQHCi0OWVuoFmR8E9F63rpb+nP3s2KsbeTZ6OJbSZJ2fl/n3LX+BNyTNChG1dbvjvGzkin/sdyDiylk63/E/dhVJV+Ymg4AINO/pQlzO4C0wUdHawzzzoHJzKI+n0+BjKMzeWrmcE16Pc+TIkktFYB5wVpAQ9+uM5RnuIycfc2gzBvIdOcG7w+y4QmXnYzy9FVUh7xMso8aXcAOmNcvMGNIoCFiW0ulkqFoHDU42Sgnxx1TwLhiZx9F29pZfLPyaRUSL8ryyu3ncSl3krJR/VyhJeoI5cIrzpvlH4MNvgJhgFxXI/fBVkmBTnDQaH4cWe/7G0kYxbOZsa1NnUSgkw3PDkPKBGTB4BYy5ZqQ4vFTBpM51K/JpEIXM3016h4iT5itRbwkyFqyWyGEJWY3CvUy+yxfW6jIkRbT5TpR7BbbdzHNlLy/dhshDMLKFmwnmF/BmrJH6uoKT6Ihc1uIJl7S+2swZLC09X9yjmpwetm/D0R98Mlzlr
  template:
    metadata:
      name: home-assistant-postgres
      namespace: default
