---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-assistant-token
  namespace: default
spec:
  encryptedData:
    token: AgBihka5lM7V/UwecuRc7+209Mxy7FDw7sq+cXo+vuxyq3PQrRhknCv0GdH0qNk3vEIG74BI4VfFXrLDiEEjMsaSlLXH9DID+vht4qZuAFB77hYrFmXKArbqEd/5DIuJ1WPzkIb3SZKMn+ZceL5P7jRXiEGQhhQGkiym+w2gwI65QMHKNNRsgXKcc2CPDdinJdBaER6lZIV6o31Zk3XkGlJNxxYaGoo9Y+71EYuyFdXyPfR7blRbgMPnn0C/Yr1Lx950F5ODNyZNG5Sdel/uhK/JNF8T1iwEmjdGQgsmylQf0bwfM3ZKrheDNsWfMyJsIFFosrd0mdaVVz9X80bi4WIAwRBHmdGW+2gk5c5kXlNWqEAARWntSPOnRUI1t8K/+KoleHOMI9W6JSFYZ4pEgac/Kj4EtRC7FOOj8+2Yan3G2BMw97nCPTm2dvHOTT9sGornfwBpytvwp5asYcL+l5H4xSk5nVn3KELG2HroE5qXOEyGAacPHbGtNue6I4hKq2VF9u7CXHmvX8dxUzktvQEtEwrUWX3cxPLtWXInsHp0jUb+JbLS6QBrsOJKEuq0LbNWRlvU4gHWVpD4XWC6So51GZEGhehQZxJKEIZ8KxUMwy23ZEqJPOkzVmK6DXRHtKNsbxIzAU+PmHL5SP2tKs//JdaU1mqObFQ37RXr0VmeUC2gOZ6AM8i6Mb0UQqtIqEPBMIZYmAKSVgQ5Yc4agEky3/H2+ylIc379uVdawQU+1jY1vZ+HumYBAAQRuvl8S7HXlD4ncMIDsxejQvvEaFXuaEK9UxwiMIYW7wPA22LTYF4OKeUxCyRKU9lQsCQMvAMoerTavTvEoyTLq+4nboCMWQNidTtXWsdBbNPZONC7t3yHe1XLvwXIZoi4t+o4lJsNEcSBO7+lAk2gsVCnmFP7s8VCXgKRy+k0bCHqm7vtoo5sMVV/Ffk=
  template:
    metadata:
      name: home-assistant-token
      namespace: default
