---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-assistant-token
  namespace: default
spec:
  encryptedData:
    token: AgBou8qzivZX7BhHjBARBtbqSFPuQyDjBBoeNlxMwFOghUloMVYgCpm/f6Qf59152D402lgUbWY7SVCTGZUe1Cfr7Tv4imkclz8GXIc/Y53NV4tqnbHwtI7x3W3pvSuaNks+BGEbfR3ffzePe10v8z2g5xJdACn+sKk2wR6+JA6AjkJS1ftNovCL/RJuUbrsrfkS1ZoL37HknZ6FC1ibVzPh2NshqX+Bn4BqOISd0NrVsOEFZJmzNsjyRo/rB3/GKqfb6yQaeGMCf+N8z+X2hS+e0+7q/j2GS6MEZ714iuKMUrmhvWdFEJMOewza9kL8SlCK/jvuBBj9H8ltM0yS0f+iIECR+vpXUZ8qPY7qvEBn6G4ZuvCEcMuTQBWdlMShFNd06eUcIELHr4mc50d5ecbGR+e107iciWYb3nOODzxWUsPDC/FUQXZ/9yUw0PTfTdkjRNC7erYsuakLTXTXmGa6ohMMFERrMq89Cu9Osaox4dYYLOv2KzxQ4WPKB3tEZ+ekD6/7ZlJ6z/EjLyuJ10GOmARKDmVeB9Bnsya4gXzQVDECLFe5Fn92N4wPdFprBK+SbETCdoyCdajzbwi5nn64C+t+kGHutm8tHdbbPQQcHq1Lqq/k6PuwpCqco7TxYFm/+MIouKf8wuS2PBAZN8BO75nH2paLFdFNeIZEveZOPJjgBQYh8/aQN2H6xUPFyzzKWiutsbOzPmYveuxktP372iCazO26OfNS+gTGMkmgsvDSW+qpFpPa3DoQUjPDDKDonXOJJchANOmtFqD3QLugrvwTBM6Vxp1irs1cqaHbPkB3cHDWibryI82ulv9nNrZ9Mm7AVpuz58qy5xYj3RVOuqaRQ9JH97ZmX1Q04om7dvgvI77uV4t/7fizf0jPWVPYbJ+fBCiEyPDOzDRoSVWK7XpzI57vyR7ThfXzxXXQF9QQCHTEEx4=
  template:
    metadata:
      name: home-assistant-token
      namespace: default
