---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-token
  namespace: default
spec:
  encryptedData:
    token: AgBE4nxdEwzkDBSzDF2kBV5U/KF7y9shsGmAzAS3OhlkOj4SAQzImITNgH2aDmaoeuS4Pg+ERKbaXaLby6Ui3on5J8ZQ8+cT4Clywi1RxmiyBaqS/RIBMJsefqLCXyptQ8crZxPY97ynlBI3BSkUBPQpBzL8lcP0qI0irc5L68C9KjTfHODYdBKNz9CN1kdbAd5GFinLiaxZ00/P1v4c/jX6RR+l3b/cfpne8E/Fr804gWpOjTDcrrG4mOpGF3lDc+ylpIw326Iucfv1oGu1whnJNeRXt4c/PsR3rJoHDJ3UB9j8336pGUnnXEe1zl5rQpEWBRaVYvm58VR1cP5YOdHkPPsjzWq4AOROUjEpfRD7i8DT9tv6/TgDrVuGrwPZRUq/f3SoOIt2HeWgWnfe4MAZ7qGIJS9ANiIOrtAxqkAlCxb+NRL2TH6QkKkQCK8vSisWhhuQ7ESRSxrRqHlIkt0kieMVojyo6AnDco220yCEv4PCycBB6BFz4DoFMiIngvZbnSLTWHoHRgToOw3HczW1xICdRCkxiFWMYUWfk4kkdWjUdI6Igar0znhTNO+qOXuoaWu6JC2WvVpiZy6m2eH6Dnoo7ZNXEvlwnF7VSmRO2JhT0U6B2AlEwEITuhBGBll1f2hGlTNXylBUfT9RinKsTKGNg6hAz0Gf+2WiPgEFiSjEfhNIHaGkdDzHtw8qGE5Waz7KlxAMOarvsvlS9XcH2zIgjA8PFG4LcWhed4BjkOeRLbgZqo7daZPe2Af0wEydTksR+9RcVZIJacjEE8GUDP3Rwo6i/GAIkE1a49oGdV9Brs8rWgiySjWxKDzn0/aNXF8Y3eIxpGceVH6RUr5t2EK88Kt+AcT2sP4mH1BKV839XcG+HRn2GQxC7uEOh5TnC5LSXIPaKFrron84cKSN6HB3JaaOI/SDHjDNSWhnyv80K6Lr7vc=
  template:
    metadata:
      creationTimestamp: null
      name: home-assistant-token
      namespace: default
