---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-assistant-postgres
  namespace: default
spec:
  encryptedData:
    password: AgCw5dwA6Y7HdolpD9n1i34KUZ4YgmszWXwCTTCvzV/cbHyYSvEhNjQXvY9bYp3NFbuNDN583+y1h9GUMze/rjYv9W4f4ABxFSsOm0uSdPiGmQBIj+iKeqXpYCprJt8AxRoKWtmuFByct2mJJs6XRLAS83C8ji83KL+5cMeWf5hr1/E+cFqpXUTkkbXILaPed6aUUUYPuYKFASLw0S7cE2Fic5erNnCtXqEjejvHnBz4eaX81L9RIuTDkNl8bXeUVPGhWg6oMKDTOY1dDIfHQaOlVJ1YKsrhp7VGhN9Epkr3dYlYhXng/JPsNGuipIlv01t1irmxbjhnlMkJnkjWAJQgP8VwStF1FCB7/XOMHu8VhZklqaqKlwG8Kd126VKUlfFOsPW+EBwZtBR5cUL1D8wnSaifs3fvDQOEzLHewED7PEMXq3ntdqoxoRlxIxGkZI2pHRinL80gGP991TtBvDqQmtOtd5c4ZJ5ET3FgZ+YHVvLyCZ7mDRse2Hq09vbzTdSjUvNPzyPkYfOb9sm9AsDfuyWT/3M3BmTtB6eU8EngRtP5xZC5MWaRZJ8co0horEPQ2A21t0tVHaPKb9ZuViAFG9UlYqi6CwD7IkA2LP70D3klEAyzwjJqRg5A6OfMGnmkBar+eUaj/E+aCx1g6bDXWEWKce5BvtCUfO0FjQ6PRAGa+XdFJ5rTXLPTmT2DDr5cNUXTqu4spv0S4oImZrfbkF7ZgktH7Cldm8ssJA8=
    username: AgDBajKqHO93N37yFD6CmYWq5h5N73gw206tcHPLZ6wPgMsD/WX5V3T1SgDPFHmmKN6BdCRV2MIPFAahyk9tbb0jQc3bh+0Vhdw+uB3wgBycE8o69CCtjifj+OTYv54Zdg0rljEcPCuYBnzjrsE5nRcQD2qfQIk2IcR1vTOK+tisA2gmWkuaIAoMm4V3ADdyIpvVyo5gNUWU+L/FsqRcyKF8RnxvgP3iSL5Z3r/FPERla8IgMpck6/GP+zUcLM354JxPosDFdJa0hGa2fuy5XQP0F7lDsgMrJEM/O/XhU6BnQTkqcApReQzF8kZbRreK5C4UtboVc4YW4nUmIM1qIYwrhXjZUOYRrLlT3OjtUKt19HdBt6A+q9krN9UpzNRXj3ySjt0yz2etHJcGA8hmalg6yTrE1thuNBNXSDnhpTWu/YiEtv1XVDnRcVivDJ0RSQOl7kSZ9+LSHuHKvpGA3Wp23CWdXN1HpknByQqDM3XCjJi8WvVHPfKfg5pOO1ZP0pRioLIixvYFvLMTGU2HYYjdeDSM1i7RDLQmIpPfTF0LJzxJYNXSvYy8SsbTmlMOZdriQfITCETUy+siH5/t0medBfZR69ibpslHlKQwNVQRc4CyCS/zOzIQV+nmSs/LvqUH5nJ5S9A2ZEmXuIAn382v/V6xD2mck+BrZa6rub9Ri2kkMRlqED/80v7aBP7QFmnWbZtarG3zHowbQ5i3
  template:
    metadata:
      name: home-assistant-postgres
      namespace: default
