---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: home-assistant-token
  namespace: default
spec:
  encryptedData:
    token: AgBqXcj+RAMx3alOcQ1Gc4YUJjr5lXWELpH3zzyfC/4hhNEVmZBqN0Ov29cFxTHwMP20t5kSAcd8YdmFyf7ikcltXF4hC1GszFXFkXieHyHOlU+TpaI/oA3arKHpE65UU7IWlEnXfSCO8TznxhB0g5lgCLNRwvvO7Lqcju2F/LvpQ5EyCmIsDwuSrkyf7ofeDCaEzZLnP/rJ78m/UpuImRH9N1C/6WF9m1FQkrZBYPG+lUMGTFSv9XWqa7dUMSfo7EsTIztlEYQLSn3Z2MWnBwwDebUM55zyCwgaXarwwAGbkqQ0t5t/Rn2F0mo4FF9KsGL5N2HGRKYJStTRGBFeFF4AEDC89FhgrKStyxTJhO7CP52ByZSkenRF252PRp9AF01Bwa8pNhjIWyPgGhngfYgd7T33M/K2pEG/Cwk+1haSqxCVnoTE3zChd4HcfLeoNl8rs/O58EcGmc6qIP49OgDwvFPd2+QAe75YYMlS+fOfNvcrDzsTdH7VomT/plVOohz6TCMQskKo+q55AOh7Iye+sO1SA9JIBdbYSbld+V8Z9G7V956mL8oWpnFWSSHWlihow0jdqSXYStnGcsVmsxIUlG4FrHSJEiJQq/i3/Frps+ck+NX4uSLfA2JQwtKo69CG5q+rXc6KMv0zKQ+FGcgtVCZKAbM5LLrpPBiWQO5YYly6yzeHR8XhgEJ4ynrcmi20JW0QHPK371kvLHKoBce3V1Ghm8caXSEnSZ6KVnTD9EM1BM1UqX2x8phaVhNvqEvJgBclHtU55vVoSox8bCt352H8WRbdN3np7XkX6FzIE+nycBP7oq56RXAZMlWbcKvTXsb7MlyVJa9MPDEXgsoE2dE/JopYutmXuP6hWQUhu/bmREDT1Swv3+ipFxKNY9U5rgFO1Q/zKYB4xR0NCfOzxViTxFY+fKLevpFGtVIO3pFLWJDTx84=
  template:
    metadata:
      creationTimestamp: null
      name: home-assistant-token
      namespace: default
