---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: home-assistant-token
  namespace: default
spec:
  encryptedData:
    token: AgC94ASCjDK1XyOvDgbU8mi346uSiV7+DJt5Lv/GaIKkz110Lne7upN88cQD3nq4ee5AKeBbXeHq/5HyZQJ3VQ3UYzfZWSZjCRH//BTlu91BVE+4Syc7c5VGGjyxlofII23GVCyW0BNh3TauhMyZytyV8+2OCx7jS4nr7tfwSRuhQVfpFJoNMUQ9PWZlJqO0eRkene+68CpHZKiPDzjtKVk3t3qGZeFYdYnFUtcvz8qeH1JouWO2azplclHB3XBtY2xZ5oxDvnPXvHVlbZaKas32AkMQyVXCetXcbgCfAg3gmu4aOQBrQq5fm2pg6uyigN2hgSB2Dwjtgz4tUwSQM+atog9Y+nXZRMNvj+DN1BH9KF3CU3iNo3SwhIpG6QBgxYs/Wd7YEGmmyIzTNYfqCL1sHQcvCCuc0xQfWCgEsMKFD+n2lLjdatsgJvTC6Snyy/Er0DRsbT7MGGLpN0oz4lSrsVq2hb25oh/SYfktdbHJjDMNHUz9hLdF/fe4FjpGnPx+9GAq/M0KdCcIdMHdv1dcjantwnhLSMdCcA8UWeLnZLDCuNX+Wot4/XSTElJRoHAlXfjmf2wzu8IsFjJLA7IvYVV4rOQQLD5QwgnHPQs6aWSsYHS9Ht8ZqgILpp/BBzk6TfZ/tmLYNaL4COYkpiyAwmvL0YBM5+kBcQrG7FP+d26aDFVUJPmqy3sT/EmzNt86xjuEE3vyFEbqAfhUgifX8foqoEHMYcyK0Psnhh5v7f8McW7ZF10PpB4QUMJauqrIHvlnQAen7dA+jWnbX/hWDemO/f/SafTv7XkKeE7qQZCaYZk05uJIVQOLaPFeP6k3KZWFMAF9/bChSi7MAzYA9Q1ElXdASaqO9f4pBGdwCHT0f1l+Z58AOPeKtbOXAHT8r5DFBpAWxuLvTDfId2bIFOrhE3+rRF5Dk7UshDFd05jOvj8VSB8=
  template:
    metadata:
      name: home-assistant-token
      namespace: default
