---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mqtt-passwd
  namespace: default
spec:
  encryptedData:
    passwd: AgACImFrlsm2zh6Yn3aZsCEEuZ6RVblsMqSiYRezQrNlquLGsPPkZSyahno14Q4hlbv+G9uSKj9eEmM9f7QAZUKxmjhBK0rQ/TwRex3MADb3mJ6sBvLsOnhJH8I3hRMT6vHrv/o1Do15OA76uC/aWb72SpufulGPfQ8OEEmejSBacDEZELzrXRyFsZP+vWpHmp2woS5axyB+ncGTnYJtE+HeR5JlNjiaV0j9p32RLuMk9vXrp44PX3R36GDw7GmKTsi2qs8vJnA+PjtLwqhXC9XbV5NkCAF4jZM73lyb3oxXGg9tq9sqBsTCsYgs3YdfCIc0190QbmmwcvfFpGxf7Vz/9hR87iHkx/ix17CTmxG6Lmizuy8q3b6FFD6ECRmiUKTyybUtZrxp0uN20SAGE753EbSKQb8SLmcZQeqJJ+inudHZYWopQealuovkGDm6eX7Okeo4KJmmCZTT0BgN1VI44q92Nhmq7rw1HYqXIheCdzPAf/o5H8T5BGNZgplgwcwdMJm5EjAoIq31eoXjtWZ7UJrilpEId6C15uqphguRQMRcM4CKSbqZERuAbwnTYJbe/ZE0sB3+U03euKoFbz1QKaV6vMcFIrCHhQcdNomzGoy/jPZyc9JgLCZDsX1YgWjFf5HoLCef3scpKSc5KATC/Sqp4MiWZ4gFRmZBNFLFNUyhydAL/4QUJXf2diqneuTkPkjiujhYklfLs6+vgUTfcuMjEXyjuamLBbvxkbpwm8Bdu5xOc1IcnFDgwDGaHK8A6p3nRpcdMS2nm+9dbqZ4yOB0LEfPTDUngYr6CEOoifJdxyjfyf7BGvXu4s+i4ku5VF9fl1sCjpYpAGa1IKtyw7KXETbi50V3yW/lIMcjeFrZnVDV+tVSk+mi2VjDeimPouaYVDsP2eVLIHjCEjyNyfusD+eyKQ==
  template:
    metadata:
      creationTimestamp: null
      name: mqtt-passwd
      namespace: default
