---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mqtt-passwd
  namespace: default
spec:
  encryptedData:
    passwd: AgABtol7Yn6WnjT7CnYtjDMfUKEitRIhY11uvmMamZNHBAJzKkKBW/BPzQ67tdaB6GuLs0Te6kqJ+nPD4/IXs0TkmJF7udERqZNz1pMbDoyZZSmUclBm78ByJG1VZb7XfR44qaJ/jskcdyXmzOQE459bZn0bI2ftUrbsSgxpZBi4y1biR7HPlhbEzsqi+tGVQszGi8IhoyaFA3PyN5mfnDgB8zsDrRc1E67dt8lIU+SCUGkTy7s86UFvKWrqSYAnfn6i6WXAvdvER8VPertg990SNL54MF+uLXrQ7TTbKgtZPjNx0Q6NXGoQI+sObYODEJ6inS7GgUyUbbFR/R3bic2qBto1jkuDkOXq8CN1F0qSKb0tf9C4IbbwDyWEfgtZRiaMktRCxAjATqWyl7+BSS+1t0jxIFDcLFd+z4CHavqbgyBKPfIxGNEqXMwe/i1DV7jmf/3b6xHcMUX7/0B6V1NuhlJLsUP8JDCyGYkP966IlFKohrFvD9jyzZAfPT86uAVgFfflVrysx2MsRMz09INKUxs6kZHRL33vhl/8WmOAjNDYBL3gEj0OpD9DfNdnTbafW1uQVfcoeU3NZYD8XvPH7tco7GAs0mrGpIixWIU/YcfMXet11y6ak4IpEigMSNIF8pYeh0gzqFT9K0fX97CbAzE4ptYKa+B+9+gl13Derzf7vHJ+G3jkdq4yqtF6/XtKmH/MV5+e+lOHf6RvT+v+hAQMaU6ASNjJBPW5pVQybvTit9WGhhVAAmW7w7fKj9buzbPfxY03z38HQeHWTrsMOIR1SFTDyFWx0H/gIrLlKMq+CtY/ElzR3M/4JoMQxJFMYiISkOkbA/C/+wWYBzV+46oE6uPW1yrXo62Ra8GhnZNjTGJ9E8ReHZBKWB0Yr/kh8F9DybDLWv3n3ZkD+1f47We9utg=
  template:
    metadata:
      creationTimestamp: null
      name: mqtt-passwd
      namespace: default
