---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mqtt-credentials
  namespace: default
spec:
  encryptedData:
    password: AgCXea+BxRgPu9z7d7QwKKuFhg5OgBSzBJifpDDjcV7j00RVzcj0Whg4QCYtqZmTdmKzs1iUdbgtQKT6o77qKSBRF2lN3TiUYLGGspzyTqvE/Q4g2OOTZXq474IMz5HjDkYP2SaS8ikwBm/+a3mZO/AQYedNjLbs32hDta022rYgJ88xXiBWe5qmyH6lO57uoqq71wQS7VC/AQeJiBBhl+ZavefO0iJSD0AuYX7m3629w/AgEBrlL1+YLhMs8L8G0Pd/kewJT/9mkS19WTyWisSaKQFj/iz72UfRI33Kop7vO2gLR77Ng1ZTcBwF5y5x9Gu9xeO6bOPOX6zcZscl2o572P+G1L9il29uHZDQuiRp93EzaLJ3V2rSf4NMk0lqIB2Iya8TFQ2tEfaL4oQ6zvU9ddC8PrQ3PPW8rDnfCBMUVdJELscsS0Mw4Hjv14QLgnzX6wWdDAv9aAEmCqAHhYHAES3H6edRXn5p2RBTcQEtc9Z9rVUgyBNpVs1BEP4hbw57Db6kz1dJhKuUfEq4H75ENA6QR1QfVOnaRYPL+SLHMN4vQVJaK/uNS7t/KzFFFPIAnXjJGHNZlcSCB8YE3AOXEfCfymbPWf+BEqNFZPeD4rllTJDsol8ygfgQ0WvO80U06AtJdfIPMrEjjq8527T/eIEJ9UUBmB+V/rJQZwasLCK3AyZRLyI+RJHayAdU+saTgPhBYtJPi6ahxaRW6Ityl55kWGo4Zwtex7hezpcObzvEasnwTjg893vbk6rBKp7PN1ixWiDFpA==
    username: AgABwVYPx+8oceCc8mU1kVxrck1mLhjYZbC8SSGLnIpmCvVh7bLp/ILJ+OhGD3UwB2rbN8MqFNNflcXzTx4k0U+wtIkNukKGmUPQHkes9VsCDecALuRdHyg2l8bBRn7B7pA5BVELZLVsLFmYw1XBe7zHH5ySXNGUCYaOAW0zuxPH3Du3QDbwQ8lz6QaOXyrCQVJktAHJOAXhUGcloXqjm3WR6j5oBYZqkrHb+qB1OKxnTJro5TGVkGYll0o/mkLbGgXbHQDVQGMw1El0hoxgTYMk4jyETELGvLbgMqanAOXpOjupZY+V9JmZw41Ho7IHjcb1PXv+N9ISDyM81L0NroOG5aOpTpazAx26eM5CmaJPLCY5wHWMY8dJHZmdKKK6W7RodypIAc9Iadvx1Lla1ojvUafmcN+Q1LeyMJhvRKTcHyaCuVTqdv6VXvH3Ahsm9zZLfEvZfqmK2iptgsiu+28livm2p74dgDlLA50h012I3c5onzLc+HZToC/s97UXmaBDfgDMJ8Os5zrdEHkRLDOwuvKVLno0A4n9EnUFoT8EEQv5aZOwRbutrGyeb7y6TJEUICb0u6cqi0x2NeoFv7yxVPo+KOjGze9rlC9Ds+UMnK3I0DmPir59yw6zrbjwYGGunfdBI4h1eSXge+n8MoIq+OGcCUnQW15SjtvG+5djgtX+y2OL/iFwjJlXhB4rzc3QiXlacUNXjvv6cFyWVp60CIgcZweMYmFXKmXjV5LNp2uQ03ywhutYiBwESFe7ByYC4CnGum/xZg==
  template:
    metadata:
      creationTimestamp: null
      name: mqtt-credentials
      namespace: default
