---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqtt-passwd
  namespace: default
spec:
  encryptedData:
    passwd: AgCbxcLlHSpmpV4ZgOiFma4uWOhJv9PWKmERD4azed2tMW8aw4zKOof0zFoabHLug0d6YIo7J+BEVY224HJ8IqiY9DS9CU38TOPzItBkAq4KKvgs7mCWvLWSXxaH5Al7GDRFkq005970vJHMZA/gUYL4f3w/u27/OTOKZz0jkxSxhGpQdF3gbaXGPHR0aedzyxAiPwLlDJU9aQQrpnlW+lBCfAWGmrcsJMg6yUwdZfyorTurEJxzssdsi8fddtKQht+YJYHJpAwXRLq+LU4hTR2CHiUYqUmy0sg17CfNFO7zN0Cgm/GFcBsSjW8lEx4AmqCTswVY05QIajXtsdDxqFNSvKzCIcq2O9eK+nJ9BTNGaSzFC+RXf7h4T0mUajNuG+fufHB9l1tFBPAA/AhuQUw+32B2p4vRAqrPscRDv+68JoOC3QH9ljruR0bnD9U6FUuX99gWAYqUNDOnNsifibZmd5DBOPeMIHnDVQsW9cEux6xi1DpJ/e8z6wkBvO8JqnMV3RDkZnvp+wSdU7nbICRqHyAJHJp50+Bd0MvtYbYWswK1uDPGy8mjEuIPc9JC01K3z3d60LGv5R2APjsKkv18XQGd+KQJkK1XwXEKsN/5aRc0NQ68iwSb3+YDo8XLTXPqDaZuTY/DG8sKMiFKIb1PARJoLj97dj7zI7BpCg0OXUJk+DFgqfARG6uW33FuRQI2DAXFa1CRzLUTa77/+4tHCZkeflQBhUC1wZZRwx9othyaUM7+hKA/clgdftm6lBjfk9VvdqSHPDOnqslZPVAiLxo5cO5S1/2rUV9akGsAWr6n7Zb8HYbbfNDfQyEohFcwufjXcscyj8IJfI3zPHH/TCw7YEYzfPEtEMuygtgt34KraYcUL87rHxsAR70AhOgiMiNs3yg5zzEU57D0Swoadti1bbMppQ==
  template:
    metadata:
      name: mqtt-passwd
      namespace: default
