---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqtt-passwd
  namespace: default
spec:
  encryptedData:
    passwd: AgDJbO96rUBenQY2w7UmYp9TMG66i6zbkCtIVQeU4ngEG/Gcs0MqpS5r29LyNZYsEDBW6VvmR+NsAeDGoi1hzHhPyFCFXjZk99S6liJ/HjZ6j8/ctjbiRSZGIx/MuRdbSqlyYJ6d2tCzoJtxXjNUi6Xbt1cfZ3T78FDtOSi1EUtnO95eNqHpBbHKc1qLAZORZx/zgpjTmPfuUXg0rBjcCtUauQH2Psg1vUDLKXJiS407pzKrXoECcVun7YPPsybA9RuNqgQx/wbabl2JKeyREgldBVxDrpCVxuRwt08hgTQeOjZiJ2KfiQrkpFf0GPHrZIfIbN/bFHKDQvQDOYw/uVGzo1nB/YOFVdswIk7g9ggzvOjrRQww/Vz+5JwLikzCkMisziu/9md6UTeWaWCE3HqeH/VxPtZEl+kOGosjU7O1qqoOLdzrNQVFxVJnamXVA99FE2RwlBHxddZxR6x0g5BoTu5ORW7GltsjxQZdTAHb5YXFLxikpC23oGWEDTETy7qPJzKaJdp2RmnQYAkYqKOqYd5DDacpdD87fUbITsVSCmhouBOmftA5amJ651Ot3sttBlm3DOdkAmzy/92vL/SresZykZJdl3A5AIzacGtavmVlYifbtfw1AApEZhk4yzYmRoCOfV693pAIBNvKDuHy1XCm6k+iNbB5WRLPGDbEDUdOttH0Dd+irmylceb6gShpdpztGdqJ9Sgb1ltg8CPEIWBnrxbUFpNeDQ9JM8iVIIvgWmxYcB2Oao0+75kU3Uj/k30jXVaWDnIjM5u2gb1EBRGnqwieaoMdFQmL+zB6BGFGnY9A1llwqwjdfSuoMIhcQ5Q5IY3pX8N2svMU4xhEMDuPVepG3u8FEwuV//+NPbelVA6ULFvPMmuul8yyA0jftkfbzKTngS80j406GThvdlh4zdvlvg==
  template:
    metadata:
      name: mqtt-passwd
      namespace: default
