---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mqtt-credentials
  namespace: default
spec:
  encryptedData:
    password: AgDMUW9gKiL4J+cw/8HJN1E8E+i1K+N2mlZdR7Pyb5PJiFxqufCF2BX3+8+togTzKRguIwu0ABlZZbF3QkYoc/4Szi2atdJiMnFZUlScJ3wXZMOSPUyEE+eewlZxQM1X7aMGYEmGH01TCU9kSx+06MS3Af889yuZxDMQotmZscxenNRCGmBu6qpSXHxJDKHNig9wWHXb03HZy9MhN4BVT8z3zbltCqTEhbohoAEJdwsl7yRoUVi6hsAG35EW3/LeSG33hDCNK40yioD0uaUmeDMwNJRT16veayBIdGGfKFAC+KnO7HOPTFmQEr42cDQXtI5SJPn3bVJsS3mICFOzOCw07gEx6DLKsavfVkr13nmlfndjWN9vEVVCiqDKZbNqOL3jYq66LNZkrY9x6AK/+3oVXJeo+0tyymZQi6ytEedADX20cGrh2MGiTFCKhomLEFLhWxnnQi9YnKuz0LD3pXP616rWJtnhkc1oCdm6GOpIp3gqDVOVmFrA0ph3vndlAWSzMDyPU697YjVJGQdXXIn74fS2CDyOTSkx6D/gk2UaPrL/5iZFQSUE67jO3wQYaqOAlEjzUFed5TAoS6HOuiyPp77GtUViLat+we3oIUkTkBYm3CGDxvFbgD0aoB8x/PhOEMGzc2s3iPKcxChVoEy46+OyrBWNn6NSPUSHAc1DYUUaBx9XUw1zKDPOK8A8+fP6Besofnu1gnGnxaV/qJCYlg4bqeY8g+XTpeI+ccnsjhMeHrBkVZCPh0VdHqSjhXyw0xB2o7s=
    username: AgDGWXq5p5YX2R7nU+e1up4s/SRibzh3IKHzUM9Iekz0L2VfyjnrAQZ4COSTH32R4iS75y69Ay4L3CyXaLXsKO+Q1kXEQYAo/SGaERMHqmNDamaGH6J8WmI89//dSQl60RmKVknn4K6AdL8bci804DOTSPXABNlv8pKQDUbBE0Oa83k5F8Oqi4g30pUvnDnOA/wfRN4SgIhhE279MLQrw2V3OE+VPhmq1RG6NyPPtQtZ27T1tFGwzM9rwH1DZcLlP7Bx4mqPsNLscRTWIbhIge4h3Ikv8uzrJeafjhFffrgf/AOWGUbWE4jyLEMiqiHPohWnccFIP+OvjAeQIIsdBYCIWtbvhWZtATxkJHL4ATHDotVbquZ0NvYi9GSdm2K6aZbqfXOxgXPLRtRJt5V8n/hNdxCaZwe157F7KXPpwSWFFY840XCd5Gic58Hh+u9ESHx6+Zx60al28Ctf9Kv2+9uKgx9Zo3D0Ao5QCPsNcJaCokQCNHFY75uhrTgB1eSiBCwiv6Oda26svExBc66/dFVfwFTPBXmYyC88qLE3wDFz90XpuJcAejfsP2H42+DXwjxKxzdiOnmqg+DNMrmdZFuIFM/eEIRtK0ejcuRmzkA5PBghNO3MKnsvbNtPrPjFSI+LAuE4LRfwb8lKCRPx+3Y+qLaADsctcV5GgyqtIyOM1HJsHvtxHnQ3/IxK1DHjy2KEMfesKmLr4LtNP1vYhNOtTk6v+EXW8CypzE+O4hb554vszoTU7SrCQ8tBPrvzDg1oggdticA=
  template:
    metadata:
      creationTimestamp: null
      name: mqtt-credentials
      namespace: default
