---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mqtt-passwd
  namespace: default
spec:
  encryptedData:
    passwd: AgDWLXC9pXdR8y2Foya0aI4plsXEbDK+3WVOLt+4SR1heCBj5TJBq/5fDc1ySrR1znW+FTGAH2qPgEY03e01tbgNLQiFM7jGhA6RqnrZcWTHtPeaXPqJTlSv9MKWGTtocwc5Xz6OMS2QFr/etjq00YrmpSiIxr2Gz5VmDi7YHlvJS3QzdFWq8avXC2YKmcRePFnkqrW6aCKMI2+rwWD4Shg1j4Kg+Bl4LFu6diwtkPhcWSehumBH8Itvy6n/FOgqlF0WZpAWt5E1z5BDxojRQ0RA6yQP6LBHMa4ouJkWzA2GOVMCK7K0nxw3Zq97UhE2NjSa4eHoDV0hKNC2Bpa4ZQgmKgyFSRjVUYo+Pc2cu2WbTghw+8nlPdSUie5C3Eux3EnGvFMVTvC6z/Y5b+3aqEzJlaLp7nAlCbQr70ycz/hwlOeOUiqLHehrqMocUoIbwj1NbQ4ZDrONwafHC49ilX15XlGgLdj8RKzuxyWpAYdkyItuicPbpqg4itWmQLodnUOSeCZU88Lh9Py2oc+5RS0HRUUohP0Wjir5BAOQlwx7rmFE+XVOI6GR1EyXTe94D36JLv8X1McKu78swOT9L5oXL8QymEvxRa0IAVbPbjadeoAX+z8Excsdn95OHVjjlsAdicrfl7cS8iaHDDtLQMrrty3hPkdksVg+JktCyblhT2dRA7OuVZ6UZf/RVpy8Sof8bzQNu8htzKoYf3g8ZkQ/ai8bHkNotNzNwJfJOBYq6Z4gMJm9JnqaU1k/kgT11Beznsuv1WMxpw4I+32WPXVDAQuiTm4fsER6vR58M+TGS5Di4WgwdiK/DKJt8rjlTapFOj8MNE5AAWVYWjMVXj29KAmFpeHu8kcHDJaqpCEGZkvI+rch3WKnFxnNAciVmHmKa6znMND5RwTe0xgLFzOkK1sUX8hWLw==
  template:
    metadata:
      creationTimestamp: null
      name: mqtt-passwd
      namespace: default
