---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: mqtt-passwd
  namespace: default
spec:
  encryptedData:
    passwd: AgCx+9wj3pj6Y67pbrL0YkI7hSMOJSIMZq5smpK8vNH3NoHFkPH2LqpMNUq8dBTkirku1b1yv21pyYokLrTVDAOQCYQcTnLiKuiuDW27fuUVkHxavffLSykVYSwiFnJ/8Vug53DZoIeZz9pvpMHevqgIPDMqSHuQhqYZ5dS54FIgmTRhj7hcg3ebhgPtogGpH9ftCeEXawGxwh+eeJFvOiTpJkgFZQV6eKggJ9I1fBKuXmeOMSfVQUKcKueZ11hKsaq1JZCSyLhMzRvLZZzyjtcf243Lq0pnRVD+s50QuZqQ7AGP8odTOV7nDvGxFnRAiqVNrgB2euqIe7RHbCF/8mKF5YyCe7BqpcSrezJJsAMTnm6Y4hvqBnjPdrNdl3FGnnmr6nR30XVf8l+GPY6mbOy9DcsQ5F2LcxphTbcjAhaA6Esajo3UDBDLiMwxpOlGndcwiPM0BB1hQo+nkIJ9q6fRiBe73PwA/0zCncff2k7LYXqx8TaCsrUTPTkIGDqysxF3RWJfySs6Q7U6SocTYAolwz5wNb0CXcU89KuR6K4RW1zC7GqtQ57C808iVr0QEKMnivaNSCnJQZKT69LFo6UW+yqrOAgbBGtIQxo2ij2T3roD6mqf5dt6wnE0iNdZGk1XROtJ8s8ur8YWXx64OaTXXuAmbPXjmxx1Gque9putWcuE1u9TX2eX8CCjm88sykWiv58uoQMmtymOSRddTIso0DrngcjkVxZvnY7RAKEzTrR359cpfBUOTGX4AJfo8QYHFgq1L91AaQu3dXaTJLu8m9mn6Ey3tx5DKzXYWoev/A6nj8J69jU8mDRwZxfDkg1x66co78z6v/4X0Nuci+GYgYW9L6uEi0x5/+nFiaf1iEOyzaedIatHplOIuzYHCWHXZ5GEkgCevwigf42bJKEMJzSyGnH/sg==
  template:
    metadata:
      name: mqtt-passwd
      namespace: default
