---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-alexa-secrets
  namespace: default
spec:
  encryptedData:
    home-assistant-token: AgBlUDYOjEuIWyq74VhX3VFWJFCInh3U0x+g0TjappLXQQUdl+3Hgh5p93cyivERlrbwY3m0ZOp626VBSbC4pqrl67uBISWJrnfWmZrP2+hnSyfhWkenSEjHWMwDEjSFJUrtCwEyCmeHI1MuH6RVVCt4a/yXMY+3anyuQy5VYNF5kvyh5ZwcEJouLCsIwm755nlvhUvMwuce/5lAUJHlPL0wqeatc4gEyz01/GAQpQeWutRqfcmNvH11Lv2f+8+JNVJ0aCLaIbDpf0aXKLcMIm57PLj+EGRqv3O/RFpE6kk7rJuIEdgeICQSU0Z0dRdbi7Rc0NPYSI5s2TNG/ULhebyYVQv5tkFnQSBjw7EE2hMtxjJP0hpnijZULgqO8Wb5i/w8ts54O0UK2sEBQPtgno9htkQ8A1XuAiJOkZefXP2nR77B/1DzZb2pZmp6JEUEXDCZ0RZI1UtpH647zqwoJxxsOAsrsimqAwtlvH9qCB3C5HGXpbyDfc0k6m7FO+m2AM4UtO93Uw97geCau9nLVuQb8c1xCGOnFaxQye26XdgkvatE4EAr1kq3xzaJ1rDU1b9IHZM8Pkpc++9YnZeTgoUN3fFuHegKftVB3cCa/AwAEIndRlWPAVyTIz3N/tEn02rnEZzpbn5/TCGyzW5B+4t29PvynwQGuepFZAlkXkLkXTQBj3hWVHQkQbtf0J1GjAPyZ8Vnb/jxWxSWYoXQ7yz02lGFlOi+rC4Bm9D6EdF/CYmFs/UNGZm1dOFy1oRmGxnLt3cjCDlKVBeRvnTne1+xll565gAHHa6AKun6M6BexE19cdqeXuHY9J85SMLsA9a4O4/OKaR1mZI+891HYRDknXWGINm+8SMHB5x/Oz700HDPAw79FN3csFlloWgJIwBGky60XbwfWLHNxosXNUhnbCqNx8Fskij6BR2KwuB6FIr3aweHmGg=
  template:
    metadata:
      name: openclaw-alexa-secrets
      namespace: default
