---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-alexa-secrets
  namespace: default
spec:
  encryptedData:
    home-assistant-token: AgBOZtJ5YBjT3+etKMHbqc8TD/5ZzrtmtJcs1aHTQpjF8nEVMHHZNynEuVVfYEblvkCR5KtpRaNgQ9YE5WrYA5Nb0ea2IpCR3OSjgnEW8Bjv3lCPfHNt7bVljvj8YAIY9qCvRkoyjjfZOlQXWGE4S4zxJVJKlpZsImB/MuVHg2gOd13IVN+hzXl2hjCR6h0ykYOd2fbVQfaOE+mBuvGB95csSgRKHcrRgHt/RQGyCki8PhgcfaxpqAEt7Qp6S9ABVBhe8aW/Mn1hVuDie9M+5mp1LfBuz34xXnL4HjzY0QmRBKyMgTW93IfQnFOVBpaJgbmNVIG4WJqEtafgHulvkgKGYIfmwBoqAQHE36GIZ5fO4d8j4SnJz4OkU1UL8faHt+/k7fuE/EfiLgkmEDBHh8Glu0qnXrA3b2wsmNdioTYuQwcJVVAEbjctrI0CVXS4HrLRhWcs+ExfLUaT3lYM9hb0ij2Rzqo8vZRRF/htTRfOdzH9tn4AzDecQi9tuNw2AURDUhB1hnKs9M3Z86gWXmPqA6kASGq+lgisUKW/hglWaRXxypyzX1gcmbSIyUG5W3lai6sqIB09ZFmeMv4IYJKeO8d7nCgICJkW6dtf0IOsN+NuFALwVUgVIARS3XNuGDLvppqvgYxVgCjdw9gS86ealdfPExKxKhTxiRd1UK/UzLnsHiMcK1RrqQjlzwLC8lgtd/NYLl+wTghSGrbLX39MnNTrhOEV6VE3CXGko+1e2rTF7V/5ioOCTeEuA9Ik1fEpKEjYgMzJthdjBz5vC2U0M3sq7znmLCMAH+jF4q51dTBZEjEHKdzyM0Vi9+7zfcXANd848kJcXYrQ65Qkx5oTOA6eQT/v94UortBj9AbRVHI22pBhTL0Al/tPdNFjDLflJJm8XPovZ5csE+qNvzodYmtvLg9FbdTpTfnwvCtKQhZo9AIfNUs=
  template:
    metadata:
      name: openclaw-alexa-secrets
      namespace: default
