---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-alexa-secrets
  namespace: default
spec:
  encryptedData:
    home-assistant-token: AgCx9mWEVCmL83zMM9aLH3VohvUzqqUxj2ky1lWlAVyc9MR44FnAlc8OFj1Ht1tNs1UbPSa1WZ4fFHBpAjugeF88h/eKctwzCeod/TxYUZDoZG8JOrAwxgEkZA8T7/gbtetN5wAY/D/xBabTCQJuB5IaO455OOXcf5AU4Bt7PoGQ6iUDnpN30nnTROm6uEAszxUX517hGrNSS8rcGss46OsD0Nhq39qbtMy3Am37Kt7zsNgH2n7qTgtUbWwqwOVVheDZfgv0/O6X7FG7LmKJKUK7rJR+FJh6nbjEAtnbhhd5rZWQJ2SZl0eyHxI0I5ZEC1ehpBnEQtMx5wNcJP7/mng1BYfBqKR3KxJadDsxgc9k/WeL34xT0OK2EJNETXPr5NoT7VnimFVD8L20eIKsmzE+gI8lKsGplkd38flp2MoBhALKaD+/hEuWRsNQc0PDTpGdTrhtOSb7zwvtzffzsKCeVk4OauRzt0V7fDUGn9w9w8Q09HXiOYJhrQlxxu7MLnMYwUkmM1GxxtC4PpIbhw16YBpqxdo1Gz23tGSmp8UgX8x9B2og4wTnXkwnRy6tVfJh6wLCmE6/0XIDADQCGkg+5FBn8z7mSWIOIAwfv/29FTlaJvaD2IgLC4Kw4MiNYeHyVvnQjgb7rRAwzTo0BJJy0CQS0PMT7NhbhzovI6BGHHLPGifKAPNKoAanZzQiOK9yOYz1zzAXedW4V98Xyyl5WWi4HjjXZvfrDdp9qAEtFZfAGxHgK4TbkO0rhAoN3oh2J+RIsQASNYt3W6buNniz71ntcYy9D9+59rNfuWjmOz66ePKp9M8QEQcayYj8cmKzyZE3x7k2MHkp4jzYvfDcB3tYeIToOYPON2TMosy3tEYfn/1hLhaNJ+yq5BRRO+HIB9eZ8bZwYFNy6WK6W4Tq1bWxmb2TQSrCFb0ceIHhynWclDGrnKE=
  template:
    metadata:
      name: openclaw-alexa-secrets
      namespace: default
