---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-db
  namespace: default
spec:
  encryptedData:
    password: AgDdgP5tR8+LgC/nD/R6DBmJXGwkSfTxprgeGRfebhv5Cwss1wsu/CImQ4FR91XYjaPnsmGEJZEkL4PiBnoTjYBubyuPRdqxqbBmx7dz09u0645F0sdZBIuYf8NvMEejE7qLhcpW/ADAr/9tgrhK5byMPZSKvS87t9N9FBpY+4XWvqFRjz42IvrbLe6WIF6T7f2cYzdcjgifraMRl7NI0RIWfZtHmWXh8Z950iVezqiwy+JYg8ZqQaTgRzrbvpvwiy9/09Id/h4MUOsdqQWlZC32CIcZ1GpTj2Xr9c7H4HUk50hyEIEoAOJqYHvyInZmTdDrkNtNWLWzYYvKJtaMnxjvjF7qmolSa9qCNWcxdZ81MNcefe5KjbzFcLSaP0sPon1eZXCdMrFqE5pqeeElAAXXPUn65QpmMT+TBRv3N3KV74iM1pc34Ap5hjJkQUx62QvkwyBYvBYZL3SnqQ1o96Z4BG0+I5YIab0N+Kr0neWILCn4rl2jUpWndMG1g85ya8t0+kW0+xf8ym1Nmou255kn9q8XAel4oXaA4VwT68fNxs359pWP+vS/2q9zWXaw06kLcJMaVoKUBwwHcQzhoGcXZq9sjRpZT4eHB+qb8Jj45j4zYWiqmB7wtDBUUVgE3WYBw3cIcv24nKpL/lU8G4u+THZy8+dJAOc3ivwP+Qa9NFG71mYHGuS3QvyPXtRlbtTd3XIlmd9q6YdV8E85x++8Vypi/7MOqhZx27xKyjw=
    username: AgCS/D/7Uim2AKmjanShYctqdvGq767W6BLrIX/6h8sdAYh4PmLw612I9M3ZRgcNbCJmfc0e1JWamftKBXHu1aW1JopPfY9nJ+iZHIsmi0BBbZlt4AqD4du4xK1SkceTOv7+O8RZxHg1vlGCzj+v5P11Hk64W3MEjq56Y5eSX54AYbCTueqXja+k4v51oBht/9EobgejcwAAhbh5fRtnJIQxooZMBZPPZ9WQgUn7js90cMYT7gY0xwb968EIR8LFnJwnKlkVAvbHAYj4cghY7gW0gt6aPI4uE3StSM9WSKWSo5vmdZKbqdwXQN0D6V8P38H/zXx4ssomuVRJtVd/IawqeOLNpdr5GgIkZHLhxv3RuleamEqOVGQDV+xnADCUhDWJo43dpoH3FaIWOM/hzBX3RuHYn6r4XdljuGOIHJ7IDZin3y1746P0JGNepMICCp6Aq3KsvBYwvjcA8TjIqwoYhR6ByHCkqrwncuZhAidvlzexQ85oeW7Ik7eoeIRT++/tdp/ZnGzuTcVTh3IGvs1/yoYgRtf0QDqG11Uk33W15navUH2cVbU38httbVn7Sjmlow6NgLIkvHCB7b7m3/vXD2MYi1OnTlxLofztJd7h/ZZnlIpNJLiD03a72Pab5Md3erBb4pThg2btFbi8MJDi7PmFZuHn1HvjspA+9x/PvnpqXS7KtOapDWajuYHM61udtYrKZZZjsAuMyuPoRaL/mFBUtEOHeSWD0j6hwIE=
  template:
    metadata:
      name: openclaw-db
      namespace: default
