---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: openclaw-redis-auth
  namespace: default
spec:
  encryptedData:
    password: AgAuHXAWUAzYAv5rF5C10VY5gGHV6ZUm2r1Bjumq4rgyH03REDOrPTKjGB35cNC+obRXAAIf5CV6p/SrXVQ+YE9ZScCHYHYvABCBwfqdGKxZaO3af/khXMZtsRrAKobhsdzHGM55gSf8k0PdUmdCcr4mU5XMIOgbyOqxRE0QmMlmbRPYrq0J5LdhILfdfGOLmSyFnwA9eG/cuMxxgGUwhL3jO3j8ylRGPTKEBh+ELBTQ1ZhBNokhkIzlniEZoLRBldC37T4HETn58TCvZzqTtysv7DsBWQeXO1zjLUTSaX12goJrYo3C0zXPBYj16YT/Ctp+e2RL00E+adWpOSKRzzfSNux0IjAH1EJ7GqVHKfUyADUyMZ6SynTeYNaEANIeVCbkZNKki16JCfs3RuWjoHBdDY/WDdidqHsztF+RBo23EgzELrEylr+4qiqKmBec2qaWwkaw0vrhsRFN5wL9rjCwXLHTTPXH8he7EudNFOEUeIARoiXOvGkcEFcjebtByyVJtLYXVo0YuGN19Mk0gQ4jmoLv8edZXDdiCP3Bznc1s0P8Y2n1PtxIZmDk2Hb2wTEBfah/VjKCQ8z20XhEbQeflhiN2byUvMpUFFKWYSV0EVDbOpW5c0eDM/DxxBF4Bo1uT/Ppy33ZIKtx4AXZX0Ay6qMoQOaDQi5EyzFmeOVDGNzXcjyOmb6B4yJxSpobiTh58mml2GTrKVZqvSxu5+B/bC2PpmHcpER/SmpkPzY=
    username: AgBPpphEEN2Vi1Qpa8xPl2psvlFbghVlN/ckyiCNPCM4Mztbg2CBH0DYiaPqXtMtRTl8cxmjskYuwFuDrXfWG1hmsIi6uA5Bizru35Z6g0ElZyOqVfM4bzN5MxY8fbYenblzGHLpJIqvyhYzsMJa1yqUpay3OArUbrd0b3unl9pmnLae0zn9ulMOmcgjN4BO9wjma1hMVuw1MlZBRUtr1C6QUrKHZ9JuTQXDd8Yml5TkJrjINCRV+njW2dOVPi7YFK32vEqkYMw6j1QCVT4vz5BL1nwaVOHLEMfjelcCRXl4rgtPSxY/z9xFgSlYEHDsZIueYAfUT/eM2PssFxo98DnFmWbQOiXnqCC9l3dIvdjAKtdSFC1Ooewhfm+a+6dKcd4425on+qO6Ou4ewBzsxGkqapz8gDJt4K3eI8OWOEnFALcpEEokgwqLn3BfVngLse/YXyOt2+T33jVpyC3Jbp9PJfGTGdj+51N4I8tvJrSDqzYD1mP0m6SHgVSdCF/4p2xCOMqCe+TEsEnKBeNpEVkD2rA2IoqacYXFJV/clDF6mPyHkslxABAWBWPMUdmXmAEhvikly6dkpPesGPbDNJMP7b117INO3HTVFhgUq6+yVztdWDqojs0ErCgLLFGwQmItn2jItcu0ZicbaJPWSQea6J0EgUKtWUURXF+GmJL/rjZItBp34peBzl/SVchLmwmv897ZdZnMja5isImPEuNxavk0ZN/gZQndbia20eE=
  template:
    metadata:
      name: openclaw-redis-auth
      namespace: default
