---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: playnite-web-credentials
  namespace: default
spec:
  encryptedData:
    password: AgA/qYXzCdvG3C4eJkRuHNLPC00c/mpYajGNs5gPt/jYcesxCLvbtc+wuYBCWNX3yMe3WFsDeNywNEIFU4OcfHw6tqMXjUt3NCYiXhsaY9M2edo3Ub5Q2xM6eQp04r0NQz5dLBrjAXv+LQEqEm2mW75n4LX4enVrSKu/vLMk7p3EQmtn6DwdjmbSSt6H2fNEPLdyTlyQSoSUHri0E/r7XExks9ZRhl1RXOGIfnXUIqNsObHLzqqXUbrzAd+rDs6iVI6NFmHepYX3B3Ge7C3Y3quearfF9uJ3zY3l6KfDfTbdggMWOMH7WkuQ8SKfW+Znz16p5KiAz0B24XeL/uPbcWv6gJdS/nBG+kERyQtQ3V2y8ajVK02BHUGksM41KtXTgHJHWSVc/O7W/KFqdonMYSJZWbeBYCbiPHtdkodZbaC5qbxy+xOFQKUxt7u+xzyQrrBnQI2tEmP40DeI/CIOHeSzTIUvej5Ms+unA9VeIa6AQLBRuaJp8gLkBvgkaH1bJc3Up9trqXKPJarP8VM+1Uecav7BmFW55txwSLIiguv83MRmR4R8NwEnDVnjpmhdKVG+eh4+UxxWgO5qH8NzAfzX4NKL8iT3dLa4fZbRXR3uFL3han1deg4hNY9Bj8XcpO8dRDtA61TIqKMWuZI+ma6nl2oTTIPBnpeNRG49RfKmsHlcZjvViEtb87wRe9ZmxHWnykIUobEsVQqI5ND9Ybr3MOL15+JGZCwYl8Iq4Sfh+aBBdBxGE11p6HhWKz9e+G1Y0qwOMroqmDMYzdrv+KhdUtHoUfTRVOc=
    username: AgCDb6oThiioGlfvC/Dow/WTaPDAbgpOk+wDdlGvi5OkCmPdEJVhJc5BcQGr290au5sqLlfkHSYVeOjoTWpDoYcIYzcu4PSIwnTMyn2XutjpM5QoOLE9onZbjLBi154s+4CrwKRTjg3rOid0q0fJGkskcJWd+wF3q+/R4R4wxgS9kmiLLS5edZI9DbTZEozaBp/W8wM2Qzr17qKoZDp8kw0TclKoa90IUTtAtc+1sCxMfTUcEAo7NF+hFbGqwyhx7yB+HeAl2JCpifB8Kx9NjTLyaeeuy2FzhVB3P0RuIvKG1kHQF+sAbHv8Y3PY09bzHSTFksLNQxsh2ylWJIFKBQxlVDJ4AV+CVzoAHY6LO1nFgN6vruwNfgLgX22LGyYCFx6mdVyzcp7BhguD8Thk/y1Q1YoQYvR/pXhau6rl3wHmaBwaCC3TMNe7LB+Kyt6P8s8vKWPwlG3GNCnJ3+2Bryl6JqXn4a+DHJUbMHeM4EKktbjWVxl5MP8FQiVs+ZQjRXojm+XgKpC7Qj/5iwDHJ9HiPvR2x174VHgRzeUAlpTEavC2CpqrCECDMz+DB2j8B4o1TX8Ws4lmj3uu7Y9kEp1xl9ffecbbDxv0dtKjTg1QrwE1cMPhY3ZtBYgDjnTBuepjBokEnq7BBgBljKBZmcAVN5ZEhQzK6CPPrafy1zB95BE8AFp63Fno9EUZFIVgAwXgnSqDbbcuLf+en9FDgJVXFSd58MgGEaDZjk3nEHrcry9WZHsbsyYyCpJnGbjh1TwJ+5e+qS7xxPkJ9QQymQQxSFe32YahVRo=
  template:
    metadata:
      creationTimestamp: null
      name: playnite-web-credentials
      namespace: default
