---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: playnite-web-credentials
  namespace: default
spec:
  encryptedData:
    password: AgCOp6xaE5JeDIJE2sz9titfS/3w0V2e6d8NoacMCXVE7+wsEEM8sLCQn6bquR/UkUduBZ/r+ypt4cbzKAKCOAIeIyrXiWMhqVEkgN9Pa2aTzx+DDdyaAhUm/0DzZNFRL/M68tAO41gTl8pfMwDUba6GLpm1FJmtezrdtEDbqyg2rp1k9IU4ImE23xisL2Aq/k/NB6Enp3+I3GN5xcCDujFoC/gx1v540hNgV0ErjDe4/CzbrI+y82pCf66FrHZ5orDPedrra0FtU6tMDxpiIIn8Yj2bpr//LFKA7HALcMwGv0OXpuoUR67JdVmZFXoi123LPbt2dVNoaHvc3PKRi9bf3l2RbJB+xjhDHt0zSVy8lP+ooHvkQW4jXQOS1gtnj2ezN4dz1SHclaKg5H5M8SQzCfclnpOjNnZenb/R7rli6mgJYmnQQby8QSWDj+nZPrt8h9LgeVRtlgXv5icA9xUp8siCex1rFMC74FpNcGhsy2WFDRixLhJYrdspRe93Q+YnOh3lAihA2GvEJiZYfmPU7ffwcRR7n5JPc8wnmjsilLBqbvsbvmrHfkXpLJeUU7ODWH9AYSoqsNphbaHVmClvZaiExjUwbVot4W4YyI0Bh2Fvi1jha5AQ+nUYTojd/AFhNO+RuMBD/4zWe1fxIA+NSQZ0Y7S72tEQBEsYYz5RPhH43sFt+CFYL/VgrQWHV3Llq5KMPxssNTGhkbZM/SnA9v/0vqJUxdtCgCogznpRH6V8dbRifF0gsP//ht+qwx1GGmnFp3ZbKQnjQZ7GnjBUm5+KoHPg
    username: AgAi/Kwj1RfWwlHRdsvDBTlSJThmpXApUQA7Y1RLPCZT3HwaHMDck5qH6vhXQ5fCfq22aSlvIadSzrfhppFwzwq25+zrYpLPCGx+MpHKH5cDeLEDYPch9xh+7c2YvUn2v1wYmDWhxKjzRSM8a4EzNHo598V0azHtKuwPHw+jKfjbb1q4ZFjaTo/uOKeOBOc5Gy68nH3lIEHZ80slLO/168QKezN23ZzTzk2YZPs5ef+QeRmeNpRAUO0jQGWlk279SGNQreRXsjrabQ++az44uymXymfqWDKS4fZWVSvuF7GkGNwqqRYaxvNiGO6Pq42IeJuE5PqXkREWjNeLxPQRMHZURMbkTDtKR35FGugCCFfcYt3wnhsdakrMy/Bxun5NAjhXSV8enrUlwpLTOkn3rrsoESTxoONYJy56GgWe+835I8LhkbaJd01gCRo4AZn7nSrb3oWqeHyK0ioGKxdp7CP3gpOoge8ZuEL8L+KeVJXkLirkBtSgJf8XUaIY5EbVm4ZOSlXIzxztgAcwsbwHVcszW8d3S9i/5vNuFcDo9oTTQCwEu/9UjCfXPx4GuFJs2K9VEZebfr2ub00egmP6k1j3PUvbI01sxprTo3q7C3Gh/YjiwESHwONGgx+MiXIPLl2ESIkwRscfeAlZycwVdmlahHg2nJwFeK3e2xNjJv+KmKCg1QxFVyrnquce6SqM79gD797il7L1GM9un6l51lu2HLgkUjgaVzS+wbwWxdglWroBUeDLwpOMVobn9XYWxKCL/Y15J2zHNW+iGEAJRigAmXI2On/m
  template:
    metadata:
      creationTimestamp: null
      name: playnite-web-credentials
      namespace: default
