---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: playnite-web-credentials
  namespace: default
spec:
  encryptedData:
    password: AgC0u93Qa3J0u+M8cTgumf+CiAc3pwCcqGah6fdeVUcDP8JIa1VPX/56aGrk+eFBJhGGKa0O25m8R0MkddfjPGQIGZasPTP9tL2yXRK5TY73psQr8EW3DkVYKWx11vI0NE4V/bTPa8z4TKRS0DODiPeexvj5DiVqWEjhEy7SNXvdDca8ErdoCJplEpSarF2Cl99m1FjBbt2XaDuj9Q3rnfL1YTJPUgRHVwTFQh1SLkNKvLjHHSM0i5emIcsGM3KG9L7yIP1qbuRJj0Fvo54GPQuNamP0Pdjn1s3dtYj0O3UoCWSEOHOFfNtGwrog4nEp6S8vBcmgYHQ0YRgleAIDin7ZKuDDpkvRkQbctCrJlHDzBCttNngBRAIt6RfoN4p/UkcXvpwIX5OYBRYMl28SOiVaXOibkPOPflAS7BeXnh0MIlO0Jr8AOv0P4uAdZ3dbQGCSPKj2TIJkNC0IIcJHuvH4lV10K9yK7m4Jy8RKOSlNBIcoFOvI01RjuEsAmF0P3x8v46eB+4gBwff+hJwAM28yGWWOE5Ajkouxsy0etJXPlKieJPmHUKLJLhs1ltjc71KmBhFlHYczQ9eVl+fYv/CEt7VuwqCGCJZtjG24skjX8CRV9D3zcKth67C3BLTkvttWGjcGbZSE9c8fcIDpO5oxdun/JduUhsABFIAboh4U+f6njKaBBin9rtuUnn7097+o5s5pWGlNBsA/+5MBatVChhfCRK26uNCJC0odOwRr2ZKZ9viA9Nj2F80re0Tkn61sz0npFmc0i5RwtemVvtiIZNKR0jl6fI0=
    username: AgDL3gTF68bIV0iIIbP64WjN5ZQ/KJNmwy3RTe76ZRzukhi9FwWGK9q3PHnTUhq8xEUeLlWnpmnVVDSMdS/joC8xddv75AWTapti6abOuIgSM2+iPZBDUuVniCiUfuoyUarLSTE3cuueIlQzyeBKo2HoxRaJBV9pshJDjvkqsYfUNpe0zUOoY+piGCgqfJJ1rf2ZJQ3fFwB20kzWyNXBMsllso2jmr1mOlqavXOK02D/lJm6S3xWFFUR8c0odD/UwGJMGOsPyK6kwfWtQcrJTWunQrCHl+Xq02LFQuPXKz1i0yEDsjxjeor3/a9v1ygPhkIFNP+/UFHY8T+IJDb/cCwtO0DgOBYjyJTlB93B4l5f9tT3z/L0jaGaBmNKSVJpXJIl3D+lDAd5agntx63E8DOp+PePSE9nzH+DoYmEARYRshaPpjMKo4xuwIyIXqfgjIgrZN75lPBKFc1L3XDwNUSQAsSBg+UT0T2XW/F51XZKkoYPhGlMAn+tD7K7hbrDAZ8CN/4T1w3saGQ4itXVBKxjwdyXO3cKruU0r7rj3fzUW0Oel85U0zN2AF+57EfyOGoVBNFALnuBA98JbJuWhedn3Lsd/90wCjordRbXlvIW3wV2lz9URFnOb3p8FHjrVYk0LVq/scylCYIKjN7YoQHUHZEPa5+F4ePpsThcJATo/i7hwNyPNryh5SpoO+vxFuKUHcqREUqzq28MsoIa345FXnG89E4IyjAFhdKPrahk5SsZ8C9w7D6t0WCW4DXHSKGg06Rw3AV3uEBMo/vf8hrkvwv3E1bbmtg=
  template:
    metadata:
      creationTimestamp: null
      name: playnite-web-credentials
      namespace: default
