---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: playnite-web-credentials
  namespace: default
spec:
  encryptedData:
    password: AgBrU/yUJ69j+4TJoINFt+42Eoov48Mj4nrCyJX21gH4k2GA6fyNhXtddECc7gLfQBoASS91ayQFlRZagJIVAEu4Yb66EwjrWCZ55suzEJe1TfOrCRxQ+0LJyxbfZyIM7W6T1B4bhS03Rg3ly3VAXczwNg3eIkQ1jUstAC4QooTQ1V/lfT1GZf4qWKN701avlTVspV5p4n/TdRngd97OerJfKvo+NeHxOu6m7pUc3IFyhYteNa2H1JVUlsu8ZRAmYgcZJ/6+85NnFsWsKc8U+B3Mn97BdAQ/qzpOe1d6JiX5qrLZ701z1RvJ+0C1V6EOwplYlMVd66TNZSWZXc6fVOR87I8DJZSXRNqdsc0sOR9kOFHfWbBapCtQ7MMDCAOtNYLbMswIvBfSLAo+RCSu+KdPlO9YVppFXSLD9PQy3XdoGzGuxXw+lOSZ7aB31xO/Dzy223CKvT2RRu853etmhZ/8Yo+sWdMctm1GGPp+J6291vpwfiYB/tdMluPIuBI15Y0zj4/+AXjSUfv/wHyaOGWuG9pzWWgp3G5mN+PVPM0FPC5MpIVYi9GNGdh+zJoexDhoGu8Wd89W+oU+oDv3f0XXLDYan0iMU0KqzMzNL2NkJ4/FKRe2tD4Wah6v5painNHtpRSKdlPesyCKiKF4xib4bxqv8lyJbS7rzjtsOzwcnGkE9pg2u3XWOHM7KzgoJylwgUiDItWunf38ghYkyC3/La3IEk7v/ZzgAd06sNxSpF0BSlrPrCMWFbx37CQkcqXrbreD+Q1q9J8gEWLpXYTKaO/lBS+B
    username: AgA/LfyR8T5WEkoUi7XDej2O7eIKmnDk9FZDG1Ugc9kzl/RW4KjozD+9Jwtj2hNwFg+V/5mVj85YLvj2rTMDNsy14Y9UXJbHoRMm18nlaokAAjd20FyDhppm7Prvfgy8ZhhVZ/3QOgHcDExLxR9ZHrfU5D2stlYMVI/LTCQTNGEjFbbud0iz2fLlBtSSTwPZsh3mfbkSLdX5DMrNpcg/kw3e9I+oLOmBwFoorGaQC3GrNxW/WQQfQloWtw2jeU0Pl3hlMxOZWYHyGdCBWjTCpOyyoQ3ono7UVH3RSvr2bJqat4RWtrBP7VXAk449aFX+VCNsVFlSUV6+qTJ5BUAR69Yh5PLUy7CwlE4m09v7DfJzukXeTCAq15VdbHOpBjR5aE2HDtvmM8mrsUrddZL6og0YCJBl2DyzbCvyX/7um+atBkOytvs6OnxTfIiGZwQlMaw1+enTymyd+yRZGQb6fu6TywsHqzGHvgH7PLISWnaQlfbH0GcgAC57ZE1clWJfyYUAdfwm+pUVC6wjQAbRvm43i+AML4hSPZTFTiQ++r5AOfzcqpEArv2S+zLXUIUe8/d05SCjSv55jZBv8NdweXmCbUWQAUKlI3DzwGA1qSavv2lSKtVKAYouqoAy/nVURHhnp3V+JZ4z+Q4ZuiqOv0Cy+VrFvA5N3mb1+SmEbSttzfk+n71WKWnOSXVUcsFoZ2leUfrVSI73uZBVJZrCo5p9Rb1zLK3A1giCOaBA2DNsu9RaXz5EQzVlJ02fH6ZmP+4Vp1lOEYpKWI1o9EmPaz8QaRUDe0kB
  template:
    metadata:
      creationTimestamp: null
      name: playnite-web-credentials
      namespace: default
