---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: psn-accounts
  namespace: default
spec:
  encryptedData:
    accounts: AgC21XM4admJ6lyxl7fsH2FpLFeGZbwLyXRfSfEZT+iPfKFSIgwiqFArELc9KT7gg+I6ZmfbbUUW2bM0OFmNXWq8WSd0QzkccXtmI1P2Qh6XbDvD1Q+c84z6AOFZA5IdH2iXb3XHdBJF+7M6zuU6bS68OGOOrqiac6TJtnS07DlBfdDmmM1xOx1+KMN6lYx9jw8c7MpEMxezEVTUb2avz2y3sBZqlYt8qkAwSIfLsJ6Sf9pGX61jlfRDofbCCuSA9S1sWAfosUbddZ0k39KrYEANIqsC/sMWeba13+GYX6WkpIvWolWFlDFvD+QITXKhjTQCecGRIMvqHwama6ddcL93ApBMMbyi6XZ2uEyiqtjVk0UWU3Y6u0am9Csu9hB7HAi74ZPrbuuaOZbVh11jBT2klnwvh3Ob9EENbNqn6t2KpZ2M6ELbo6LnJP1swkBKXNVplNcJye6vh84qJNeO0AM2/PeLrUTLPa5AnpPYH+gFcQ9yCBWl0AsXldt5mViX5XT3SvNsrJ6U5MAzOez85N36Sp7vGf5DU1aT+GUn1OrzzFe82WUZd1sYYtMe4zN0sjePkyPkgQvml4gu0lFC6r5yI0vG9e9NJrrwnRZ0yYCPJ45G954yO54mpmm9Tkx02cDZggCD/23gdUO5pbmCfl1FLKqiIH/TSHne7SF2W7ut7tIqgAWm7Risc9KgCgiXwX2wZHuqYiMUFIhqGSrBVc76J1ajrX8A0xmGb6jDTVD1V9JFLTtOcmGW786/nhgLGTKQ6zyMgrGEHXaNUTI04w/z1gX8dCngzymAflyOUZnZI03U6SMcs/JR+/FWWbeStODghzxwQfqGtbc/44Q=
  template:
    metadata:
      creationTimestamp: null
      name: psn-accounts
      namespace: default
