---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psn-accounts
  namespace: default
spec:
  encryptedData:
    accounts: AgCTGBkte9kLMl0OTUTpt24/frf4iplup9Q/W4heekmYwc5nZv8olhSxWGngEOdChAddkOxj1NxYhFMzbBVzrap2IL/M6cIhXoH1Q+6sHbTk01EmomsSUB80xsjzSKcJoU6I6wuf4V/aIaSyV6T20P7MwwCXW4l4xxKGbDUVChvpTqWMBj0A0fD6kG7Uu8VEOP5Idy7lFtJJCRHB8Kw3H2zpndiIg5C/S5k2A+x+/iBz4Ozdu3rNolcxgDFKIw4wseruF50luESuUEUkPNIgwgmeexCZfWuA7h6V1sv5yWhNIbf/cDTu6sErheeOqffi1Jqx5z5KpVPHJYzPYadXYeHrMT+JHDWjSFlI5GpXhbCKsP0Tl3cG7ZlhGXd/Qx0J7CPd4JS8Q1WvmxhEYkjNwSRGT/FKq7dp67mGSKVGbB1FzbFly4ATtFMPju2gF9F00Sqaq+rMIqIUEFeugrpyakzl0KU0zrjfbjX5S3WVfjsSB0AQKx4c676nto5gbl9vz+1cfz6v0dadmLOHinwSaPGde6iuEeYo8l8/srUVurf2OgpWYTe2HvhkddALDvfLAkq2lFfnBo98gxL9dB4Y40JAbo3PsVNKt2N4UX7YijG8K+gb9wwQT6tiysrU1Tdo1TOctEuXYax5E2nOGynVgvyqsAlH9BN+WILqCBesLNPsHYDLNXKERys1Pp3tPYjlVeZosyDv6e29f3bLOy920PruFGrnn/FH0+/kEqMJjDfVUkBD+SM9wc2CtVE79F3EKlbNtpCi2m6h3ilO4uZ5xPledJsT5tpTqk4DFtpthOjjNQEvtJ2z2NOACVkkL5xhnetSsIVdQ9az1MnmKkk=
  template:
    metadata:
      name: psn-accounts
      namespace: default
