---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: psn-accounts
  namespace: default
spec:
  encryptedData:
    accounts: AgDMlOkzZEcYI7pEWtqXXtZCGQNEOsoEOu6S7EJ9uRHM56Sn8X50ahjfEe4b94wel7b5Y4GqjM1ybb5sgDDir2DAblliT65oWoTb9f21ap8euC879u1gk6k8iHT6RWeqbcbmREgCFEYxoXrQ1cA0oDpHrOa4JVmoHLF+bcehV5CjFkgXxl4beTOLTnzDY25bZtOAqg36a23xtUNu4qDGdrDRmogLgnuN7iLQyFEwPJF5/QhFvQe7xYiWyD1fH8spx9Mk0xJbI/Ol2SyfDOeMRKzOHnMCQM2EYd0NVybtrmLksO8UuqTwZSXn6XzICEOYouKAy1gLQ/JJAtaiGlhVvu015dHsawGRI0sXjzZbKbUOV5ifob39ODXyFLtBFkxp01LP6ErxYX1UUgiIkcBrmEuiJZQF2WbmRCeppLTetCL0ojRijtqSX/SIubzVuI54m29OAj7hYHFa3EuKj41+N0ocDCT4RxE819qjrfBYx8K2NyI0GRAeI8p8q6SXpJY5foxaHhYQYG3QkOy5SmO+I8so+qzOWgKeRVTD1ZlfP+Mkhp4Zryrz/jH7P9Rls6qOQIetQ+ANoPOOKam5e5Z0fktmHrRJyZZstgwWCnZiTb3BsEN1fDNMOGjkgooxN4NJPGQRzGz67hRDeJ5PQ22vjya0I0zGw43Fn6tKYzi+lKdMq0cocYH1Fv5++o7BB9UFqn84cc0RCcw8Cly0EJv9hmY72XNYiE1lyXMMnTJjmzlUTmQxSXnwxXvtKXroBy1iLHbAS73pIT/gwo/jMQmD7bOI7WoHdc9R0//+aqiJ2zNNTr4VMKNUfr+zLxqjlWaNcTheRzTyjF2EFFw6kHU=
  template:
    metadata:
      creationTimestamp: null
      name: psn-accounts
      namespace: default
