---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psn-accounts
  namespace: default
spec:
  encryptedData:
    accounts: AgBB+fgGLyj4+MW+eV2FzA6Epg2HCdoU9eJE4+g3FobwGAdA6umVk6bIwKIAI5mXg1FpBeR9HsKNIUUOdG7E/Om3WKB8jRNxH1JTiTW2mk8HxOXa36qkj9/3ih8NXqAKmuuatgnOeBdoI1oUtZqrf7nqa4xqvSXMyuNMoYRuc+LPul/Uhj7QvdDMEOYf5TM0LIkC2kk4ovEIueWpUJtgmWHIj6krlNgjxkvbctyvVVOLWiclSZU0emo4/j6qtyfTN6OtwUqZHWUI6oS9jLYuLQ1EYhAiPqWpeLkGuRhNQGQeGNJB6Y/bLPaHHip9nEU0ZrFuM15JqE5Qu7iLAxFIlBy0FpDHBhuyERzhQHi564XmDQCjQRby6I3YzaPEOssHcHu3fxq+RjVGJfUWO3OkIfL3rLH00x3+82jyLmkr58esEihqWCIJnoSSxREhhMT1MKtb0WSualQbZgd2+8Gh8TGLEihO9unil2cz0BpObbQdSCykbqdgyBAs/ymekvIWRTQAqwAunM3HfQll5CeNjWphFhaay02elMaLFS2KAwYHlWn9TPPvy9NI6HWy0zImZGTYXCmtK9qdw23LAz/PzO9ZUlUMj0icrquaV/NY0IRAwvyFVbY3z7aYd/1nFKWXnio47/AsCHigiEgCyijWjXD72Gvjh0mQwBmHNCOwWrPny60jAdnNib/pW37h5o5khBn0aS/AfD5C4Hv35LHba+kXwU55Xbryu01hQKu9ozoGwD2y/aQqcfyUx+km3zff6nJuwXR94BwVDDbyFOhvMHh6RRKDh2Onf+v9ueKGugjDlirJ/KF7Nz0yD5odIXFaANG036A/GkIqdxSI/nY=
  template:
    metadata:
      name: psn-accounts
      namespace: default
