---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psn-accounts
  namespace: default
spec:
  encryptedData:
    accounts: AgCrldfq6ZLFFiJG5u7gwVAd4btOJfCuNcYu/iE1gwBORAHbiZiizoS8LdkPLLN2FvdiccCJreSyLLDKNehReclWskXgu0+Wm6D9vB2rDeWfEzhuW/1IU6Wwvljc5ForAd2tyJ1Qzly09wkZneubfC1Jzhzn4jk7SRjDZ/Ely/qBSYFJH8hcsmvof0Qh8fQPPnMm139hPbJfEKlmwIQphePzV24UV9uRa4RJvtUtErj2bCrpv8/yY3LvLBmsM1VI0TUDI/LS4DyTNbznIMlEAW9n1JccpaOs8nPlMe8TcRmWUlJI7xxQUxgka/sH3UzaJBDD/tgg+YTN0NcZ6xFUacf8yi5Vpbjiyjv8M1ggK01zEyiChWo8YshHBL+4xV0LO2v8zrM+Crwvdy+qvlRHr0/WcaH1+K8D+inDa0AXKHu8dXRbtiqZ+rDoBZUTmCmNcgA5voGuBhmJYegePvAk/rm/Dap0DKb/1j71cverx6FuSr3bzTHTK7l5XlUXp4TP8r0FAOh3K3CUz5a5znV7yzHDqHw1M4ggI2S3ORydiltmfH9NSem8BrAneLqF3fKdQx2woouEMytP2CkLFLk2TF5o2xNbvSBulmOJO8k/Atc+J+D74DCH4lcxtxYHJyqmLId9Ai9wzCVW6zx29SG1Ue7uhMbf2Z+chA1/FQfuWG1UrDIYwBdqiKD+qFhGPk4o4nMLkar3eZfH59BIT68ExB4vpxRnaEK23EdhNEPbwgLngUSyOd40xFed4OWfIMTGHYsZk1bQGqwzW0D+i2ZML06efHkM2wjwHEKKbz29AHkV28O4ogjZ9c6SZZtcGA3Fc+sTlkk+2FD/9pCEo9Q=
  template:
    metadata:
      name: psn-accounts
      namespace: default
