---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: psn-accounts
  namespace: default
spec:
  encryptedData:
    accounts: AgB1kIcWP0TcRde43D2KtDX+H0MxuU++J+f8aziaI90Xw4edbfTBJNPNvoG+gZ54WYtRe8CylB/KXXIUL7y9L94aFoGGt7R/BQjChJJHlM+gVFiGW1/l9p4tiV2m2TZL6Ume5R6cU1qpXB6RYcI85wqmhnFecbcuiWOM4MJ0AzrTivqHMCIEAr76sa+v2BnEqEEcJfdHLJeFyEcF1cL1epVRlwyBjH21ZqLaQQCPar4ynIVotkyqWregGXWhP9HB3jS63bfl1FpnAVY0Gdcr3g+yup/I07sjvdKWrX6QNJS0v08iVY2xhAHDehTaYof+is0KAxUz2Zk05VKavD30ygilX6DwZhM70hA8Qq5pMylY+G6yjlaupK+yr8lptkpF0nRIvGvmRn7vXZDRO8y4xfsTtvkbrl605GIUB8bRT1psw420aX3peX+cMi9U5dig+P4ONXq40a7lstiohLW8m+kK4Mb3PFBfzuIq7rUF9hub2qOo0PaH/cnGCDSW5xrsDefo4Ix+qvZ40PxJphmhDfwe5Q3TOvBhgnhAfRsgT4Ld1M8ALZpc5A3NqLqHDgTQJXJeL7hv3wIlc+4MA35P+cyi34fq2Nfsq+Bk3NMS1ebQRwAL66hIirIka23O15ijaNe1c0WrJMyL1mKUnjqevh/K7AKrnX0F6vUn3EsEtzRg1eFOyiNDafptGtd8E0D9kgO9PflSvXSc2lxMNQGjYXaUZPGVp3DBo8GFraTi5c3QEENa3BzUr4Lc/GVtRtohgNpB60q4uFJWtlEYsziVvJ6vk0Xx31G3hlDmKzDPT/kBKiNdbpB7TePdpA4Pl0kLYIpqWo7pZDWak/BgruE=
  template:
    metadata:
      creationTimestamp: null
      name: psn-accounts
      namespace: default
