---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: psn-accounts
  namespace: default
spec:
  encryptedData:
    accounts: AgAIYUYhxRp+NO8jEReK2jedAgcU02MOHBpVVW8+TthroSGRzZkRbVuEtRQB3NPLleYTUpDCq1HjFq9e9Cy4eVnpyYL9AWx3Uz04NON9xLkKftap6kyKCyxF0LRkkMwP+C5FKVa82ztTpqzOLGux0N1oBFELGissZl/YoTMyqyEatLmu4BeSa8/6x0yxjRO69IWzkMPw5ouHUaW4ADk3/3QmuHjMzNc6u/BW5Cq02TJBop46a+ypY1TT+2DNaMfuKtvN/3qXDnBKS/W4wbBRgZquq7JeEjySrQZt06Et+RsgYUSlGn3h+4lTf+XOlVAHFL5t954+X9e7/c77LLTGn31QEIiAvRqQ2pi83k6jyrPJ4LZcRK+QHKhcOlM4e+iD6F0//bz0cF3Rx7c9WjPwT9ix69+/LGQ3AGB8Xjor4OX9tzG/rlfgEz9ecIlJ55ZnwgmyLPAcgFShLH3vclEgXbGilrvY87LQJ45qytYPPn+NHEPHSq5U9zBV3BEsc6a2IxSubvX9Xss9GCA9RbzWbTLHeM1RqBAJ6Vq8+A0JzB3hVDiefYPW+Z/Ksm9eFvYs5paHFwv2F6+M+Kc/i4ryDFbPupPnmneowJ9B09d/ii1RUhQsVPTiczFyr3r2HrmA85PNy3V16t47qHw0/jJl/6t00cRVdtHAVs+B2mpeKhK0Y0GltVOpcmqley6emkEl6iTMsZUuIS4PToVIRUlzEwPEuIbFuGxtLVthmWuRHj3ak3Ku1Hhp0q1iT5uVUUfooGO8oNi+2/ijFH5w2wncJwE+VNV+2MHKGfc7fO2LKuEq7MCjQMPplMVBVDkhQVdi0C2lyVT0shRGcNK63h0=
  template:
    metadata:
      name: psn-accounts
      namespace: default
