---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: psn-accounts
  namespace: default
spec:
  encryptedData:
    accounts: AgDHK3qRZ24Q33SCJRN44mTOiZDloW/F5OwatYg8lhfu+CRcL/1zd4tkYfB0obWP2tKVoZjBsIoDImeg+bv8qOhsWoi7+f+CDQ2LbDBKuOG+xyFthVru7PxnbVDN8m3RKqM6lGlcxjCeWZbrYzIkQHTzc7P+9wgaaWgF7QpL5kfgqDv9YVES7LknY5z1RTwPy5BynJeMkDHzzZzd6CoRt7gDlbSKJLXZcmsbacsozFOkaZzfhIiJ8yUypuE7ydUrtLgSlkD0LwpP+I6nbo3/eoWa8DNUQ+2H6hcWHEAKXsBYIMOmqDa4tR0vRzORCyL59r1UXs1SEDm7zXnxRqpt/gStmb76wAaAoOCGpHblrEGWooaMeVXral0qApLTWs/fiCGqBfekPaj+XTYoAq6JFZCKeVzY3AwVp1TNZUHA2N6hwcFBkhP4T8q6a37jGRcuTMgkI62d2opuAgwh5i1fbpETbV1YHjmmMKTSkoawsUzBiMmdtsetfYlg5fl90/Npw7NMhrwGd3xcB7MmynBnn5e7NcLs+I2ZO2eSXrOj4lwi46wzaxX6sWBr2KJq9KMl0OVN4xvam+PkjRgqLcOpOF36rdRGqtsjkoKS/cp0sZ+0HRhwYzNo7EQxBzY3YrXLslUgLeOEvChVuNtiCwBzqVxegmHsy/onPPAtFxEMV930ubiMxQbxGuZgPdH9EtmNS6/3WLOwFIesd3KiOqWiAXiLJtDPA/+fUbPX4QswMU38YmKT+kwtvNDhwWtT6Dx739Zxpr3fdmSrahc7O5NWo/Ew3sh2j5TmrUJ0zsywchgKiv988nCDO5Vt1dfaw/M/j0Hf2/MOs5mdGOSVq8U=
  template:
    metadata:
      creationTimestamp: null
      name: psn-accounts
      namespace: default
