---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAZQVSvAFUOiGRGp58mztB5gB1LOh0CY5D91ex+nx3cBnBY/baf+Fn1mUDNYqVhi3/bLXxGpqCmROT3MX+bNcUHgeS3/OiAGPy4Px2j9WzHYhySy2lClHA1hpdZezJvWfqibSTRRayeYtcVpL8oUyysxvNpphz6VmJEaPnUhwE+JtIPG1GFEo3Dyir626x8Lg0PqrxbP+cXokFPNlCTwjT3Ny8nhwC9ETgO46hAT5optwu8aXrReyAHQqH+0rsCPueEKklV9IZVzn/koSZVTD8vSsfoxDPbfazBIQROCwsd4fgAe6DypCK25BAKpRJvBB4fDdT25mC0MbrXAXILs7QIcBaDDcpEYqBiglqFE4mc0Ja+7k8PV6deOOry3XwTB5DbaUM9yuYiLNZ/9ALtYhR/WAcDwmp0wJc2B+csNNFKw2ZrY84roXTiPZjo4A/QBVslNVypwks96E2IuhVvas6Yt0+em5x4xbJfTEPlSKXKzAI/4bOofkLm7NLkVhTN2BzXPkw8qGP1L/P3r62KUsfBnEwF6MzTrNPj7cBlkiMLAuJJMpJfQM426kAUBRB/Q/onK2Vriw2D1KiFJxTVcy2ZL/GU4HNvlm21AJqc6hlC7M3lkz6JzIEOeu15A+JBfay6k5yPe6nYQsy9yVg52kv5SGfY0zrJVeEV4lgd/sdCdYqg5IdxaGkYEEirQE70IlUk8IGnzI29V9fFEEPkjohY0spK754fPOdL/1KlTFj714voI/F2xuyAr7iKnavCnQ3daJubi4ahkA50kHISybT8rTQH1GUJ3DX1Lw1pWDb4KEGSKo4uQpo9ubO1j1BMZLbNND7CgXlF8lNHSaLCfj8I6YTnEaZ+ozKDdjYLA01h9sz/PGlsgQo4bM+qGPZRLq1tViDJQuhARJZwIgetn+r6R2e0le6ii5a5S7Pryg26zUz096kH/N3/AXe4xO01MX0eJIu0aqIi5AgXGjBmmFoUb8g+REvUXg==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
