---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBbDz6CttDzasquL4D1Elys9e1mVbKG5juHhCHXjVqlrFLjR7tfcNLZip74n+nGdBjdcnIqHiyfORC9Qq0MhwRhjOErwWE8hPea/wsXGCMySc2vXByi+4DTjPVLWj19nF3OOEe0IrQOu1Vw/SJjcNEb3oTphIwD2/OTMAg59lEta95KPlyqeqBO7JkIEs7dM0nTGG5iLvhWBZQ+10HgL3TzI2VUcE++MQua+IkXA1ALIcowbO1YWPcnL/CwsHuCpZA69pGHhEHkGUtE0IgLnh5SnxhTrV6s/RpfXjp0jvgnhEAwVpBzOUCwYttYeWAohVmQEyfk4gqk7FnoA38dfNTtlQwjw0FR+ZzLwH+EyVFpW+A079zcdT6iespGOElP5QX8rYPuHd472HIFuFhJGeRdtLwgSHt90d5+kMdEHgmZn6oeo/LDic7tdnnwXAISTmN3k0JISrcbm2/mWT5lN9bHVkMgVXOmewh8A5YiCg7oRGZ+gwGzYLBkplJfpM+Avghl8yrkbld3UN8Gn0Ey8PT3x9dEMYF8eJ6QoFLdZEZySLUoZ6Xwqsw5YV1rSu+U1wyVkpNFq7VOJeSX4gYHc8gSoZgkv5lNqtXHO/gGZ4ClvjaIII51h4XAbeHT1mICjAAnDzxj4mQoVMZc30gIYoFovx2Wgh0vCBfFYBCk5K3A9M/6h4eig9H2u5JHBPM6zww8BInyjSju07cCEZ1Ix22mc6PLLje9IgBdL/j2QJ8aoEa/EiLm/qq01kVjQqkYXSW2AoUF+2g663YKvevzrXZQMsYCo8+H5XEVckFPqCCa5myuiI4X1oaO1dvmasrPQPLLvGwrgcMqzyOy8vI6FVTWt0Yl82MR6iJXK6jYgJo8aIkxnZAIQSzT7LY1Xo0UV680Tq6nny4r9CeNdFCr6FNnLre2DiqSmH9EKjFN9l58d0owDONSrfgqTtqrP/em33eyfkjNzvFCmIiSIF6q3Z1Q+hAV8o2v1w==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
