---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAWF5mSXvB+UWPmGyTy319I0YuK3VgzxWVEgv4wubeVYyV34P6vccrEgr10wXfTI1pErjmZgnWb/I4Zd/nTiOg0C1Tb4nn5RV43vGT0KcLkZmicussIRMq5+pckv3SbwILoaa8afidF29+leguIKU9yI2lduPKG+M5vHl6OvDKhZKMEQV/AFUSpE4lvuHVpOx+aLdiiwI/vZ5BOQpT4B2P73QDUmQ+T1veRCCfA93jPkT3KKEBhxqXc2JXuJHCta0MpDYi6J6JD6NqOOel+aSfYJaYTr38MjJFZ9nETghWcTs1ke/kuv39qzOs+XW7Pdl0E6d+8AQmVBvvKOd5FL27ykm6Kr1Pktxv07bc3bwHiL7epirs7o5ym4mMZ3pABjwM8ll9I6Eyp9aARaISRxE85caWVAgSGLAK7/IIfxfkuTKAQMxGBX9A0wOK5vjy2UMrWuA4HtZc2yFBuLYVdQYSG05ly7/TAwO7u1SG8iKWjJpZoROon+s49J83p7DFS5t5GiQwmLwGw+r/WboNAxNPaOBdNsscDrPyMAc+8plIBpJwrHttVMH8W/YpvUpBRFmERA+jpVh7Xpuaajzb1w9WLnYXci3nscnzQeB+KcelB7k5g+uoEQgy3uusERq6j+wvx4v4T6UyLtWeOxQSd9NncxlEqKIN3ScffSV6wHkWO1GTWNy7NeICT8yHztgrzfZ86G80MTpQAlE5GQzZ/MV9VX/wEhjWABiLv5eXHsq1x47RUl5qA5N4T0sLhr6JMR6TC9tMlJoHXebNJcDmlS9uky7BgDNF5dvq0CjyBnEmin359Xvkz9YLjbJx7TrLxXIoodOWwx7BDcx6OMetVCQ0SGN93kfjMTaY6ql3ctOrmWntSG0DZzAg8oUVM9r3HYxuS+EUZGED5ra3KrgQtUaIXpE+U3PrXWh30Jz1ArepGNeVgEclyg00O4cW3oajGMkWD9Z9EeNh6jFb1qCEfdoeLKLr1dcpZmA==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
