---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBWv4+4s22mu9YCIE8kInUgBLU6OWXaPS+8Y5UoqbRS4yy0W/RoITh2YLCwqqj7kbLP7HkT/4/TT9uh0aoQhjJRw8nr1HEMZ+dpW11ONWz11REypOPMO/oOZnjg1ZdUPnye/Qort80zPvEgJKEwp+winwwNrshNOpKNKjqAWzC122CYtarQBxCofRH8W3uYUzQr1kWaHpEh9gXTipY7YEH7j36ufkC62Zucy9415c8t/Z2ax1R5DkaDnz66w5hg/Y1cEwy91//GBeEkN/1NeY4n1dWUmCbU+pywHH3OWZ79IY7uHnwajrjekmH66M9ef+UVqATCHDUSSHjtlz/s28MNOgWaoMHql4EfVLnVmX8cqGoG1dan5tAuTWdsHe/+sO/MH8+/tkTYmxiegKxGQPs/EsUzRP9uaHhbcytNvNO6ItiEKNre8RczcDv+BT4rTBcj2LHHSv/YKcCdZ04kWD9Zo9j/0OxsW9WywOP0Ldq1vb/kTn2eJ/H/Y4McEx8QqWlWQMDV8OtiTyRiDMsg40lJAypnivihTkqIeFqSZmD44kqzY5LoyZXzySio13jZshHgZtXzBWEJCH1fvxTDcyMfrUnQ3VYCRf6e7+4DklcjrX9wr4F9w9kYbCug6cNYuZWiNohDHtEnDN7nD96jh18poKTM4ItztxkNmQry7JIZoeUK7AF4I4K4gSEgvhbXOG2FfXOH+vsDxyKn9lz4Pik6ig7HChG1BM2Mf+BZ7RJFiB/fuYdHJnzg+FRIa7U9fxAGe90JsBYcuaOxi4CRrJ5TkiFuSmFRhpsO4ZX8xjmNOzshN6NzPw1pOttF3cI0qSXPCVieEi18U0na4TDj/rt3awQpFTali096oKoIsSNh78xVoaGWJ8VVPp1tdAi2EigIgjFIxUXmrMGZvkZniidDVTIpfPE4J/AztsIb8mH2Q0mwn23G0Xhp2KCjPjPkfKjNlSUjvS3Xk0Pmjd+JF1gG0T/ZwzdGrA==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
