---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgA1Fgh1I4I6pXh5uRV4LsbcGaWKP1EJT7a6s2h0dO0fuvuuqgOnjYQOEx9D3YLSvHtwGpTQugp5FCbrE4o1V3A48mwB9t36poi7JPeZFXQ/Z95eJPNtS+19gegQIOEKw58tTpusYTdJN9zYNokFA/zz4YT8v7Phh2DXPTMpng+y2YFO9W2XJz5Sv+ZIyMgIYprD4IYlukXuhMO9A3NeE+o/FAVMGll3jNomUizyK4HawPCqlWWuGlGt/bN0RmoDU9hykH6jI30USo0QiCgiW4FjEUmMXfDbNiCpsyd7znCvEZ9sSPgypAP9TD97xbtaTraFodZK4odtp0VwskCWneG3FDcMV05a5MtILrKdvlwVxgKfDm8cF3nGV2XnRHV/NTwd6XKrv1xhZqZjP0L2iAyRdXGHZXq7tU7NVrxtM/B37Rer6P4sSkD0Bk9Wgbr+6jcgFtxRpL+wnmoXxBVTCDHag+n/RIOo2rLi6uakQ+R/ps1D173ZLHgU70yzQwlGmlkIZvq2nf2O7X6eXsScIoBdttuH+hAW3xdQkX4PUU/RViKxZ6A/g2FgLwk7cXolmWXQht/pwvEAxWv7Aazzz4ZlXHgwQ6sGGx6k9b93tMIYILMArD3aljbXp2ua4ekb7i4oEegtbOeHL8pAG59M2QL/ui4ckLj4/YwNhzWl4+SfSL/EjLulOKQDnNEXB7SBWhU/RAjxtTOTtVTcfAAu98VVdOKblfgy7sulTJy7KDWgu//jqsQHvMeXKYbeAR/jVkVGyxInKrO9/RaE6Zz+cB+Ia4/QkOMB81AhwldZF1/cGHeQKeB5S6k78ahHShF+MSvsrhqFBQaihS9oKNLRlheBjfi75fIVyJcxMoUlIWqo0Wb8nhGfCS/NIV+xpW6PG8+BASipxZABrJwbc+StPHn1l8ZdMQwBVNWemwLoMxKuoDKOkWIU1vFaPjlHorPCwTrKeNQHoJsnj+vrUpN+262gL++A1dX1Eg==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
