---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCfBeVme9KBoZrSuAWOsCngQWhiSIH6bfgtQDlzS/4/ksgJV4D9tyHzDHxMiUP/Gtrwqn6hhLfmv5sdl03AIyXuccHQho5lQ3fnLzQTzpV4dQltYmtKT9fC6JLOTqZR/iuIEU7/CZxVOszTnzqH/4A+RccDNgnZ3nUCAguBoZR7zrGLRHvC7pHoHz5ksPhLbQoRhGcrJRJ+7JAkCsEb8q55X7eHdpi0btCSbnBBRehuPHatTj0BN6xGGfK0RAmt0xjaP9GfAfgfb+Uo+05ilYFoKiU01z3rSd+VW5vjtzwKiH9aolHi2bBuvPV9yGk5sJngkfDMjGlGRHJdFMOOJ/Aoa/YSXI2QSM7RSgjSP47LVFAShj6tCU/Qya0FkXfMmnfrKV01jOcoizz8xmgIgyNtrxQ+QyLmHjc2RwBSm8aWA7bTnWj29jQJoJaGkxyRvHjnVaGAkFt5KpuXm8/a8KxPS9fv88eGnapgGdFUcAARLJChLRIZyAK+/gNTRXvQ9n91QpCCGEojuFJGz1fYgjeGTfis/Kp8nvubkFL0sRh48bZ4ZC2hm29JSS13hs8dKjfl76sNHtkzwmsYIVJbFjISJv21NA4JTVGxKCuLcgIsHAfMNylwY00qVwnELbrmo5E86M2qHLPj5YyQGIUaWa+kRjrni4Ny8ZbH6+4mKZAds4pJy+yIGqp+vhTNdnTJyTfdDYmQxkNAqEYgWJ8482DTn3rKeUQCBFBnhQ8JibmwG2eKyikrXwziHDfRvqI58v3QmuVioUKavlYoABy3ycgbNoEgW5MoTZIWC6Yhtan7Mp68gKIRYH2NyjxEDy9Icmy0Vn7Kr7P91oyHa4agyYBUOmtjH9kfQ9NMGHeaBvdZekR5/DhYl3vjFbkfo0hSWVoA5q487puTGLoRf1qbznUVVjEEVQ4QMgDJ6NmQuB48RxfoaMAJWah1OPg6XLvPWyNcQK8zFOa/EASWAUpLiPgvizSsl2SMQA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
