---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgB3mYQsWRsUEN5j2g5vJHkGpS+ojTxJoA+asD5YqCI8AW49Uif8baH3Br1Muf4R/uU6EfPSPheCc4IHhkTUjjqajGFGl+dLfKd8b6AdFKsi3AE53udZYc6g7LXxLE4Dg2VzIB5SCPyN3PDYu9YVVCRfF83Yht0c5oyGQNqVafEIa+z6qHE+mTndHKNCfkbZN47aEVwgX1BinDILCT2xEpJN/3X01uig1GqnuiCZE/sLcgDbASMq4kYNOFlcvyQ6M5w4p01CTjwyJHH78dPJtxlu12l7wpoEwX5XcsADDD3FmYV+R0VulJwtTrkl8okn2f3FFMRkGyT3tp2P/TcInZW/jOkr7iOinvR9GrEtYO4SnuIB0hHtxiqPVLBPDDJmZpIyrGOoxOTTUqD/lXQodeWjH9/Ma1zp16uv10k09S9Asi4W3r6M3NhmwCBEsLXMPAP6LV9hVYhiv/x0dnO/k3KK4Mvnlg9+Cib088ErQYq+3ISDPa1tTWtEBWpCrCPzp8teaVbDx91l+/XXeVcZQ4+++rMFsvwK6QUHFEHlDpGgnYxtdvWyB5DbUKj7Cs8DwktTS7Ymtkg0wPpx3IVlKmaKUHpm+3plZc1pfeL4MAcqLeOcVdOfq28v5MpH/oKmawz5sOkY6cbQzK+suwLmAa7PXpKE0Tcu5UfWlxTVa6m8Ht/7WbMqT1SHK/xHDboA1boB49aizPJNC2n5WkRokqR9XyABX4sia/oQ+elHftsZDJf9XTN6pD21EixbS9xjbtRolvaigckjxYByIUkKui2fSvmCufVweLon8A5+qgLVKtU9x8RE9EQQBRkmAFA2zJc6y3A2UmW4J7ME0L6Ij+JaE1aYRwJocTNS7S117On6lu4Dt7ufPBiqDp1EUYi/HFBv90H+tJHexTBdkkjjAxZBs5QadTn1IoVfBn3VImQtkMFQigM5LgwIS+Atls3WBp4uDzPyY3AzAzz7+bTTyCUOp6mH7TzsDw==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
