---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgB+e25tjIEuj0grm09kfef/szfvioTydv4r2sx2s6qqtKc4NLv9hEEsWZiZVgoVPMJEKswxo4ogipTv9/m3MK555a/O5U/04jlq1OY2+iXC0CBlTQW0lFQAUGD8AIXErLKw1pDwCA+6WrD4cjmnV/sqsw2BgjoPS2AWj2Wc6fIy0yrMu0YumV2ybYCOMm5LvhwOxWTb2KpWUeT/BrlC0Cn0mvtNXHog6FFY3eWBf+qpecTpw9Mk+2ViZwkf48fBSjY/K08jgO3aySY+U1ZdtXbgc4q16vZDVbiaXyY3dfEbPmn1sNlJ4okM+v5qgAFFf78YjBRnYnYXve2WXj4mphV70toKkmMHTrGiIzFZ0XuQFlkxbvKPl8Mr7hBoVGNi4MvYPjeaJZs8UiQ9MD5fow7EPqfdv7e8Of19LJHZccOjAumKu451J2MGAr1bNg7mMEsIl26vo+jeYtEyNBwxFATB3gqWvGB2nJAVlSNyrpLdCerJzFXt+wuxB52+PCJbJ1ThaZp6f+kJSESSmgYJ5hCkaGlf2PDbizaub1zG7qtaVteH0rscpfdzrWznEHKnKGoXHy8q6ZLiCsBW13A4B+i+LoO/wgz3Mv2cnWL4xdFZzVe4iG+ROtOBWEcabV33+AGPZqWgQkI8xumK31esx2Vv7hWVrkuo96icSYGFDHZ7G99lxfm50XKPTkkT3L/YQFRb1BLOXcDUde7ZX/AdBJqhEfofm8lCx2wyY16Rol0pPU8BpS/rX5PpqNk/QEQErqy7eGGOESdi68aZCHNJXx665C7eeA4WiSkhs3mgr2aKqgPHma9SIwsMrWd3VY1BJcEslOSLtNEYeLnaI6JbQyvmVsBUgALJjr/PrslZZwtg4JbrM0LY9YP69rzJBCMtoK3vcRURilPIMNMiaKirns8oMWYWqzugULlnJ4U7m5DhGFzoKFGIzqP3FkOOOFqhLhjKwj0+P5gbxyajV1x3NRDmNdampcQ0Yw==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
