---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBBabUvYn92zzb6iOEbxtVxHY200gKA2NhvFEf1tCD8X137laQk6GmgXhf5SkUKjXaC8P+/WV/hzxnnA2xl69MSXTNqALywkiPwSazQv0U9ZsNogTVUkO+VUAPmAee+7lai4xC/U3IItufCzTdCpw+OHn3S7RqdaOt4n3gPIeMMwZwD4tcpCD2YvHGachqDjGLIEFyh5zlLkbHPfkIYA56sNizV8BF6Vf+8PNoAi5x6qN3il6BDr+AXXnz+2SJQXOHxEr4ikiV+p0stZWDjkjgy7OV+HfC2XMyUW5K7ObtP+sCKLbkGTlCjkOxvyUH6+C2tRxFgZnmyVaICkPzqY+gexNcStx+By1Oy10J5Td7gk/DnhtRytu7jFouIM62lyqTsdsezq5CRZ/JBKM5Q1MT+jiHtUsI5Mnv1u/JLo7nYRPgNijB2CLu5Y9nzSMLVnD0UYU1480RiuLm+BB04DJZ3Y+YCaxknsev5RAwKRwjxDbzOFVGSkFdV3ySfYzb6iQ+YSkpt79GOFLhsguFldORAiBmjwbVGXtLehQlbvfS2WNHKV1flQSlawMqlA40cx27ChjQfo9fnJPJUuYjCqdJ+xfsMEx6Hs6wpyJtt2f+ldCe3BiNNgcBTWLDaZUXh3mtA52LUFGzETE6vjf33k/wXl3qlRMF2px/2+vgKJDFTIdoyBF1v9SoIEAQDee0+artUrQpR1GjXp2hnLtnP2qRAGbB9MoelDkMPOaQ/XeNNzWLC0ytyDnCxogTIG6TTYOQZoCBQ6eRN9F+6JfvRrt+jH2Wxz3l30MUEnJs6xIZDKKwrXegCWtsyDDlhN4dADqb+kl8QG/sWnupfTdnqHZAXBq0EC7lNThY015H/nayv85TyWR9FYrTLGNZfL+opSKL2pgwstNymygef//1dSo8DUV+KvczRHFdGVyAMCI+r95tAwUqZoIg9LxLvqOFTakAkAcBWtMA5U+PMXeMrwaQtFO92hVpo3Q==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
