---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAF1ZV9P3rZ3M0OrzeFzxCjDw2sECpinMiEqJHtaAz/KeDiVj/dHyV6EusEdIWxtOiGPi04aPfnFrnGQv9T2VIXU5D47YtnJZBjevzdDkA3OBAT5V1jP/JWks/O6+po/IeT/qpO6rCafec5j35WkkZPOdQ6q4RHQCcfwynRVfSW5aCegnT54Nps+qg4pI6X3tuN8/lR7IN2Blp0vJsak4BIfzLUDwwVUCN/BSg2twGkqGNBwOXAF18hZPdXBtJFRHeoF0tvW+37PLJIJCEiBT8gfk5CHLAeI6crhpymVrbYkCEcjGK/n9//RewHO67mDSvBW1I+tsOULkgyp39vPBSGww1MNsz3ZQelzJLSopn6mKOrze4pfdIicY3iKxH1+cYATuzhN7EG2jUqIu/bsW72tytB8nukM0mb5ydvBZahfzjM2SnoQzY4ETjYZmXaRFpPsT2ZZEflnH0KOkEpzOSCgptMZqcJwfadP5hDbnA4L4prSrW2PO9+XjMoPbBM46ogXeLP6MSDUYtbqEguftn1Vu/GX42nGhZ5pOv+2TBf9gEBgvMrJH7TRcwGXb7WwoDAymBqLOHlV1p8SBJrceCt6ArWUN/yGwhGfTnbvXzTPvXsbbaaUOL493LKKsb7STFHNSjT3g31gjnOnlQ7ISSCSDxIQio6KRKIBMRRo026f72dFCQ600qY9oHs4kEKqn0iKcUNxiXJGJiHj5x97ty6RyFRJUg1YQq8ETqEhAQqXVE0yXQbBKgIlL0e2M+Y5DeANjj9OVpFeJu7pf10jcQ4yzUCPmyyWdZp8HtrS6Zax/H4PaIf+G/8tkxs2LFYGAx1mnhx1CkPhEnS7lbgyqSJY4kt/JRqxTPXty5WM4YwDZ4P4fdZt60JB2THpxFYkAyeE3tnQ+Qp3czQy7lWzzxaN7396XtiUFOrfb7td7QIIOJ4gasKVGGc2MOSYzP/2IIv+5LKdBM20vfS6aWI1Q2fat1GTSyTdw==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
