---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBE7r9k/Ggp2qi+YXIU9DnkdgrsLluIMsAS4zTJeVmS4qMtMTK/z/BgHFKkQXUM/cMmVgy8870DQNYub3dOAeMu7vqnO93yrLpDzZJgiO7MgWJC3D6638Q73WCze81SWDnNZuPWXReYpwTZSHdpdLb9QYCm0LRezift2sw+TCA5LydegZZ5QRbI5QodWfTDdSFve9FHUkzRYUl7X37kRSCxtM/RNRsnIAiLxwB4Fx1qmSTd0rwX6MGceba1EL7HfBl+RYE2JqSIDaAck88Z896J9t4NXiY6JkxZw6sWSh6frQarBGXsZQ4hJGBjTLyrdL1iSkvKP95rA4eMWudm1RvE0Yykp+VrajysdbxhcVqwaAZpPYKm6uhKZY7uVcaAAuxMOEsqTS89YRXoKQW4V6SX8/jrKc2gvvkRuIUflTScfPNPxM/oeZY0By7zKGiTfD2UFKPTDttIHrhfZPelOtSpjVgoRQjMHPfnGEFZocG5uw1jLuageFmZf3yc3omtdV2MyinWMVaZt1t/WaSzSX0dxxS5GAioWwLOaa5Bv/wm27Dv0/Ox2RiAehoVFfxJHy+4fsnll8y34FVg1tdfoX0aQtS8lHzn/zEwxZNi0Bjfaij5JQCDy/pBtoQfxX+wmsBNryrO/Z4cWYGfCQjygRKk6CqyT5cKESz251f5VhBN99YznxR1RAPKcKdCqWpzwjw7D074oVBWPa/Z7ALpj1qcYYeYSSRUUSWIgC/i4gmAgZoum9Z3h0xsVY7CHd9ANRut8mHUPhoEbQyRbU75+wn0r0hEc2D/OAy9DctPi+BsQL4h9m+G2UlrISdWt05yfofj1e2v4kMHeNptpiqopoby3dDOE2V4xNv1KsO/6eumftDK6H1iD7xiuSrzlyDfg1FQ/wMeieazxb4bUZsDd5Y3l3fpPFfDPNiqNf6kBArcxWOobBXKML8m04VIiZl9OIP7yf6AmhqIuYKiArNwTFHhpkfFrHQxrg==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
