---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgC25amjuBX6GWxmdfYJC0v8feAL3TTFnlbWPrp/ZPqglJ8jCea8aLHOlETyFx+VaVE6TbmuPmFWeIyzTF353a+a4SuXYYB2Xi6JRP2bvi5kpRT+91RDjhJREe1QdaKz6/vdzNDAJAqoK4zSWf5Oz6jMGyNG8JbWqllsftYTJJqxJVisCuM5jn5FddnRinUVR6DGKAFSjXRDVYRSw2uHUeQKr4uCvGx/hO0mcgGdZZ+I20gZybAFN09iYteqJ4R/txX7f02ZC2ON14QOoyEKErE11Vb8clMR/yqoRMKuZuH0WemWxKCMeEXRkd83tHhIyFgOxVs1Lo/Ilm+3ywY1WtP6i9ihJvx3bVgixnKf8vhzi/Iw/v4KjrPun1qsi3oC2a02abtpbCVWx3lywRzljpxzKkC9x9TofRsEGdo9ryp3JAlkZMhNRyEztJEvxPhkbPoVRes/ZKZgfk1G+bs0pu/mbjwa7Xy/PRhx5RsueQ/z8Ljlk9gPlQo5B/VfY/co5OeBwfeRJqxOeiCSSHdgP/NAvThFmDKKBXx86qDO6DYA7FXFJjHdKJnZ3uZfX0diN6bmNNY3K+krJEdS63C9WM/MnoT+fXMEWSSFhCctJX6+DEX3LOZkRd0wJz1MkkvJn5jH4tZkgOieIwGdWiRs96AjnjqyoZAEUnCcEAhqfKNnvb6gFlfxTV8leCsr3crmBLVoWBvhFaFu3bAZxAXrJPO7T06Om90Pp0pvfInmu6i4Ywum8fIvyyeaXlf1/dZzRSDpdELsX1T/BMAJvQliky/GnmNittZJaXzrsGmH07kZfPh9jaZqQfPIhE+okLPan75m2sZxZ3xNdbjdH49fipXMUdn8oBJVQbbBMztQMgONXXbRs7mJ90GH+doK/RlLS4p6Jh+eDqpD5/ViLO+d7soKRO2ea3Q4Y980+Io5rDcCjGQsMwnIiZ8F5FnCfPJNlNx53+71W/h3K+IcipyFYiMXOin2A/Tc4A==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
