---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgClmtA0z1Vdk/oAoRowoNAstOpEu0/0VEPiigpd4x9Ok2SH6n1O3nNt2HNQgrpcww5rlu33r8yReqWhcXfHzztI1qWnuqj3WVwp/tn7K+io5skQn7/lFYX1YPNv1QjYDNSpdQZVVMgDtYyNkHmNzMeDOTho3yyPqHHB8MMcy/ws1OhDchGTMjb3YKfgi5Orb+LkOcDz6cuVo7zegJjRDeTurfoMSucigVw65ECZbDqJjcFrrw9kukfGsIcg+fyKjc/HILWR+j9FRx14vEv/2HWyPDf7WTxd6ygfBMmg9vAWi0+GuVfatxldXQqcY2JF1eAZZdfdU4aD+3mRirRG01VKSpIDoigAnbQuTBDsLXQ6bPEOIOD2XA+wyw6F8tS/SOv7mcsNj8Yv4jqo8suQZXFVxPJzxTueV8UXMTb7x3prHi9pIUAHbZHPCV5uYSsNd+RjRD4ycs7F4U4P48FGhfxHt6E1XoNXUUR7BwnunwmOqezFoO4FX1KkzDkW1ITAxqVZChBlL7+otaUoAlsUqNGHjrevR2AgVTPhk/bd8bbZXSehnlfYO9HEs9Ts9R+MOr1fiiKHBwXuZ9zEVFds/6DfdhA1xSh6fLGqvhXsLtEUfGpKjTcrNE0N0xAYOIPoU2xTBimHdph6Xr7RHGKIjgSZWxXkUgRp0bK1gtjnxpS5sMM5+pTDOIk8dvojQrgWs75iVDSOvEbKUXO/yTzC84JSR1Jhr6TSO3klT7jMaj5z2hIkHx6MXUEhzaOBxJXaQjDSBKH9fCrljxZoIvzrjdN1GDbcems6fPTqH0eypBqb+gTFcw1yurLiQs4RkXaq32irelb3Q+2It6sHIkyIfz3o5Gtm5JLgvoS5fjuS79lJA6Ksj9JYZ+HTRwLWBprIRVyoieSyQ8CV8bPiScNhz1tWdhiHOgCe5FkUQDms+ecclKtAHIrdUB074IPqS565aIgQA0G/Rk/TpVv6glBsbxyN7cgPXb2TBg==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
