---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBqKVqr/s4gKHxn/35tExJ2GNab6cMuxApeACJCfypBkYEHssC4Uo5+GIazANAjuOQ/ffBOdqdVwSyNnxyLkyxZ0t/WRwEgEJKwZWkWu1BOZCScDQ0SmpqsriRDIexToTvP92dTPeTlllO2umYFYl0PkNS4onP3m/MzykXni6TFiXjHwnOLkPmeSsqlb4XSq2tYcFJwpCxK3CSXwA+pyJXT09fW5NgoMgJdrQ/oH4ZH19iujEpBjVoPf2ao9y/OtjuPBuq8E4eQ086gVNiyqOyJmCjbILtffgqseDEEeF/8gyntjKOpq3OoL0lojF8RAdEI+QHg2hh9eBVDo90Vs3GP/t9zOldWOzGgZSOV09FApf60IIZy9maHi4x5qdipagOO5bfrxTSbcqdd1SHXe0687yW9uHbUhU7GetyjNAEihI/RXH+aNcRT8j3RaIEVV2aE0Qa1tVluQbjg5m7aQzaQQFIF2VZHuBFBrUMSqLXKqBDj00aFchklBSEGden9O4SfptNhEia9S+oyOB9F+O/2V+WUIyOrYmWOavNCVyDFiThR7i858PnOc4nFoA/HfWky82D1cNB7aWAc6pwtLU9lxuYnQLgYNOmf92wFR1TGu9qaq7kM4QO+pHXeOeMbeRfJlu+k+b4QqEG3eWRJhLE/c4vnAa4fNPvM4wRam+RWTL4DJWGiQSisNpigzHLZucVBhX6WxmtwjuzlWJF8ciRVhyKTZ6juGFwvGfRrEI/d2hMCQ4w1nVGU7T1ybH2u9bGP//fSFItqnw333Y3Q3K+3VYi7YDIlVIAkfkh+p1oVCiMyUd9+gly4l3f5lz9gK/v2W9s5F6Baqn2LESY9zHXE3z3u0iKRVvwNrDaWjJSVhMHTzD+NThUXZOmhPIgVbZfyIV5NR3y+ZUshKdyxy2G2z2qn9ZsmxavSBG+eFW7dKpPXE1D/BV5e5Stj8Ekg/tvsempISFd0yYvaffEzzAvWqnr76mSjWQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
