---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAdr8g4/4bW7l3Lkplx09Isbr+7/PQIr6rQkvPsdeKFnhQ8CgQz5g1OsU9QH1LAGtJIHlVcJs9Wf/s/eQdAwqWyqygqoh1NvvbagDQut1ajdVEqHYc5tEtPu+e7YZn0+yc+OM2L2TSNv0WFjEN5Hx6aKXGxOBHSk9OY0bAe+6iVJDeDLcstLLqRcOsIAUPQFImlTwOjnXxhHVrp0M/aWYp6P0aNC6ySgury43EENpw8Nngi7KdjE1RGRfCDR++fCa8OMK1CnCJpmCpp8rZ/gZS39XiqN7LZOCVb8yNFRWgsLcSA03w+OAxAHCcUBEe5oBhYUf0qKvIks4QXY9WTqT4v69PkcyPdGri1QX53vmwb5w7SvHhqIc3UKrExe5ALjZ2xs1h9dC3J+NGYNZiJPmqZL/4EslbaT7LT+9zTcrBoyrOaZerx6kjBeBbQwHezfV4SRj8EYnfEL/qE2cCx/V5/xZKlVDoVmlngcmdZszzkFpQtlF67tzozSNlM+U1GoWLNWXkMAwM26vr4WlxTQswkbMPv5iZudIc08NEG2AtLDxMXbozOoT4cHb3tsELFaUH0LaK/3mPRkh3whxh/mPvWMg6B+ljT6Y7gAuQBI3ikIeXd6QdP8WrVkPTfpW2ucjpoPehHT+m5xAyIc5rugMFbOR6tSKlmNrvNX7QafmpEbaLBvTmOqM2b6uMHR8r2KJi9HYR9X/1KwY2ulcZnh8kHHI+z4dQa3VQqoa1f65bnYDCY4C4sYaMegWScI5bqljwgnMSARQrCR/fdj8U1SYPbA1+A28ms9hp0yX16ZxR2KYAJCgmipLJttmxexLv3C7hZ4m1gAUFjDQRejot5gw+eb8Ook3VvabSBWTxL9+6PGjW4qccQ3kAxQoXpRrjdO4Rm2fAfi2+dxPZBmcCLpm6a3VOz40iT4gfdXINnu+ZvPhxXfUIX2Qpu7H8esiz4dZcbZJqoFtBeAmaXkWdKewMKxUDRmMiPaQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
