---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAWKYeZGFz5pB7s6HbUUNZxsM1tWDmtZSe39/ehWbtTvCm4dbQsnP6dr9/S1TLEXPStlluhnGawg3IgE4DvFlsHSkNEzeDcskY08MZhhTEImyY6+q6oNeZz4iJyMs7onrZhBc5acQ44lw0PhjMBikIqK0+326/BUGurxGb26JGgQSlXdxlDQbPC2pfFZ6+1i19Fy03wqpgLh0KHVDZ7fHLXb8dwGfBhzicwoM5mPVAFLESL00/cqbGiQxLttEkKP18aRwsPwhdXUDYmpdYUjzwDHN79q1Tzo9+3lBdfhR9zA8aHPm6JsAFiV2+PYzED3VqYfQrfjPLiZLYAKN1994MQd0M6MQts5SdelyzSbjI385XFYBLgxNmfWffXAJ1pY9F+ONEfbJgTcPufwtFp1jgIzEf73VtVYY8VjgoPI5EBkv/wgomZmzx/YLmWY7hGoi+kpbC96McI8dKoexoVVex6B0QwY5DVLkdJa2dfWVZcle6kH8YVPMjlppMD8wLbqCoEezMLFsLhRV+f9zGgxyGT07bYcmvbe/w/cWM/sMrN1x7JZ/ZbqMUFlzg/sMuIs5VY6P38c26WKR5N3iSBH2FAJlkfKJOJ5oIQHDZL1kYrar0XyCGyE2bUc7TsDoJXKsLmlzDRRGF3kNimJFYORpNJ4MqHpauva6TFFJOjwpyHEKdXEs/EShZumzBWIWffdSV3/a8DCSeoV8Sc7q+eBwownUr5L07J2Z15IcCCUpHLGwTECFyCz1+0PHirmk7kkRRJbrjmzsl/Hr0JL1Pw0VyHvJ+Wl08IjCIe7aO4ejbSpTkwM4TiSmDKGDXvITcSUg2joiezGbbi0prFM0lxAZsOQ0B9Puq/Zlw3ejjA/4NHw4DY/Zxn2/CrIgOCOvL07qi43frIwAzGSWTfbELUCoOwHiZT4K5WRLzCxrs+lts4hgJOUvz/JCZSE0s3Db6SNIzJ83YEPKLzbnrPhk0uNMOnPYYsYKu0Tg==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
