---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCnI5iGPiXPxNKbNKwEYfgsE/VDB6B7ISH12/gPsPRe0yLQ/SkmpAl83gB/mI97iN+OhPX2b30nnR91yIzAUBKbS8Fq7ahr8sSmmd0Kgi75G7XhADZJ8NUmzUEbnuM8o8q2CPlGX5LDfu1NZwtvUexYeNWx/N2vDsG+6PUwz2MytuTKmWNiu2fdP3SJFTjS6vnw2i/pzozHCLdT7mlFifo7dzz+xM2uCqMXf02TlUK3fsgsOThpn+UO0QP4o7XbItv7nTrJUiYTJVxWnEP2cxIE1wDubxkBQiCTojuXX66soefZ0zcodANBxk8hX9aC54vNFznFruW55O6atCS7jhItY+RrAgJOiPF+t8zHyzX70YwHIGPfq9h+CjrjnxjT1efAGhcxnqFFXG8zJBlX1BmAWyFqjf9L6XXr9z6rnCEnLQnon1uxhgGbSQlu/9yM6PfnsgGX4+JJanRHFaKFftnsfgh4SFn4hqUv7HpP4/CGS6Kdk1aZ+jNDVfIRK14V4JvzqOlPHZahr1ISzWflDebg19gsdABsSy4fw/8jHqn6mVxqAg57hLuFrNb10CL6QNwQGDq+dgLhgK9H7wrsyhYUu1kXIhlMvAF/zEz3W6B0JU0vxy3YgU42kq0yVIFmRbqxPxTh6qn46VIlFmsAATCfzuJy5EW8k/AyjE1O6bq7eS3JW5JriiCvr6DKf2LKuAcFyX3sOP7EPbFfC5WOfwV7eGOAKSLjQO0MCDjJmKKC401U48fL5FBp5CJPyBPkQ0eKPBp2LRD53nGgHPUnvc+POBBuQa1dexBbqO9ho8VjCrIxkVWP/8mqh0mZ2ZY1TQPV/NnPqTG1sbxP1nurSI9leatF5vtfO14FC0lKs+uV3y3FwfUirvuhb6tVpy2n3HDvdQhURNwOHsGv1PZeH9b5jWZvyBGoRB1YrDq/gOM497MttCsf6jCV/AQySHp1uat6NB+u9h22xCxqnDciWhiLUl1SOQWzwg==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
