---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCFwelD+yUqBwsQu/2imKDeFTr0DkZ6uxX0KSML/GtkCZWceMZqfanRNOTsbgaSx7HgG06Y+c3xgBcrDWILOGDDiWcLDJhkLZ9lL3WrBeGKVqLd+yD017qQWi379VYuWEQ/3Vt1wAF2yOAR50dflxz//oTObL7op9B3WHWO46tmYMOyIa5Mzv2YpxujqHCZbiQRGQcewrcGleOhJvosqogje2w5uWX2mjs8oiqu3OlgaTjSO/OPfJKvfyOIHXB9NbXfsdOTHVswB2n247W1W6w2skfoW/1Sa1zogPTr3xDMI+F4uHSzMYQoMG4rGv4P+xfsdLjGyceU12BGzJTzb4cajgX+Hd6M83CVVKoJpTLDoIZ7L83Wlg3WmYHkw70fwMju8jC3nnWc8/EFdg1SYRcUdaXA7fygkAHUBU0/0pH/V26P1+wlchVVmv35np/ZDa67mhnVhvw1nyiDIDrCsFrdf4SvWkKYtf+OqO2Ad6QXXhMmhOl15MGZl0EoZ8UUy1CPv/L8teIIRpaDJ5JKjQfY/9dzhLWg60AGGyBg0dBrA5zpcLPj5/Af1xv5Cz5ntF5BHQexPf1F5G2tHGJHkXspz7hBGx690Pz2mkJPuS/NlH24LN+jfr5dzi7b8+nsbrKmS5cD8f/3y2zYokNKVx/jlWaXl6xMb+INJCKBCQ9hsEXg/k1WjBwGrFGDumvWl2cHf2m9rhGT6JNUl/6LwB/NFXYLquzpT76qRmayeMobx4sbl3oSH/sy5rYix0h++77SZvuLy0ygl4bLwXu7+Tp9/7K21CyrCuN+/U8nxJBJ491ELDH/77NORmn73Xv1ChSyg3CC7aXVCvTrVReuJDtJfhy0IWbhm8A35pVckaZMLiZmI5IeThwbtrhXHtKOPdO3Noq24xxEGYFSUENflJ6Cqo4ufV4vljnjF5iLBdrinqhEjtIrPdKx9mifrTsT2ZfA0SgiNY1ixs6foNCbdRaxrTWOr4m69A==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
