---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBuqn5cvALa56tvf+gl0L+ZZV2t/5alAfUEciyi2IwWicgRYgJODDN+XLO7E+JRIxN533XCWHBJ2CfdMWo1jPNteOfENYxFVX87R6ju5PK6GahZIC6RQqnLzMa9KNQS5pw7vVpBVfAT7YBemxDmju3XNPZesJIn5NTBSxGJ3V0EbBJdpUZckL2Og5FSAUT12Cq2o0IgKAkMikcDuDc5fWLYz5YiwxIth7jdKsOBj13uw8EA+WPCVYly5hkVTsZxiE42lQtgo3tGbDaZ65z8sBfkFtHtYWUWnDC+m/KLzdOMG3ZotWhTypITaT+kTCfa1RM8+DFjBO8/mApU2gOtbrzPrWui49KZVpqliRax3Hy9U586RIHV0G3QNzRTC1M3wvYv5dtAONMOQRxPi+OfgtfMLfxFLTxXmAfjiNoSV0TkZkZsoRF0FJglDA24BadADdNObB+5B3zo26tTjZnik+9vwLQZrsVy8vws15Ag33B4Ngw2mAB6wxTfoIUMbK4uqhrtl2h4dW5wAw2L98HdGZVKdhu22/jxcLHvdUqLu0aVDyZQm7TMB7gK7YUVikjez5vOPXNbHL+ktG0kj+oChrcODW+PFnxdvpa11d6jxnPBNNT6DKyg+o+oHk0ew50IEWg2T9H9NZCFewvxioCsQ/x56iJRuY6Qu7uqW5k0x+YVjIcUAFSlJ6jQx8qy/oK9GWz+yYMk2WNU6FQE7mRD/vGi4Asbm0Lo/mlCUyBhfG9rUEPmokdX6t/8X/4lM43H9znzOPGNnmdIbPVcjUu5BNYj/2wAH7tJM/zJUll1PmH2xbj2dEK0M67tYLJtZOoG0zrroqo8/MiM7NlhsoTZwORgRInDbFRQ/ZGFF7iGVixNBAHFRnUV/hAUoO/wfD6zvgnvpD3GuCLHd649jh5vaTy9yX/wZNRqecHqHl2myBmAxjOCkXm/SUOu5ZHzCNFX/na/HX9v17FJS3iSkV56/S8tSFFVn5ud4g==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
