---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBnSYnzlgN/U2RMg/fEuY8826u99NmOuCpWlKgpsJnAtqRHgAXWV3r92FVqjK5IWL0wG8ZfRYpp76U6aMQfRsCY9IMxqyDXZAlj+SpzuMnW5J0wJTqDGlegDylF/ah59Adyt/Co6dun1PhFCxtHsyEOkG8NeUCcjB++Yx+hMqK3QpdbYi3BPUdj9RHns42i5ZFfQQQ53MQanPgnNyljCOunP4arZuR4lUdpcrvBVC0w3n+Zrg97KWvdoln7oNaD3BPEVdLam7s/vhiXevllOZ/o4nT+SRetOK7XHKkHpjHSc7UQAtDsuxcTN9yeBllUNwd0mAlAqYakh5yafL1LqG/sgxmH2Xg3wS8BPhndk10oFjTk1Yl+XLqRKoW6QOtRfFoD7k2wMHlb9b+i5+VvEpuIh9v7kKSSS+65F+YlbK3uEmhDuhU7A/SRkLAR2BKGL8nmkj6EVGPVDutC68nqcuiuzWD1tQ3CeN3fVY9XkwSJ3AymOweILqE2qGoqXlaaqS5SWC9iVH+xvVH7gyHaLju1sedOYtkzLNh0GSjYoYZwP9/TfRdNc75LEvaAMB883gGU3cWZk2+wOGFyxNQNLLm7KyYCa8nRX4eNr779gfwOXDpcxI/Fkm7/Cvcc2vfnz9ihL1bruP7Qg2QAX8cOvWNIpvtfBjV8eBUPHMkS60/0XzLYE3DutkfG9pp4r8zCmkqi9jH3urY41P0ri2mNZKi7oHGZ3ZhbFQg1sfWGZ5IvtCq+Ikwp66bx/POy/tHQ/LAF48KaL+5778nBJVaAkm5r5uR+OJOtmKqFk/S2G2DS1/8A+Ocda3/uWrlbVF0Oqi+ENSMrvSAB0gWu7TdIWJ7vaP0FFbLYoCK492f7KTGMQ8VkWCeelNi5gcPOhnScamPMgy2Ah7pbKkZqDR7uKqtcz3xkEPQK1fIOagrCN4pF1Dxw9+8MBQFsYR7foup29/LK4gSi+GBRUZCzL7D9VANH/koysp5AOw==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
