---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAX03s7nvYPp53/CgfGgHGnDFDoQvqq4ACZYLFL7XqLJvM1CCnmlzo0RIh2R5yil8qwWIpfKAGfj94OqEnjfg+glTGQGIK9RUlTsxemWqZsw7nfuA5quY8P1Y5aSGm5ThZcsTA/JhyNEAZKxHX6gepfEpYbuzNCcjg9pouxwLV6TiBNNfUqhfhNlhmT3ru2CbzVKIT3e9KJwu1pDOuJ9eQPKfwVyDpIm2R/+fDjKTXfB9ip1sjldTVtO7NwFbHhhe1pkNy/3kSIC0FmsfdcQicX+9d0jC4dYCyPcr9UcM41RX/tN2f9CVWZBlnlz1NH9tFILCXhZrbv5xPE+hTSBWGIYzDADZZNV5bTF7aDzwsz+DZX33bEnKPgXsIpfS9xuPXh99hl+ufsEZMdypWTmw2W9w7TR88Pv5ek7L3+vHtaEJw4dCc15vMq7yLLK2SWCOIrBx18kM17Oq0UqANdvwSCpkK02giAXGp+neyOwH01XJnE3xwoZj11l2bGamQYnQm0tkl8XN4UiemS+25F6BkH91UnS6dd9xQJnCllZa6Yb0aJDw0HMfy9ZfbCDFfhpgUzehNlq7J04ueN0fKcbJ5sM8CKN8aydU5bA8AfqNK2OjlhmkxymnAIIIVHBmJhxeel+3uNKZnTOZAlFAqRt0eZAzHiiJjLDNoPfvsN3KA9cQw/cYdjy3xRf0JPyejwewb6TdFlatbW1/4p8IdtLU8cLIcdoS5eKJrwMb6vw9Lzr5ERh6hTKuf8Ru0T2rZ7O71GwZgUFbNVA6hVYl9aSKqkAH57UCDqcqNkkB2I4Jy9wYHHR5t2NCy3EI3le8RoRpoc4ZLVFO73wbfIS7cFsQc96msa9t5AC/8mi7Lu2SvrX1EFTLJ2wWitHjocOLaKTM5GcwrwZB/SlRf7dodLERgNuFox4PtwefcTx3FzkPPaLyCeWx0YxrG51EtuCnc5oMZe6O4y3wSFu6tGrcpJx92HxHAlq3gdug==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
