---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgDQR1d8Ko9xP451X3YjatvVNuk/JF0kL8mwf2FydpvB//Uic+S/kkNSuHLvzcxkVsWX1oZCOEJydIzeVoGrvQ/jfMV32eejDz4xgYiwlk4nImFuuZf63yY/MkGb3eIjsKnRjoqvQgv172XL2GVGjY3aHqu1afTnWdR0EM+dTH6nrDu7g/NcXY5DdZDUZdio3EpTwQgN2UCL9y7aWf6RLkflpagNmgxKSNbx8FEWmxSJCDkE/lvksPRix/h9tipua1vNp6u/8OMQla1wnKVYqVlXXala++hIsTvfR6P6UpkTFMzKUJxS7EVuAzDcBwtdUCB3zcTDYJWXhsks5kWQ9DZcxf1ro/ReROMZJHzOoNJjteMW7O3sOIWu8oM68jWGMBSoFP5vZ44VQCKHi6IQzT0WUVfhNPt2DQSUe7mujXKLFWu2l/1dT/HufdEguQ29RkGZBhaIVMYB0dULLM4XgTvqEP26V/3uSzqCOebYf6BktGTFfPoTB4hwwgT5opOldY2poazSKasWeOPkJxvThZlEC4kJT2Re3DAdDH/Mijg0SlKcO7QxcGLrmdggqy4aqH0keT1hRUKEXUrKlOooo6n7GDEyM/A1XaD5M9Os6T1Dkoh3l7po/j3nNNA5ek/eui/Bb13CoSC4kSww3IlNYC5PEZh7Z+pVg1FxD4SDk3KMvw5NVzEKCA55mzB4HFqUPupkOlc9hJ8GRaFJujXWFDmVAcQWaQtlpTkaDrATzvwr9JCN3QWz3Jxb1KMU+hxtaZy/Nhw43KDr9yOYBIQ1egwjYPMlZcmJk1A/vlnkxplmxZHcREuC/VnjFUlCW5bTJHt4KOLOmA5Al75LrytoKx4bhUzvIknEE7qbiFEDsjqa2wZCBdyidKVdGSxgV/EL4+XdoKTDY4HATi1etdEJr3efE+4kMWYj57BH8Ah7o64VCAV9mUXN3J3jZ+YYDy/DGkBMaFc++z28R8lUekbR5VELOKHdA1wtkg==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
