---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBHlt8Fqh4fGcCxnK6OQ/x6kdWKQl3oARZ9CE0nPbuaghWBiriK7WadpqTb1w/0aaaayViP0VwzoEjuAh6KPdZtsLHUhARwBYmvUufbhHC7ZebvUpYsQK2/r2j70vXp+TAGui25NLtPBsd1I4NK2tLXPxlXkE/5ARRh8bC17TCGey0faxijDTEc46L+ou/iUOpxQCib8n/lMflyZVwxheRzJqPfkcK9ZrTl6BAbBTfqDzaRACAbe7b47vmi49Xcl8dQXQzDpiBqm10mdAQTaA9N3Paf0FaF8J3ON89RgWk4j858xV9LH7HTzCrLiSenFvDkdYILgZoHaqvA+OkFKf7aVclO+lit4vuT7qDRRb7hCj8YCIqwKoR72XWu2OvuWNjpSQspKLA9HxL18cpGzIF5hxLx5jdfusDB/qT2iyWj2/OeidNgd0yNlaWp17oLW7WKNsap8yuTntDrATMy7pkoWeVAcnr4wp4QwvaovXPdIFJee+nWmDLvCVKRuOqePE4/JHa0ArM/cWazyuKRd/ZORllEW3jgHDeFN6qzLIwVtrsVHw2DShKWAkcgXxOpHr2G5RRuHY+Rp/fgg82OSUJ/x9/lZw0aG4AxbQtLS4BUbp8Bal3SfduvoHqUH8INTrpxEqGoLGOJAUMDA52D5LFQFTR3ENcsse3t4yvMtmpGVICSxmU2DC4VsuXnwUrbyS0QiFrbD8t++9ztm0+F/DSQhT0myGZixIBe51kMBT1wsWo+tk2V4ni0oh+jHcEERrvXFtK5NfFYit6mB9l6Bx9a+AnVbzabq6ziU9GvuMTSM2keRZe+HqF0IvvGkQEHJ/84Fm3781sCKMdBNVBS1y96QPYnPZjf/IA6ARfqYo4XlwHOcG+Eb9xLtYKyimvWyXtsRkJnezZtll/TGyS/Tzmrws4l5zwYUcmNW2hATQuEm+/2NfhDU3vtTmE12XvQzb4RqJtsffPlvaK8mjCgh3IOqRN3Kx9bhA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
