---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAj7guKU42oVB6V5XCiV7MmaY4SFFvh8AaWKzsRMVnKD18y4jb7O1WU2AvOlsWleucDHBaXRtbKBw6z571wwxKAq8oYSelYWLoYrdFC6ee8HDWd9z5MfvSgeF/ZbdKMOn6VJDliv2V4kE5TwUhH1z24D1VAs8BsSqJtVlB/xs8QZ0CZ62jx1Xs1Gr/69Hfy0UYdpeuNXSRHD3mqmxjjntvEKBIF8KpbNaMnGbsIMpx4vnRKJr21oBLniAW25NQDDMxdRlrpctoxyUAPRSBO8w11AeSz1RRuzVo2yVOJGTOGx/yZwC64NBxM0JQZbqE5dj8YWVEf7xHcpGKpD7cdetAcIF+YOXI6iFc9wC+FAyiLo4gNG6K0+l2wbxZ/gQN2eBV9gfpYmKQeHHeV6tcGPZSFaKxhJsHaBK6fwKwwv+5oJ0Gzqw3VIhIkYZnZ9SmDp7Kczfhzypf2Vhutv4yyZvW/RwXArM7lmrWMQTWoKZb7skaxXX8L4+qjoaD+bAakSJwWTz2pPwgFDdsICKy2S0gbU4XXbb5UbGmF1pM9r4dnH8vSM31pOTdIB1UbvBmQt4g8UQ6LbkJX8p9yhpyBNj4arOv+FV0LY3JtFXGprxMDJ04k2BWCFJH3z2FX2YdBUvr3QphEz2GVuxNyRaqPLR9beF7r5nuENgzxKxc+wGL6/inLKWJ0ACHfWnrl0E1ZpjkqOidhqmv+eGPjLVlIjsdDhWhRB9rVP+lVMsKTDw/O8uaw/0DMPDAy7GE6G3yYGH2vQhMfheoCuqErwZSnNgzvA7++6DZtJ+ZEfxxOsKH9iJJClJKNvzoyfSuTPpm+CKX4wEjcHSpKTPh72+UINO9p06yb4nvcrIxiD6E/yctxjqa5tzBoXKW/wgv+Uocxsg2/hl9o/dadC8Qp5QF30qYkExTBj43Mv+fc6/DFcXkBPgaf05NinHRBfX2aSZUrGsa3UBoiNnzap5eNm2ndMus3vIv8LfiQqg==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
