---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBoVb7o79UNFSOXx9OAhuYjc6yz8fmoTsYmzKxy2gfZADWZq6+WFDVpspfVlXRV5tGSLMIthq7wJk6+MRPy/7VHMc17m9Xu7qiayWD20rcwka8pt2NmmwuaYjXsLzJFUaQDZvsUqvz2t9hb+F5p3cnPcw+WqceWUcVPGO7aLWyy7SHY4SEt2U4ulIo6LOi1KGvNKX0GqG2rnAtJ66yweHIn52ztYDiTeBwulrv4Px8+xaaaFKAY7HhNZaSOZg/j70rdRTRGhIN02i+qiGYN4y8gBW38AdTgJKzEuueRng4c5qSQWsdQNQKjZ7Khc4c9BT576QWf1wu+BHIfv3nEV0LQ2GP6795TbgfM/ezUjdSBwprkaPP3mAV9/oGG30QNMoUDxGkcpJAJYvGgq/NMlqIMih0yG8Q57sHSjOcormB20MLbzwd1bWUIJwshSpTaNLVG/Ib4CgTl7z54TbbCWUXypwpVqaG/GjPFBYA5v/yituH7gXT49oFmRdBoxYwyPr59hZtzFaav/3C4cPbcRv4aCCtAvkQMZVVM8tEa6uRq0shNG3nJ+ci/JPL9fyyEi5HCo+EH9RBeUsVTuuW6UyGRVPzf4k33kDvyFxaM0dxIaV7qNjSsDs38IGGM75lHl0uZZjW03+HRjW/I59oy0Bzom70xJwPtIqwijPW4BW8VouWun4KlLpV5egZNa01jjhWFiGYzdZwL8ZbdRr3VpvbcB7PNmZ6PFWCMh9vymZ79shaUc6e0pUdu7xTvOPUS5RtMOTxUFf7tspjqKJ90yvsrAXggutLjkSixnqNB5rxaX5ZaDYvC/7XzceLzE3/DmFefekETthHJVOg+atBDsTJaDj8v7cy+YYBljg6U4BaQpWeVTtTRnXv9aVr7+D7QNM6KYtz2P4FYNiQHxzUmvYXIqv/fyqt1SZo5tYydm9rfv5ePt0Rgaq8R09VMpqwRu5EIRAcfL/CiVbIDfWXkgUvXqjoSgmUi0g==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
