---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgA+4lwPadl0UBJxgVRihJZJnYZV9oYIe/ommwzWeXZLCNV0jQu48fWItHUFQXRbliDTQFVR6rVKqx7kfA/c7tYdsfifbB+bBaKXTmVw945H3SN49A3g5Yxefg+HbZ5hPIJbq5naVKkBTHZRxRSdIeP97vdWnRnsY+XP9JsP04PMltRwM9WS0AhHNuPUHbuaGaMWq7OJg52PDSesYvIPAdco5ZiwkfX/2VsLL37JQhfwv8ebwdi7s3xlHokZzg52EbSlc5SY7Md3iDFJZr0brND96UyFeDMEmMx29wnInd6eOXPAGCZb0UGuXuCJSRZVCj+ox2gec4PxM1Za5q/CsA4bq/4LRnxyit48rnNj3TENlO8ktnQqQBZWUyU4Ypccg9V5p/ls8GekeKEdhdseYt+d6E7NfhgRFobh7y7+x1ykNyqkmJQxw91d4nRLi/hi2gWD1IHGITyhxL3xAAC5rao+2FRhvYgRszudq3UaeESX/oaNeUlfS2E85CpEHs29vWHWk3iovRUf03D5knU3IXNNWaEeURdxOqiXexkDYj8fVLNL5mhxU7OE8Vtrn3Ar5G6yGBM8EskjbSZHhU/unzvkDr7yVncbvJbx0Vw4Cxwu3Pk+fO/akCVg/pfdVXPtHZ+Lzi1XX1FI0akXpM/TNe9IhO7hdpumb5tNQ6gmHAUzKt/U7DiNZJhLsMgPmArn+h+N95f17Ii5zrlU8lqkElXntprHU5hjETxc2V2lA3ORnHnE5UC8uEu8q23bdS072ok5rmGjSuf5qBQvyJ2tMYNAHgvi43oOE+9qsLJQyitmOyi7c3RQtGmn3rdnYFdMcGSWdcSMJdmZ8+aMnMmHFg44N2090F6vyhO4Qc6CMLFTg4AKTDhyoYObi/8vyFYy3unY/GicCbyPJcL1wSy9SOHbUPIfrwFtJTc4V2vegLyKVJyQsLsfmdaawfogfNH/Y2RnZPtOIiYJeuA34FW0rZyMJJIL1+bCpw==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
