---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgC4RRx9EE6tN9mHKcSApVVapMviaNighJZynbiyQvauF84BzLII6TaS9fzm9A/RnGmT4HOYxhCiuM1nbKynoeCWPu1wgNGsfbasFZzfQLb9dtox00uaOSx3+A5Vvuwvckvh1DwCospJa5m2jmgs7ewF6JgIBxW3d/19KRiAgnq73BcOm1MTNdecO5aL3SoILbAvHUGVPnULQ/YTym61FIEKkK6fM6OkZjkE0jSY0JqVViXBh/BlVz+Prirdp+DUfSE+AATs9zyy0Uzp9MRlZVJNYljrRNQyFWV10tMUxSNa5GwilH8//2TXAnK8pi6tu+Sysh+EM10Wvkr+zcHgTRieWXhOv++DOAT8HbbmxpHtwYnNlZvEffJwRLgErw8JSkzdONmEOK2IX6kYqKs5enANbP76jsL9dvQbPxvbCkv7sUuiHamGRaOTW6tddnZzziDo3jSXNlHWdEF0kFAk9nQL6OOWaKt12EexmOOBImY7xwusoCniwkVO4WFY5LM7DyoCmOlabM//00vUH/KkXsRKqLdS2PDc0cLXUJYJOhwGuYIHD0X96xmuqHqX4Sy/NqWFoIgg9JQ7IQPwY3IAs6T64ItDUXGDC+94C1aWrKf2N4wBBNuCCC3bNZAp+NhQYVwiEfXD/93p0U7GcKAzlfjL8k4n9fAFeBUlPwbQWoIabMADI/zzKpBDvmS68H+cn/C2Ua7+UA64/ZrI8lOxC5wPGTrmreJyUNjrrWcZ/k0ODTC3VZzrtbFm6I12g/UTsGEdFO1cHku12em8uZVLJXKfiTjPKG6NzKNVap20E1Ykl+wAUaPffrFyb2HpfUySlC7XxFk/MadWOwDGEso50d/B5LpsyG40veggBhQoRHXUkQYisUk6aSNqhJeq/XoYfLYJQ34k2y+kT3hJ923uXbP8Md++Cq2TJfNkZZwwGx06RNzIEXE9emhqy1Hggihk8m4cm3hPTjSURzp6RLhYnBknBem9QUWyJA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
