---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgA+b7DawM3F3lsvBR0WViPK6OpTR7Yib79jPWKZgw2Bt/nJk6pxCbL4nM+wuJIs6QU4YFcnFNik/IYGApxFlYSzN9fhw/giJPTkoDnuRI9Tnxx/pULWGVOQ8puA1gCrUFfK+hDidx/sLYxR7aip1vA66wwG2EECHk0O/ZbLc0OvyUHYuiEW0su7AyK0UyUd0JJI6q3LApYB15Gn7o/7+krybL7TsajMeajJ0WkEWPopvpUJZOWvCralj9RcM/BxofctBW2gcs4bTe+M7B4UNtyzeYopc8CZzF310HvCKSWxM5lgTsCsfIBehvaaoBSOUEgRM7ffdoRM9xCDPLlDlsnyI1nuoNYbo1jpMgNJE0tRORPsCO1EGNgf2hndsHEAwCpxEuGuvlVV67Wc5rtlV9ZbgGk42VhKfrhLvmg0ZXnfW0Q8CbaP9y0AOhHtjU6Ifh8sTkv16bWVMEniOtAGxDx3RIpZ9M6sgxLXD8ZfOMqk2NZgC604y3Xje9AXtybnQCRGccaaN0sOu0yfpJ8uIsNn5uk0/BXp7ztEtp6I0RvWe+NjGvFhRY8QlrAAyN5UjU55Xougu6j6e9y6dqRhBynVj/dx9qiqzOB0CkL9KQmNNpugCLXOFjxIvmdSHQtdbfDvmCXBSC2LEAI1E39pIpgceAz/utc+W3uEAYmGLgGKNVMipxOKFLsm2Drv5yBDfzf3lD8GpYH0P7fBOYTftxagmRParJege3I1OcGmiW0jZ/k5KjkO/c2+TC2/ZEoA8vAtqjlWNUqdXAtVHBYEm/p2MNw/nw7YtiMPOlggABx6DHs6iUn7TbBUUQdwI/dIJnBGO4/E0f2MNomKxl32EDtuN2YRKalU4uCBtbOtA7h5jdcUt972uDZ5tT7f4v9vHKiS9IeYFDPylNXyLKD3mC4Cq1RYdOO25FXreLxeEtts0bB6Xoi7XDI7PR9jbbNOwy/dE/QuyzcoFDynxbousBnsdgXTOcdQAQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
