---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCtxMspCTjzoNjKKldu7g3ql/CVKnLaTf1DT3teb+aMUueAlUxjmRr50wfkwbIkfMXHOtyt46FJWrsWjQvC1BTVoaTI8GfWa+yNyFUM34dCzuZJfoy8WbkzSShzmx4QT5jOm7EO9ZIBF6NfqoPQy/Th+CaDQyahjHb0DRy4G+T0PfDcSRCr468Wv8KerJM1nHFP4KCOMajqeFhK37ZdrO9mWmREaZv0q4PnOvDCkv1iLEb80yNEu0uMkiWWULceNKXaojxthvv5jzQ4TnplosGiZ9vgm87Lc6h53zUs88CaOLcLIcT2jmMh/od9L4u86uwHFBFAZyOlxgabLzxXb2kz89W/vJI6Q+/AqexYhupv0FZLXpoi7Xz+fKd97qg0f22RmHCTQcbFpkFKDL/n9Cqab8jHGc3GTetj0zKHgLSbvOd7TfaZSfPKyPuW0VDzPxToqUQpTqI/WpiHlD7nxOrbmVRzc7SV7pnTQrJ2U9d0pPNh0EiWFKtSI32DoRQ8Fqe+/oZUw444phe9DmhxEFzsTXlasR00KpTU2BqwapV3vfVccJ056MRvltNQuIaMwK/0ZPeyZZ4LHyaZOeKUD7tWkUYyeqjjGAlYFib8qEOi//JmBPEI15+E08EyPwq8mi4uadoafj9YL8PvRYvTBVFN/34uIxVZC3Of0QyWjuzpGHCqifxF+qab0rWUzx4J9ys+EV3EYAJLlDCwAkgE19T+XhEs5gTrTY12yylBxZyJEspeGaIOBdBZo0N6QKotxkWpYth8SFxeyHChAOIIpTMdNIzUUURk6kFZCAtlRG3JipIjNKX/e4i/egy3N1G5AWq6CHuKO57+sRre+Jp1+MDhCkRREwQi0dmUf/TXbRRI6imme48MLAqvjJvaaqolCPZG8+zIPKQlYjE6reShCFJKC0AjTeBAHCYjqNIOqN29OKBMHTr6OXtQxz1ahSr+IoXMT0u1m3o6U6MEciuDRPQaJI58Nwp/gA==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
