---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCSQLHpPJrWRz7X/DG0qoyru9tWvKD8mq2JX0Sc4p0nxdxPvCN/GfqLXYXxeMuYdFRByfLanAv+P6GhJkLTmA3VMT7m5yTW1JAI+if+nH6ZR7DacwCJl0IZUeJ49VktMk4HIRMLfDx9GgP/Ilfcfddds5P3tsuGQaOodPCUmdM45nK4hnWHLIX5m08PPW56BK9N6fCOE6ggaPsEzVkqIBUDK5yDjUTCm22JAUzmBOq6bbVph97plis1e0K5skEhNXe7/wMjGKUWvjK6u484GoJy0o5zJHk4g7bgSdkTfuQAbw9zO8GCdnnmi6eYjfpT69hhDi6o3SYJfA+N8eQCUkE2Zp1N2tir/UbXFW6DR6cb0WL+DJbQJiOPNtN2FFWOKfce+o/nNvBYsaK0DJQ1A2i8wruvy0miIdnhmeOho1lwVhpQFVIYvJ6L76deecBX1w9+6YyoenoilSQlhEldynN6v1C1ZlvwCWK2rc7hymZk1aP3969rXgWQZvt43aqqABWq4imHYY7Ks/66gpVFCfbG30F8dxTXzJrp9tqOWrEK1MGgOFFoAKguKk8QwjcSlDQzi36ca0nORUny7HSTp+0l6qu0Znz3t82g6Y1DVrIVO0oGbmW9YNW+7tL4W7bx4YECVZezxEfPornOBIH9W49tZUaNiErxRQAliprZ36kR5yI/TPwQo0tJQfiuwuekpvZFpoasPC9TSiGkB8iE6CzXp7uQ1fOt7AYoWtaHsyQCE9ANuhlm5l9gC8KFQWFOOIxueIsCkyBdf4VQYlcfMwaAImPszeXgHB4/VPFJsNmbOh5U5NeicT95skibGp5rcTijpKZy6g8BRjfZ15FJXdJZ6Mh+KkntF6XB1Xo6FI38ZgBQjVxIjaUUJEVImXE4EPxj1wOkVpB+1W4zSHUNCarwNWhfN63HD9RPzMqTwt0cGuNN8TsqhjYpAE6n7d14cqvaOebdndrfD6gdNEyxMNDDOCogYg8IjA==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
