---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCyQwtG82WkPQPZQorVaoAZvDsN+ag6P2/8v/mJ6rdJwN/Do0Db5C5BH6z9dL9PjBJJMYx55Q3ERCD6grlM+MEq4W3OZh7EZaAr2txTRmhNeGHhEzpWPqEqMGiBV/I1nQYVpPlET+4lQq2UbA3o7nwT1fsVz2Af+Bl29Mm03u4gCiLkwj+sx6Rv1/IITESodPyVN3VvjfHZR4w4tJHo2YJr8cDFRJ2WEztVaYgGnaHUqbtLJJtYCpjXSRbT6kclgxZTuxTeTuRm8GmPG9NnRWweTsZqqzYnNfvVMWoG77kq5WpiGJLuFJhRC1RQrblMB/yegZWh8PEng0IiRCDXJCjrDqYtIFOoiP87lp0/6RpJeRE6Ts19wAAqNo4hSPnJ2MeobuTA5jsjYqHt1zsrNEZk5itZ149X+Ib7tQ+YtmQ2CZuKrGAZVrUwcMCZ+kP08A1pDQW5hNGXC1PXddmuPO5hY24zZHhqW9YnCLJGZelIUzT1hLHrR2AgS4tnqnphYGF+DJN5kAyR4/+ScauVcd31OUyENb7q3jhMd5PZP8yeFe5X+MUV3Zh68q3AD7GXqTVX1ThDU4ddvX7AfghmkqAeyLyuMs52eXzHavgpaEGnQd+wZpDgiPhx4YkUGrWAp20dESbv1p31/BgpCixmVqBPwHzlQJ7GQyf5npX7iPuNKI38QtirsOE2w54DBcNiS4o+SurYYN94txU+v/EukHD0Ekv5yFRfmy+smiUFlmXAYJwgdrNofdtSTngveZQ75QeJz4orJuxAJHNsFzX4xfXyQZyTm9KctX4Ql6D+vMMQq84rrUXZfX6nu6zUALhTUi6WBlfkyJ3EPbbTyQSUltZgsWVn4v49XvsKsWwgdQRR/Tk+0qchCQ6kSRGIGQ6pPKimzf/IHbOPBNUn/78FD8u3cYbNRM2TJEHeV1uAqNUQ8mQ0dPyC0wGjrnLJeA8wacJ2LuwEnoj8iGNiQaw+gOXPQyUux6nuNg==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
