---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBO1vIiLC6zWvreQSuLa3CfWu58phWqmx3ivGqv1quDlAzEUuU6l/50T/AzINm+OSMorJuR5Lx6M6y2nhbxsjG1wV7k9XPj9m52QCTMN9cmbJeO1WVp5ErCowqFY6/URODckU7EST7dOEUchjhnl7dH9zlWZ/iR02+Iz9n1O80Kf8tcqtIbw34e5EL5BvEQ3REkA+67ZU+P+PrgHuJBU1NEOTp24Re2SFdH34lImqDrYztvsIBvqew7HJccQ60rjcJ6E2bps/ewqRwhDLd9JHGnVd6/3RT6hsefwNDsPAN9Y9nUzfTGI5DBcBifkIiDagyu5LWR6TYNAndobzShERT23bvWmBPoKw44SvGQPCx+CX004wDfYVe/DRg0EYzvbdNjLHmfT8W+BaYjkmcfoZsqsV5MQV/glACYRZm/HVS1li8zqgy+vLFqzTr/GVmde9kqk+yf3bcrIXrx2zJD0pBYUFHXRiWdjIhOgc5Kn4rS1VtKRr4CZ3VOkOTaeDReXJKRqUdmUIauqQeN+vmQL/hiqg5aExi0iNvMHus+SCiGwGDax7akMqfNyp+etaxRgb8hBwyo8ewizW022F6kMz4pQQC9OMNzLJJhhtGoRw7HVZJ4xFouurw5zpxltzbX7Vou2UeCN/TM9b7qOBKYukbki3i6s/D6pYJIi5CDshjAyKs5nhSzyGkvh4SLHOFEmP6E94z3OYZ1SxVe33Nj7QoARSkZowPvzrGkoDfHAegUaDuxoUrt3XG18EN+f3Z/7hhME2ZM82ZOSmqAjWVMhjHKG+hcBCcbNA4EzXjl4iHyazeI0QBa6+PYIBozUevDdBzdIsOYrLcjftFA3zKL4bRThr9erTDVLRKVf3G5xD+y+UY81bXB4PCLMtzqzXTVQLsKUxmlbKpqcCojroGtJRfVBw5fpX+Bnb5ZQFlWvkkwN9NE4nROnnslzPCiSU2pAcvZsM8H5V/cL6MBFthNlw+tBseuri0DGw==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
