---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgA+2orF67Gi5OYFkfMkcNqiaSDF1/06rwaHzoxQxj0hWn7BPQ4+i6fhojtUZ1c47/Ivpo63VMUUuOg4xMFlHv+SPfw3nkf/nwn0BfFuc18QJEQdodUkuX9uIAyHgBw1ZyZ50eh7CAztXBsU6+Fa6twYogr7LRS96Yzw7j5EHB5cOSDcr7ZThHQUBjpHm95DjkgLAjpbIRAXtSLnDrHPf+bOlXv5t/0cVzuhvKN356jGt669J0TENnnvb47kkPsTUuUI1yqF50C53g1/orsryRqBmM6Ihm9FwP/CSJGYjBMJEa6rbiDKTswDj/sJ2NAbmCUCdcvv0+OzOgT19+SHeJKiJpZddny8Qglntl3ukcyoN9zCxhmyIoua6upVHdsW6YjLEsMVYxVkXcLirbbgqGuaD4IGPTvUwByFxm2ATckYlyv06xSsUwcffbntlkFNwZW6mWuzgG+JhVZV5YA8EJhRaP8om+03Ef+InQwILeis+Ef7wlGFxsKBvpwP5mKIM1BOg/2fdR/FRhG0JZXJ51BJWXFIYSN33LYacnlFfd8yPAHh90Zfz0VOvbpYaQwx1UoDfBAhXIIeivlbxUS19jig4YIGyuXcN5wuOF0xMrs4cKVGhhVzNixb+NSCI3GNXoDk8RUI048Suew1fESb9U6phEYb86GJ78aAT/ZyCpt0rH2Uk7MWk2Kp3LSj3RxrH8uQef0197sFloKsmT1mMFm+DbhCoOc1OJ8u6raiDgF/v9FJKJz5NlNO3X0KISESF3zwWxkm4qR/TJXqDAHIYNy0PpH2LvC+1obgao4nlM6fOwVTstc4U3im3JarN5DfUF6nni6tEQvpSRIPvUbQXcZeRyehF2VHwyzhzQfWoAO6TcvFo/t1/ZA0MjiUsagz/PNAgI/P2j/glkNUpuis3XrDf0kxaR57Y9nQJxTqKqww6IAlJhTpOVTPjOqx2Xk99Y50HLQvczlFfGN7ngvZQL8IAJ/spbE3oA==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
