---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAQ2hBNY/GkhIMU7Qo+S8n331wUNYaJRVeeqIioSVazFIFeS99x1IC2a6c65UB3tuEbJeyxB2EcVN8fULuejKPydLCkEeFcmWI/mVkiUQzAX2Wq0loFefKTIhmW0GvlnljLfqhyN/pTx8uq9tqWJUEus9Dr1GWnN72zt7WCAjxGOp3eVHzy1YL7TRkp4wNXeUeQS9gf0hJ2XdGDi4/bYef4S/jWNH8MNrAW7UTaB0aA1Tez+pNDDy+5Qdz2AQ7e8BivU8lPvYREBIrTNdbQmgyqnlncS2FLfFi4LWN40nIA2103EIw95gvL3na8pZrgz5MtiTh1T+FJyQ2/wQ0H/uPevVASujpBwRhR2rVU4pN0VsdEb2NgvTJlkqStkpEc+tdaQTQSGdlCXbdK2TwKUuo808HuzJFSx0ObNjUPMr+9vWFZkbiY7Y8VUgTywpmEb0xGg7UnJKU7q+5iZSYMDYuHEJtc4lN7nIBExzVA687VGnuLX+C76NekKRwWrYQzddDc5p89EIW2B53E/fUJoD1YgDaE2+toFXzvZfV7aib2Q0uyFxNvsIi88wGxQqnJQuj+PAULZPijyZl/E8sb6geo4c+luc7+MDvnz8yxu6eGXr2vrkaAjJQis5VmT5NfFLqwdc6UD7gkj5OGDW2dtY0BsRXTVuIWDYu3b6cwDzayTHoC5MxiZJ6okP7LiqiRv/AutsUMW3d+/AionySRp1ezEaOprDAmWV0KqYqpM12jpadAkdmNThA4YDYm+4dTOJiauphl+QZt6sSjFwRgvpsjffCKgs5cZQv8ry/jwkRpAMBQ42Wz2D6N45LrhX3QofNzPPVF+P+S2VHE4mTGP3/SXcvq2/zkhF9EV/KV0RdHwQDto8Mb19Gp/CxJBbduTHC5Ss3E6YsDlEGv9UOSGgxgnhg7e4GzFgGn+PBq2xMoyYhGGYuk+c3ogR8PVx5OYn+kKYnB4IEYdh3yXNaUonFK8k+Xv1b9UQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
