---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgAPWR5nzaiE67hDPYfotYkWTLlF0qiPFlgkBK8bzLhOsRtzCnrRDFaB7sqOXTdX/dKdijt/GHTYn3o4l2ih6mUUOKPfEY306fmqpr2usI8Xa+0VfkKAl7bfWDLrmQGQ/zE2CcIcpz9gnzSiae6VjLTTjEaLUhmyrCy4AA6CYW0qHevY3bcpZAB+UTiIjRTqqd9+/EDPs2VXUEBzsjKogs2jV4qERgvCwMGPYNvqWvRAE+xNHWyhrppqvK77kXzCME97y/1ur+D2S5xTJaiBlRiwRmpS2dI+lfFv6hQR67rlougPgz48jKDGI4Ily+/C9HueRqpZML94ZvZ1mbV4VhQ80KifbQn5gvoWHZbxUDANNh+OcFAPp3Fgj1UCWBSoq6h2KxibPIMtEKYN3MmU6+iccSzZrYP+ZS9Nn/azgPsqNPDMghwPtWOKqsiQVVYBGZKd6g1ASJohkIADixR63sw9KGSxrl40xhmka+whoR7fi8vXc9Bvqc5pNPrNoSMbA4mkPtyZ4o7BJDPzg0qA9UzDsByG+HtViHvzfq4ZZAr0kqYpeHoRuL5ZyuQNU/HH8MaWZ2RHPZZsS2wsHTIqZr9oUhDJoopYUXRoqxr0sxZp4/h8strcg+P4p+AOQUwMmrK55QdkTC2MyoeasDPMxI1ArSWuIkpyfDG2F3V7T46a+/9M9ROy5v5hsWmg31QBnvaMw/JbVzSfHpdKA1ILbHRRV2zV0QPXgdxasuy0UbN4DwvVPlcwg9uDUOg51ZIBfQMNJ+G5wacLJqlFjio7t05kbZYzdYKd2c3HmANY7KOt4YaB34WI7W0gzEdVGSJvLS3E4Y/MpHvFD/Wree58Lp27tOCJ0gRANcwA0S0oXdabQwC2LCNegB3ow07XOREYmhoYKyOnF/jUW6uREBXhMgYbyBrpltmIXXhAqC1rDacf5oxRTAuBEyqV5Zo8gy9utN/h1qjmrHsdbvpIZNzD9qQSObKs5LuqSA==
  template:
    metadata:
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
