---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBokvHi01Qk60lETpQXM2o2Uu4xr90nK9AQ/A89zkVdDw6NoZx1d5+iGtmNEdBsO6zftZ572+6skZ2TNv3BTtObvKtN7d7BnxfpF8koaTQp8PdGcIt0SHBk9W47asGg7LA3r827zRYgRZKwd+DWY7288sW5q1RHvWGHLHHbwBPw9vszC+XRGdwJFT8u/n8+mPvCZ963gIXiZiJMYIJSsyqLOdhx7ONZGsyJNmYh5RdcBK0ZoKrtRyLSGF/4LFAAE+U9av3N+T+SWPDl70GheKVOQOs2ZRR6J5934ixnhYMgq7/Wri5RpKjEOeYsNBniECJoobwIjAwDHJmB5pxGRsuZl+wGVsGgxGgDpbDC8Zaxpv4e32e4/sjq6HhmZqZrKm4/Ji604i5CL61B/izCHbcKfZWta+WZFfS7pD6mD78Drpc4Rm0TgRTrvwEIkqUgfC1N6f91VwFBIr9i1Smo81wTrt18pyVmPeyYUuipIj1BSH+Uoav1Fh3KwU1KoPEOz5pyBq1oI7Krv0fQzMPdNYOCeQqdjgFAkWjwaqYNFsDSWLO+Fw95TOeEBJrqLY2QgTPFO5PjIcNXBzRFuwzHVFrLIglJiAbE9oRMtPCZZi6UIsenJhLyom3Dl+2h3C/Rb0bz/IwNWuudrm33DXTwn7El+pEQxNLxQdom8YDQ8N+uW6WFwWfbZtJVDkefjCH2D/Fplkk4lLvH0QMbNPkglRxnnIH2Jqioj/Bn9jvoiXuxo1UFWnTVP6v+8VGb4OUrWHWrM/veaQYHd89R1HYMaQYdPY2m9czrEXzf2B859AbTvOt7gIGZFGDu+bnXeO/xBC0m4HVq9O+Y9+fwR5hfLoFKc2viJ3+z38c85nTg+plf6AU36jyfsd6gtetFAteyJmRDg3Dq1RHd/u0TY9y1jEt15Tp7c+7RUNI9wdVHAbryuErl9YPYneit6oFBymkFwQyS6a4oI012tXFv2w8RWKgxjpS03d8asQ==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
