---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ts-authkey
  namespace: default
spec:
  encryptedData:
    ts-authkey: AgASzuEfx7HnsQrb6JrflD10ElFgoc2utPHvf1xzTa+XRKalL+XajBA9zdT1SgkA8Ot/23MkyPkcWNnKCh6YEcQGfzlLwa7b2UnOtI0Rr21Fl44DQVSsakEBDnYsjBgn8jBs1zGXdF8LDQ97xsw8cTKxPYL1g0Vfwl5MtCpuaufklMgHjKSAw/mLuEKF+RAyW4LnETrxJfYxKYmTvXfJ3X7EZO7NiwEmTaov9sDBD+3/iO8ttWdQvIF022AQToOdp0id8VSwUZ7alHtKCGW4gvOoe+DgvoCsNMkhkSxms3Ehwdu3ph62ayOswoOExOoXXW7Q5YXjChB+7Pkhu3MWqDXJf5T7qDmAyFJob/RkfypsrcngUVN/5Qg0KGQtnQRdMSUwa+AGqC1f1z/jOYbaI3Wv4QoSms/JI5Np3KE5H9/fuSyQxHOgu/nJIB1J283Pz+zgQP4EuYZnsW9gJJApd3YIsox97RKOCI2gvHlSqR7ZRg6EgA8L+cHKnhB3h9ZGqQTsnm6b9tyxC9mnHV8OltoqUApiRrRIhsGLZIkRrQNP9QKnXt6LV7f+T/jpavoQbkanGX1EkRB43Tx9cgTaIEhjApUjLkeyZVDRGN8lsbQxWLqklj2BmGAkegEd+0XtZN8NgFnbUGmpE6NZxyikYY0YaOOb6WIooYZ2RrFT7nCde4s5KQFSrDbQFA09VgqJP2zYizx0Q9gB8VZUvm3N8au6XRg39ZreqJEwhT9VOeSxBjRL8J37Nq0+QKRQR+duqRy7M5mBpayDWcglB/+T
  template:
    metadata:
      name: ts-authkey
      namespace: default
