---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tsauthkey
  namespace: default
spec:
  encryptedData:
    tsauthkey: AgCSavpNVamIpxfqZAeB1qIFkyqNniWvER4QWa6NYqUUJJ/FQkfy+Ce9lRvOwutzdREuvyvLQYoYFW3NbRqwCa8EBcprh1TGX/3lJNP+MGSWJSc25yvbcIV9eVttsJD8dr1H4SZ029x2OK5FPfDBWIYQEMirjwvH2vtNZzN9yBGv3igLzZL6AlBMA6W4zKx+rC43111ZImsE1qX5nGOGg64x2gvW2grUshfex6hJ0Tv1HoKA4KXUm/kHSxKfsuNH+7Iypa08BAdPCdfrgi68piiHUyRmLLAGN8uQrIc3fac+JNRcpFoNHmglpENb4WjOl/Bvx8l6Iwyk8vnC7CySX2GU9hBg+M/QL7z2HVorzWzHq7SMgFjLc2uH7pnKAXNpPZtP7kqRhvWYUHWTSshP92inYQU7sMxpAtNKnC3rD74SXDE3VVxV/8WRJqyYf3j8pWTzcm4gra1EafOeXhshedQDLUCsxw3w552M4wTzzlnPM3u+sJaijXKnPbrKkQ1P9ci1gvVB45y+nhWMpwiOKGGTK6bGx9p5s6J/Ib51V/gvEgAYPujQ4edVCT5GOLYuWSubpZr73bQ9cQJ+0iEh73BApJCfs25ldMhorWrF3Plu1L1aGH4bfLIa3uNKBi7Id+Luq3L7qUd370XPQuiyjgEVDmvbcElbyuAbnrouxpZ4EM73wuD32GJFghiWtqr+xo8g2cOaPPX0CViCsCgd+VOcIsM7TEzmroTBmzuHMxkoFXjKt4ttjF+gqiY/4vdyf3TUxlGD4CqkmKfciSA2eQ==
  template:
    metadata:
      name: tsauthkey
      namespace: default
