---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tsauthkey
  namespace: default
spec:
  encryptedData:
    tsauthkey: AgC2MZfkzcVVPZtXHv0JmoWWmD0KzYLuomk2Vu8vpFnW3hOX1O+PI3xLo9cN1L8wkXuaZbUSN1gv9WYpwu5BM8yxHDK1srrvIZFjloZ4n397NoiBodKsLoxPBJDUO/LIQTB62CzGeP/xsdtU6dLGtYvavEQyn3bvWEauNlazOAKrEm16ejkg6V4oYLjiADfDm2RRLS3dJJlLq8FhMzaWdlmuPjHkWZArVFU3LIEY/3JltF+9vOtl0I3w0AiRPf/AZAQ+VFQMqqM/FVwgvwmjMoJSWc4vYXiIQcKfhlDXIFpkPb6LRwx90ZLjp+LPkNu9s/NOW8NZMPQ1N1OUZWaLIBpYax+WMDtTKsNS1JeH3jkVj8aMRfsaGhJguKSzuMA4lzgghCwdox3LCtokAuKAPOIZLHNrbvErQ49XYsbFGfVjf5olnru9SjfD++fTf+r1cmT3woZzToM/lruOp/dj1te6nMaXILCdcBDl3r81oSatQN5fEcZp+NsxYgS2OzxxWDtT/b2ZpVJ6/DIPX2DwUY2p54xzCUSonraA7FWdUyNArlbC1fCm6IKr/h5y37MzCAHqlBRWRKl1mje8AT1ToTvVFFAuCNRefHaazZqqBkwM8ExVYAw932WvJ2Up/YYLhZgDDqARdBIaykCAcOedY7RDTGO6pZkZLiTjC5eYQu+uQejta2ZbnVrEymRdCoeIBBD3MUAz6BiHL/uuIBaOgiw8Z9bqzIC7Weq1ssvWRJmDaoPMvEgYyxcXivtzKwJu6MJ+hWWEEkFeNn3kI0y9wg==
  template:
    metadata:
      name: tsauthkey
      namespace: default
