---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tsauthkey
  namespace: default
spec:
  encryptedData:
    tsauthkey: AgCEUM7rAL5QKlmvQ1xPmQFVw1AY0EDlUGuHn94Ijgbq99fyN596b27vkVsg3N7QUnxcq4H3ecvonr23pzU0o9rGsEDyDiTZok7LKIIgog3eeUvQ9qtrSzW0/CyvwrvWIT/zgWXuv+cEel+ojojYdWqGLKKhbU92uH/dpFmiKXvOCAympCwoTGdTszA3gknoDj/KjmB1t8mVXS6OfyZ/j3dv7snA+2FToBPM+XmUCR5Lk/c9TDu0ElGVxrJLBxvfZLjpuQOGq5ZlX7WiZIL5FxUOEd1wiy11u/y+XRzxaQvCqytVwDbtv5lanKx0l4BLaSbrf7PS1lwcwhsqYYqs3ipsDjlNB3YlFnFpZeRbUYRo3AZChgGhZXX5TLbUY49Y4CA8H2c7yJkhjAL+LQxISnsuHVWuvdE8vJhnLgYEPzPqHdxeHe7sXJEIS+QNHoeVPiLTmVk7zIaux9QgsgwVeadl0W6MI9dw8Ny1A7Jt7YVfgwjrvYoY4QgrdbiXEjr0ynuHgf65N263c4Kgc6AGUgyZym6LNY4U2zAFPnHiuXSEP2ilNOsT4Lv0/M93y1jLQWXyQ7Fv7JLk3aLI1wkARDJD1XCYiUFxLxQzoVDjreCV+molbskFbnUAM11VY16mt5tXAIYqKzPfpN0Xc+zIBrVM+iEdfjTB2vleZInrxb30JLhS+GOpNIeubYRjoMKM+iGjHvL3u7VA6zbrBFy4KMw6sbMGBcrplaMF5PB+n5WoQPSkNXqJdj44VH5yeUsg1uldgkICUtMo7lekFNm4
  template:
    metadata:
      name: tsauthkey
      namespace: default
