---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tsauthkey
  namespace: default
spec:
  encryptedData:
    tsauthkey: AgB3VuFaVjEEAKvVm+sct8TXqLSq/kM8CIRUTS9zcIuTA401dKo1BzDb+Gte177/XzX8bfEv9wquc9ZrfL2kw19yvmmHNfRoIfDvp5wKU6bOluitQ1qiRBf4Wv1oqes2DrZqeWHU6s7qbHrvMTxxivuAc2EXS98ES0VPSKDi0AuUWgmBQkAG4CbrTbZSOW5ODFKJlrcQL2V3K/hRST4AAc6Ro5r18IJjwFR2UxCHLh6T/nL4RFmf0aGZq2zkoDSXmn2+rnVu9GASFkRDkn4Ja35Ba61gZ2rSFKtOGhac1r1+G3yNJ+0z+4RJWO98phTIugySuT+s+UKqiR1qhFLlMkPkDp3ByfzNDRK5fbYW4IO1Bm/OfUKBHnEcriwiOtJKEuWja10CLaEWI/PWVqnSsklzXmupE7jXWXES+INZHJAX65xYGI+QRjADCqMcaEsutdCgir/ieqJKrkxTDaiqpPEYSQaz1T2v3EQ4dkuUBFRNJRrddZZdK/gCa8A/UsKh8rKQbfcNqjWsQblOcKQe/wHH0BWcOBTbgM1Pu2yLCIdxfarj+PhNhZfITi6o+xeIO/VC1OgJLH4FiH9WCnkpiTsXTrr6LLKDWt0FRzWr6pJvlr7+PkyGPLghqNvdxhvIAQdcggQH+4BJddV/ZUFzQjWKQEzEwjlSsRd4bpgAnJqhzorEZgzDL8Rea0fmbGxE64VwC0tCkgq5UX94f2sRQwaC6X86qD0ZWYoB/r7uBILUwSoePw+QGNDej7MPQ57KVFCKQFF4WkBaqc3r+u7mgg==
  template:
    metadata:
      name: tsauthkey
      namespace: default
