---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgCOAfuyB4cQ/KJOi6e8vA09Qq2VkaMq6IbKFTApwoCu1u/An288xFq2Q3q4kI9mo25ebuldgOLHSfbePWoasas9tcrjJ1BCHAtyG7HJofSjn5HcN0PhCtVJoWNtZ/H/fv/r6l26tZ3OLIHU9qRl1fPMJ6Y+9tNofKA34BQgbfB972lUer3F2AtlWR6vpg35t4htUoB4JsweZLTrVzZpiYB/yc3016pUitCmk9Rq9nVOP7Y8y6YioLbwD6Gqe74+nTMhogvXGXA1PFrzkpC4HJG/KD2S4EbJPSSFumWEvg8qOcB1hOhr66GMjy/FRwTkqABp4eVntt5HvCHYktNzr2FWeKlDfBywBGuA+0zSjEP1sfXBrghhtIbVocdEaIZ2KlCR2XGaC9sFbUh+TeYi3D5g1LeRkObqV4Y/14mTStVva6XGvlE2XpREo6f+zjA1YpU1gD2v/y9QeHtYW3JC4+QKoSANTcQ0Ga1aVGMJWDE5wOS1zeykpAUXljE30IQ2p+IIr7UDiZTs78qJlZ9Oa+4zcRSGwo80pW1V+AL0R7dzNP6kZFb9wsQexOnowpVGp/wt1Iu74SSuaCDeqy3dfijEEXuqZLl0iVZymFmKp1sc54J8gc113dvApDj7BhqB8/hiatgQ+VDW5qL/Vrr3/kjXmdFn9YzLbJcRTr2bNomflCqf3qBT2VxNNcGXS5lWYvo7obl703ko9JjDgeGzanT+2SqSL7TJOe7W1TDWZgRrMERsbKnJ/ZrrL22Za6zxx6kPlAlDZlqVolabVgvQ018t6kOIzX8lIWiXFE9pp/E8OTaMt48l0ZIj7jPkhkZUTMJg7um/AobYbdJMfiAoHK8QKqa7bsm+HxI5pK3RkRre7VyFcdb7fMLBqvEMCbHJwwOYHX/lBIFSf88q8aeJHxsOsg==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
