---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgDJSVCue3tG1ZmMQ2SIDW6OH13BHnNb6YMPGujnRXchz4Es/Qv5ENJuwT4bn7yblVNO6j3mVQE2PWknMuvyBcHR9Gf2ZrNPTtVgRW7KSrVJzuUBMZjXiAA6JHIVhUyCmJCKve8I9UJiFZo8J68InNnnaP7J8P4hdxHAbbj7QJ9WJ9lAjWFKgcFzl6/XupKQmS4KFiTjGljEL5FfXq8ZCUT4JCKfM5ErcT1+F9PKT+lXS2gkja5d6rcO521B+ZbEOAtGJWqS4MZf7uLm9ltScSx4+09ubr1Xi6MDVtb2YbnbI9JE5+9f92k4rvDnLULIpxm44yCMpFm3E28F0PBxQ66t7ccAGB++x0gkvP4TVJoSjyi9ViLk9+hZ6gaoRbugXifA2+ipBOJYYhY5RgaMRtTja7h2tM6NCRqXiX8lo4YTGJfLZZWjGP1x2fc1/4tHwRF5h9EbCjrC4sF3wpNeluSqBkmYiq4DB/vJgBgHAQGoFI1jd1KJ+2jAvDLHtZwp9JAUGxY9g/KUD56eEiEmhQ2Gei08iUfc0JiTOuKXVx591VxfLA8D0WUWr0Z2VTsFfqLsRl+bzgzvwC1tRhJuTR4DfAxjz4rJTFoj2W0BFjT+/hM5yHMtCSQAo9/RgZHPy0ambZ3mLowgvh2pQJbw2T+2AHjprNaeDEWkHucCn/jkT3xGedkYKc1MNudwD/gVKV4CC0bCclNFL7AViZjH4RT2vV8XDqZ+ekQVNihdPa5nyDS2uN11ZbQhQMUg8Z3UlpcRdUz2nWb5BPOtI7H0Tvd85w7Wct3p9p0YM7kNMr69Ec/rap1rOgruuw/vJSW8FlTRLLsZ6ttGrtc6xRlYZbvueZdxHA3op7zYMx2KsFKRROkKizCKa5XcMlGVXsgNBNjmNZDskmcH6hGfPz8FZiF2ag==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
