---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgCiDZSAh1Wx7uMgTCSI3C0j2JdxHVRFer8q8hpyeL0uAIZIfvMECCyvPaSN5baIdip/aXTmChJVVPbS62kh1/si0ARgcF2KbRvEFpbTBIDZTi2A0WQgVxyhzBELwrCJWyo5foE0J86E4v6S98fELiQIxnvqbKRl6WQkJzEbbvrdWTtfC6XRQplwVi8SOET2iZ358QX6UiUbc5ahRM3UstWh7ZSG/CFRKb4xJCNMo4SddGxn2t6EDP459+YpOUIr/xtRp/NOAN7mD5N/sgimm9k2R7oZTb0tGBGaRloMtUgIpiBtmc0NYVCe8gHSwG+bH3dFtT33B3L06nRvURUX4o11gdW1hTrzTV1/KiTjBXK/2dTDw/1Fl006W8RJxeEFCb8k0rgAQVMClUq/SYyc+WaidR+EZModV9jO+rUNUwKFyRg7B3SuNxfW4ZJvtTcfaOzKBbD1xseP5YkeTtn0lrGexHsGW0sksugwulTeJsQ35PiCtWpJJkUkW1dKs94jyV8bvHXFPGAVJIqwNNi0GNd0P9slPuuQBnhDE1ZXG8BRytrWE3hQ12qm7pHgnCj7Evyq8h16dNQg5h3BlJpaVfIyWEMMXyYixJ7G7Bjdw3vKubMpQE/l4Ztp/1d6uzBTHpAF7SJZmM/idOS58JSsfV+Nro+p5xnlLiUg2UDE3wuFhAzQ+ZD/Mo7Il3gIjLhRpEBAEsIRYY1Kg1Aw6vct4o9YGGg6XY7z+kl+kXavtT7tVOQ3zOnWfiBDXo0b03843isLYqU3biXtfDZjyak6xxEwzuFtdx3gHs/Z39Owp0E+yslV9dOXCGp/kZbNNTybyLAcJr5VdUO6TySRddtqVyaYrgZ3+rAjOTYiu593pKSHZJFwZIHqyDUTHQAbEe6lUFWge/OAcFANjG/Ng+em3/sXtJ429DAzqtFnWHw7pluo
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
