---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAQd5BDVozTR5bVDynfR1wyOjQSUlpf1otlt+rUkkxaHf3kK6VofucfDJSGtIjbQf7n61y/brO0OZQkfUy4xuS7CntaGcvkyW1TX6sYKdMo7gTLlHFM80WT7fQ0sd3S4zgxpoNXq/vjun+MAG7liHQEDqjT0ftjZ3ZSisDNgP3Ew1UfiEuxXbVtAtvk159S+i/ZaDvZ0sGGpZibg6jSNJuAKv8LmlyHGXRUQA0l+Irp+CrFdm+2yNPzxk8zrUrOKF4xFOI20IkzPsZeCX1M5mTkQO+x0Jk5F4NCUx6W08lg3TI/j0rwpTsGZy/OjQ0aUlUN3WLEf2B0SoAg4hF7jvqm3ZwHejeMgs7efPNC53MRo3ya96uJNGh78cb0+SzYcgPI87fQm4ZB2F2OWrsB3v9J0I23ONhLp3tKPFq6qkdDe3zMczIFkQuNVj/HW70it7tJqdEfapQQR80XZDvt+eArgOdBNfLZ9pznVhkC6lQXiUHcTxk/F1Oe4i19NH0REVjw3c1zLzptIbNlE7G81z3XP/9PQb3qxrdZDJy/LTRRJvbxYYU6q6OwA/ztzFZrF1pXb38xlvn6NzhdXCuOMd+ylZTvum40EXOkzWG2TtzFHS8iCOGZ4T3WRCaqJ4zb4AIa2L5JYJwoSQWJY4ZjJvGn0NCVemmL9k18XBKpowxYOvYQD/ZmDj9uqFrkfT4kFYL4Xf6IGIC0QojGf4GKnsaPRXwD3KC4noeo+MlGNnRMe+yd5Kn659kXYxnebSOdgI98DmTRErZD7UhhH7UOdKWfPiyc4vEJEiZZy5M2ifm/KRMBFayMdhKC++WhIZFzkJMl5xhAt/eMPEHQ3oie3T12lcPeyZ6UYf+NRakeUj0pbtQfq0JLykgdrqSj4q8xz+3FMSzj2XLt0MIDGR7s9dddFjsEobtvdDSPGYNbnbZW
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
