---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgA4QXr/moBZxL9h554nJiJWSL3IoSY6srouGwVMnNf4EfXkkSOvOLSet/uM45P388axQTM9jDheNRZAmKUY2G9kqnxawVqRtlcw+j9D+foGp83jr1umAcYu+OdrTyjMTT2ov/TilnkdEJ2tr35Qk0+jVXYdUXIt0Z+BTypxf5lwOi0Jg7TQVD0GJ6zsx0OOhctmwzNiFt4KJJZ4Tgld31yp3vFjLcjZmkGOnx5OX9J4ayoHmfTXQtpxjc3cJYDhe7+8D4BJX2j7a6Dj6FFOxbZP6jo3K/4WSKap54Nb3IDAdMAlRVhCKUQMDahU5qIL0yec9AScD6Lw2E31g0qNMRm6ozyqQDK2lD/ZzN8KQg5Dq6a/NJIUoxJQ4/1hncTXLrR2h/rQqZsSMFaNFVZVhEhbAyVn9sEU5RNlSBP+WF7NJV9d1B/z9DgbdRX0FGPsMisA1h20OWv5v9IhJ4sC9R9ja+yDAPQ4d464bxr6E0cpcXX8KBJ6Mrf2L7jq46I543yElbCsRlOTjKmJEFfPAcsFL7aebBAajd6caL8BBvfDur8RL0RFWTGAZ5V2qeVRwfiJovQLajjFkwTFgoyI2BvCmrVVj/Z5sjP9y5e/VQe5sxqnTPlYSNfMv7NFfB9B2Bgd4XHD1kJ6e74FrUUyWSnLwgRp/y/s+eEjRh4DV0od4ZKOtag6RP2LaJs44yAB7i0zjJryrVFyUI06Pm5FN8MjauT+aP0CQCZVJjCy51/IfpBUkxVQUh3kSx+mQQnTl/WpLFWYNb00Fsw/uenFG6knNyCmhsWvA2L3eS1fAnWyLKh8n8DKWANMb1nB3RP64BLGqrEJFirE7gzQpbIQcIy/T5mWjVfkMqsYiSQANRvZpuF8p5bswni41EnQiLw+G+IQts4YUzlmqVetjlfDK3WeK8y+bX2tqez/fmbwgfQN
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
