---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgA/r3v6ZuA0WSlLId0gtLIq+TYw09hmrBRC6p597L2SYVdo/jiR8tThYTy47XPNcIL98uNTVqbyt38KXM9M3Q0v3xm1qy8o2mcmGOiBtraoIN2wvknQEgHhssD0iuXaByf0xGmfs171Muo0cLmMxH4rpyrp/Ct9RIQ8+hqSOv0GZN2UdTfzsrVQYQIKP0KuUi9sNDBYyak1tavTDhi/3SDPmTCLDsXCKr8iCk6rG80dadacaaN5CxsmAq4s3YqHaUUfIsL+QOnzNfkQhaMQZfLaSQ35vyV0xZya6ECXQ12LWJhliwkj6ZzxFtT95J+slehDFW3DupjWizI4YWyRfQV6mCWFfSsTJHYGREyjp04CUHai540hwWwqTHfn1oouZ+JELssOi1/FojaY4nw7d6AfPN1xIYYu2kpXoUAGB6Nj7lXZG2/xWdgB+Jyx4QN/ly2ioH2a2FOmsDSExb9RNVbw2+2iCCZ5gqrGB3jRx4F+hBflVP495oTuetyANcprlkwlX0YXaPygPc4k+wBuyrqeIOL+raXs4YPf5iUyZFumI9/SaTO2tJo75JR8gP7KCG7YcYMP39JWKhalKE17Z81dy7XaZMY9iWkuN83RkmhRrRSGnIoioqImLr9A94/yDR4cMU9U8s5IJzyJA8P4XDUPbd1c0kThSAUEDX6ir1N3/r6P8iTd4v0hr22B83LU33GkT4Mrpww3OcTs/xhgNrJoSLgP4hudnx4ckZTJT6lJxutIz/fYrYIu22kkxh/d+lLXu5WmNIqAdvZ01AxEjz67evZ/4GuUtCPPgSnVijvO5Nx+OYJ7mvQ7rXk6TYQxmLeOmJd8JoIjmKpGwH8=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
