---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgDeYwfyTnSoFdP7EjVoV+L9zQDONZh5cvuwNqC3LnyWQGZqA60lzLPZziFQGaD1ZbU/r82P4WpF4RF3sExlB/UCcxoQg0dIY5MSC6jUTUmzYdawjwgo+OSuldGO3VyOHCUKh3EgEEFXXX+Wraibpim0C4vLhcksICft1jsNLCabAGG5sE+e05dAAj4OEyg6tkbrZ2qWVoNHa4GseCjSOz1KguVm1o8ssH0SBXldJ0DMjIDc/Cy/jcWuR8HPdgl8xnTf4nMZX+DSDHkCQk+L044CCSMX1+oEsetduEpgsKKdhaoBatiKyVZhFBq+kLykW9zX+UvRTQs78pAGNZg1FA8x+VGszfG4Bs4XsBzi8ZazrxNxowvVymOHPL7luV+kNNk4mm71sSoLJibBVFXlrdjWm0CS1uXOe0nF/QJpHMiXJfWiXgjKdM+SDS5gQ2UoBz3KndDuE66EYH7pLsUQq7Ur7Lw5JL/SDQUfEJV5P9R3Em+I0XWzbW3BjEM1utDODd6kcXJ2JqSU7iSPr5lVYcFHxlz/9XxVqIRx54fg3hra8yFacufF6LTI8p8H1E2TP86nIcJ92G/FBUOfKupqv5YY2zcST4CaaJWYxwG96qrs+C8qOAg2VcNlhiLHImCJQTw6wVhSyy+jwbY2rTjdpcG8+OB19EQxQKmCIgnPpp85EYTUqm1YUi0sVmtfUAp0qgD57CaM0Z/J8RuJ9/r3Ftzrc7s8ruc5143bt8SNqgCQWg5Zk9ssgdc46myuJ3THzaeIt/CZvkn8SiJwoP8Cy27iAy5LzlmdNVQxPWFu9VzsiPs+i4GAXzyV0JNuk8CqM1aC89wT96F0QPArB8W4KnHSItmfqW9jspVmTZnhQLIZuMrovcj7zunBYI/Aw5DC8Cx3iu/l6GF2XyfN9Te5izAvBw==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
