---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgA4dmbhPIvVBN4r9y2kr7z+APQmLiwxRah7LDLpVA9GinOXUbUeAY6PS38mxbJHMNFdwWeEO2JfOVfPRWtN1p4ArE7kPD2ezzJmCMOUCHQqNpZzQsqxM9JdtZZcntVfv5YG5PX9ECls7F6hEAzT6UlRs4nbK49RYJxXpEgd83Ye2TeOmtnPiNB4RAbQc9OkqY+gRpghNlwCjdf3LAS34pAm0g2b564bWrnAtW5XiMFw8+qRcphGEolvMYwoFEwigaxqrsYvJj4habUhySpfCxBh/8ZShmA3wMBVElGeEX4vRVeX0awWO9lZ3OwkGv2qKTeZBqUrYMq6gwR54Jq4Fp1icG4MGceVIwE11Q7aQvRJzXdy6nEpstYiKd1ktTX34jphqqt5vsZyGtFowbo02yHwEG82YOLHtECwxpTSYFG2J0O+3li5st9iykXknS91TnHuJQ23gI9SjNANK7IJn4GB2ltsiRrbB9O3LC2XvqGD21cSdg6oFCzxe5Y0ZOxQ/scMfHWzXW7rT9aocMCY+hhoeKKbIypoHiOItKrzHao1wrCtdroktZqlSa0AnVuqMlKcMKPSR2UbvweGvhbKCjL7XpI/W6MdB21RctJ1UTjXiMiQLtVKmZ81AlF0wE75NRjdOJKR8Henbrn8gIdnLGnI1K4sPzqb5WEaldrklT5y8y3yI1v4HzRoa2B8EPMCAKDCIj1iW/QAVYlGRbd4C0e13KJb3SWiJ3OzeqwHmI2T9nwDvHKSGWFF6u4Jn+pvSDD3fzamFueSmrsNxV7Jl2U9Ow0TT2KtjXbY17TDDJA9x/hyIyr+42nE9uRrUG3oRSbEf6oDb+1lRRLyDmGq9YklrPCqp2khqqT8fGwFMhcWUwXHepdyCH8SL3T6mU5NPrQu25cZNf+zfQwP8jVAjTOJ+w==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
