---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgCkkIPE4/5LDNZrr3H5VWkXpl0AFefrjej3mFBne/P3jUf32o2GTRZK3BD91ni46rCPILciVuiPl4CwAbvto7+/9qBKlUAV5AUuUwKO+mCT4lAcphSlzxsln/5yzSLTxlFMgBBEL/u5s0TXX05vYIGGleAUZuTfEUgyM94ccFqK3hyYUZRQ/VclZUtHhpUF4mqAkPlHX5/qKkpOkhTEzX/YUG1/Q1VmBh1n9pTb4utMSCYVxxIpg87hoYKPRYu1ohIIAFYGJpDOxqXf42OXnZ1k7jwhxeDBxiqpRQnZ9KZ51IHz/mqHmhoGDIqbpBQDshoz+zD6iM9iJdmgIR2j+ay3bzUJYuyd4PDuIbPj9bdiONrpBkRG2umKVTp2+uZf2VCOKkugoHHxrxRzKDkJDGjPQ0EQFEI6y0nE8RB3wVtx9gxIskome9Gy4w5qVtsupj77SKhdJD+9uRx0Rqb1NrNQcvezsRjGqigPKCBNGuoBZP3PSOcWzfqYdSzFhhATnZ+Fxl1CcWM3tgNeAmUoirWF3Oamj9h5v7pT+QifQ8Z0v0snqKghQnWyVH5PaaiAtTyqrKCbUd9cbDZCWG9s9SWr6VatARuSd0gigtK7QPN7lsJ9OQevo1Gy4v3zvzOTNNd82yDfqjT/x1fmv+tD6aLVbQancPzIO1CRO/xwP5cO1DKV3Uo9pquphs3HCS8oWa/DN49Z4qejKoiGSDoU1K3VaMat56dL5eQtG4FOnRczh6KmcC9yZoGFOOrKTQ1+Ou+tRd8D3wyMNplxd0D8ITQTQCUrM55CQHhKOukfd3GCGNWulrBSIrWBn1D7IV3UmziCg0hZpDCDg7X+G3w=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
