---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgCCGnBAUm7giN1RGgklp09ycCqDEUX+F9MMhrrjjQstHYuw9B8zgAQ4veSzTCwpMEQSrHcmucDBz+WI1YtxGpgA4POR92wPG36NyoMeT3tZfjI70ykYL8AAasuc//pfSg1MBi4IDLbiAJ0f2KYJBL/55Eus6tM5SRQvYG6vLciq/7ONkNnNh/i74ZFbixona6DAOmPWXInoOot1Pia5EZ/lkA4+SxyDrbuL+h7CdWZqShLJUrgU+pGPC8DcfjDJHPgxoyjxNv5Cr2mAwOIaYrxjSGB24w8t3MadJpyrqOwE3LqhQlVXgTMHYNHuKHxBYHSYxcH3R+SFyldcgrs3Iy1BZZANz/PrEDH2FEhxn8dmBUFaMZKFhOqpXvvmd8jBL9MzRR2qGcXG9ElDL7ebyUqSseE3mjAkFOY6n7OTRD1vyeF+a22L78zihhytzSzmpaJNRMlJ2LoL/YCbLCbfkk/F6H+fehIUNjKxTj2FAHV+Tbrd7R1WubvAaAh2917iyBx9a8WbpDvUH+NfVw28CVt5S0pfrzAie35wUIQqLJIxZi+uOKKj2XHcyb4vWgO4tr6gj5qcVTXyZoX/D7mZa0xq2WIs9/JYU5HFiOEdeC5iwF79wyM8ec7EIcpXQBgXKoFHG9TLhDQWEvjgiy82zUmmtX9PSSbxSXT93H3AWgIUCb2i4A8Y9DszHjqlWYqr+47Kh72G7qhUUod8uA+TDFTpFNamgYxGyuczpnOFL9GkbuziAf5EkBxQyTCSzf3Dks81bD2l5w1HS6fsvAMNHVP8AJia6/z8TVgSFxoKXeU+1HqvciioY/bhwWZ8aHRvD8lo+K6J92wL9Bmxjfg=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
