---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgB1EQWthdvt0exluo2FAE/osA+t/VCIgi+QhAejqbUtXkZ1/dvUoYFJdA9o0/mLovk8PQAgBCT1rbtM8Hn1nRqss/wGr/bPY7KMJA29WkFM63H2fd8ETET+c+41UXv6ARqgeGrkXUGrtE+I4yDdF8/qvylc6YGnEmq/zUYGlH3xYxC6BnkA/RRRGFmdpxYRtiMd+GM0J9kcJhhDWapwOL+SwfLgWEykgd6ffuK5iqAxWLD3ze4w3064wvyt8KjeYIK9GZlduV1RHbLDbL+3gbB6PIVzhJXXdEVp6lsoBHuS5b7rfEFXzRNhm3KJCENMEG3nczPPTv4fGYS19k9ZvwWUHeoa9HpeO77u6jPELLSZKIi6uM2BbGwyF0YtfxNNEJYadN8PHCz0gf7b9rzZuWH1++w7jBqh2TaP5u4z2f5+QzgXdMthdZJKiLnK6iFocvEZwHgPGbdUsuPMqDJuNmSzVUy3tiZBoVlC3QwbRE9TAgds0r/vjL0NPkHbnwUcYlw8uMBgWzGkhCaS9H4Gxfq9qskcMYcTGEO0W7V0a/4wPjl0bHLd/3o2/Lp8NvhNRbxLPCivr5yK0QV0bDWsNdECcViFNOkswk6cnDbVGpZuon19QwYSPPsNgnwKfUWEzdpUS0aUY1EmSt2h2fvbvrBc2hX5gnHUrr/wNCtpJ5UAJcON+mOMadFg57JXf6ekNlx43xfPhN27Ryhcv2Rja1JCD7PFvRv9N+dMgo/K3t9uuTxzitd0P60yhT1mFcUjn8HwJ4n2AVCpt/Sv7bcNBKrrQXLZ+NWmxwnezdKgdGNnOXiewjhG25pKtFm50EaS4uFS78rzJ+7ik1n4f/4=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
