---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgDBzBaek8V/DpHtLUQZoCZlhES53s4h3CUcFslKVw22+zrEZRK1TyjwQZInyDHFkANPApVMGsRNsa0taTtRmNJ9kXfBVd7GLsTJFEA26oG5ofqYNpfuvPpSFBopQjZdm4H7oN5SZEdMGfUgvITESqSAeoxxUgNX8dX83KQwhBALAJguYz7gmsfdVqhEjFVIU+/Z/t+vZwq7vu2F2pgyncOfdbz7P/XDmXlT9Zr2cssL48vF1WY5XFRqZXqMOS8N9412rMAF+LcncZt5HJxBvsJywQaU/ASlLuM4teN9aXcNGeBrJz6NuKbau6F0LwWjdf5oZ2eE2/wxCqboPeXeTD+n8PRr0PtepJINrWH1gOa4v8lnW+CLr7tC/Q8G3rTpwUXFlX/Y6jpFF58gF/TU7whdFcy4Lnp73WjDUglmK7rtdNyAjMuDReE6cJhRJexKxqEir87WXQxvjzEqwB1/qZYVA+kuSKpoJq29YdcIFeXFMqycbV5CmIkL5q5ewd4brViNCexjGV0Yu+7maDJzPZteZcVTi1PBgriMhMeySS9BuERwef4fzJl76QxkD1jZ5EAOPTeBRXzutWLcJVIRKS84I4yUZ6ujoTMuefsJWggQlnyu6Pxm4qY3ihJrW5qbgkFTvk3C/us5d0be1kWLPaCyH/DnmPBys3WBZ/Iz6o7k05KsoI9+tqfYixD3JoqAp+YmXfDMZfh+lFZemrQM08ges9clfKzwyraMZbn3x23byRtTEqIzaRTuzFkN1OCUoPA7K7Afi9PwLqXp1da291x02Fyu1EHIxBk8ZEOLuRVAp6ZyuGHoxKKLsrvLOSyCIihnTLXDzNokaurp4yo6SAOkIP6RxrKcfO8PyIZDIKQf22/0Aef7vGNNFZ9dGdWT+MpMn64aKd8LsNoiop7cHnbyZQ==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
