---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAjS3qUYdifSheCbmzI10ln7TJ4JYAylHuwoFmfLT7brVuUzY4U0XNcC52geitJpH/GhCqMAkztskwiY8a8/8lzXccysE58cKl0k2LGKrkrWejercuK0QEGxzY4glr1VwaMt2nQ7SqC3yStr7NkLli+CvP0UvJsQ9Vo55byqa1awjV7n/c6pjQH/U7I0mP85CjI/Pb2+GNVMunn2fCyPxbzPjN7GCjw8YO8JlU9L7C7OPDlkOm/DjKpP06pwNfJ8KaPcukgXIDVRCSm65olTvPx09eJAdNrCP9Y3Jt+R9pi5gI5Vwwkc874D0oMA5NQSO8l3/8rAq5eNiefQMBck3UlUIo3DjKXCPKnWJ/Azyn6BLHiITfukdpwIDcGteVQmwHCk7+95o/iTnYNK6XsiSQTPIg4dr6XTLuH+mWApS8c4QvWAONsQzgNyvH/3eTGeaKAAkBW+kZzlGhVlqaH/XjZzRV+VQqofeUeZIwfN6oKUbxTmI1gL0b+cPvOHdzlR8SwOWbPcOYSVsLCf6mcMDFDreFPlF/HommCDc8X4YD13enD+EWfLjrXoXtpEi7Yvg8ed0akJ0N7NyT/VUnf556Lm+EF0JVnzuannuk8XL5kS3KmKcHm7FvW3AGnouRoZ4B2M1rX7Xj34cNDQAkx+MViSI/AQzIuwAUDqEVr7H26CpWeh8FkOMuxO6n1qTSd67mZO6nXxpkZeKxiLdit6+aVjOFppGswNPABKMjtQ53qVnWYMdAFag7pn4AyYpYBfjli5WKq1d6BcbsCUxEUBAcHOadiYfaLDL2h12RwihWCdcrkb+Peksnwe+VNXQlgX0f65acKNWqL68l8ViN9DAl2uHiIX2yx28ur9rx61wOl8kdm1cRwc0OM1fv1Uvf41H3fHd5ngW9XXtZ05Q1VsxXa+tJ5GMbgtPCd0WoITEu7
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
