---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAdveOJh4rLnhHpL58P6uQ2R+qxvvOo+O25CD+0vIKFwPfJY9mFmbZZNDvndHJ0G0rErBAcPEiKOEv+5KjHY9J2qfrfwFBrUCGaUnY/PlT5wE+j7nIYHDeYJb0tbbUJEg/ayFWjRn48dF4xXRo7WnzvbPIu964NTvGJ2Cev1hDkFB0bA9ttpLBISnQdxkOhu2bNM7FOO1YAmI7KhkgvniXSMaJPem8LOXaz9OYvGMC6dQ6k+l2hDIGhdPNpOobx7HG8tP8u45YDENuYdPW+af86XTqZkroi0IZ3fzKejWPSTi1rYTBweJWUa74FAP1l5XjOOBgikPSyv2TmbC1mmhbqlNDNULACMIH5yqWjkss4clLTkKOrbjSfazifqPDVVdrikXhmPfI0wzxqoMimkC20Xs7yZilwWE1xsgKFG3CcujwbKYYOhGKgLGOs6k00F65reDrE1VG/+crMdnXKXPWls5lnoqX+tXgVpv4GRzUlv7hq40deZ0nycRvBh2W+SpUmz8cl08X0HLYOqhjGjrUNZsSf0+Rk1N0LNcP5dyLdzgQnHxF+BDtlRHRD70VDjvgNTGRSy+nQEYGLogYL8gwmfADZ55xyfEiIFTA6ylDx3GvUnTrEneyEU08hTZrllx+KqPsM9Seb/1uyUJ8BKsjzVhHYbFGEs7eOF36IRj+jNiWnSizsg5NvkZDjzqrKnKX0gQ+++bPcON0lFjkhycBth0YF8UzAoBO1KxRRMga8wzckfh9lMNytMO6Kwf4JrwVTCTAZKh2YE+rkeC0IK7TgauuCTvXpl6GDCk5NCmUMnTOi+Y5Jb3BBUoKl/i+qznoztyhirq3jzIETERr7FwHgg21M85OEbboySz6c5M86NoeMpLcd0L/2l5WGjaD2p1nDwAbAkpW5V78d2wFhU/aw+AWiZWka0Tzh8E7e4ek/
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
