---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgARed0SKZbsL7ueoO6GS0GfR2lmD9XFpv63XfrS9WGueYEGPF8DziS/L/0m/e+Tpr8kAgOWxh0tTsiVRjQRd4gA3lbj3wX/LeZsmITQfp6l6LpexeKD3ViMAdnTMHoE7BT85aEVb1j4U48RXTECGrZDqt/qe4UU0Dk4KI9cU2dPaDQRoCFqPiBC49IR2ahZy3Mzwch/wS5GQlL+S9nn1mmKCCqZQaiy0czHpTXdc7quV+7fPjkYlb0NtSysPQpBcQ1OP+BQxVPceeVUQoqsby/vLCjdG32LkfKmjUrzZHHREzUWvgLuKkb3Y618zMkWYkIKscA2nH1VxxwlpDGHg0Ib9WzruaOH+M1gVuNmmmtAjvhW7RM73sNcqkw+o6V5S9ltWpboEU3QbOuh5NcK+wJL2B4bmBKz6CigmIAf8dPQ4QFJvG2ftbdO0UQIRyK7tWtZA6aPi4DPO4YvOvPohZY8Qoks6IBa47Avbfgb0OPULthi+mPz9+untV8giM/2DSE2FxyIUsIFOz6q9et8P0j9mhZIeHRn84uw8FQg+oev1psvcJVL/2esKGFJf9n3364A0w82jTcJ7GSiGP3K0RlzxinyNIRdH1S5yHMZg5C8unAwltJYC72rsBRCUDsqFF584WhfoaQcQHGN0N9B90D4XzYsikhSn0wJ99w0EYgbN6K6R9cOAO+vJmVHjOdYVs9Bu+0CrGJ1nOxLBsXzq37QpnG2xlYE+KbF5IAOgK+frt+2VBTA/jQc5rINqZYEA+DoZttLFwL4tjTr2Na9+M5qr7r3cZ69TGnlfk2Vqew/fB/XTJRB+RhePJK0uC5ZjDO6FwJiWd6VKEB67EA5wE5/kEUQMxMKAT0e5CB5n1j9OYBqMeV2Hn4sxQTWKQeBjqAvlzZ5Si3krC4hJLHvE2UKvg==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
