---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgCE8rD08A2i6ejhpcXjuu3IEPgIQtInuw/5bVtvHK7ZTuGdJypBsGLdml7YumMP5svFzib8TIh2U8KhIN7zAneXtKbnqJLNfkAccdvSXLYEgALVs6fW1s2nk0tOu8dngqZ7XRvErbIpSgVFDsA4CFKgEMf0MnWhRktZyYYB6XJmjNjw3py9im/EcCUHH70rZzEM9sDOu8zfpIflLAZOTXqdQEHFnVf74Y9EJoReC/lGsh8C6oyqZ2IRl2q+t3g4m9NgxfrMlpOmSaLSHU4l2VtjQVYTeaEf5nITun+MTWjzVIlBPHnu+uh+CU3A9r6lELlCLFtTB/uaikxPYmfqO9Qmicdrs7HHEBtoFdqo7hrHzG0RsM9CbKNKrNxdTnHpjk2wV/D9nGi21OMc8UEQeIRloqJM4Mf+mkXZ+nkRnLRoB4E9Gp6Dclue6Iv9n70Yb/hoW8ulaPfeoqSKf8C2inQQsB/it1uSndIRZA186uy/XF+3uuTTcXVEkmk4FYCWFox9Jn/2Cp1ZwpaEFbsL3fb3UGWsDC5MxC6Nl00gxCYaNPsK1CZJWVt8LCoPJ6aFs67AkQrk4Ucp1Nx5IKQ+J7qyoMg585BepTj7Nv2H6Fm93AN/SSZZPGDf8r01h8+/sYJOEGkuKcWHJlUkCXUf7OBUdaEC2dybYPKyHrFiaL22QGfVEbhCmIJE6NDEj+DscbZ9FA3AaeHsRt8MYkbMRZ9OQTwFaodAZkAm6ikof00XuDaKFa75UpxkySdJQxIBHAjffybJ7JftVGK31rMHydy9UY+Qhb0CFot0ZAjpO0af8WsQf7GG8FT8aibCmESEcVpOqhwl89eKL8/nh8A7e2Id9Y5QcjikVwHoO7fIVCC36q5pjjW+2lJdtoUmpmPu1rfqmFSKc45WEJC+X6ZJHNIaQA==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
