---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgA05+7pHxgvYS1Q3Nt66H1BOMbr7SsT1gGwt4fekkuQKZEeVAbweYXbi3EItaYjsUnnjQYSnHVoqqViNlQW8rU7hrJWQJ+KYrl8DEelnK9+st1HHm4nkECtxl/yzBEw+mbMVwYRoDrtt5UZ3uI0xNy5/ntJ6j/8BWYB8Niwz7nJ5r4l+0rwDEI93Jut8D0baGGDPXjAGuKoQzwRULENpmDjUzbFKW80+w57lHa4RUVpT1dh1dRZ2TTaGFRA9T50+5SCGjFB3lLzibuvx+fNtZQT83Q60t5mJBU6QSMTTzPrV2VsJ9eTSOrB/LejD0Y4DBM6WeU1RXD4w8kHqDsdgfqXpryKX4Nf1fSUsEY2xKQrTYp5i0mi/KDU5xAgRQDdaU6tWof00DFp5suEoFDvniXukIzr/UIJmvqWV6K/qGMrjjPJJWXZN6rKd9zGE7uioOW/WrZ7575bSlFhYQYD2cjfNQCjLpRZ2NVC/czvqTtJCY5U/CI9KvjZcoXwKY8sOV6KeMdQzd7JhxVV8VaW+0fHy8zdPXWdpATfuoFdgzY+hRAXKzEvDN87hK/7SDmwKZahluAKdbemadIWcc4JN26J3tQGNXc99Eb9IpwsKMYxDfC40ScPoYqwcnuVkR4qQUQEPvcIpxYmF23pDAuLaUPpir5tk04YuCmy2qQDDkWCibwiAVs32k0oqxHDbK3tKQQVSgP/JzRWFJorztGa9lSO9JdzmxAOitaEnqeF62xNfmTYZo9CotKkO1qNPqAIrkeEoZrGnegsf3w7mPVM650XyqHSxy0c9Fbl/Mp0bCFykRofxJ9P+oZlJVpVgSp3ARG+oaHEZ1w2UVkngg3+1p4XRbTteB07TzXryH/TQ2A6bNM0CV86doQGNgyoCdcuJ+uxLah5GN9S/XTGYen7v4Im+Q==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
