---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgC/lcCzVnz7SSVzE0dNqFSQONJLqaxMRCZzni53Xd80EK2u7RWYHpt+mI8fz/xzdIIedTyfKOWwTg8rZ36DCc3fcIQH9lKdd1EeQAxoudtHXb7wnd9tOcm+ryyZGbv5V/fNspc/umWzo882uIBUZO9PbFlAZlix3gDJkBA3fqYUKFm1ff74NvUlrD7RLIkhleITkVgfIzvIO76XrUR95VXkZ2b0tBJbXmO1fU/M6ZQaBbuJDjENXj97bnD83RB+OQbbN7U55zJ+3FW5pgZ0/qbENKGj/TWhQegAxZTe6xdGPTQf0EzipBhHGiW90RgAXX8UhkBUUFRsTRs/wgIDdOyA7ATmHVCYo4W8p9CHSp/cRn3RepfYSS4KeguVTMzLa/QyIN3rb4eRT0JB02a17HegcAde5MWlP7QQoMoBz+p5o4yMMtiFp9YIsvn7OUFI/3UymC1WcpX1CEnV2unyjwmiYo0xSG/2rC5rAfahJfZDeNv0ulW9/tJVAYj5YkEsTafiMGLKc1QGjzV15TazNUgpoqh9s1DqwSK9LaW2nzQrQ6FCv2lq9H3KTWMAmf3ykTCw5iYhWEd0+dGqpHVKLxT7S6fm9oLqsIsCGaypbkNqfEnzzzYSugbfypq1fon4QHwDRRkmqU8G9ozh0ewn931Dlh73for6PsMo+hGepr20kj+3BT2YXi1MXQMMTbeQzBBpqJ1eb/q+wc+i2DKt38ZRTtT3iW55ridepr8jpwFhTaEOsL85RZwnEk9Url2gJQxGd9mW6G0WkhrCFLQJhLMHyVZme38H+57NFw1M00KWUu/uuq8E8JGoy8E80wy/u9wFDU8ylcNjydvHTHgmgqqw/f6rUXgVxNRZgd+huI4vTHcA7LpvQpXk7cwyfsZP9YbM2oWIU8JgKYcat7b+WPYjgw==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
