---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgA2yNL37LimRkd8Q39b4iddtt7jYaCt0lerM9EOoykiiL2RVjeADgO8VvxHjVqwijJDGm8wH0KtIh5Lo8InRAnLcL77L6jnhwfUr9Zo7v1vYhkuQ+TD9rbV9c5mphIqZb7tLz6+AfrAVaCj3XN4/MQcYR5FDGi/ndf7PgtKgU0PwMTgOoJ/30PTvu162KArHqXgvt7JM2dPYl31EFZacZ5mV8HUAtHSkOXj353fA72rFh/br9LjWxIjyxDS3Z0/7MDJNEJZ4Tet67olM1YNmagjWE41hzuIqPxQTu7lhuYjHCloh/1kEMPsF52w5XFW1hiRMDQOn9MlwgtEXa6duspwjl+PJyUWJsGwMlk4f0+Stl7H3EXkwO2LRCdbYUhLIEHPTNR9rMB8Z6Zf2aquuOBqerGEGmaAYN5zH4BeDeZG+8JNcxFIWNQHS0G4u3eG1l8zySgKqo+dtaM+EjT4lPZs6nbEq6rnwbv5eO7NQTg1ouIcgH69fkbptqIJ7b6jcfNovLPSvC3XAX0giMF3h1NALZKHysq8v3dVUQIXpaiSgONvoeVOa3aJAhFk5AiGc2urqrblDZfA0f91CKwbMKPUdQ9h2KUhaqGPRBeamt6/Y7gJm1Otj1K8L5NDvKgZkrWoF62lGjPn+rlTOPc7+FXUmOpr8QjrBPCeEMxLdn+BGILM4F/VoFaWRhrSLzU3gp/xM0//oV6DgAyeZCWXi8KJsqm5P8awMrr9jheUWC1q50+VxnQF1ya+AmqHylIshOCoJFjFJtfjFXG7XJz94jxkNFai0AODPKMgxokZD/0G956dfhL2XzQKwWj7UJV4+HTp+jYinonQst12KRKSmiGKhKlWYC0L+YrNFOgpAvmsNRDwYC7BxplQmNDImE+20iPGbpM/6bfbo25f0nsn/eEL9ByR/Y2MTtMvN554kRTL
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
