---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBL5KtOmZUF4giuio6+AYUaWZOUK54IRDAp5ErHcoHI0D/HETUX5vrPkl3gUr31j7cfa2pflsp7YpZSYz9dA2qW4Jw79XJLswPznV9O0AaNE434HTBQc/zEGX9KXqsOiD2Uu9iyVCwMQKsOdO5AVW+x4f8GJhriaOQqABcBD9EFrluIDjr1quSTcjAju1L6bhGnsPGRPkyyv1qIL0/l4xoHVXVQeNzC9uKwcaR8xiOfFBr43xSCQIQGpew+HcNcvkC9RCEcMyXZM4U6jNEuhnIhldTHkOuVD+/4ahNpPK7kZL296MB8/3fyWBVoX07FWEmgmr2wR9j8ygjHnywiTH9hql601DYglq2dTEADTy8hYZNcbXGC1w0uJ62dTq2+kh2oMVW2IQ36EFkCOGD3FOE7QaLXyF34msVfAZLPPdi+ag0h+v6vZjglEmidZXvQlwKoTgX+rsI+QAiRfZAdXXK5qOZkfR+vQAEk1wXAZ6ZrA6ZOpUfsKPMzHW3LRnTjmJtQRpIDAUe+bx/WdowxcfJlvg6y0pcI7mAxPtJQioKwx6FdR1Exuvh+8cPr57gpbbNgK+bCtk1Zq7o4rnlV8LG3PuNRTBeEK5Oz8C9eUIZQgtBWN4fQ/F9fwwMSrlfkDFCKVxqM1Wog+HUOB28VMFzhC6i15nVFe25sBg9m57sPBWqrTeICZwYBYGg/b7rVi/LLcziqxR96B5z+463wl+PpJoVdPmDURTEoEIGNkiXdXWIJggvbBKP0amrAMxre/Wjrl7enu8csfR5JncI0exDfjeS6swKk4i7PeWYVgiS2q/J2lQ+qT1YHAYJY4pwN08tqiSW5ZTMnOZM6tU8YFoVHSrepcvQ5almGoOcSwmL/HEVrY89EvP+ntHUH/TrZcP9cznlKXE+8i80jRlUmeq/SLKJ1n7zn6i+3RnS8PrT9
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
