---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgDM97tF0DPsi4GHoNhoPUHWTY2c3+5PLHJ0Wy5pMnAAzVs3lERxsFnTBG162gfeekAYw4XOuj2G/z4lNU4eC9eH6WceVn3H8La4rw3IiNXVAmlQ2iqZG50SZOpUTNCgD9DmWP3KJ6sTpMc7RKKLpPW850UNZAtUdXiwqQhwrIND+hU3XF5ygnaq3j3+k9qn4ctUB/ySV7w0WML+eRfXl7RACM6FoGG5Q8wXJ035HbBhBtOPg1ujITxlVW+l9+cdBWb/VEDBO36dDBYcNR7AN/O54XJ7wvuqfd1eZy6jd3CxpoB+BfXxVv0lnySb38EEgJY2g4EmmKq3ajLVoPF1b9U3as91zdBRMhSqPqCObzTyEF11Le/hpCUg0f8qzLRRRFC0hSNktL3HHNffjDUDdmr+mLtSp646ezhM0h/CZTpxkwWOVOv2uKnb+GMsiePlckGiyWlt6IZ0J7IcXWmM3mOSNNFSOxg0bpxN2z7jYsUOCk+CMFLwrwskcdPxRD65SSWn7QGl7xHiWAkKGx77CRoGU3mbbNr0fTrNwsBgeEXyYmYVAKbR63xRk2koCsXDFmxvTkJgVUDV6Y3mCEsN4x65o/jofu2xrVRbx8HKbW8PVPsfq1Hb436pOVMwkF3PSda8UqggOHLoIym3Ih8DsW3NZHsKxQApdwjL2ErD74yEDIB/oC2wSN/1N9Lu4j/FBBdGVXblLkpy1vBo3bB00GIX1MHBNQhEwkG2AHZzbgghAfuZEuA+5NW9gfwJTLG6evST+tJ9O3I3oZcvtjm4/zRPY8hnQQ8K+C5Y6ojUOlUeClfMeiIkO5u4qb7sPozwYWk7iy2ky9RX7ShvrD01Rvye4CLmpoCeppY5KVtum0hTLg26TKEqjLdSDm63/81KxmiGAebV+ZcA45tgbsVauBTwtg==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
