---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgCVzwNgjRBdX30YEGeBknZ7cfT4pB6IgZI5doyw3dE7EUm+kQTT8/gHw6Lwlsi2bwK3ELK+5PHJ3ySC+6AkZbuQwQivqWUa/nnyIKdyXYBoDHSgXt7z/0ns4pO9RPlrrU7BBh4Rc8inyFojAKXF09/FhtlkZrHDfLwWx3RplBjRnrRcRYGaV8+FrI0OrNUhgSGKjiQUMWQ77oopMEmPoQxuXq+reXXS6LJUt+Ohl1+WjCjT9m5+axT901IfQAn/e5de2Tc3O7UT6+2ixv9mTNF9DOSPD8ZCKyegOiledsgIo7Twn1Pg6hSCLTAUQn/sklDcmLktL2N86xng6pSTC83IY3kJ5CR2vgBWLoZaczwMlbkpKls5dpgO1RfqMwfX813b2V9M9W0c1gox7KsIvBsc7s1l2hAeLTIB/Aq/rJlDhqplmckYFvsWvZH8xb+BkWKZbVO2mt6HT7IsQ2hx/yXc+vcepPqZ1Es0fFyorxen+NhSTjHgRjQCrcjhz1Z/Tu5ut5/PZPmHUvwLns1ATXQnD+4MAw8a7v6H0u0RO0qqzSnOL0TtHrAZNGHBxYH8BdaMmiKSs7yL5Yt5eH5t5dQmJUO2UdQf5XkVx+WJjJsU8ZVs1ZVRFpXW8cR+hk4XM5sD/ulMK2CZR2lBRJn5BG8eaH5+/fJ1ttgCXjAJnJbLRLO27yGOylKErQeZE29M9HdjdTKIgtBRdhvlhljbhftBam92LVHxnZPj6IjhKVAK+LJApg+L1vKg6CVYPCGLn7loX/Jc41YRWMocdZc8dcN0VYsZuag8ZPbfn5rBIX0UX8AcUjRTNacIzcRl+Wbm6cdIzpfCJRdwkftwv3xQ4te8Dwc4dWACAtuvbiaCz5QLeYNgZ35q47iY0rU3YOBdVWF5aBIkDBAnF0yxP60fSVRViw==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
