---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAHoPJjfHJSeORNYQRgwnFPg2O0dtKa/k4CBxUtBfHg/oND7O8lflvj2F1DK9iXmOMx2mymGt463BaGmLBou5aa3xzbGAwrSUthEPR2xN+CF3VTYKe50V5JBuINJ/YiqEy3J/sFwmqpQzUN1TCXoCYrfKPnDdAUUzrs9xb7X7D7jyrf3asMWwwTAmQrfHITImyTanNf6uj6o65MOUAlKAWrwDI20RLNCWdWreJYsdlbTSU5e3hGda3bEbboeDTBRMBqiJOiWo9s7YPcKhVB6c8NnEi/Fw7Mrz0IvaYN4leq8qYKSUDVr4jAhuXmV95I+AuS27AR2cB2rtcB8xyWhOZDRnSlOOXshKs37FkkCa/mVs//sfLdyrP/dYybjGUHWCmQgNwRJT8SSpJ5DKfoO5dVBi3zXlYXRE4lo+i//+ioEPsiHAqyasmSXrfGKLaEXhQ50OK0GjYKF98Sf2lA2CrVVh48Qn1O1UjxZncjOVjQbRZFGFnKiAHN7cFmTBb11kqLs5ZtFAqLmUXqidGkQIOwuOQ67xeu1p/NZMS5xZlzXC86K2Nl+IVUh12fDUX/zfvN/XbiarcI7ujGPOLtEoirLk8aT3E/wPVAOE4Un86a4ub+M61I5Tlun31ruZmrxOTRqXU0UEDyppgx7gTcGO6OHkeCDp0mSyldrqA/lCbcAmZXceE19JNacLCSzmy18WhXdQCnv3kE6rc/BGgrGcyVX7dV9tTg2uZvyro8zcLabxrrlEjc7mqxmo99cI12wIQkmuk5JjKPAchX1gwTNPNcFvLR/ONSLGd0UchvCrbKh7kacO+Ry+34pwsWI/bdn11TS3hyRRz+JajzpsWiWQr/vssbhbRh5i1v7UMKiEiRpLs4rgy0diWJmv9vofiVfhezwOw4vCH6b2SHvUyhz6r29Q==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
