---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBG/OYL08Jf39J/ob7MS65bxBOgZKeNB02FsJ6h8Xl2SKhFG1L4Vi+h0j1jS4bGndVRf4p5Y1M3j6/cpep+HmiP3x21SxlTAlG6M2+j4vdBjxWcOVBXFsFMrcKko50RczviytI2D3RwkWHlSjOcdUomzxky9xi1XbidGXHnUVRGAdqB2rT8o0nDjgldmDTu5vWDM2122FaNhIDZ+I8WLAsJj3d8/dGbA6zG4tsdE0oPEPEhHtb06JJgwcKUWgwr6q78hyCCW5LL78Yo4e/S+ADkbAZfhczI79IPHDG0spCl1WiWwQF6TgUUOcuPGMtGHOWYjfgnDMBPk4arm2KXqYp7OhF3sazCfU6uLQP1Ajl/1pgW+meOklqikr2HIUcV1frsktOBT1kxCuqnYLZ6wb7omAcN36rDc5bPUMupUuzp/ykktFm+JXCbIkrSssk5BkCI/Xt2fL8j4wft8j7QCuX5k14G/41nn8OrjUwzTmg3mMVwWKB3CjdBTdbRUjTKn6/3YQinzgWL7PqY1Jln9xWffqnIrJus39+kLs0WBZdkftd0yxN0GH1cdqKBcWTtsqx23qa793uoYFC6RhTTwAV4ftHH7a1VdiA2p/6eBZiew5D2WcZ6trVqZ3oGF0uE4Ctp5NtEgKyHGzdRZbqTDECPpTeewPty642xJY+Yks4Pc1LAxwEmxIx6WzsB9JAl6iwxzZvntD14LZrN9q8hAsfiXVaqEBWzQiVysTO6/WrgYJqDmGYbvmlWKf0JE0sQGl1BvKY0/OFgNb7eRQ9R8gj7zIGNc7dZEJHTe5TVft7WHCet9yZ5LSw5MJOKSJQ5LnAwMpiF2YMyrCEYdFH2LyAgCQ3bJEKmRPPa4zbr9w22HJaVgF7r4QYKtq8RUNmaNrLSLBY/zmCeGD0Xo2NY0Vq1mA==
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
