---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgByUMyzHJuJ53FgdraJRJkWruMEgd1kCVXoeZm/tBhRhTx3oDlY0BbVMDUNacYyGO8CIM9rGlEa3LbE0yji/rDxEoow4Wdti2fjroAygc3DlgxEY5aP+qui+aL8W80aHU8EYJkY4XIkZms/9+4+5XnvzfiyNUnDhpek/NIX4GvYUEOsaypc3yslTY/2gDjKQDnBg2JgSpYQ3VLna3CfQ4e0U3MlUHo3z5nD2UNue5lpfWe37Ps9Va12t/Csfis510IXfu7zq7zUcQlZWw4QIBgDTfGj4s7EGDJeKCGgP3fqaFzr9HDb7dXZ+9iTKRrecw9MAjaMx8cB00gOR3qiLs8baiol6kwGhEs+Zrz7C5TB+pUpb6wxUhuahF2287oWsRx9OJtLT5KCxr2IE9EaWR0ySweKMEhYApsVEtHKUOJJgow3WA8hMIEpisO6uFtVySVsQWi2a9KwCB+qehyXJaGY2QoHjG7S9MgRqdbYiwNMdg6jmdAmaTbF3Iz+npgTk/JyMpmEld2VKuu6Atfaoad/N2+AKDPeb9q0J9WwdxuUIk76WTfiy7jFdE/M2pA3KQIvBWD9FMvmIiPgkwjGE2VQSQEs28yoywoYf5Lwm4scwPgjHSOGjzSfvftYw9n4232vjptahb9mdeN50pZQYcsFaiUUHqX3LOWG909PcbsuzKLonw1Z85epKKyMP/UHk6YcXauBsNoMMkWBTI77hQXAPAY/lU/fPVTOaM0Cc+Gtf3DuyeDS3cgLkXkGLwPxSx6F1qPSraWF7sWp2Vb7BG3Z3Cp+Wanohk/42UVKnscfRM0WyXpUIu27vMBywazjY4tFwl96UNHmVZdwC5fWqR1kbSEJEfGCT5vQSMGwfv2TK27HeT6dQnf5NyGS2Mxn6KgaSX+XucGOQ6NrBLmf9ZJhvg==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
