---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgDCiTwk0+spt47wl5e1+m7uPuX3PPWAwqUf5avQWtjbzuMZPgFcUV9CElUIzNpx9pIL5/Hvv5fBuCKvaUh/7v/n2rs2vN5/CCwwMIHZbWPHsHGAEZuhrGBMIYG1a1D9Z3C4zYaocN7RuA+AAogmJDf5jbSqk3gOLO58dwISGIwzSSxKFFvsqNzIQch4yZd/byJ1uVjA6fE1/irt0UyN1ZMfvHdW/0wpz4cjg71SMVj/ysdNjCIgg4f2we6PIW0w/GOkW+18KgWJZzJQNjtcXCo5RJQ4hGtnNlcBD74lLGXGMrBN3RizdfTMe7MHiBByT2efzzIMIlXWYXVscywCCGqrad5DN+jkJzzsrHexxOsvnFi05WJl/xw+rLhubXivyxTzH2S1coCzdP5pNeNPU2rm8P/IHA3WoC19b37ZYGOZ/gnYYpnpNk/P7iUraulT6FyNV09hD7wAxnKPIHf8IWSFk5N1O+PIC8FmO5eDWtLAxH5rZyZf0AsOXyL7/ngk+HoiNMFss6NJ+boDd6nIgVecJo4vZQUrI3UtLwsTR+ahzHK8Nu1UAtgQ3GbMUJimUscxzKv0Yd8dJAq/s8RjMaq/aaCkVDm3DJBuuW4SmJkbYXvd0tMTyu7Xp+44sQA+t4/QXZOYQeX+DuSiwSzw+8NzNIEefaREgx0arWGHamE5J3WsziBn/zfBbbv1qo2x36AEOzkN+9KXi9GVtuHuBu5unTJyIIxB7r91DSHKGt67gCH8oUiUqxmmwcfilRKCRW+7L6t2GPmUIMzkBcXrCx7GNGxgbUjAAZSseJmYQ3oCGqDxc9nnx7LbkzkkQoXZvuHg24a3uNAccqS5qjM=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
