---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgCBXpw3ZEi7W8Dl3sahqF3CCKUqtRHj08EcTbHAFiXniVZQtoaei8vfUI8+wLjuvtIPR6eHalrLVfiegZfdFXZiQnRjj+Xu10sDILU9qTytaFm4stvOzTj5TIS1zX75yt5x26WLk/+5gGGJ0yWuy8d5P37b4SK+GpPkBen3LvvPKZCcElYgYU6K4VCShLqp6DO+MTQUz6YG/uOklplTW37FJQgMGT1PCZYpMENKy/8PEIo0hWvb2FW2CkCv+jwbRuWwFtNO+ZPF1kwfvFZm5aXCMWGGd8X3N2iGh153ji3WmkK/8zB8yNpcGVmRYKyHyGbn23C8dFQuLJYqyK52dNjYVkBWnd7YZgx0uXDRCvgEuCDIPEC8275jcV3ifK/5UiypuGDeirWBSHXpZw5qKr48yxXkIgFYeVHdpjoy+1BvumYpD4BwvkmMJ5Rdz3eyoFToxEg66rf3xuiSUfvXLLaQ0IIo3rZiHVRCPj2zWkofxKI5VtpmnwiFTIYLCM1Ntue8Et/sQ+a2bt55K7tgnz+MkSiFHR2EHqGGy9sHylt5aCw9swagNWJT9q4oNKYmdGsNZRJ7H4yGwNZeuM7m7sRl+TTffjGW8+baVuTiXpKNGczmdm7XOhFCMawEVVIbXL1ffysu2xtGNMG2muPE0pFH/mv5WD/toxplsOz2Jj8+C8318tDAnWWEXk0jvmuEYLdVITS9NRhpQ5ZvMazap0gwPJYGvA96/41j8cRXnBSa/NPFEh5zF8ZG2z8VkQ251pejM5LcZb/bY75vciz5p66tS3NguXRQtpQkHCmjfCHKxS+hN8PR/rFAmI+ikMx4LSb5DXFpKkT3kJyn8EM=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
