---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgCX6R2C3OEq18XLjPYfUjWMKVRR4iEId6seqJbamQFEsAsuEtr3Hk9VNl7vd8G3FTRpO/E9424E7aMG03BQGnb4F5StG6VlYsl+5LkAyZ520LMiZiTav183cyvYPRyRXUbG0XOmSyT6/DBxmL63/XrcRu4diGV1V9+YUhyE2FnTofa9vUFypEFzpsLpRnBaEaTRMUmREfdmu7+AkFEkdzRTtSdAQ2CHFCIQRRVBzNycsJPCStgDea1o/YYAjv6y1FrVIYCdL77g+uXkp3lYv4s7C+RsV21Qnbp+mPHXAdU2Jgd4rzWqEJD4T2w7q8JBPmKIk5DAa8dZw4zsulYVyUkUlZ2eP2sUojvZREfRZvJCHAhKSsea/yKvx1CMoFjh1cGwe3Z7lbffeuKS6wHmIofzTRQIyemlyag4TsIm826MlJnAPGsi2ShdPIp2jsu95AOJSmBZpcsA+tHBTmwmwCWLbXHct3MYbgPZIQNkQRHaeIGSe9c+bQNDcPrcYzXBlcGkFSQ5evidSiFjKKZp8L8uBirFFGtKyRL1Uqu5SS7+l3lIBf4EdFfUUir1jFeq/9pZv2glTO1Z8Ww2+NFtx4gTYmTjhU9RN4xVde0ULJAL1D2wooBT4Qo3U55p1DOj3UJVKXfMhvkeRTq4p8FgRvgMzdMF5xiEnfiG5NjVUnaN7DFpdUpb2OcA7OHOQn2AwGatv5siSApS7FIHjjfNY8EbyQThyBmu1/YmsjVzrT/aRytpuwq1IjH27ktS96PFvvLQJJXAx4NTMz9ID2R6QUbVeHStpiix4JOm4LIzkEPbz6MXSQueu3u9l4Pk4SS8lPV1gldCv+EFPBbz/RD0h6g0K36AaiZgEO0prbNzixBWZhQS5Dzm6gqZ/j4qFJyHC3MTOkzurzaXGHG+xxQmGR0Sqw==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
