---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgCamtFRY56QvrhwuBvQblTUGtir8l4hzA1XBP8RGbFwkwPzidOTQnOwnzUn1q+TQnliphoHrWbB9OGXgz16hpPBhiyMsxRGBHfND3QwLiJFTMXsCybVwL0z2nqbbQBzHHVN9M4hiQn9Fk9cpKiSp4uQjpo19pt6116xG5WtLXhYc5L0pDbUSDZFflo4M9iwfLfsR35ooPhC0HKOK+pTAq2vtnQhGVgiS9dJ7Rh6NUXMJBAeyRrYVXufRdlRM4CHCw/Uqge/cumT/0G9TtxErAEEvk2Yu+aWOUBx7uPVQl2967wHfvvmGw2cRE1NrNVizks4F0STHCoKcQJAJ6dDYJdt/JYXh9ULI5zvSTLkDVWttme0VvRfRx/CMemO6pADYRr7xqgE7JfZsk91izdFebS8eCWn5ORXUinDgCE0Yne2PyJ4KXptAPPW+v3OLPClQ/iIVboU2ZT2U6G9mQTq0j/v9CS+1Oar0RLjutu0O4VgQGMrDTX8X855/4csR2ZdAwuJxh0C9oovFRnzGscC39fYFRS4I5QZecwE0gyLYRrVYrXa1WghfyOTcSlonwhe2YtVD3kRVz+ZpJ9962S23/3mnbt2LP7NN88Ysl3aXOrAu6vBwMWFAWwpCHhos89vyTHgyY1elqgMNTCSlgAAqtRLrId1wPx7Mvi2hNzQiAniebE6+ROwyh6aDRi2zea3YM5gb13ICGiqp65Yfwi2oNow+CG/8Fu4BDp3xowJo1Z+t0himXmEbluNxL9PU/n9GnNDDmaKBexnvj1LDDTelcaKwkxz6+nD6grsJEMa4piAvhpsWWyY9RWP4oppljTIR58L7/hwoWstheUgXPwXaOmdhcuBCuq4MA3uRAOHAxfR8RT/NaLDcGCsqWRewlf/lrWSmbZ44lex7IB+fUZTr1xn7A==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
