---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgA5vBZ3wmKx1pSxYqa1eWjgWMQSsxmTUOVxiDEiYZIvbX4Ddv1+aI18DcjbRQ7mGXeqo2MMKZXFq1FvDIhzBFhkfRjsIFb9HPBWHUAobo2hooRiu7QktyFvV8j6AgtEkJ7YI7Sbuo/O5+Fabf1PiSeoLmuEXqQG5opae4idqwypqKXLC17mtZkuWpQOLzgTyPkVhUkq9dvqQqkboZYDke2JEgzySHztaOYz5Ae3twhpc4EfbVIPIgcIs+DCVK6GWtHNUOE3po/1t5Dt12QQ48mpfyEEgeTnAfIG4y5eRVzz1YWhJx/b5x0NeCRbf8OlncF4TO4PvosX8hV+5i1Cs7gk/PHPKSvvuSEte/GNoacTEqG90JY1zmRtKBaxm5ZAcFBb2zNz0YFl+WJJT2yF7PEvdLi9kk5/04fgTmfH3J5zUK43fcs2rbBNUvNg0xa4cz1CeT9xsO6JKgduKTwaRuu1UHbROo4DmSkmjcL4tcCMLDYoNqMxw7Uw0GNkBRC9h4XxS+d8ua+MJ+YeoH5ZNvKDgaf7UVPJ8XrQIu96FPIwvC2YpYPIBCq9tkfvTgXXFGokQ5L7pR3JCEWap3XbKLmTtQaZkEYeIBg3lXnlKLZp3VZiv853z/CnHyZ5ule4ap0JPET9lCKlVK8tNw6Vhp0eRktyZbf8Qi7MUkUOa8BmbjCF1G5/g/YfLAQHyb9ySDQDA6vFEyni0dUJMzQGWTa6zVvYgRrhOfJUuhqdRc9ckd/WlpAJE54xNZZAIbkhDDgu9p3RkZIWpeV9y+xkdW17dXG/t7G9RbEhAp3Pc3NLB4K5gniGRuX2Nech0PB2HQqnJ3R+36I+qeiKm0Q=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
