---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAcZfrx7ZBafApxg/9XE80/Bhd9a6KLO0KPVHq7NX6SEVI2ScplXMBKsYc1bXCUeCS0iDgx0HQu/lzCY2F8wo199PQLjON9ljpYAnND1cbBfou3g/FcmgmbIsnQuF9CuCN2JjltTeNYEagl/KmsqkM6zZip203IRkeegodVBawuE2MA1AN8gw0e0ATBxGQBipVG24KeSEkRqhKGf0VgFwbg/JtgjsyiCVLpwV0WlxY967J/qCN8VOr2ROYPMSTEO+E99volA7PjnAsbhT/kevH66bWVZe/h6EPhUy8361okcWB45+5Apk/49YHBqmYnSUypxQOthBj+mL5dkJWxbtEJpfHviYqlAnKp34Bpwi1twCqf4tg3Zm0pE5eGVv/6MnvimsvMkiMS8xuIt40XsRk5RXxs59HBXqXFhPzyhCsnzb0chT6DcxFM4KgF/tzrB3vRFkWENxXrP0VNkV/maEM+eSevx3RTyWWXD6ek5MV+NFfEkhoZZYHBFHi0mdFMc3iDi09NE+sblRcD2aRrgz9iWaQF0fYt1BLvn7ZlKSkCs7LabGNUDEXieDIZN5YUrKJ0yBdeQFYytMsNQ9vbaskb7+0+ie+PYTvLJtHh8vJaRuzgAWBF6YAXYxFbGI+6SltEDgv6HJIZRG3CjsMzZkNmLQ93oQOTF4Iq/u0o6H8gP97Rc4fHg1VcJXL1Ifd9j+1YriC8DgpzrJyy0u8nqHqc+nGTBoO58sYCOEOpyyjL+ejNUqag7PaC2tvJjm0A8oFzd2CxSMHzuXiMER8rt5OfuUq6eah83Qgwi/N4/muUOAnSTTjW+sA0y5m4NPhsrt+WglOYMDbCkeWinSU4h6HQSCt0b7SOu1yv4W8fIwJ+avb3i4r/c8kscVXACAwIZVf2wBz9pozYxlSy+eIN2u2z+LmEFFfuu1Q+WPSkzmsA
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
