---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgCmo1utV8HJIn1/g1FTIHczmF7colYF6rHzUw6kJOgbvJhMHdYRBxJ2V/7ne+LOolfVlucIDOJm2t+PUgjjD4e5K+FvNfr4CnpKbe70/QoFqu1nruxUzBkqoOVHKL3LKMDyYIYN4WEWeX+3vwts2S4CKFKYaLwdj2brKCM+4Asj5EefteLkuGTSp2OoBFye51I8ahEjf1oNZE4k6wSpcYvnL+Gjub5GkrrTI24lK696zz9TLpD2xZ6R9/FWCRi4dTMT7sPEqdiDxszmNtx3GP5ugetU9DTL1YZx/dpGleRx2ApjbbDLaU2qD75duaSHPvHFD33EPladCwEiCHZFIsCHC4rYkFzXfHxth7fvgNiU8CdPeKskQcjqWkh545ZJON2TonAjARTYu+tujxTpgHZ3ezZ+HS81Z5G6iwBOB3FKvrWqRVJigpIp0r3DENG9AnckrvzXY3wPmgz9XN8W9o7Dbl4ed9uqWh3QQPQtwOti7Caqr9lifOvLYKRBleGqWxyOuZxO6kchpu54NBUHDE+30wLgYI/gczbePIsTYOJJVT2it3zvmRt2I7j9VxBHTr+nTvyPErX3QbSl5P0ABNAyKENrPHCyVqkHA/k2K0t6uPA8RLmNivhe2tlU4Mabt+OGw4arDxX4qY4nEpGqDwtR3Dn+Vs2puiBWTfLNOLEskvCyE0m3GO+QJXVonHZySPoy0Ugops+1+mp4AlpJQhgkh1IGJ4vxQhtdvoFHeKWs15hnKYvlMA0mRPpHj/EkPxcLY/4rPzarZuHVtXecthRY0V4zpCrSbFsLvYyoX8rg1zkVp4cU5eTi1iVup3wF5wQY5AULU5JVrBIEhaDA/cK9Z4EXnET3wIFXcReG/A+KGqQZ8ixZiv+esCYQv5N/Zx45uZwy+Ojzab/ueUUKgGnGCjATZiZVywGa0hUzLudH
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
