---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgBOjR+m4o/2ZT2LLZ4gWfyVs0BbK9dl7S5IVRwfIwUJep2LS169AYuw90hnHvybqHG9QkN8mxbztPyzToclnAqDc4OHrRmYSdWsgAZrseM31K+qXlOFtpXJcgYA9rl16bT8StLW5fegZ44T5l5JwIqgArvYnsW86pG0/FaONmZIZdS/mhZ/MGpcuNli8wm/xSg9ogQ+ry7qCt+zzBCQpySJ6aRTGbhhakW5qRJemaSDXDXnJCWrFnR+uMyHvSYaZl/hM2nUCZjzVIPv9q4Rb+hm5STLr0wKjAMGZrLAZ6YjjflYo9kJ4yNkhKNq4Rs7V+/iN4rHqc8xiQ8TGB9QP6R/Ab1UFrh62x0zPoY5RNrz1Z1zBkF9DeRoynW99XIlO/xYjRaGclZCPp18nrGbPFLdnFdJLK1XB04je9FfBnU2dKGhjkwL4Gwur9AQ/T2XBBtmnXqJNS1P2gc+s7TES5DG9z1anyoqu7sMrn2Xr/8y1HW3JZficjh9PHiLp8z0X0ukt9GfnQbfSXh27YtGtJlLBQMCL9b7yKEvIMgM0eB84Ln+EiFSM32ypoWIpXcVzrYCKbX87yMAYViVIafvjWyv9roiNT0a7WdHM8cZN7cF9hECBh9Q16MtEWWFMm2xztkAPlYaamNO924UI4bsuDR7eUJjxodvI4iPFfxrcnRhCQbDhTvo4pv0yXKRsDvl64bquV8EJTBXEVX+y83sRSXCr8HyPGFDP5g5sPiTIKQBBY9LZaZM2yWyjBIpt/aQG10+aRe2B6/ugKP5sK2FJLNkciRETwVho3Cuf3e87o3v0qlRrAgPgurAJwYbdcJ/3/b9x/1XGyCq0e6BW1MZen9AtuBnbaBjZAkR2158tcznB351gJVo016PrGBgJ5GnHww5RG4pYjBNkR3VVUkhkbSXhZ81jpJkxmQyMbPC17UA
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
