---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgC7Bf8Qi6+OzWB7XQfXEEn5PL3XPWyMpGOisHMlKMwZB/zgxpJWYqmqrODJWsTtbDWoVd66hDuVnSQe/ACGQCa7A+YZZvhkkq7tndIFDjcWB3awdjdqCr8qC7Lsx/qaoKIgMBZ8dGNgSXhVScdtaxuIqKljazT5Isess5WRINZAv5bVU5pfh/a2oPl/MjFipgiRS5X7SG4iQYKEOvvbwgi786H4XHtFS1tDhEihLAfjTv1rEi6rj6XecRUpfooKjOAndNtzODeXQB2MM3Uia843KEcGaeFPsmUx0ntNw08+Vm2GTUQQwhqj/Zpca5oTRTfbT87Gkw/mAL0FDAqaClNo75twwQtH3T8aUePrp2gXHsZKvF0B1ypXi/PSgQOMdHZJIDrbNufbmRK+44kRwmemAMbp4bEInyoankP/09/pF4cQxi0wD0E1amr/iyRkI/Xa+24wR+Zr06+KD9AxjqtVI/YMf1wMfQwUv2bNckfCzOnlxSFX8cGMUdtM6xQqe54AQao6Do/KuW3FwaBf7xJCU0kQ0+oImi1m+0lnyDraK/2n61fkfiROcYeweYUSpOIuVdplG4W9mmB+dsbSvki8ioZrzIk+z9iRejt5mSDWDo/+leV8ge7IDv8zBsQ8RVCK+jy1fy74hMMJ7dIR13GGJ5ugHYDe6N6S6fDy9sTDPXE//sAHzUtU68n8+Sq6GXEmyErYYuOyLmuPIagk7FLnalWM5my+RNqUDS+SWU86ObaYhTP0Dj+laVq5AmqHlNW5gY0+u7jvQhoz3hlznNbEqP29ufCYwmmG4HGlWQg+d5TbgenOc58MOrxbIg52ZbPP01p/Z9WS9/yF0v0=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
