---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAeAftCQ6TCwkQt1oQ9JG7Knp57CsYQflz5A+e/BIxYnC63OrQVg2Ww/d/X7XuY7S1B5cksCHUkG1MAebD1z9BskuOcidWiXjBvNfDuZaQxMClKF4SKeKnNtuokd+uVYcobhCh/r7rWi/ByI/sNJgwG2iK4EaoDic5j2Lp36gH0FrsF3A+0E/iVNMObu59/KoGh2deLvrEqHxmJr1lOW7JyNc5QSUBrjGVkgSwzIoWhYmwwsum+SXIiie22/m/DGLuMSWOFZnEy3upXX0oreb+22oVTn5gdGj9AI+EwTGtx/xgMbmpjkU4l1H7oNk3Td1IXlwe+NnPm0ZLEggP3mZI+/3t9aaJdKBZk2kyFL/ig1plryun/C7jv2OZELqmEWW6sdG8MlsyM6JtXtoghdV7fFkRXuIUQVO95i0kmaqO+XaXwUB9CzIa/KlEq5qpO3d256jrPjgPFRd0vjaznqqmhF/F4Jit/+Ye45ywaIzJQYgKDhO9kQ1FLXHDOcdDU89j9vnmpuWhLst8gI24QT7j49ZZxzOSaPdz4v7DwOmd8aZdwpiV9Z/YX+8qfS2QyukViDOLz/JVPupaDWsbFn+O0MvchlXWwXtO9dSplPcV0iw3vJHfh4Ygf+vb2QGv2uDifFbOJBPeqg/FxDXbtQC/naQL7R2TGe5/f+DVJkBjisevAwA7HBXGVmyFdpZkKsItnEB6drsCBygfoAuttRP5Iwi7gx1yFIcp2/6/Rk2Kp3xTAjR93bnW4HvtUPmrGyjA17okCRN5XiP2nj6b/ywMRKi6mE7fCQ7pQ0z5yOacFsmITG2UwD/RTQt0ZDL4rMpu6shaAL21Gcm2rsgc/pAdD9ieSdw4RUhznuQUFd7sWt+ASfNfU17YXf3QaOP4CgCNR9xaPrNjfpRmJQYtpVIHrbw==
  template:
    metadata:
      name: tunnel-credentials
      namespace: default
