---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgAe3ijzoFng2d2bePrpd0zDk+MqOuO8ytux50JhUBWBcHg3bnVpAdSfOWGqvKtS/uT2/Pju48lSrTqXan76/ONnQP5+06aB4ancr0QIxAFfd8zcOfdxMKFqZaw3Bs9M79JjXtHXJN0nxv2OLyQq2syr3oyArsaeSY1FAKQp5Kc0URBRbKaFWBhJZZseG5XZNZ4LT2Parr1XpmfmyU/iJcxT66SSgeXzHR6UFHhNRcMTUA+7daJingWMQzg2tK4kilu0pkotoTPU9SR+WUFLMvjYb/PDzSyYrcRK44SZxZ7y0wt8R0YctX3db9SPDD8B3Y0aM+oxYukj7NzqwgTbmDtKgs+T+N1X8ubvgdkaOANxrFt5DWtpLgWdpCdj3gR/r5q+9N98nrr+F/FFW2Fp7fJeuH/rRwvMMR1LOasy2ykKI/ME9CBeUBXALDB6L0FZor/jAyjS4b6hvc5ep1wXM0ODK0fvrsQCIBQ5YbhQ+nL434qTGwjvUcXH8vVZZxEevYlHaQ7baws7YzFg7xMXlaxmeTOHRFkZEDh7l99ki6ARBTr+PoLo7l9bgT287CjGeyjbFY87KahEWV2gNN2kK8FtLANVMjbJEokza10VM3poLeAz0ZiNClNskP8Xb9m8DEGc0y+vMVrZIz9uyD9cxFuW3rV25mLb129uUrdoFcoBIK334+t3kaz6ErD9xo2iyJ8k2grb+y5WgSkXJEeFyN5GsZGb6sHAO4yJM3oJJlnXUrhk4y40FQSAqYheenD/rWN2ZSBgusc+lstlNJWSV8jwzoPZfPX6KY1G11HcNEgGJ2U1CCWSPYDqK2dJGpnicu3wYRUxSb4r8a4ncCo=
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
