namespace: default
resources:
  - deployment.yaml

patches:
  - target:
      kind: Deployment
      name: cloudflared
    patch: |
      - op: replace
        path: /spec/template/spec/containers/0/args
        value:
          - tunnel
          - --config
          - /etc/cloudflared/config/config.yaml
          - run
