apiVersion: apps/v1
kind: Deployment
metadata:
  name: mqtt
  namespace: default
spec:
  selector:
    matchLabels:
      app: mqtt
  template:
    metadata:
      labels:
        app: mqtt
    spec:
      containers:
        - name: mqtt
          image: eclipse-mosquitto:latest
          imagePullPolicy: IfNotPresent
          command:
            - sh
          args:
            - '-c'
            - >-
              /usr/sbin/mosquitto -v -c /mosquitto/config/mosquitto.conf
          ports:
            - name: mqtt
              containerPort: 1883
              protocol: TCP
            - name: websocket
              containerPort: 9001
              protocol: TCP
          volumeMounts:
            - name: mqtt-data
              mountPath: /mosquitto/data
            - name: mqtt-config
              mountPath: /mosquitto/config/mosquitto.conf
              subPath: mosquitto.conf
              readOnly: true
            - name: mqtt-passwd
              mountPath: /mosquitto/config/passwd
              subPath: passwd
              readOnly: true
          securityContext:
            runAsUser: 1883
      securityContext:
        fsGroup: 1883
        runAsUser: 1883
        runAsGroup: 1883
      volumes:
        - name: mqtt-data
          persistentVolumeClaim:
            claimName: mqtt-data
        - name: mqtt-config
          configMap:
            name: mqtt-config
        - name: mqtt-passwd
          secret:
            secretName: mqtt-passwd
            items:
              - key: passwd
                path: passwd
