---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mqtt-config
data:
  mosquitto.conf: |
    allow_anonymous false
    listener 1883

    listener 9001
    protocol websockets

    persistence true
    persistence_location /mosquitto/data
    log_dest file /mosquitto/data/mosquitto.log
    password_file /mosquitto/config/passwd
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mqtt-data
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: "cluster.local/nfs-subdir-external-provisioner"
    volume.kubernetes.io/storage-provisioner: "cluster.local/nfs-subdir-external-provisioner"
spec:
  resources:
    requests:
      storage: 5Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
---