apiVersion: v1
kind: PersistentVolume
metadata:
  name: openclaw-postgres-pv
spec:
  capacity:
    storage: 40Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-openclaw-postgres
  local:
    path: /mnt/data/openclaw-postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-man
