---
apiVersion: v1
kind: Service
metadata:
  name: couch-colors
  namespace: default
spec:
  selector:
    app: couch-colors
  ports:
    - name: couch-colors
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
---
