---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: couch-colors-data
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: "cluster.local/nfs-subdir-external-provisioner"
    volume.kubernetes.io/storage-provisioner: "cluster.local/nfs-subdir-external-provisioner"
spec:
  resources:
    requests:
      storage: 500Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
---
