---
apiVersion: v1
kind: Service
metadata:
  name: remodel
  namespace: default
spec:
  selector:
    app: remodel
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
      nodePort: 30613
  type: NodePort
