---
apiVersion: v1
kind: Service
metadata:
  name: piper
  namespace: default
spec:
  selector:
    app: piper
  ports:
    - name: piper
      port: 10200
      targetPort: piper
      protocol: TCP
  type: ClusterIP
---
