---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: tunnel-credentials
  namespace: default
spec:
  encryptedData:
    credentials.json: AgB6/Mr1RoGIZvu6iSoAGuRV59TLDWZB6ijRwWekZuEFXFHjRf4wz6qYNNC45hxVlps2jPUhhTenNM10J10ctdtF9HfDamfThM9lMSLxD95u5FBzpw0jngIuQkJJC2AzOpsPu3eMjgihGaYly5rnYlE0Z4J/FyxlrBpJj6raeH/D1xIh7GD/Qf2NY6rWpqIuodRDzXazRC/g9iJ4q5n79tJnSjLMyd0JOMHnBLxW90OsWC7IXfsrZaoVvfD6UtRykfRMPiN3w27ojukF8aa/84YJZkhc+b8Pwra6WXhR38481wvCApNjN2Ddj4f3vjjl1yNydC7mAJ+s7sUUN6POAB03TUr53aIaQonYhqEzb6JMI2wX3yW5SwgoXkaD6O25w42/+Z/VnuPtYMfMSabhcHl62zG01K08EVxkWFQaI5DWxvaJqgaoRldTbMieWbZP3aVggFOs9CU/pc+5sj893hYZzJRg51YbQhwhHbDSIkSUexRi4ixobQ+w+ZFK9160XL74k8cCZw2YIJi+RFVRLtS15+HgZ/h90N7HFPNghbL+1zG5+cNZVAKN7eSvY500ACiNb6jMsLGIMRFZqqLcfiw6gbONwZoclAVRIxCOD2kcjOeU/Sw8dlsrFdUflmOzm0dVCrYNTJC1+SqdqnIvIfFMEy7cMIFfbYUljkfuNIUONMzeWMWkZZ9jkRgrN9NVuDr4Qv/FUUz4bUA4un2Zvexm9Gjfyk0NwmnuSiKFc+4ZIBPsENxMNG9/o6LTnVx61x3ksyBrzhOfcz3KBMkFHhn6nQsX8t6kdzi51ZfD1W+EVClanT9PDHU7E177PTx8hSlrDUCrZoXcLv19ro/SqujYWaWMUzqexoG8q2aWshQ8kV3+pMdV5TxW1I0VdXnpxMCKYiKk2VRcDb6B3FkBSZup6fO5cQJob5n+08CbD/FF
  template:
    metadata:
      creationTimestamp: null
      name: tunnel-credentials
      namespace: default
