---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mqtt
  namespace: flux-system
spec:
  dependsOn:
    - name: nfs-provisioner
    - name: kubeseal
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deployments/staging/mqtt
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: playnite-web
  namespace: flux-system
spec:
  dependsOn:
    - name: nfs-provisioner
    - name: kubeseal
    - nmae: mqtt
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./deployments/staging/playnite-web
  prune: true
  wait: true
  timeout: 5m0s
---

