---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: docs
  namespace: default
spec:
  interval: 10m0s
  dependsOn:
    - name: regcred
  sourceRef:
    kind: GitRepository
    name: default
  path: ./deployments/staging/docs
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: docs-adr
  namespace: default
spec:
  interval: 10m0s
  dependsOn:
    - name: regcred
  sourceRef:
    kind: GitRepository
    name: default
  path: ./deployments/staging/docs-adr
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: grafana
  namespace: default
spec:
  dependsOn:
    - name: metrics
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: default
  path: ./deployments/staging/grafana
  prune: true
  wait: true
  timeout: 5m0s
---

apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: home-assistant
  namespace: default
spec:
  dependsOn:
    - name: nfs-provisioner
    - name: sealed-secrets
    - name: regcred
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: default
  path: ./deployments/staging/home-assistant
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: metrics
  namespace: default
spec:
  dependsOn:
    - name: nfs-provisioner
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: default
  path: ./deployments/staging/metrics
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: mqtt
  namespace: default
spec:
  dependsOn:
    - name: nfs-provisioner
    - name: sealed-secrets
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: default
  path: ./deployments/staging/mqtt
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: playnite-web
  namespace: default
spec:
  dependsOn:
    - name: nfs-provisioner
    - name: sealed-secrets
    - name: mqtt
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: default
  path: ./deployments/staging/playnite-web
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: ps5
  namespace: default
spec:
  dependsOn:
    - name: nfs-provisioner
    - name: sealed-secrets
    - name: mqtt
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: default
  path: ./deployments/staging/ps5
  prune: true
  wait: true
  timeout: 5m0s
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: zwavejs
  namespace: default
spec:
  dependsOn:
    - name: nfs-provisioner
  interval: 10m0s
  sourceRef:
    kind: GitRepository
    name: default
  path: ./deployments/staging/zwavejs
  prune: true
  wait: true
  timeout: 5m0s
---

