---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin
  namespace: default
spec:
  encryptedData:
    admin: AgAav64629FViztlwaw3vCPF78B+j9gCCfLJlrvEgvaySeoXvFsm6GSoqxQ3WKj0Ki1mzyC31xfKUNWGMov+itq0AII5VQ/AwccVCY0ak6xGmVUOR57qp3xkktbBKMkjpDWyt/KFC78mPsh81X2SMQX8C6z05OvOH8rfs32rtuLRIRUwHPMvq7Dz0EdHmjGO7j5WJfa2TyGXFZgKngGxj5Id/AeymTqjcSQHbqYqhymqt4cKJnrVxmm3Czeahy07UPky8vhLiNTRzxd1yxOJws3gRsNFHI8gomztKUJAZG39kYlB2LD5B4lKlFD4ZeLrQYoWGGaisWM0RnqWl1G1Sd6CDr6RqH+fu8F5Fxh7ql0h5+/r1RvwmFWkkdKtfgulbqNxMn4BLwYyHQcRv0coDuYAhKNqDFwqXRUirHBX7JxYD24LTY+163d8dsJzqUViJ0wHqwTt3Tub5vnCyyRJz2c8ctNfCti5pfELi6SqY+VH4YRZnivsSPvfofYllN9N+NlnUEfMM9/H18F6H0qRxCAu/axBbMpmd6Wy+G4PEW+uoyvvygpX9K+tQNtU5VuDoJz9bFuPxUZAWoU24/yBPkRQ9TBksJhB+3pxdY86qKTmrI7xF3SG/5lEc6UYrijRJgpLwk/ndvS3t2udmr6lFBubgbeMI8AcS9UW5t1BWjL8eK+1j8gSO19xDJ9SpCtjJRQKAFupPMutEJr1A8yRnukwI/aDBfIyqfWwGhRl8lXc/xzth01nroI=
    admin-password: AgBLVEwg2MSvVJI+uZgAPy5o+h7qxJqy7zSNnRXUKJ/RjCs0gLG9ln3iS3/lA4jGhCWj2Ve9oFgzlRZqx3rM15LFlVcXM1wYshQBTUPG+bION4aaGz0F31hN3FqsxoaW4Zi716l8u3/w6p10YdUY3dMKWh9mfLzUdvjjEHHk1OtedpjnIXE24btJUMbhGim5dzROv7NBTAa4ITM5kiXCBJtLDuOhRpgy9u4ZGXkgwIeiJOw6KMXAD8R28+buOTZthrBZ4TGr0WdvGqTbLkO2hKguKFliN05dwE0r3qiEsw5+d8/+O7mLUn9m/k1N3iSUAwnquktskaPwmp94fXCGpJUJigYVylyV2dKuFvBGDcAzgJdzQGRw+5A49HFkHMzAbEBIl+cwRmDh6IH9nSgrl+1mxcnKWcXWCi3bHnODyXjv+hfBwyt14inwBF/mUCUUDNxAW3r/QHDFlGiPO637g7FQI6L7rEcngKwDPqNP+NnMxBaAmpW7fsoBuHyeDt/MoMy4olcAA643mWDVujb0gF8H7jl+tKVWm24liSBnpYnPkpEnAP9MfzGKkUPbaUgLdeU45+s0zqsKPA6pEcFLd4wtZA5RbggxpYGElnzI/xngqIyRtyoZ92rQJKhikVCXAI5KYXi/GZKners7aQPrpBGzsuo6tVosChWfb46pUBJWljwJPAGCxlXbTyHaC0esZAmC9TvsjtYUVJqZKZkq3A6xIAAWAa/d6otR9MIZGH4bH5n2HJ2mvY8=
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin
      namespace: default
