---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgBwhMBWXeapE4G3E6J4zyX6zKm9RqC+NWTBUbfQTyipIU2LM5Pwl8ixUAuUuep1HR14Gh4Cx0dAjnWftIgxf5N5esKfKuZDSQP3JQb0UCxYyZxK35K22nc54CKJou1EA6LDWyY9nSgJcaGiDwZonKkLxuP/p1MjnmYu++8ZTOOWLi4pQhHVpeCnCNB75Ud9lG4ZJV4oeJxLpCTqnlHj9+CwKFyDNRPKb9/axgUAF69e5FH5x2cuSG4pXN/YXIjGqCX7C1mMMszX7eux/J+StofCEIQLiiSji5gyU0gFdj2Zgx6xj3mA6qSRqGEdsvbkCKggazwY/8EMti90S0eNrnrN+cYY1LLEpkSBQ9mq7KlkgJh15JNCgaS7L7IoYo+INGLcrGXPm8J9+zO0peLxH2rxU9eC5B/mOuN1Ab5GJq+OarZyXtGgzr9dYC0B41ZuO4yAKyxQde0GgKiHbTnKIgSIPft8N5iC/Zmhvx5XM7LeVNjrFiYyVJYEX9SrEYtsB4q4yzW0WafQMJS2mRWPcfHNHxQ2lyrzMI7qsCFM6EkKFsDrhzHc03xvOA5uTGN7nAHa8oHW6KK57+vSEIKoUTRe1AjROwdpJyx8qcM2SHPJZHznLlaZciV6HzeTljbgAM17data8etADiqX6FmW64I93yjN6yuA34N5aaW0modhsJTYb0j+il5XeCTN15abridg4XKPLeSjx1O58gvZUHPUMOjDWAJ+Uj59gvVKgmT/bRBaz2htOgoeiSWRWzHujWrW1DG5If8vL5/I3RuxA0EHTIeIRvxg5QtCzqvwz/+s7npXo4sEDVsyyjKsunNgljiYzdOwMlSNKAgP4sJlsRbWRG2EgkPl5VMxMvLKXeSp/EhVU6grNnLQERMYYM2OKWjl/4qLNtLewksEmZj/kxewfezVXHrmDJqW1HpYGm84H+mxKvZs3VB51SVhNZlqHUSuTFruitqSsEGsL9xxAqUFg5Ua9Kdk4g==
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
