---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: regcred
  namespace: default
spec:
  encryptedData:
    .dockerconfigjson: AgCMnVim5z6A7JB6gcvk7S8tQqytDUcjwCCaPN2qX0qyY3KcKgevQnv4i9SoKDLRWiezOIEjuN50lr81OiDuiaJWMkAJ5IHUBF35IZlRqoLrYKVDjmpV7UdKNVZo89JWXIa/NFhVu8roZ6/lRImYfW0/PinoL+QHR3LR2/kpAdshn4TKz0Of7vcWqr6B+QO8qdu4WI2gQz+hCRbo2gTAQKEUrBRzQr23QvroF4zrNw8L9qCJ6gY8Kqz89UnOFqKeT9Z58ow5jc0YQMdhx7059ZoqeJ4DnLN9R/he+f/K8IooKoEUVCsysNdOAVcHprbpB2PCLGssup3KTwLM3ChcXx0GTrjwLqG9JIInaWMx7SuyvZ3jKqZG/9vbd6/hsY5gz9K61tjiEzgbmnMIYYq/ZL1+z+BixwjBpfOOUHIbYPiq/tKEkq6iUWBazoLvv4qz9Ehg8D+9j7AIc9W+1ZKc4ZccjaPCgtt35Xsy2/LneiaT7GpKBwIHJYvsnVjTelXmTPaBsXadzByzYONwry9E/RxIv2xI8zoGAGB6J1A563SfK5/0vwQozI44AZp8r460Y/SAULCjTpvtL3Q3iy2cq2OE7bIdkaONckygx1a5Iyy2YAh7+Oso7URKc6OBP/Dx1NKmNTxJ5Kj0EDwkjaUhlt2UaLu0pI47cA7PelWo5/pz73BtdNK+yXSXg8sUfCoE8FsgUUpm/hoCnVRX4JG2cY97bXm9y/69B7wGhZnobUpuDWxug3rgNUc0GdY/PWLJc6dzb+E4AVqhTFVV7MKA7rvQPL9Up57z+S0XmxJuubJ7gNcM1KShrjl6SIfmKJ77jclaWrGJ8QiYuyxMPjMvTUWKZ9OYQzmDicVEMHt4u6Ur5xD/tnMbuMM3Irar5jURr0t9Ud03sRyT9BhBy82HvOlOJGrJE2PpGFEWw7vQXTmOnkCzKLNuGykCGP424F5/XAMcM96MLSy9W2aSD1V+ALvaqco/8zIZFDmEuPQWH/rw
  template:
    metadata:
      creationTimestamp: null
      name: regcred
      namespace: default
    type: kubernetes.io/dockerconfigjson
