---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 8123
      targetPort: http
  selector:
    name: home-assistant
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: home-assistant-app-daemon
  namespace: default
spec:
  ports:
    - name: http
      protocol: TCP
      port: 5050
      targetPort: http
      nodePort: 30505
  selector:
    name: home-assistant-app-daemon
  type: NodePort
