---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-config
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: "cluster.local/nfs-subdir-external-provisioner"
    volume.kubernetes.io/storage-provisioner: "cluster.local/nfs-subdir-external-provisioner"
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: home-assistant-app-daemon-config
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: "cluster.local/nfs-subdir-external-provisioner"
    volume.kubernetes.io/storage-provisioner: "cluster.local/nfs-subdir-external-provisioner"
spec:
  resources:
    requests:
      storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
---