---
apiVersion: v1
kind: Service
metadata:
  name: ps5
  namespace: default
spec:
  selector:
    app: ps5
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
  type: ClusterIP
