---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ps5-config
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: "cluster.local/nfs-subdir-external-provisioner"
    volume.kubernetes.io/storage-provisioner: "cluster.local/nfs-subdir-external-provisioner"
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
