namespace: nfs-provisioner
bases:
  - github.com/kubernetes-sigs/nfs-subdir-external-provisioner/deploy
patchesStrategicMerge:
  - ../deployment-patch.yaml
patches:
  - target:
      kind: StorageClass
      name: nfs-client
    patch: |-
      - op: replace
        path: /metadata/name
        value: nfs
