apiVersion: v1
kind: PersistentVolume
metadata:
  name: home-assistant-postgres-pv
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-home-assistant-postgres
  local:
    path: /mnt/data/home-assistant-postgres
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k8s-main
