apiVersion: apps/v1
kind: Deployment
metadata:
  name: docs-adr
  namespace: default
spec:
  selector:
    matchLabels:
      app: docs-adr
  template:
    metadata:
      labels:
        app: docs-adr
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: docs-adr
          image: ghcr.io/andrew-codes/home-ops-docs-adr:latest
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          startupProbe:
            httpGet:
              path: /
              port: 80
            failureThreshold: 30
            periodSeconds: 10
