---
apiVersion: v1
kind: Service
metadata:
  name: docs-adr
  namespace: default
spec:
  selector:
    app: docs-adr
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
  type: ClusterIP
---

