name: Manual Publish
on:
  repository_dispatch:
    types:
      - manual-deploy
jobs:
  deploy:
    name: Manual Publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Extract node version from package.json
        uses: sergeysova/jq-action@v2
        id: node_version
        with:
          cmd: jq .engines.node package.json -r | sed -e 's/"//g' | sed -e 's/>=//g'
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "${{ steps.node_version.outputs.value }}"
      - name: Use Yarn
        run: corepack enable
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_PAT }}
      - name: Install deps
        run: yarn
      - name: Deploy apps
        run: yarn nx run-many --target=publish --parallel --projects=${{ github.event.client_payload.projects }} --verbose --exclude=backups
        env:
          GITHUB_USERNAME: ${{ github.actor }}
          NODE_ENV: production
